In [1]:
import pickle
import pandas as pd
import numpy as np
import torch
import transformers
import bitsandbytes as bnb
import random

random_state = 1

random.seed(random_state)

In [2]:
def euclid(list1, list2):
    return sum((p-q)**2 for p, q in zip(list1, list2)) ** .5

In [3]:
with open('df_annotations_embeddings.pkl', 'rb') as f:
    df = pickle.load(f)
df

,Document,Split,Name,Id,Text,Type,Scheme,embeddings
0,A2008_Commission of the European Communities v...,1,prem,A1,must held first Article 4c CS prohibits granti...,L,Rule,"[-0.01507568359375, -1.73828125, 1.4287109375,..."
1,A2008_Commission of the European Communities v...,1,prem,A2,Also clear consistent caselaw Articles 4 CS 67...,L,"[Itpr, Prec, Rule]","[0.93017578125, -1.0146484375, 0.0575256347656..."
2,A2008_Commission of the European Communities v...,1,prem,A3,Court deduces Article 67 CS covers general mea...,L,"[Prec, Rule]","[0.195556640625, -1.734375, -0.1546630859375, ..."
3,A2008_Commission of the European Communities v...,1,prem,A4,Court also held action taken Article 67 CS can...,L,"[Prec, Rule]","[0.404296875, -0.2352294921875, 0.34326171875,..."
4,A2008_Commission of the European Communities v...,1,prem,A5,Court held particular inconceivable authors EC...,L,"[Itpr, Prec, Rule]","[1.0849609375, -0.98828125, 0.39453125, 0.8774..."
...,...,...,...,...,...,...,...,...
2530,R2021_World Duty Free v,5,prem,H7,question matter dialogue Spanish authorities C...,F,NaN,"[2.109375, -1.3642578125, -0.62744140625, 2.50..."
2531,R2021_World Duty Free v,5,prem,H8,present case action first instance WDFG compla...,F,NaN,"[0.880859375, -0.65966796875, -0.67626953125, ..."
2532,R2021_World Duty Free v,5,prem,H9,regard General Court recalled paragraph 212 ju...,F,NaN,"[2.0234375, -1.150390625, -0.70947265625, 1.59..."
2533,R2021_World Duty Free v,5,prem,H10,General Court err law concluding therefrom par...,F,NaN,"[1.6494140625, -1.5732421875, -0.857421875, 1...."
2534,R2021_World Duty Free v,5,conc,H11,Consequently sixth part WDFG’s single ground a...,NaN,NaN,"[0.853515625, -0.2034912109375, 0.038696289062..."

In [4]:
df_train = df[df['Split'] != 2]
df_train = df_train.dropna(subset = ['Scheme'])
df_train

,Document,Split,Name,Id,Text,Type,Scheme,embeddings
0,A2008_Commission of the European Communities v...,1,prem,A1,must held first Article 4c CS prohibits granti...,L,Rule,"[-0.01507568359375, -1.73828125, 1.4287109375,..."
1,A2008_Commission of the European Communities v...,1,prem,A2,Also clear consistent caselaw Articles 4 CS 67...,L,"[Itpr, Prec, Rule]","[0.93017578125, -1.0146484375, 0.0575256347656..."
2,A2008_Commission of the European Communities v...,1,prem,A3,Court deduces Article 67 CS covers general mea...,L,"[Prec, Rule]","[0.195556640625, -1.734375, -0.1546630859375, ..."
3,A2008_Commission of the European Communities v...,1,prem,A4,Court also held action taken Article 67 CS can...,L,"[Prec, Rule]","[0.404296875, -0.2352294921875, 0.34326171875,..."
4,A2008_Commission of the European Communities v...,1,prem,A5,Court held particular inconceivable authors EC...,L,"[Itpr, Prec, Rule]","[1.0849609375, -0.98828125, 0.39453125, 0.8774..."
...,...,...,...,...,...,...,...,...
2520,R2021_World Duty Free v,5,prem,G4,accordance settled caselaw appeal plea directe...,L,Prec,"[0.5693359375, -1.30078125, 0.0073127746582031..."
2521,R2021_World Duty Free v,5,prem,G5,present case even fifth part single ground app...,L,Prec,"[0.484130859375, -0.362548828125, -0.387695312..."
2526,R2021_World Duty Free v,5,prem,H4,pointed paragraph 146 appeal plea directed gro...,"[F, L]",Itpr,"[0.34423828125, -0.83349609375, -0.04077148437..."
2528,R2021_World Duty Free v,5,prem,H6,regard true decision adopts end examination Co...,L,Princ,"[1.3798828125, -0.8056640625, 0.01039886474609..."
2529,R2021_World Duty Free v,5,prem,H6bis,hand General Court rightly pointed paragraph 2...,L,Itpr,"[1.4169921875, -1.34765625, -0.240234375, 1.42..."

In [5]:
def contains_str(value, string):
    return string in value

In [6]:
df_train_Rule = df_train[df_train['Scheme'].apply(lambda x: contains_str(x, 'Rule'))]
df_train_Rule

,Document,Split,Name,Id,Text,Type,Scheme,embeddings
0,A2008_Commission of the European Communities v...,1,prem,A1,must held first Article 4c CS prohibits granti...,L,Rule,"[-0.01507568359375, -1.73828125, 1.4287109375,..."
1,A2008_Commission of the European Communities v...,1,prem,A2,Also clear consistent caselaw Articles 4 CS 67...,L,"[Itpr, Prec, Rule]","[0.93017578125, -1.0146484375, 0.0575256347656..."
2,A2008_Commission of the European Communities v...,1,prem,A3,Court deduces Article 67 CS covers general mea...,L,"[Prec, Rule]","[0.195556640625, -1.734375, -0.1546630859375, ..."
3,A2008_Commission of the European Communities v...,1,prem,A4,Court also held action taken Article 67 CS can...,L,"[Prec, Rule]","[0.404296875, -0.2352294921875, 0.34326171875,..."
4,A2008_Commission of the European Communities v...,1,prem,A5,Court held particular inconceivable authors EC...,L,"[Itpr, Prec, Rule]","[1.0849609375, -0.98828125, 0.39453125, 0.8774..."
...,...,...,...,...,...,...,...,...
2406,R2021_World Duty Free v,5,prem,B11,regard Court held numerous occasions objective...,L,"[Prec, Rule]","[0.91455078125, -0.69482421875, -0.76904296875..."
2415,R2021_World Duty Free v,5,prem,B17,regard Court Justice points reviewing legality...,L,"[Prec, Rule]","[1.5009765625, -1.8251953125, -0.474853515625,..."
2416,R2021_World Duty Free v,5,prem,B18,Article 264 TFEU provides action well founded ...,L,Rule,"[0.237060546875, -1.1904296875, 1.1767578125, ..."
2452,R2021_World Duty Free v,5,prem,B53,Admittedly appellants rightly argued apparent ...,"[F, L]","[Prec, Rule]","[0.431884765625, -0.5126953125, 0.21923828125,..."
2480,R2021_World Duty Free v,5,prem,C5bis,General Court established assessed facts Court...,L,"[Prec, Rule]","[0.8046875, -1.4853515625, -1.005859375, 1.484..."

In [7]:
df_train_Itpr = df_train[df_train['Scheme'].apply(lambda x: contains_str(x, 'Itpr'))]
df_train_Itpr

,Document,Split,Name,Id,Text,Type,Scheme,embeddings
1,A2008_Commission of the European Communities v...,1,prem,A2,Also clear consistent caselaw Articles 4 CS 67...,L,"[Itpr, Prec, Rule]","[0.93017578125, -1.0146484375, 0.0575256347656..."
4,A2008_Commission of the European Communities v...,1,prem,A5,Court held particular inconceivable authors EC...,L,"[Itpr, Prec, Rule]","[1.0849609375, -0.98828125, 0.39453125, 0.8774..."
7,A2008_Commission of the European Communities v...,1,prem,A8,Finally State aid granted undertaking falling ...,L,Itpr,"[-0.6279296875, -1.154296875, 1.5390625, 0.588..."
8,A2008_Commission of the European Communities v...,1,prem,A9,light foregoing must consequently held Article...,L,"[Itpr, Rule]","[0.65283203125, -1.828125, 0.75, 1.142578125, ..."
9,A2008_Commission of the European Communities v...,1,prem,A10,Contrary German Government claims interpretati...,"[F, L]","[Itpr, Rule]","[0.460693359375, -0.8759765625, -0.6455078125,..."
...,...,...,...,...,...,...,...,...
2499,R2021_World Duty Free v,5,prem,D14,regard must borne mind accordance caselaw ment...,L,"[Itpr, Prec]","[1.9736328125, -1.0966796875, 0.06695556640625..."
2507,R2021_World Duty Free v,5,prem,E2,party entitled put forward pleas arguments ari...,L,Itpr,"[0.4736328125, -0.90234375, 0.394287109375, 2...."
2508,R2021_World Duty Free v,5,prem,E3,appellants therefore entitled call question fi...,L,Itpr,"[1.095703125, -1.23828125, -0.1693115234375, 1..."
2526,R2021_World Duty Free v,5,prem,H4,pointed paragraph 146 appeal plea directed gro...,"[F, L]",Itpr,"[0.34423828125, -0.83349609375, -0.04077148437..."
2529,R2021_World Duty Free v,5,prem,H6bis,hand General Court rightly pointed paragraph 2...,L,Itpr,"[1.4169921875, -1.34765625, -0.240234375, 1.42..."

In [8]:
df_train_Aut = df_train[df_train['Scheme'].apply(lambda x: contains_str(x, 'Aut'))]
df_train_Aut

,Document,Split,Name,Id,Text,Type,Scheme,embeddings
316,A2013_European Commission v Ireland and Others,3,prem,A9,Yet submitted Commission stated Advocate Gener...,F,Aut,"[1.9296875, -0.994140625, -1.013671875, 1.4736..."
402,A2016_European Commission v Aer Lingus Ltd and...,3,prem,A6,Advocate General observed essence point 41 Opi...,F,Aut,"[1.861328125, -0.7568359375, 0.1915283203125, ..."
435,A2016_European Commission v Aer Lingus Ltd and...,3,prem,D11,follows Advocate General observed essence poin...,L,"[Aut, Itpr]","[0.7578125, -1.0390625, -0.47314453125, 0.9809..."
520,A2016_European_Commission_v_World_Duty_Free,4,prem,B1,regards caselaw relating aid exports relied co...,"[F, L]","[Aut, Itpr, Prec]","[0.56640625, -0.97802734375, -0.8818359375, 0...."
524,A2016_European_Commission_v_World_Duty_Free,4,prem,B5,observed essence Advocate General points 133 1...,L,Aut,"[1.6123046875, -0.6708984375, -0.1895751953125..."
569,A2017_European Commission v Italian Republic_DT,4,prem,A10,addition Advocate General stated point 38 opin...,F,Aut,"[1.5224609375, -0.841796875, -0.388427734375, ..."
609,A2017_European Commission v Italian Republic_DT,4,prem,B37,apparent paragraphs 46 52 observed essence Adv...,L,"[Aut, Itpr]","[1.330078125, -0.74267578125, 0.00800323486328..."
755,A2018_Dirk Andres v European Commission,5,prem,A13,also noted essence Advocate General points 57 ...,"[F, L]","[Aut, Prec, Rule]","[1.1591796875, -0.7392578125, -0.53076171875, ..."
798,A2018_Dirk Andres v European Commission,5,prem,C22,Consequently also noted essence Advocate Gener...,L,Aut,"[1.205078125, -0.26904296875, -0.316650390625,..."
809,A2018_Dirk Andres v European Commission,5,prem,C22|C23|C32,also noted essence Advocate General point 109 ...,L,"[Aut, Itpr]","[1.5673828125, 0.0211334228515625, -0.61865234..."
820,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,A3,Advocate General observes point 26 Opinion int...,L,"[Aut, Itpr, Rule]","[1.2353515625, -1.255859375, 0.927734375, 0.81..."
832,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,A14,Advocate General observes points 48 49 Opinion...,L,"[Aut, Itpr, Rule]","[0.62841796875, -1.1826171875, 0.380126953125,..."
860,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,B17,Advocate General observes substance point 52 O...,F,Aut,"[1.15625, -0.81494140625, 0.233154296875, 1.35..."
880,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,C18,circumstances Advocate General observes point ...,F,Aut,"[0.93603515625, -1.82421875, 0.36474609375, 0...."
887,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,D5,Advocate General observes points 107 110 Opini...,L,"[Aut, Prec, Princ]","[0.79833984375, -0.74951171875, -0.25024414062..."
910,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,D27,Advocate General observes points 116 117 Opini...,F,Aut,"[0.9892578125, -1.412109375, -0.958984375, 1.8..."
971,R2000_French Republic v Ladbroke Racing Ltd an...,1,prem,A18,Advocate General states points 25 26 Opinion C...,F,Aut,"[0.93603515625, -0.80517578125, -0.52392578125..."
994,R2000_French Republic v Ladbroke Racing Ltd an...,1,prem,B6,regard suffice state Advocate General done poi...,F,Aut,"[1.3095703125, -0.48681640625, -0.876953125, 2..."
1000,R2000_French Republic v Ladbroke Racing Ltd an...,1,prem,C5,Advocate General states point 42 Opinion asses...,F,Aut,"[1.0576171875, -0.607421875, 0.017501831054687..."
1433,R2011_France Télécom SA v European Commission,5,prem,A16,Advocate General stated point 59 Opinion prese...,F,Aut,"[1.3046875, -0.395263671875, 0.2066650390625, ..."
1467,R2011_France Télécom SA v European Commission,5,prem,B26,Advocate General observed point 100 Opinion ov...,F,Aut,"[1.5263671875, -0.55126953125, -0.77783203125,..."
1617,R2013_Telefónica SA v European Commission,3,prem,A1,Advocate General observed points 40 41 Opinion...,L,"[Aut, Itpr, Rule]","[0.7158203125, -1.1513671875, 0.309814453125, ..."
1624,R2013_Telefónica SA v European Commission,3,prem,A8,Second Advocate General observed point 48 Opin...,L,"[Aut, Itpr, Rule]","[0.172119140625, -1.1455078125, 0.8369140625, ..."
1628,R2013_Telefónica SA v European Commission,3,prem,A12,Advocate General observed point 33 Opinion Tel...,F,Aut,"[0.5458984375, -0.78515625, 0.0069999694824218..."
1629,R2013_Telefónica SA v European Commission,3,prem,A13,First Advocate General observed point 48 Opini...,F,Aut,"[1.638671875, -1.1435546875, -0.1285400390625,..."
1654,R2015_European Commission v MOL Magyar Olaj- é...,3,prem,A1,must observed outset Advocate General stated p...,L,"[Aut, Class, Rule]","[0.94140625, -0.65380859375, 0.045928955078125..."
1663,R2015_European Commission v MOL Magyar Olaj- é...,3,prem,A10,Advocate General stated point 86 Opinion funda...,"[F, L]","[Aut, Itpr]","[1.0322265625, -0.260986328125, 0.096252441406..."
1680,R2015_European Commission v MOL Magyar Olaj- é...,3,prem,B9,Advocate General stated point 91 Opinion issue...,F,Aut,"[1.2783203125, -1.2470703125, 0.13623046875, 1..."
1691,R2015_European Commission v MOL Magyar Olaj- é...,3,prem,C10,Advocate General stated points 107 114 Opinion...,F,Aut,"[1.5654296875, -1.26953125, -0.10546875, 0.595..."
1757,R2016_DTS Distribuidora de Televisión Digital,4,prem,D30,noted Advocate General point 96 Opinion DTS’s ...,L,"[Aut, Itpr, Rule]","[0.60498046875, -0.10125732421875, -1.00683593..."
1791,R2016_DTS Distribuidora de Televisión Digital,4,prem,H10,noted Advocate General point 219 Opinion provi...,L,"[Aut, Itpr, Rule]","[0.6826171875, -1.66796875, 0.08990478515625, ..."
1840,R2016_European Commission v Hansestadt Lübeck,4,prem,C16,concept selectivity Advocate General states po...,L,"[Aut, Itpr]","[1.9609375, -0.69775390625, 1.1201171875, 1.08..."
1844,R2016_European Commission v Hansestadt Lübeck,4,prem,C20,Advocate General argues points 77 86 89 Opinio...,L,"[Aut, Prec]","[0.496337890625, -0.459228515625, -0.134765625..."
1854,R2016_European Commission v Hansestadt Lübeck,4,prem,C30,Accordingly apparent Advocate General states p...,F,Aut,"[1.1796875, -0.720703125, -0.218505859375, 1.5..."
1923,R2016_Hellenic Republic v European Commission,4,prem,C2,Consequently Advocate General observed points ...,F,Aut,"[0.8857421875, -1.2080078125, -0.701171875, 1...."
2027,R2016_Orange v European Commission,4,prem,A8,noted observed Advocate General point 42 Opini...,F,Aut,"[1.23046875, -0.52001953125, -0.89697265625, 1..."
2052,R2016_Orange v European Commission,4,prem,B3,findings observed Advocate General points 66 7...,L,"[Aut, Prec]","[1.146484375, -0.84716796875, -0.87060546875, ..."
2067,R2016_Orange v European Commission,4,prem,D3,Accordingly first Advocate General observed po...,F,Aut,"[0.796875, -0.339111328125, 0.0650634765625, 1..."
2069,R2016_Orange v European Commission,4,prem,D5,Second Advocate General observed point 85 Opin...,F,Aut,"[0.60107421875, -0.654296875, 0.2017822265625,..."
2072,R2016_Orange v European Commission,4,prem,E1,Advocate General noted points 90 93 Opinion ob...,F,Aut,"[0.86279296875, -1.337890625, -0.1842041015625..."
2073,R2016_Orange v European Commission,4,prem,E2,Therefore arguments put forward Orange appeal ...,F,Aut,"[0.822265625, 0.0293731689453125, -0.789550781..."
2172,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B17,finding paragraph 35 present judgment supporte...,L,"[Aut, Rule]","[0.7314453125, -1.263671875, 0.372314453125, 1..."
2182,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,C8,Moreover Advocate General observed point 58 Op...,F,Aut,"[-0.1265869140625, -1.0302734375, -0.494384765..."
2246,"R2021_Prosegur Compañía de Seguridad SA, estab...",5,prem,A7,Furthermore Advocate General observed point 35...,F,Aut,"[0.982421875, -0.958984375, -0.6103515625, 0.5..."
2254,"R2021_Prosegur Compañía de Seguridad SA, estab...",5,prem,B7,Consequently Advocate General observed essence...,"[F, L]","[Aut, Itpr, Prec]","[0.352294921875, -0.81787109375, -0.8891601562..."
2291,"R2021_Prosegur Compañía de Seguridad SA, estab...",5,prem,B39,Consequently Advocate General observed point 6...,F,Aut,"[0.84375, -0.59228515625, -0.57861328125, 0.05..."
2394,R2021_World Duty Free v,5,prem,A7,Furthermore Advocate General observed point 35...,F,Aut,"[0.55029296875, -0.89013671875, 0.191162109375..."
2402,R2021_World Duty Free v,5,prem,B7,Consequently Advocate General observed essence...,"[F, L]","[Aut, Itpr]","[0.70849609375, -0.693359375, 0.07012939453125..."
2438,R2021_World Duty Free v,5,prem,B39,Consequently Advocate General observed point 6...,F,Aut,"[0.822265625, -0.32958984375, 0.31494140625, -..."

In [9]:
df_train_Class = df_train[df_train['Scheme'].apply(lambda x: contains_str(x, 'Class'))]
df_train_Class

,Document,Split,Name,Id,Text,Type,Scheme,embeddings
120,A2009_Commission of the European Communities v...,1,prem,A2,relation first condition set therein settled c...,L,"[Class, Prec]","[0.9697265625, -1.6416015625, 0.5419921875, 1...."
121,A2009_Commission of the European Communities v...,1,prem,A3,present case Court First Instance held paragra...,F,"[Class, Prec, Rule]","[1.4775390625, -0.89404296875, -0.7373046875, ..."
463,A2016_European_Commission_v_World_Duty_Free,4,prem,A1,First must recalled according Court’s settled ...,L,"[Class, Prec, Rule]","[0.418701171875, -0.712890625, -0.207397460937..."
464,A2016_European_Commission_v_World_Duty_Free,4,prem,A1bis,First must intervention State State resources,L,Class,"[1.8837890625, -1.041015625, -0.82080078125, 2..."
465,A2016_European_Commission_v_World_Duty_Free,4,prem,A1ter,Second intervention must liable affect trade M...,L,Class,"[1.5693359375, -1.37890625, -0.32177734375, 2...."
467,A2016_European_Commission_v_World_Duty_Free,4,prem,A1quater,Fourth must distort threaten distort competiti...,L,"[Class, Prec]","[0.681640625, -0.297119140625, -0.7919921875, ..."
612,A2017_European Commission v TV2_Danmark A_S,5,prem,A1,accordance Court’s settled caselaw classificat...,L,"[Class, Prec, Rule]","[0.7919921875, -1.1328125, -0.8232421875, 0.68..."
613,A2017_European Commission v TV2_Danmark A_S,5,prem,A2,provision sets four conditions,L,Class,"[0.60986328125, -0.7099609375, 0.8125, 1.06640..."
614,A2017_European Commission v TV2_Danmark A_S,5,prem,A2bis,First must intervention State State resources,L,Class,"[1.8837890625, -1.041015625, -0.82080078125, 2..."
615,A2017_European Commission v TV2_Danmark A_S,5,prem,A2ter,Second intervention must liable affect trade M...,L,Class,"[1.5693359375, -1.37890625, -0.32177734375, 2...."
616,A2017_European Commission v TV2_Danmark A_S,5,prem,A2quater,Third must confer advantage recipient,L,Class,"[1.859375, -0.51611328125, -1.455078125, 2.179..."
617,A2017_European Commission v TV2_Danmark A_S,5,prem,A2quinquies,Fourth must distort threaten distort competiti...,L,"[Class, Prec]","[0.5009765625, 0.1854248046875, -0.26220703125..."
653,A2018_Commission v Spain,5,prem,A9,term ‘undertaking’ context covers entity engag...,L,Class,"[-0.167724609375, -1.546875, 0.68603515625, 0...."
654,A2018_Commission v Spain,5,prem,A9bis,activity consisting offering goods services gi...,L,"[Class, Prec]","[-0.151123046875, -0.919921875, 0.46240234375,..."
655,A2018_Commission v Spain,5,prem,A10,According settled caselaw Court Justice classi...,L,"[Class, Prec, Rule]","[0.1878662109375, -0.7578125, 0.02291870117187..."
656,A2018_Commission v Spain,5,prem,A10bis,First must intervention State State resources,L,Class,"[1.8837890625, -1.041015625, -0.82080078125, 2..."
657,A2018_Commission v Spain,5,prem,A10ter,Second intervention must liable affect trade M...,L,Class,"[1.5693359375, -1.37890625, -0.32177734375, 2...."
658,A2018_Commission v Spain,5,prem,A10quater,Third must confer selective advantage recipient,L,Class,"[1.580078125, -0.252685546875, -1.2314453125, ..."
659,A2018_Commission v Spain,5,prem,A10quinquies,Fourth must distort threaten distort competiti...,L,"[Class, Prec]","[0.1343994140625, -0.9013671875, -0.9614257812..."
780,A2018_Dirk Andres v European Commission,5,prem,C9,merits recalled according Court’s settled case...,L,"[Class, Rule]","[0.74755859375, -0.91748046875, 0.024200439453..."
781,A2018_Dirk Andres v European Commission,5,prem,C9bis,First must intervention State State resources,L,Class,"[1.8837890625, -1.041015625, -0.82080078125, 2..."
782,A2018_Dirk Andres v European Commission,5,prem,C9ter,Second intervention must liable affect trade M...,L,Class,"[1.5693359375, -1.37890625, -0.32177734375, 2...."
783,A2018_Dirk Andres v European Commission,5,prem,C9quater,Third must confer selective advantage recipient,L,Class,"[1.580078125, -0.252685546875, -1.2314453125, ..."
784,A2018_Dirk Andres v European Commission,5,prem,C9quinquies,Fourth must distort threaten distort competiti...,L,"[Class, Prec]","[0.54150390625, -0.9609375, -0.892578125, 1.77..."
785,A2018_Dirk Andres v European Commission,5,prem,C10,far concerns condition relating selectivity ad...,L,"[Class, Prec]","[1.41015625, -1.181640625, -0.418701171875, 0...."
789,A2018_Dirk Andres v European Commission,5,prem,C14,context order classify national tax measure ‘s...,L,"[Class, Prec]","[1.4462890625, -0.9912109375, -0.7880859375, 1..."
791,A2018_Dirk Andres v European Commission,5,prem,C16,examination selectivity condition therefore im...,L,"[Class, Prec]","[0.63671875, -0.9638671875, -0.35107421875, 0...."
828,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,A10,second place recalled according settled casela...,L,"[Class, Prec]","[0.98779296875, -0.8427734375, -0.26123046875,..."
833,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,A15,issue whether act general application concerns...,L,"[Class, Rule]","[0.5205078125, -1.1328125, -0.0205535888671875..."
844,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,B1,According settled caselaw Court condition natu...,L,"[Class, Prec, Rule]","[0.383544921875, -0.8818359375, -0.03009033203..."
912,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,D29,may seen paragraphs 90 92 recovery unlawful ai...,L,"[Class, Itpr]","[-0.0167694091796875, -1.3232421875, -0.049102..."
919,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,E2,context concept ‘undertaking’ covers entity en...,L,"[Class, Prec]","[-0.5302734375, -0.41650390625, -0.29663085937..."
920,A2018_Scuola Elementare Maria Montessori Srl v...,3,prem,E3,activity consisting offering services given ma...,L,Class,"[1.123046875, -1.01953125, 0.270751953125, 1.6..."
930,R1997_Tiercé Ladbroke SA v Commission of the E...,1,prem,A2,order State aid within meaning provision neces...,L,"[Class, Rule]","[-0.08001708984375, -1.59375, 0.6865234375, 0...."
942,R1997_Tiercé Ladbroke SA v Commission of the E...,1,prem,A13,Since two categories bet identical existence a...,"[F, L]","[Class, Rule]","[1.095703125, 0.11041259765625, 0.183227539062..."
1654,R2015_European Commission v MOL Magyar Olaj- é...,3,prem,A1,must observed outset Advocate General stated p...,L,"[Aut, Class, Rule]","[0.94140625, -0.65380859375, 0.045928955078125..."
1820,R2016_European Commission v Hansestadt Lübeck,4,prem,C1,General Court recalled paragraph 43 judgment a...,L,"[Class, Prec, Rule]","[0.736328125, -1.05859375, -0.2491455078125, 1..."
1821,R2016_European Commission v Hansestadt Lübeck,4,prem,C1bis,First must intervention State State resources,L,Class,"[1.8837890625, -1.041015625, -0.82080078125, 2..."
1822,R2016_European Commission v Hansestadt Lübeck,4,prem,C1ter,Second intervention must liable affect trade M...,L,Class,"[1.5693359375, -1.37890625, -0.32177734375, 2...."
1823,R2016_European Commission v Hansestadt Lübeck,4,prem,C1quater,Third must confer selective advantage recipient,L,Class,"[1.580078125, -0.252685546875, -1.2314453125, ..."
1824,R2016_European Commission v Hansestadt Lübeck,4,prem,C1quinquies,Fourth must distort threaten distort competiti...,L,"[Class, Prec]","[0.681640625, -0.297119140625, -0.7919921875, ..."
1825,R2016_European Commission v Hansestadt Lübeck,4,prem,C2,far concerns condition relating selectivity ad...,L,"[Class, Prec, Rule]","[-0.485107421875, -0.61767578125, 0.876953125,..."
2148,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B2,connection must recalled national measure cate...,L,"[Class, Rule]","[0.491455078125, -0.85009765625, 1.14453125, 1..."
2149,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B2bis,second intervention must liable affect trade M...,L,Class,"[1.365234375, -1.1513671875, 0.31396484375, 2...."
2150,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B2ter,third must confer selective advantage recipien...,L,Class,"[1.1455078125, -0.650390625, -0.8134765625, 0...."
2155,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B6,accordance paragraphs 88 93 judgment 24 July 2...,L,"[Class, Prec]","[0.58642578125, 0.2548828125, 0.408447265625, ..."
2156,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B6a,First recipient undertaking must actually publ...,L,Class,"[1.3857421875, -1.3671875, 0.8095703125, 1.728..."
2157,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B6b,Second parameters basis compensation calculate...,L,Class,"[1.7666015625, -0.5, 0.6669921875, 1.559570312..."
2158,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B6c,Third compensation must exceed necessary cover...,L,Class,"[0.77099609375, -1.8828125, 0.022216796875, 2...."
2159,R2017_Viasat Broadcasting UK Ltd v European Co...,3,prem,B6d,Fourth level compensation needed must determin...,L,Class,"[1.51953125, -1.68359375, -0.1859130859375, 1...."
2191,R2021_FVE Holýšov I and Others v Commission,5,prem,B3,Furthermore contrary appellants claim cannot r...,"[F, L]",Class,"[1.353515625, -0.187255859375, -0.408447265625..."

In [10]:
df_train_Prec = df_train[df_train['Scheme'].apply(lambda x: contains_str(x, 'Prec'))]
df_train_Prec

,Document,Split,Name,Id,Text,Type,Scheme,embeddings
1,A2008_Commission of the European Communities v...,1,prem,A2,Also clear consistent caselaw Articles 4 CS 67...,L,"[Itpr, Prec, Rule]","[0.93017578125, -1.0146484375, 0.0575256347656..."
2,A2008_Commission of the European Communities v...,1,prem,A3,Court deduces Article 67 CS covers general mea...,L,"[Prec, Rule]","[0.195556640625, -1.734375, -0.1546630859375, ..."
3,A2008_Commission of the European Communities v...,1,prem,A4,Court also held action taken Article 67 CS can...,L,"[Prec, Rule]","[0.404296875, -0.2352294921875, 0.34326171875,..."
4,A2008_Commission of the European Communities v...,1,prem,A5,Court held particular inconceivable authors EC...,L,"[Itpr, Prec, Rule]","[1.0849609375, -0.98828125, 0.39453125, 0.8774..."
5,A2008_Commission of the European Communities v...,1,prem,A6,Court also held first indent Article 672 CS de...,L,"[Prec, Rule]","[0.05633544921875, -1.2216796875, 0.4230957031..."
...,...,...,...,...,...,...,...,...
2502,R2021_World Duty Free v,5,prem,D16,Court Justice held measure measure issue desig...,L,Prec,"[1.08203125, -1.0966796875, -0.65283203125, 0...."
2514,R2021_World Duty Free v,5,prem,F2,arguments cannot however upheld since apparent...,"[F, L]","[Prec, Princ]","[0.37890625, 0.330322265625, 0.5732421875, 0.6..."
2515,R2021_World Duty Free v,5,prem,F3,stage Member State thus called demonstrate dif...,L,"[Prec, Princ]","[1.11328125, -1.2724609375, 0.088134765625, 0...."
2520,R2021_World Duty Free v,5,prem,G4,accordance settled caselaw appeal plea directe...,L,Prec,"[0.5693359375, -1.30078125, 0.0073127746582031..."
2521,R2021_World Duty Free v,5,prem,G5,present case even fifth part single ground app...,L,Prec,"[0.484130859375, -0.362548828125, -0.387695312..."

In [11]:
df_test = df[df['Split'] == 2]
df_test = df_test.dropna(subset = ['Scheme'])
df_test

,Document,Split,Name,Id,Text,Type,Scheme,embeddings
172,A2010_NDSHT Nya Destination Stockholm Hotell &...,2,prem,A2,regard must observed follows Article 58 Statut...,L,"[Prec, Rule]","[0.5068359375, -1.6494140625, -0.43408203125, ..."
177,A2010_NDSHT Nya Destination Stockholm Hotell &...,2,prem,B2,regard Court repeatedly held action annulment ...,L,"[Prec, Rule]","[1.076171875, -0.91064453125, -0.53271484375, ..."
178,A2010_NDSHT Nya Destination Stockholm Hotell &...,2,prem,B3,follows also settled caselaw concerning admiss...,L,Prec,"[0.90185546875, -1.087890625, -0.5048828125, 1..."
179,A2010_NDSHT Nya Destination Stockholm Hotell &...,2,prem,B4,contrast form act decision adopted principle i...,L,Itpr,"[0.92431640625, -0.471435546875, -0.3063964843..."
180,A2010_NDSHT Nya Destination Stockholm Hotell &...,2,prem,B5,therefore principle irrelevant classification ...,L,Itpr,"[0.7216796875, -0.82373046875, 0.39501953125, ..."
...,...,...,...,...,...,...,...,...
2123,R2017_European Commission v Frucona Košice a,2,prem,D13,connection also borne mind lawfulness decision...,L,Prec,"[0.83251953125, -0.8701171875, -0.16796875, 1...."
2124,R2017_European Commission v Frucona Košice a,2,prem,D14,However information ‘available’ Commission inc...,L,"[Itpr, Prec]","[1.4931640625, -1.1728515625, -0.70751953125, ..."
2126,R2017_European Commission v Frucona Košice a,2,prem,D16,Paragraphs 180 213 235 judgment appeal Commiss...,F,Itpr,"[0.55419921875, -1.5498046875, -0.5234375, 1.4..."
2130,R2017_European Commission v Frucona Košice a,2,prem,D20,Advocate General noted paragraphs 125 131 Opin...,F,Aut,"[1.2119140625, -1.08984375, 0.0924072265625, -..."
2135,R2017_European Commission v Frucona Košice a,2,prem,D25,considerations far concern information normall...,"[F, L]",Prec,"[0.62255859375, -1.1865234375, -0.74951171875,..."

In [12]:
device = torch.device('cuda')
model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"

In [13]:
pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"torch_dtype": torch.bfloat16,
                  "quantization_config": {"load_in_4bit": True}},
    device_map="cuda:0"
)

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0

In [14]:
def test(template, nexamples, df_train = df_train, df_train_Aut = df_train_Aut, df_train_Class = df_train_Class, df_train_Itpr = df_train_Itpr, df_train_Prec = df_train_Prec, df_train_Rule = df_train_Rule):

    count = 0
    autTP = 0
    autFN = 0
    autFP = 0
    classTP = 0
    classFN = 0
    classFP = 0
    itprTP = 0
    itprFN = 0
    itprFP = 0
    precTP = 0
    precFN = 0
    precFP = 0
    #princTP = 0
    #princFN = 0
    #princFP = 0
    ruleTP = 0
    ruleFN = 0
    ruleFP = 0

    for i in range(len(df_test)):

        query = 'Text: '+ df_test.iloc[i]['Text']+'\n'+'Answer: '

        df_train = df_train.sample(frac = 1, random_state = random_state)
        df_train_Aut = df_train_Aut.sample(frac = 1, random_state = random_state)
        df_train_Class = df_train_Class.sample(frac = 1, random_state = random_state)
        df_train_Itpr = df_train_Itpr.sample(frac = 1, random_state = random_state)
        df_train_Prec = df_train_Prec.sample(frac = 1, random_state = random_state)
        df_train_Rule = df_train_Rule.sample(frac = 1, random_state = random_state)

        examples = list(range((nexamples+4)//5))

        examples_text = []


        for el in list(examples):
            examples_text.append('Text: '+ df_train_Aut.iloc[el]['Text'] + '\n' + 'Answer: '+ str(df_train_Aut.iloc[el]['Scheme'])+'\n\n')
            examples_text.append('Text: '+ df_train_Class.iloc[el]['Text'] + '\n' + 'Answer: '+ str(df_train_Class.iloc[el]['Scheme'])+'\n\n')
            examples_text.append('Text: '+ df_train_Itpr.iloc[el]['Text'] + '\n' + 'Answer: '+ str(df_train_Itpr.iloc[el]['Scheme'])+'\n\n')
            examples_text.append('Text: '+ df_train_Prec.iloc[el]['Text'] + '\n' + 'Answer: '+ str(df_train_Prec.iloc[el]['Scheme'])+'\n\n')
            examples_text.append('Text: '+ df_train_Rule.iloc[el]['Text'] + '\n' + 'Answer: '+ str(df_train_Rule.iloc[el]['Scheme'])+'\n\n')
            
        if (nexamples) % 2 == 1:
                examples_text.append('Text: '+ df_train.iloc[0]['Text'] + '\n' + 'Answer: '+ str(df_train.iloc[0]['Scheme'])+'\n\n')
            
        random.shuffle(examples_text)

        examples_text = examples_text[:nexamples]
        
        text_examples = ''
        for el in examples_text:
            text_examples += el
            
        print('query:\n'+ query,'\n')
        print('retrieved examples:\n\n'+ text_examples,'\n\n')

        messages = [{'role': 'system', 'content': template},{"role": "user", "content": text_examples},{"role": "user", "content": query}]

        outputs = pipeline(
            messages,
            max_new_tokens=10,
            do_sample = False
        )
        final_output = outputs[0]['generated_text'][-1]['content']
        print('LLM output:', final_output)
        print('ground truth:', df_test.iloc[i]['Scheme'])
        print(200*'-')

        if 'Aut' in final_output and 'Aut' in df_test.iloc[i]['Scheme']:
            autTP += 1
        if 'Aut' in final_output and 'Aut' not in df_test.iloc[i]['Scheme']:
            autFP += 1
        if 'Aut' not in final_output and 'Aut' in df_test.iloc[i]['Scheme']:
            autFN += 1
        
        if 'Class' in final_output and 'Class' in df_test.iloc[i]['Scheme']:
            classTP += 1
        if 'Class' in final_output and 'Class' not in df_test.iloc[i]['Scheme']:
            classFP += 1
        if 'Class' not in final_output and 'Class' in df_test.iloc[i]['Scheme']:
            classFN += 1

        if 'Itpr' in final_output and 'Itpr' in df_test.iloc[i]['Scheme']:
            itprTP += 1
        if 'Itpr' in final_output and 'Itpr' not in df_test.iloc[i]['Scheme']:
            itprFP += 1
        if 'Itpr' not in final_output and 'Itpr' in df_test.iloc[i]['Scheme']:
            itprFN += 1

        if 'Prec' in final_output and 'Prec' in df_test.iloc[i]['Scheme']:
            precTP += 1
        if 'Prec' in final_output and 'Prec' not in df_test.iloc[i]['Scheme']:
            precFP += 1
        if 'Prec' not in final_output and 'Prec' in df_test.iloc[i]['Scheme']:
            precFN += 1

        if 'Rule' in final_output and 'Rule' in df_test.iloc[i]['Scheme']:
            ruleTP += 1
        if 'Rule' in final_output and 'Rule' not in df_test.iloc[i]['Scheme']:
            ruleFP += 1
        if 'Rule' not in final_output and 'Rule' in df_test.iloc[i]['Scheme']:
            ruleFN += 1

    if autTP == 0:
        autF1 = 0
    else:
        autPREC = autTP/(autTP+autFP)
        autREC = autTP/(autTP+autFN)
        autF1 = 2/((1/autPREC)+(1/autREC))

    if classTP == 0:
        classF1 = 0
    else:
        classPREC = classTP/(classTP+classFP)
        classREC = classTP/(classTP+classFN)
        classF1 = 2/((1/classPREC)+(1/classREC))

    if itprTP == 0:
        itprF1 = 0
    else:
        itprPREC = itprTP/(itprTP+itprFP)
        itprREC = itprTP/(itprTP+itprFN)
        itprF1 = 2/((1/itprPREC)+(1/itprREC))

    if precTP == 0:
        precF1 = 0
    else:
        precPREC = precTP/(precTP+precFP)
        precREC = precTP/(precTP+precFN)
        precF1 = 2/((1/precPREC)+(1/precREC))

    if ruleTP == 0:
        ruleF1 = 0
    else:
        rulePREC = ruleTP/(ruleTP+ruleFP)
        ruleREC = ruleTP/(ruleTP+ruleFN)
        ruleF1 = 2/((1/rulePREC)+(1/ruleREC))

    print('Authoritative F1:', autF1)
    print('Verbal Classification F1:', classF1)
    print('Interpretation F1:', itprF1)
    print('Precedent F1:', precF1)
    print('Rule F1:', ruleF1)
    print()


    print('macro F1:', (autF1 + classF1 + itprF1 + precF1 + ruleF1)/5)
    print('macro F1 (reliable):', (autF1 + precF1 + ruleF1)/3)

In [15]:
template = '''Classify the following legal premise as one or more of the following argumentative schemes: Rule, Prec, Class, Itpr, Aut. Rule: whether there is an explicit or implicit reference to an article of law or citation of the text of a certain article. Prec: whether there is a reference to a previous ruling of the Supreme Court or the Court of Justice of the European Union. Class: if there is a definition of a legal concept or its constituent elements. Itpr: if there is reference to one of the interpretative criteria contained in Article 12 of the prelegislations (literal, teleological, psychological, systematic) to the Civil Code. Aut: if there is a reference to an indication by an authority (e.g. an opinion of the Advocate General). The expected output is a list with all applicable labels. For example: ['Prec', 'Aut', 'Rule']. Only reply with the list of labels.'''

In [16]:
test(template, 5)

C:\Users\alfio\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\generation\configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
C:\Users\alfio\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\generation\configuration_utils.py:633: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

query:
Text: regard must observed follows Article 58 Statute Court Justice conjunction Article 1132 Rules Procedure Court Justice appeal appellant may put forward relevant argument provided subjectmatter proceedings General Court changed appeal Case C‑22905 P PKK KNK v Council 2007 ECR I‑439 paragraph 66 Case C‑806 P Herrero Romeu v Commission 2007 ECR I‑10333 paragraph 32
Answer:

retrieved examples:

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Aut']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard Court repeatedly held action annulment purposes Article 230 EC must available acts adopted institutions whatever nature form intended legal effects capable affecting interests applicant bringing distinct change legal position see inter alia Athinaïki Techniki v Commission paragraph 29 caselaw cited Case C‑36208 P Internationaler Hilfsfonds v Commission 2010 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Third must confer selective advantage recipient
Answer: Class

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Aut', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows also settled caselaw concerning admissibility actions annulment necessary look actual substance acts challenged order classify see particular Case 6081 IBM v Commission 1981 ECR 2639 paragraph 9 Case C‑14796 Netherlands v Commission 2000 ECR I‑4723 paragraph 27
Answer:

retrieved examples:

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: contrary settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrast form act decision adopted principle irrelevant right challenge acts decisions way action annulment
Answer:

retrieved examples:

Text: said appellant entitled lodge appeal relying Court Justice grounds arguments arise judgment appeal seek criticise law correctness judgments 29 November 2007 Stadtwerke Schwäbisch Hall Others v Commission C‑17606 P published EUC2007730 paragraph 17 4 March 2021 Commission v Fútbol Club Barcelona C‑36219 P EUC2021169 paragraph 47
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore principle irrelevant classification act question whether satisfies certain formal requirements namely particular duly identified author mentions provisions providing legal basis
Answer:

retrieved examples:

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore irrelevant act may described ‘decision’ refer Article 42 3 4 Regulation 6591999
Answer:

retrieved examples:

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also importance Member State concerned notified act issue Commission infringing Article 25 regulation error capable altering substance act see Athinaïki Techniki v Commission paragraphs 43 44 caselaw cited
Answer:

retrieved examples:

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore principle measures definitively determine position Commission upon conclusion administrative procedure intended legal effects capable affecting interests complainant constitute acts open challenge purposes Article 230 EC intermediate measures whose purpose prepare final decision effects see Athinaïki Techniki v Commission paragraph 42 caselaw cited
Answer:

retrieved examples:

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard possible definitive actionable nature measures taken Commission procedure reviewing State aid noted first Commission must Article 101 Regulation 6591999 carry examination possession information whatever source regarding allegedly unlawful aid
Answer:

retrieved examples:

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: test applicable among factors Commission required take account purposes establishing whether aid exists see effect Case C34296 Spain v Commission 1999 ECR I2459 paragraph 46 Case C25697 DM Transport 1999 ECR I3913 paragraph 24 Commission v EDF paragraphs 78 103
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination complaint basis provision gives rise initiation preliminary examination stage Article 883 EC obliges Commission examine immediately possible existence aid compatibility common market see effect Athinaïki Techniki v Commission paragraph 37
Answer:

retrieved examples:

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: regard Court’s established caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 94 caselaw cited
Answer: Prec

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 131 Regulation 6591999 applicable context examination complaint alleging unlawful aid obliges Commission close preliminary examination stage adopting decision pursuant Article 42 3 4 regulation say decision finding aid exist raising objections initiating formal investigation procedure since institution authorised persist failure act preliminary examination stage
Answer:

retrieved examples:

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: stage procedure completed Commission bound consequently either initiate next stage procedure provided Article 882 EC adopt definitive decision rejecting complaint see effect Athinaïki Techniki v Commission paragraph 40 caselaw cited
Answer:

retrieved examples:

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain business sectors judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 55 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission finds following examination complaint investigation revealed grounds concluding State aid within meaning Article 87 EC refuses implication initiate procedure provided Article 882 EC see effect Case C‑36795 P Commission v Sytraval Brink’s France 1998 ECR I‑1719 paragraph 47
Answer:

retrieved examples:

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards Commission’s finding measures complained constituted existing aid noted existing aid course subject constant review provided Article 881 EC must regarded lawful long Commission found incompatible common market see Case C‑4493 NamurLes assurances du crédit 1994 ECR I‑3829 paragraph 34 Case C‑40099 Italy v Commission 2001 ECR I‑7303 paragraph 48
Answer:

retrieved examples:

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However receives complaint relating allegedly unlawful aid Commission classifying measure existing aid subjects procedure provided Article 881 EC thus refuses implication initiate procedure provided Article 882 EC see effect CIRFS Others v Commission paragraphs 25 26 Case C‑32199 P ARAP Others v Commission 2002 ECR I‑4287 paragraph 61
Answer:

retrieved examples:

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Prec']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: decision refusing initiate procedure provided Article 882 EC definitive cannot characterised mere provisional measure CIRFS Others v Commission paragraph 26 effect Athinaïki Techniki v Commission paragraphs 54 58
Answer:

retrieved examples:

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: situation persons intended benefit procedural guarantees afforded provision may secure compliance therewith able challenge decision question European Union judicature fourth paragraph Article 230 EC
Answer:

retrieved examples:

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: New aid therefore subject precautionary review Commission may principle put effect time latter declared compatible Treaty
Answer: Itpr

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: principle applies equally whether ground decision taken Commission regards aid compatible common market view existence aid must discounted Commission v Sytraval Brink’s France paragraph 47 considers existing aid see effect CIRFS Others v Commission paragraph 27 ARAP Others v Commission paragraph 62
Answer:

retrieved examples:

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: General Court recalled paragraph 26 judgment appeal persons decision addressed may claim individually concerned within meaning fourth paragraph Article 263 TFEU decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressedjudgments 15 July 1963 Plaumann v Commission 2562 EUC196317 107 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 72 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 46
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: finding corroborated Article 20 Regulation 6591999 governs rights interested parties
Answer:

retrieved examples:

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: connection must observed context review conducted European Union Courts complex economic assessments made Commission field State aid Courts substitute economic assessment Commission see effect Case C29007 P Commission v Scott 2010 ECR I7763 paragraphs 64 66 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Prec']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According second third sentences Article 202 thereof obtaining interested party information concerning alleged unlawful aid alleged misuse aid Commission either consider insufficient grounds taking view case inform interested party thereof take decision case concerning subjectmatter information supplied
Answer:

retrieved examples:

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows Commission examined information taken position takes decision
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently given Article 1 Third Steel Aid Code prohibited aid aid specific steel sector Commission could implicitly withdraw 1971 Decision
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: []
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Therefore action annulment decision initiate procedure pursuant Article 882 EC brought party concerned within meaning article must considered admissible party seeks thereby safeguard procedural rights available latter provision see Athinaïki Techniki v Commission paragraph 36 caselaw cited
Answer:

retrieved examples:

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: noted begin assessing compatibility State aid maritime transport sector aid issue present case social aspects Community guidelines may taken account Commission part overall assessment includes large number considerations various kinds linked particular protection competition Community’s maritime policy promotion Community maritime transport promotion employment see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others v Commission 2000 ECR I‑3659 paragraph 52
Answer: Prec

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appellant undertaking competition company benefiting measures complained without doubt interested party purposes Article 882 EC see Commission v Sytraval Brink’s France paragraph 41 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 32 regard definition term Article 1h Regulation 6591999
Answer:

retrieved examples:

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Class', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances Commission’s complaint reference notice relating State aid field taxation ineffective see effect Case C18299 P Salzgitter v Commission 2003 ECR I10761 paragraphs 54 55 unnecessary consider content scope notice stage
Answer:

retrieved examples:

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw definition aid general subsidy given includes positive benefits subsidies also State measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 38 Joined Cases C‑7808 C8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer:

retrieved examples:

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Consequently measure public authorities grant certain undertakings favourable tax treatment although involving transfer State resources places recipients favourable financial position taxpayers amounts State aid within meaning Article 871 EC see Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Paint Graphos Others paragraph 46 caselaw cited
Answer:

retrieved examples:

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: paragraphs 70 71 judgment Court stated supplementary requirement identify particular category undertakings exclusively favoured measure question may distinguished reason specific properties common characteristic cannot inferred caselaw Court Justice
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: hand advantages resulting general measure applicable without distinction economic operators constitute State aid within meaning Article 87 EC see effect Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 22 Joined Cases C‑39304 C‑4105 Air Liquide Industries Belgium 2006 ECR I‑5293 paragraph 32 caselaw cited
Answer:

retrieved examples:

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore necessary determine whether proposed tax reform selective selectivity constituent factor concept State aid see Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 54
Answer:

retrieved examples:

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards appraisal condition selectivity clear settled caselaw Article 871 EC requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 41 Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 82 caselaw cited
Answer:

retrieved examples:

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Class', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: noted paragraph 73 selective advantages advantages resulting general measure applicable without distinction economic operators fall within concept State aid
Answer:

retrieved examples:

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First appropriate recall Court consistently held Article 871 EC distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see British Aggregates v Commission paragraphs 85 89 caselaw cited Case C‑27908 P Commission v Netherlands 2011 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court admittedly held paragraph 56 Portugal v Commission determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation
Answer:

retrieved examples:

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Class']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However contrary General Court’s reasoning proposition put forward Government Gibraltar United Kingdom caselaw make classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general liable tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings
Answer:

retrieved examples:

Text: regards condition relating existence selective advantage accordance settled caselaw interventions form whatsoever liable favour undertakings directly indirectly must regarded economic advantages recipient undertaking would obtained normal market conditions considered State aid
Answer: Prec

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: interpretation selectivity criterion would require contrary caselaw cited paragraph 87 order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer:

retrieved examples:

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence would national tax rules fall outset outside scope control State aid merely adopted different regulatory technique although produce effects law andor fact
Answer:

retrieved examples:

Text: common ground Commission required make complex economic assessment examines whether particular measures described State aid public authorities act way private creditor see Case C52504 P Spain v Lenzing 2007 ECR I9947 paragraph 59
Answer: Prec

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Class']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: true absence European Union rules governing matter falls within competence Member States infra‑State bodies fiscal autonomy designate bases assessment spread tax burden across different factors production economic sectors General Court held paragraph 146 judgment appeal
Answer:

retrieved examples:

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly according caselaw cited paragraph 73 different tax burden resulting application ‘general’ tax regime sufficient establish selectivity taxation purposes Article 871 EC
Answer:

retrieved examples:

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus criteria forming basis assessment adopted tax system must also order capable recognised conferring selective advantages characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 871 EC
Answer:

retrieved examples:

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Indeed neither contended established General Court developed reasoning running manifestly counter content provisions German law issue ascribed one provisions scope manifestly light material file see effect judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 81
Answer: Prec

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent judgment appeal documents included file appellants submitted General Court contrary Commission stated point 97 grounds contested decision normal tax rules company profits could used valid basis comparison thus reference framework assessment selectivity tax scheme issue
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Even case tax scheme issue confer economic advantage general realignment scheme
Answer:

retrieved examples:

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court Justice stated determination reference framework purpose determining whether measure selective particular importance case tax measures since existence advantage may established compared “normal” taxation Case C8803 Portugal v Commission 2006 ECR I7115 paragraph 56 say taxation normally applicable undertakings light objective pursued scheme question factual legal situation comparable undertakings benefiting scheme Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 41
Answer:

retrieved examples:

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Commission examining scheme light rules State aid envisage subjective choices might made beneficiaries scheme absence scheme examine scheme order determine whether entails objective standpoint economic advantage reference tax provisions derogates would normally applicable absence scheme see effect Case C14804 Unicredito Italiano 2005 ECR I11137 paragraph 118
Answer:

retrieved examples:

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According Court’s caselaw however State aid defined Treaty Functioning European Union legal concept must interpreted basis objective factors
Answer:

retrieved examples:

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: According settled case‑law correctly cited Court First Instance paragraph 169 contested judgment abolishing unlawful aid means recovery logical consequence finding unlawful
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reason European Union judicature must principle regard specific features case technical complex nature Commission’s assessments carry comprehensive review whether measure falls within scope Article 1071 TFEU see inter alia Case C8398 P France v Ladbroke Racing Commission 2000 ECR I3271 paragraph 25 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 111
Answer:

retrieved examples:

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover according equally wellestablished caselawthe concept State aid refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature general scheme system form part see effect inter alia AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 42 Portugal v Commission paragraph 52 British Aggregates v Commission paragraph 83 Joined Cases C10609 P C10709 P Commission Spain v Government Gibraltar United Kingdom 2011 ECR I11113 paragraph 145
Answer:

retrieved examples:

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent considerations carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part
Answer:

retrieved examples:

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Class', 'Prec']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly Court Justice held judicial review limited regard whether measure comes within scope Article 1071 TFEU case appraisals Commission technical complex nature see inter alia France v Ladbroke Racing Commission paragraph 25 British Aggregates v Commission paragraph 114
Answer:

retrieved examples:

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance rightly observed measure vitiated misuse powers appears basis objective relevant consistent evidence taken exclusive main purpose achieving end stated see inter alia Case C‑11097 Netherlands v Council 2001 ECR I‑8763 paragraph 137 cases cited
Answer:

retrieved examples:

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance undertook assessment facts unless clear sense evidence produced distorted constitute question law subject review Court Justice see inter alia Joined Cases C‑28099 P C‑28299 P Moccia Irme Others v Commission 2001 ECR I‑4717 paragraph 78 Joined Cases C‑23899 P C‑24499 P C‑24599 P C‑24799 P C‑25099 P C‑25299 P C‑25499 P Limburgse Vinyl Maatschappij Others v Commission 2002 ECR I‑8375 paragraph 285
Answer:

retrieved examples:

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer:

retrieved examples:

Text: assessment General Court facts evidence cannot challenged appeal court except facts distorted see effect judgment 15 May 2019 CJ v ECDC C‑17018 P published EUC2019410 paragraph 23 caselaw cited relied appellants claim General Court examine evidence adduced take account offer submit additional evidence
Answer: Prec

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Class']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appeal Court’s jurisdiction confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C‑795 P John Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C‑21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer:

retrieved examples:

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: respect borne mind pursuant Article 58 Statute Court Justice appeal Court Justice limited points law lie grounds particular infringement Community law Court First Instance
Answer:

retrieved examples:

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General states point 20 Opinion Commission’s appeal based precisely upon allegation Court First Instance infringed Community law failing follow apply interpretation Articles 87 EC 253 EC laid caselaw Court Justice
Answer:

retrieved examples:

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule', 'Aut']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Regarding Wam’s argument Commission’s appeal invites Court Justice first review substance judgment appeal rather limited review ‘essential procedural requirement’ laid Article 230 EC second carry review substance Court Justice jurisdiction appeal stage noted Article 230 EC gives Court Justice jurisdiction review acts Community institutions Court First Instance
Answer:

retrieved examples:

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Appeals judgments Court First Instance governed however terms Article 2251 EC Statute Court Justice
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined judgments 16 March 1978 Unicme Others v Council 12377 EUC197873 paragraph 16 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 47 caselaw cited
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next must noted obligation provide statement reasons essential procedural requirement must distinguished question whether reasoning well founded latter concerned substantive legality measure issue see effect Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 48
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: However financial situation recipient public undertaking depends means used place advantage however may effected amount undertaking ultimately receives
Answer: Itpr

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw statement reasons required Article 253 EC must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer:

retrieved examples:

Text: contrast Court held contested measure affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders see Case 1182 PiraikiPatraiki Others v Commission 1985 ECR 207 paragraph 31 Case C15288 Sofrimport v Commission 1990 ECR I‑2477 paragraph 11 Belgium Forum 187 v Commission paragraph 60
Answer: Prec

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 88 caselaw cited
Answer:

retrieved examples:

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 871 EC
Answer:

retrieved examples:

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Princ', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard even cases apparent circumstances granted aid liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision see Portugal v Commission paragraph 89 caselaw cited
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: context noted also according settled caselaw purpose categorising national measure State aid necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition Case C22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraph 140 caselaw cited
Answer:

retrieved examples:

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard specifically condition trade Member States affected follows caselaw grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently meeting condition taxable persons perform economic activity field trade conceivable competition operators established Member States see Portugal v Commission paragraph 91 Case C‑17203 Heiser 2005 ECR I‑1627 paragraph 35
Answer:

retrieved examples:

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore Court held aid granted Member State strengthens position undertaking compared undertakings competing intraCommunity trade latter must regarded influenced aid Cassa di Risparmio di Firenze Others paragraph 141 caselaw cited
Answer:

retrieved examples:

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: apparent judgment fact coming compulsory levy contrary sufficient identify State resources see effect judgment 28 March 2019 Germany v Commission C‑40516 P EUC2019268 paragraphs 65 72
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard fact economic sector liberalised Community level may serve determine aid real potential effect competition affects trade Member States Cassa di Risparmio di Firenze Others paragraph 142 caselaw cited
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard condition distortion competition borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition see Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 30 Heiser paragraph 55
Answer:

retrieved examples:

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: findings examination interdependence EU Far Eastern markets relate possibility indirect effect trade intraCommunity competition referred principally Tubemeuse judgement
Answer:

retrieved examples:

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 55 60 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraphs 88 89
Answer: Prec

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law General Court obliged reject inadmissible head claim application brought essential matters law fact head claim based indicated coherently intelligibly application Case C‑21405 P Rossi v OHIM 2006 ECR I‑7057 paragraph 37 order 13 March 2007 Case C‑15006 P Arizona Chemical Others v Commission published ECR paragraph 45
Answer:

retrieved examples:

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court entitled pointing Article 441c Rules Procedure application must state subject‑matter proceedings summary pleas law application based manner sufficiently clear precise enable defendant prepare defence General Court give ruling reject argument alleging infringement Article 88 EC Regulation 6591999 inadmissible ground satisfy conditions
Answer:

retrieved examples:

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According established case‑law Court following restructuring entailing transfer production facilities one company newly constituted manufacturing companies since former company continues interest newly constituted manufacturing companies companies may far aid granted concerned together form single group notwithstanding fact newly constituted manufacturing companies legal personality separate former company see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 11
Answer:

retrieved examples:

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: However first factual assessment Czech Republic voluntarily undertook implement ‘review mechanism’ apparent caselaw cited paragraph 24 fall within jurisdiction Court Justice hearing appeal except facts distorted alleged appellants
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: former company new operating companies form economic unit inter alia restructuring carried constitutes indivisible whole industrial economic point view see effect Intermills v Commission paragraph 12
Answer:

retrieved examples:

Text: sufficient Commission’s decision include information enabling recipient calculate amount without overmuch difficulty see also Case C‑48098 Spain v Commission 2000 ECR I8717 paragraph 25 Case C‑41503 Commission v Greece 2005 ECR I3875 paragraph 39
Answer: Prec

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also apparent Court’s case‑law entity owning controlling shareholdings company actually exercises control involving directly indirectly management thereof must regarded taking part economic activity carried controlled undertaking Case C‑22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraphs 112 118
Answer:

retrieved examples:

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case simple separation undertaking two different entities first pursues directly former economic activity second controls first fully involved management would sufficient deprive rules European Union relating State aid practical effect
Answer:

retrieved examples:

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: would enable second entity benefit subsidies advantages granted State means State resources use whole part benefit former interest also economic unit formed two entities Cassa di Risparmio di Firenze Others paragraph 114
Answer:

retrieved examples:

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: may reveal possible exercise functions relating control direction financial support – going beyond simple placing capital investor – illustrate existence organic functional links entity owning controlling shareholding company controlled company fact members management committee controlling body entity appointed equivalent bodies controlled company see effect Cassa di Risparmio di Firenze Others paragraphs 116 117
Answer:

retrieved examples:

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer:

retrieved examples:

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 42 order 21 January 2010 Case C‑15009 P Iride Iride Energia v Commission published ECR paragraph 42
Answer:

retrieved examples:

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next clear Court’s case‑law need prevent cumulative effect aid repaid aid planned regardless whether individual aid aid covered aid scheme issue TWD v Commission caselaw allows Commission make compatibility aid conditional upon prior repayment earlier unlawful aid see effect order Iride Iride Energia v Commission paragraphs 49 50 70
Answer:

retrieved examples:

Text: second intervention must liable affect trade Member States
Answer: Class

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: event case State aid notified delay may imputed Commission time learned existence aid incompatible common market
Answer: Itpr

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First Commission must appropriate take account cumulative effect earlier unlawful aid repaid new aid see effect Case C‑35595 P TWD v Commission paragraphs 26 27 second find new aid compatible common market evidence disposal enables reach conclusion see effect order Iride Iride Engergia v Commission paragraph 70
Answer:

retrieved examples:

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court correctly pointed paragraph 187 judgment appeal apparent TWD v Commission caselaw Commission decides initiate formal investigation procedure Member State potential beneficiary new aid provide Commission evidence capable showing aid compatible common market obligation also extends need establish new aid earlier unlawful aid incompatible common market repaid cumulative effect
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: presupposes action must liable successful procure advantage party bringing judgment 28 May 2013 Abdulrahim v Council Commission C‑23912 P EUC2013331 paragraph 61 caselaw cited
Answer: Prec

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Lastly since clear Court’s case‑law sufficient Commission establish aid issue capable affecting trade Member States distorting competition order Iride Iride Energia v Commission paragraph 72 General Court acted correctly finding Commission required circumstances case carry specific detailed examination advantages derived aid issue referring specifically position AEP ACEA market question relative competitors trends Community trade
Answer:

retrieved examples:

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: pointed paragraph 77 duty incumbent upon General Court state reasons judgments require address expressly arguments articulated parties reasoning sufficient enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review
Answer:

retrieved examples:

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Aut']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover clear paragraphs 186 188 judgment appeal General Court set therein interpretation TWD v Commission caselaw
Answer:

retrieved examples:

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Articles 482 Rules Procedure General Court provides new plea law may introduced course proceedings unless based matters law fact come light course procedure see effect judgment 12 November 2009 Case C‑56408 P SGL Carbon v Commission published ECR paragraphs 20 34
Answer:

retrieved examples:

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place regards plea alleging breach conditions laid fourth paragraph Article 230 EC made clear outset Article 4 Regulation 6591999 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid notified compatible common market
Answer:

retrieved examples:

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer:

retrieved examples:

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination Commission finds notwithstanding fact measure notified falls within scope Article 871 EC raise doubts compatibility common market Commission adopt decision raise objections Article 43 Regulation 6591999
Answer:

retrieved examples:

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission adopts decision raise objections declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation
Answer:

retrieved examples:

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: position would different alteration fact constituted separate aid measure assessed separately would therefore influence assessment Commission already made original aid plan
Answer: Itpr

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Prec']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: latter provision decision call upon Member State concerned upon interested parties submit comments within prescribed period must rule exceed one month
Answer:

retrieved examples:

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Since doubts must trigger initiation formal investigation procedure interested parties referred Article 1h Regulation 6591999 participate must held interested party within meaning latter provision directly individually concerned decision
Answer:

retrieved examples:

Text: Third must confer advantage recipient
Answer: Class

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: beneficiaries procedural guarantees provided Article 882 EC Article 61 Regulation 6591999 able ensure guarantees respected must possible challenge European Union judicature decision raise objections see effect Case C‑7803 P Commission v Aktionsgemeinschaft Recht und Eigentum 2005 ECR I‑10737 paragraph 35 caselaw cited Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 28 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 31 caselaw cited
Answer:

retrieved examples:

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: order determine whether measure selective therefore examined whether within context specified legal regime measure constitutes advantage certain undertakings others light objective pursued regime comparable factual legal situation judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36
Answer: Prec

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly specific status ‘interested party’ within meaning Article 1h Regulation 6591999 conjunction specific subjectmatter action sufficient distinguish individually purposes fourth paragraph Article 230 EC applicant contesting decision raise objections
Answer:

retrieved examples:

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: Thus General Court stated paragraphs 302 303 judgment appeal range based estimates provided French authorities administrative procedure since Member State unable calculate exactly amount advantage FT benefited regime issue Commission entitled rely data thus provided
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Class']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard although applicant contests Commission decision initiate formal investigation procedure must accordance Article 441c Rules Procedure General Court define subjectmatter action application initiating proceedings requirement satisfied requisite legal standard applicant identifies decision seeks annulled
Answer:

retrieved examples:

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: matters little whether application initiating proceedings states seeking annulment ‘a decision raise objections’ – term used Article 43 Regulation 6591999 – decision initiate formal investigation procedure since Commission takes position aspects question means single decision
Answer:

retrieved examples:

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Prec']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard first third pleas General Court thus rightly pointed paragraph 81 judgment appeal according settled caselaw General Court interpret action challenging exclusively merits aid assessment decision seeking reality ensure respect procedural rights available applicant Article 882 EC applicant expressly raised plea effect
Answer:

retrieved examples:

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: follows Court seeking case determine whether market position members Aktionsgemeinschaft Recht und Eigentum association set promote collective interests class persons substantially affected aid scheme subject decision question
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule', 'Aut']
ground truth: ['Itpr', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances interpretation plea would tantamount redefining subjectmatter action see effect judgment 29 November 2007 Case C‑17606 P Stadtwerke Schwäbisch Hall Others v Commission paragraph 25
Answer:

retrieved examples:

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: use arguments nothing however bring change subjectmatter action conditions admissibility see effect 3F v Commission paragraph 35
Answer:

retrieved examples:

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrary existence doubts concerning compatibility precisely evidence must adduced order show Commission required initiate formal investigation procedure Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: First order determine whether measure although applying generally set economic operators effect ultimately conferring advantage certain undertakings examined apparent caselaw recalled paragraph 41 present judgment whether certain undertakings favoured others light objective pursued legal regime concerned comparable factual legal situation
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 1h Regulation 6591999 ‘interested party’ means inter alia person undertaking association undertakings whose interests might affected granting aid say particular competing undertakings beneficiary aid
Answer:

retrieved examples:

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Class']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: words term covers indeterminate group persons see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 16
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence provision rule possibility undertaking direct competitor beneficiary aid requires raw material production process categorised interested party provided undertaking demonstrates interests could adversely affected grant aid
Answer:

retrieved examples:

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: EU law cannot permit rules State aid circumvented merely creation autonomous institutions charged allocating aid see judgment 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 23
Answer: Prec

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: purpose necessary undertaking establish requisite legal standard aid likely specific effect situation see effect 3F v Commission paragraph 33
Answer:

retrieved examples:

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw Court classification ‘State aid’ within meaning Article 1071 TFEU requires conditions set provision fulilled
Answer:

retrieved examples:

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule', 'Itpr']
ground truth: ['Class', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus first must intervention State State resources
Answer:

retrieved examples:

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second intervention must liable affect trade Member States
Answer:

retrieved examples:

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: []
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: third must confer selective advantage recipient
Answer:

retrieved examples:

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: matters regard fact measure irrespective form legislative means used effect placing recipient undertakings position favourable undertakings although undertakings comparable factual legal situation light objective pursued tax system concerned
Answer: Itpr

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fourth must distort threaten distort competition judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer:

retrieved examples:

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Class', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: concept ‘aid’ embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 30
Answer:

retrieved examples:

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70 caselaw cited
Answer:

retrieved examples:

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: public creditor grants payment facilities respect debt payable undertaking assessment made applying principle private creditor test judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly private creditor test exception applies Member State requests constituent elements State aid incompatible common market laid Article 1071 TFEU exist
Answer:

retrieved examples:

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fact test applicable among factors Commission required take account purposes establishing whether aid exists see effect judgments 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 103 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: regards Court First Instance’s finding adoption Second Third Steel Aid Code led ambiguity whether subsequent application ZRFG notified ‘plan’ within meaning Article 6 third code must first held article expressly provides obligation inform Commission plans grant aid steel industry schemes already taken decision EC Treaty
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: result appears private creditor test might applicable Commission ask Member State concerned provide relevant information enabling determine whether conditions applying test satisfied judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 33
Answer:

retrieved examples:

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place clear caselaw Court appears private creditor test might applicable Commission examine possibility irrespective request effect
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly Advocate General noted points 72 76 Opinion nothing prevents recipient aid invoking applicability test recipient invoke test falls Commission assess whether test needs applied assess application
Answer:

retrieved examples:

Text: regard particular unlawful aid granted form tax advantage also Court’s settled caselaw recovery aid means transactions actually carried recipients aid question must subject tax treatment recipients would received absence unlawful aid see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 119
Answer: Prec

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second place regards relevance subjective state mind must noted Advocate General pointed point 74 Opinion starting point determining whether private operator test applied must economic nature Member State’s action Member State subjectively speaking thought acting alternative courses action considered adopting measure question
Answer:

retrieved examples:

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: extent reaching conclusion Court relied fact measure issue worded form exception rule governing forfeiture losses recalled already pointed paragraph 92 present judgment regulatory technique used cannot decisive purposes determination reference framework
Answer: Itpr

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case private creditor test intended determine whether recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor sought recover sums due debtor financial difficulty judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 72 accordingly whether undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70
Answer:

retrieved examples:

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Text: regard noted distortion must obvious documents Court’s file without need carry new assessment facts evidence judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 80
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Second must noted Commission doubt applicability test clear paragraph 24 present judgment asked Slovak State relevant information regard carried overall assessment evidence see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 86
Answer:

retrieved examples:

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: follows length preliminary examination procedure constitute indication Commission may doubts regarding compatibility aid question common market length cannot lead conclusion Commission initiated formal investigation procedure see effect Case 8482 Germany v Commission 1984 ECR 1451 paragraphs 14 17 Belgium v Deutsche Post DHL International paragraph 81
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Aut']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: accordance Court’s settled caselaw applying private creditor test Commission must carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 73 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 47
Answer:

retrieved examples:

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 78 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 54
Answer:

retrieved examples:

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover purposes applying private creditor test relevant evidence information available developments foreseeable time decision taken see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 105
Answer:

retrieved examples:

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination Commission whether particular measures classified State aid public authorities act way private creditor requires complex economic assessment judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 74 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 48
Answer:

retrieved examples:

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection must observed context review Courts European Union complex economic assessments made Commission field State aid Courts substitute economic assessment Commission judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 75 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 49
Answer:

retrieved examples:

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: follows arguments submitted intervener admissible unless fall within framework provided forms order pleas law judgment 7 October 2014 Germany v Council C‑39912 EUC20142258 paragraph 27
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Courts European Union must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 76 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 50
Answer:

retrieved examples:

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection also borne mind lawfulness decision concerning State aid falls assessed European Union judicature light information available Commission time decision adopted judgment 2 September 2010 Commission v Scott C‑29007 P EUC2010480 paragraph 91 caselaw cited
Answer:

retrieved examples:

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: According settled caselaw order tax regarded forming integral part aid measure must hypothecated aid relevant national rules sense revenue tax necessarily allocated financing aid direct impact amount aid consequently assessment compatibility aid internal market see inter alia judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 46 caselaw cited 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraph 99
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However information ‘available’ Commission includes seemed relevant assessment carried accordance caselaw referred paragraphs 59 61 present judgment could obtained upon request Commission administrative procedure
Answer:

retrieved examples:

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Paragraphs 180 213 235 judgment appeal Commission’s objections referred paragraph 64 present judgment directed read legal context referred General Court imply new requirements incompatible caselaw Court Justice
Answer:

retrieved examples:

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General noted paragraphs 125 131 Opinion General Court merely noted paragraphs 191 195 198 199 judgment appeal internal contradictions decision issue made findings fact according none evidence administrative file able substantiate liquidation factors used Commission
Answer:

retrieved examples:

Text: Furthermore aid granted Member State strengthens position undertaking compared undertakings competing trade within European Union undertakings must regarded affected aid judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 141
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Rule']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: considerations far concern information normally prudent diligent private creditor situation close possible local tax office could priori ignore capable justifying General Court’s decision Commission failed take consideration relevant information see effect judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraphs 77 78 81
Answer:

retrieved examples:

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule




LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Authoritative F1: 0.5714285714285714
Verbal Classification F1: 0
Interpretation F1: 0.3103448275862069
Precedent F1: 0.813953488372093
Rule F1: 0.6308724832214765

macro F1: 0.4653198741216695
macro F1 (reliable): 0.672084847674047

In [17]:
test(template, 10)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

query:
Text: regard must observed follows Article 58 Statute Court Justice conjunction Article 1132 Rules Procedure Court Justice appeal appellant may put forward relevant argument provided subjectmatter proceedings General Court changed appeal Case C‑22905 P PKK KNK v Council 2007 ECR I‑439 paragraph 66 Case C‑806 P Herrero Romeu v Commission 2007 ECR I‑10333 paragraph 32
Answer:

retrieved examples:

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 60
Answer: Prec

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard Court repeatedly held action annulment purposes Article 230 EC must available acts adopted institutions whatever nature form intended legal effects capable affecting interests applicant bringing distinct change legal position see inter alia Athinaïki Techniki v Commission paragraph 29 caselaw cited Case C‑36208 P Internationaler Hilfsfonds v Commission 2010 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: essential characteristic remuneration lies fact consideration service question see effect judgments 11 September 2007 Schwarz GootjesSchwarz C‑7605 EUC2007492 paragraphs 37 38 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 45 47
Answer: Prec

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows also settled caselaw concerning admissibility actions annulment necessary look actual substance acts challenged order classify see particular Case 6081 IBM v Commission 1981 ECR 2639 paragraph 9 Case C‑14796 Netherlands v Commission 2000 ECR I‑4723 paragraph 27
Answer:

retrieved examples:

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrast form act decision adopted principle irrelevant right challenge acts decisions way action annulment
Answer:

retrieved examples:

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Prec

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore principle irrelevant classification act question whether satisfies certain formal requirements namely particular duly identified author mentions provisions providing legal basis
Answer:

retrieved examples:

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore irrelevant act may described ‘decision’ refer Article 42 3 4 Regulation 6591999
Answer:

retrieved examples:

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also importance Member State concerned notified act issue Commission infringing Article 25 regulation error capable altering substance act see Athinaïki Techniki v Commission paragraphs 43 44 caselaw cited
Answer:

retrieved examples:

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored judgment 29 April 2004 Germany v Commission C‑27700 EUC2004238 paragraph 75 caselaw cited
Answer: Prec

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore principle measures definitively determine position Commission upon conclusion administrative procedure intended legal effects capable affecting interests complainant constitute acts open challenge purposes Article 230 EC intermediate measures whose purpose prepare final decision effects see Athinaïki Techniki v Commission paragraph 42 caselaw cited
Answer:

retrieved examples:

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard possible definitive actionable nature measures taken Commission procedure reviewing State aid noted first Commission must Article 101 Regulation 6591999 carry examination possession information whatever source regarding allegedly unlawful aid
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: measure issue judgment concerned sector years receiving State aid approved Commission object meet additional costs operation already received authorised aid Case C‑33499 Germany v Commission 2003 ECR I‑1139 paragraph 44
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination complaint basis provision gives rise initiation preliminary examination stage Article 883 EC obliges Commission examine immediately possible existence aid compatibility common market see effect Athinaïki Techniki v Commission paragraph 37
Answer:

retrieved examples:

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 131 Regulation 6591999 applicable context examination complaint alleging unlawful aid obliges Commission close preliminary examination stage adopting decision pursuant Article 42 3 4 regulation say decision finding aid exist raising objections initiating formal investigation procedure since institution authorised persist failure act preliminary examination stage
Answer:

retrieved examples:

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: stage procedure completed Commission bound consequently either initiate next stage procedure provided Article 882 EC adopt definitive decision rejecting complaint see effect Athinaïki Techniki v Commission paragraph 40 caselaw cited
Answer:

retrieved examples:

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission finds following examination complaint investigation revealed grounds concluding State aid within meaning Article 87 EC refuses implication initiate procedure provided Article 882 EC see effect Case C‑36795 P Commission v Sytraval Brink’s France 1998 ECR I‑1719 paragraph 47
Answer:

retrieved examples:

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: apparent judgment fact coming compulsory levy contrary sufficient identify State resources see effect judgment 28 March 2019 Germany v Commission C‑40516 P EUC2019268 paragraphs 65 72
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards Commission’s finding measures complained constituted existing aid noted existing aid course subject constant review provided Article 881 EC must regarded lawful long Commission found incompatible common market see Case C‑4493 NamurLes assurances du crédit 1994 ECR I‑3829 paragraph 34 Case C‑40099 Italy v Commission 2001 ECR I‑7303 paragraph 48
Answer:

retrieved examples:

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: may seen Joined Cases C‑7291 C‑7391 Sloman Neptun 1993 ECR I‑887 system established DIS register enables contracts employment concluded seafarers nationals nonmember countries permanent abode residence Member State concerned subjected working conditions rates pay covered law Member State considerably less favourable applicable seafarers nationals Member State constitute State aid within meaning Article 871 EC
Answer: Prec

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However receives complaint relating allegedly unlawful aid Commission classifying measure existing aid subjects procedure provided Article 881 EC thus refuses implication initiate procedure provided Article 882 EC see effect CIRFS Others v Commission paragraphs 25 26 Case C‑32199 P ARAP Others v Commission 2002 ECR I‑4287 paragraph 61
Answer:

retrieved examples:

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: decision refusing initiate procedure provided Article 882 EC definitive cannot characterised mere provisional measure CIRFS Others v Commission paragraph 26 effect Athinaïki Techniki v Commission paragraphs 54 58
Answer:

retrieved examples:

Text: Third must confer advantage recipient
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal see inter alia judgment A2A v Commission C‑32009 P EUC2011858 paragraph 97
Answer: Prec

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: situation persons intended benefit procedural guarantees afforded provision may secure compliance therewith able challenge decision question European Union judicature fourth paragraph Article 230 EC
Answer:

retrieved examples:

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: principle applies equally whether ground decision taken Commission regards aid compatible common market view existence aid must discounted Commission v Sytraval Brink’s France paragraph 47 considers existing aid see effect CIRFS Others v Commission paragraph 27 ARAP Others v Commission paragraph 62
Answer:

retrieved examples:

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: General Court recalled paragraph 26 judgment appeal persons decision addressed may claim individually concerned within meaning fourth paragraph Article 263 TFEU decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressedjudgments 15 July 1963 Plaumann v Commission 2562 EUC196317 107 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 72 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 46
Answer: Rule

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: Even circumstances aid granted show liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 89 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 49
Answer: Prec

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: finding corroborated Article 20 Regulation 6591999 governs rights interested parties
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: connection must observed context review conducted European Union Courts complex economic assessments made Commission field State aid Courts substitute economic assessment Commission see effect Case C29007 P Commission v Scott 2010 ECR I7763 paragraphs 64 66 caselaw cited
Answer: Prec

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According second third sentences Article 202 thereof obtaining interested party information concerning alleged unlawful aid alleged misuse aid Commission either consider insufficient grounds taking view case inform interested party thereof take decision case concerning subjectmatter information supplied
Answer:

retrieved examples:

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: accordance settled caselaw appeal plea directed ground judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Prec

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows Commission examined information taken position takes decision
Answer:

retrieved examples:

Text: Consequently given Article 1 Third Steel Aid Code prohibited aid aid specific steel sector Commission could implicitly withdraw 1971 Decision
Answer: Rule

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: also follows function repayment aid general rule save exceptional circumstances Commission exceed bounds discretion recognised caselaw Court asks Member State recover sums granted way unlawful aid since restoring previous situation see Case C‑7597 Belgium v Commission 1999 ECR I‑3671 paragraph 66 Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 99
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Therefore action annulment decision initiate procedure pursuant Article 882 EC brought party concerned within meaning article must considered admissible party seeks thereby safeguard procedural rights available latter provision see Athinaïki Techniki v Commission paragraph 36 caselaw cited
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: assessment General Court facts evidence cannot challenged appeal court except facts distorted see effect judgment 15 May 2019 CJ v ECDC C‑17018 P published EUC2019410 paragraph 23 caselaw cited relied appellants claim General Court examine evidence adduced take account offer submit additional evidence
Answer: Prec

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appellant undertaking competition company benefiting measures complained without doubt interested party purposes Article 882 EC see Commission v Sytraval Brink’s France paragraph 41 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 32 regard definition term Article 1h Regulation 6591999
Answer:

retrieved examples:

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: second intervention must liable affect trade Member States
Answer: Class

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances Commission’s complaint reference notice relating State aid field taxation ineffective see effect Case C18299 P Salzgitter v Commission 2003 ECR I10761 paragraphs 54 55 unnecessary consider content scope notice stage
Answer:

retrieved examples:

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Similarly term ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 41 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 87
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw definition aid general subsidy given includes positive benefits subsidies also State measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 38 Joined Cases C‑7808 C8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer:

retrieved examples:

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: therefore follows judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 selectivity tax measure established even measure constitute derogation ordinary tax system integral part system fact remains judgment consistent Court’s settled caselaw cited paragraph 57 judgment effect sufficient order establish selectivity measure derogates ordinary tax system demonstrate measure benefits certain operators others although operators objectively comparable situation light objective pursued ordinary tax system
Answer: Prec

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Class']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Consequently measure public authorities grant certain undertakings favourable tax treatment although involving transfer State resources places recipients favourable financial position taxpayers amounts State aid within meaning Article 871 EC see Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Paint Graphos Others paragraph 46 caselaw cited
Answer:

retrieved examples:

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Second recalled Commission required establish aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 8 September 2011 Commission v Netherlands C‑27908 P EUC2011551 paragraph 13 caselaw cited
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: hand advantages resulting general measure applicable without distinction economic operators constitute State aid within meaning Article 87 EC see effect Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 22 Joined Cases C‑39304 C‑4105 Air Liquide Industries Belgium 2006 ECR I‑5293 paragraph 32 caselaw cited
Answer:

retrieved examples:

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: However Member State provide justification
Answer: Itpr

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: said appellant entitled lodge appeal relying Court Justice grounds arguments arise judgment appeal seek criticise law correctness judgments 29 November 2007 Stadtwerke Schwäbisch Hall Others v Commission C‑17606 P published EUC2007730 paragraph 17 4 March 2021 Commission v Fútbol Club Barcelona C‑36219 P EUC2021169 paragraph 47
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore necessary determine whether proposed tax reform selective selectivity constituent factor concept State aid see Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 54
Answer:

retrieved examples:

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Class', 'Prec',
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards appraisal condition selectivity clear settled caselaw Article 871 EC requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 41 Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 82 caselaw cited
Answer:

retrieved examples:

Text: Indeed neither contended established General Court developed reasoning running manifestly counter content provisions German law issue ascribed one provisions scope manifestly light material file see effect judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 81
Answer: Prec

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: noted paragraph 73 selective advantages advantages resulting general measure applicable without distinction economic operators fall within concept State aid
Answer:

retrieved examples:

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First appropriate recall Court consistently held Article 871 EC distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see British Aggregates v Commission paragraphs 85 89 caselaw cited Case C‑27908 P Commission v Netherlands 2011 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: provision sets four conditions
Answer: Class

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court admittedly held paragraph 56 Portugal v Commission determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation
Answer:

retrieved examples:

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard Court’s established caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 94 caselaw cited
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However contrary General Court’s reasoning proposition put forward Government Gibraltar United Kingdom caselaw make classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general liable tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: However classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general subject tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 91
Answer: Prec

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: interpretation selectivity criterion would require contrary caselaw cited paragraph 87 order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer:

retrieved examples:

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr', 'Prec']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence would national tax rules fall outset outside scope control State aid merely adopted different regulatory technique although produce effects law andor fact
Answer:

retrieved examples:

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: paragraphs 34 35 judgment Court held since Sardegna Lines concerned Decision 9895 virtue undertaking shipping sector Sardinia potential beneficiary aid scheme Sardinian shipowners also virtue actual beneficiary individual aid granted scheme recovery ordered Commission individually concerned decision action directed decision admissible
Answer: Prec

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: true absence European Union rules governing matter falls within competence Member States infra‑State bodies fiscal autonomy designate bases assessment spread tax burden across different factors production economic sectors General Court held paragraph 146 judgment appeal
Answer:

retrieved examples:

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: CIRFS case CIRFS Commission’s interlocutor regard introduction ‘discipline’ concerning aid synthetic fibre sector also extension adaptation actively pursued negotiations Commission prelitigation procedure particular submitting written observations keeping close contact responsible departments Commission
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly according caselaw cited paragraph 73 different tax burden resulting application ‘general’ tax regime sufficient establish selectivity taxation purposes Article 871 EC
Answer:

retrieved examples:

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus criteria forming basis assessment adopted tax system must also order capable recognised conferring selective advantages characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 871 EC
Answer:

retrieved examples:

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent judgment appeal documents included file appellants submitted General Court contrary Commission stated point 97 grounds contested decision normal tax rules company profits could used valid basis comparison thus reference framework assessment selectivity tax scheme issue
Answer:

retrieved examples:

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: noted begin assessing compatibility State aid maritime transport sector aid issue present case social aspects Community guidelines may taken account Commission part overall assessment includes large number considerations various kinds linked particular protection competition Community’s maritime policy promotion Community maritime transport promotion employment see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others v Commission 2000 ECR I‑3659 paragraph 52
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Even case tax scheme issue confer economic advantage general realignment scheme
Answer:

retrieved examples:

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: proof may furnished reference body consistent evidence question whether doubt exists requires investigation circumstances decision raise objections adopted content comparing assessments upon Commission relied decision information available ruled compatibility aid question common market see effect Case C‑19891 Cook v Commission 1993 ECR I‑2487 paragraphs 30 31 Bouygues Bouygues Télécom v Commission paragraph 63 TF1 v Commission paragraph 52 Austria v ScheucherFleisch Others paragraphs 71 72
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court Justice stated determination reference framework purpose determining whether measure selective particular importance case tax measures since existence advantage may established compared “normal” taxation Case C8803 Portugal v Commission 2006 ECR I7115 paragraph 56 say taxation normally applicable undertakings light objective pursued scheme question factual legal situation comparable undertakings benefiting scheme Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 41
Answer:

retrieved examples:

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Commission examining scheme light rules State aid envisage subjective choices might made beneficiaries scheme absence scheme examine scheme order determine whether entails objective standpoint economic advantage reference tax provisions derogates would normally applicable absence scheme see effect Case C14804 Unicredito Italiano 2005 ECR I11137 paragraph 118
Answer:

retrieved examples:

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court thus held undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According Court’s caselaw however State aid defined Treaty Functioning European Union legal concept must interpreted basis objective factors
Answer:

retrieved examples:

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal judgment Isdin v BialPortela C‑59712 P EUC2013672 paragraph 21
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reason European Union judicature must principle regard specific features case technical complex nature Commission’s assessments carry comprehensive review whether measure falls within scope Article 1071 TFEU see inter alia Case C8398 P France v Ladbroke Racing Commission 2000 ECR I3271 paragraph 25 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 111
Answer:

retrieved examples:

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Prec

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover according equally wellestablished caselawthe concept State aid refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature general scheme system form part see effect inter alia AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 42 Portugal v Commission paragraph 52 British Aggregates v Commission paragraph 83 Joined Cases C10609 P C10709 P Commission Spain v Government Gibraltar United Kingdom 2011 ECR I11113 paragraph 145
Answer:

retrieved examples:

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent considerations carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part
Answer:

retrieved examples:

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly Court Justice held judicial review limited regard whether measure comes within scope Article 1071 TFEU case appraisals Commission technical complex nature see inter alia France v Ladbroke Racing Commission paragraph 25 British Aggregates v Commission paragraph 114
Answer:

retrieved examples:

Text: Court held nature scheme preclude finding measure concerned selective contrary ruling General Court since condition relating selectivity broader scope extends measures effects favour certain undertakings case ‘offshore’ companies account specific features characteristic undertakings
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance rightly observed measure vitiated misuse powers appears basis objective relevant consistent evidence taken exclusive main purpose achieving end stated see inter alia Case C‑11097 Netherlands v Council 2001 ECR I‑8763 paragraph 137 cases cited
Answer:

retrieved examples:

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: However Member State provide justification
Answer: Itpr

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance undertook assessment facts unless clear sense evidence produced distorted constitute question law subject review Court Justice see inter alia Joined Cases C‑28099 P C‑28299 P Moccia Irme Others v Commission 2001 ECR I‑4717 paragraph 78 Joined Cases C‑23899 P C‑24499 P C‑24599 P C‑24799 P C‑25099 P C‑25299 P C‑25499 P Limburgse Vinyl Maatschappij Others v Commission 2002 ECR I‑8375 paragraph 285
Answer:

retrieved examples:

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer:

retrieved examples:

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appeal Court’s jurisdiction confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C‑795 P John Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C‑21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer:

retrieved examples:

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: sufficient absence rights issue would possible undertaking perform particular tasks entrusted maintenance rights necessary enable holder perform tasks general economic interest assigned economically acceptable conditions judgment 15 November 2007 International Mail Spain C‑16206 EUC2007681 paragraph 35 caselaw cited
Answer: Prec

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: respect borne mind pursuant Article 58 Statute Court Justice appeal Court Justice limited points law lie grounds particular infringement Community law Court First Instance
Answer:

retrieved examples:

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: However requirement General Court give reasons decisions cannot interpreted meaning obliged respond detail every single argument advanced applicant particularly argument sufficiently clear precise see inter alia Joined Cases C‑12006 P C‑12106 P FIAMM Others v Council Commission 2008 ECR I‑6513 paragraph 91 caselaw cited
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General states point 20 Opinion Commission’s appeal based precisely upon allegation Court First Instance infringed Community law failing follow apply interpretation Articles 87 EC 253 EC laid caselaw Court Justice
Answer:

retrieved examples:

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regard may added Court previously ruled tax measure solely undertakings carried specified transactions benefited undertakings sector carry transactions could classified selective need assess whether measure greater benefit large undertakings see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraphs 47 50
Answer: Prec

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Aut']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Regarding Wam’s argument Commission’s appeal invites Court Justice first review substance judgment appeal rather limited review ‘essential procedural requirement’ laid Article 230 EC second carry review substance Court Justice jurisdiction appeal stage noted Article 230 EC gives Court Justice jurisdiction review acts Community institutions Court First Instance
Answer:

retrieved examples:

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: contrast Court held contested measure affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders see Case 1182 PiraikiPatraiki Others v Commission 1985 ECR 207 paragraph 31 Case C15288 Sofrimport v Commission 1990 ECR I‑2477 paragraph 11 Belgium Forum 187 v Commission paragraph 60
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Appeals judgments Court First Instance governed however terms Article 2251 EC Statute Court Justice
Answer:

retrieved examples:

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next must noted obligation provide statement reasons essential procedural requirement must distinguished question whether reasoning well founded latter concerned substantive legality measure issue see effect Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 48
Answer:

retrieved examples:

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: However Court stated State measure must regarded compensation services provided recipient undertakings order discharge public service obligations undertakings enjoy real financial advantage measure thus effect putting favourable competitive position undertakings competing measure caught Article 1071 TFEU see judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 87
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw statement reasons required Article 253 EC must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer:

retrieved examples:

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: case public undertakings assessment made applying principle private investor test see effect Case C30388 Italy v Commission 1991 ECR I1433 paragraph 20 Case C48299 France v Commission 2002 ECR I4397 paragraphs 68 70 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 91 caselaw cited
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 88 caselaw cited
Answer:

retrieved examples:

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: addition paragraphs 80 81 judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court recalled fact recipient undertakings belong various economic sectors sufficient call question selective nature measure concerned held potentially selective nature measure issue way called question fact essential condition obtaining tax advantage conferred measure economic transaction particularly entirely financial transaction available regardless nature business recipient undertakings
Answer: Prec

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 871 EC
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined judgments 16 March 1978 Unicme Others v Council 12377 EUC197873 paragraph 16 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 47 caselaw cited
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Princ', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard even cases apparent circumstances granted aid liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision see Portugal v Commission paragraph 89 caselaw cited
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: party may therefore put forward first time Court Justice plea could raised General Court raised since would allow bring Court Justice whose jurisdiction appeals limited case wider ambit came General Court see judgment 29 September 2011 Case C‑52009 P Arkema v Commission yet published ECR paragraph 64 caselaw cited
Answer: Prec

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: context noted also according settled caselaw purpose categorising national measure State aid necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition Case C22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraph 140 caselaw cited
Answer:

retrieved examples:

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: EU law cannot permit rules State aid circumvented merely creation autonomous institutions charged allocating aid see judgment 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 23
Answer: Prec

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard specifically condition trade Member States affected follows caselaw grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently meeting condition taxable persons perform economic activity field trade conceivable competition operators established Member States see Portugal v Commission paragraph 91 Case C‑17203 Heiser 2005 ECR I‑1627 paragraph 35
Answer:

retrieved examples:

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore Court held aid granted Member State strengthens position undertaking compared undertakings competing intraCommunity trade latter must regarded influenced aid Cassa di Risparmio di Firenze Others paragraph 141 caselaw cited
Answer:

retrieved examples:

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: Second recovery unlawful aid view reestablishing status quo ante imply reconstructing past events differently basis hypothetical elements choices often numerous could made operators concerned since choices actually made aid might prove irreversible judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 118
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard fact economic sector liberalised Community level may serve determine aid real potential effect competition affects trade Member States Cassa di Risparmio di Firenze Others paragraph 142 caselaw cited
Answer:

retrieved examples:

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: According settled case‑law persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed see inter alia judgments Case 2562 Plaumann v Commission 1963 ECR 95 Case C‑32195 P Greenpeace Council Others v Commission 1998 ECR I‑1651 paragraphs 7 28 Italy Sardegna Lines v Commission cited paragraph 32
Answer: Prec

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard condition distortion competition borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition see Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 30 Heiser paragraph 55
Answer:

retrieved examples:

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: findings examination interdependence EU Far Eastern markets relate possibility indirect effect trade intraCommunity competition referred principally Tubemeuse judgement
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: paragraphs 70 71 judgment Court stated supplementary requirement identify particular category undertakings exclusively favoured measure question may distinguished reason specific properties common characteristic cannot inferred caselaw Court Justice
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law General Court obliged reject inadmissible head claim application brought essential matters law fact head claim based indicated coherently intelligibly application Case C‑21405 P Rossi v OHIM 2006 ECR I‑7057 paragraph 37 order 13 March 2007 Case C‑15006 P Arizona Chemical Others v Commission published ECR paragraph 45
Answer:

retrieved examples:

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: Furthermore assessment reference made exclusively subject matter action see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 30 31 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 50 51 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraphs 38 39 caselaw cited
Answer: Prec

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Aut']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court entitled pointing Article 441c Rules Procedure application must state subject‑matter proceedings summary pleas law application based manner sufficiently clear precise enable defendant prepare defence General Court give ruling reject argument alleging infringement Article 88 EC Regulation 6591999 inadmissible ground satisfy conditions
Answer:

retrieved examples:

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: contrary settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule', 'Aut']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According established case‑law Court following restructuring entailing transfer production facilities one company newly constituted manufacturing companies since former company continues interest newly constituted manufacturing companies companies may far aid granted concerned together form single group notwithstanding fact newly constituted manufacturing companies legal personality separate former company see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 11
Answer:

retrieved examples:

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Indeed according settled caselaw grounds judgment General Court disclose infringement EU law operative part shown well founded legal grounds infringement capable bringing setting aside judgment judgments 30 September 2003 Biret International v Council C‑9302 P EUC2003517 paragraph 60 caselaw cited 14 October 2014 Buono Others v Commission C‑1213 P C‑1313 P EUC20142284 paragraph 62 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: former company new operating companies form economic unit inter alia restructuring carried constitutes indivisible whole industrial economic point view see effect Intermills v Commission paragraph 12
Answer:

retrieved examples:

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: regards second third parts ground appeal considered together must recalled accordance Court’s settled caselaw actions failure fulfil obligations brought ground infringement decision ordering recovery unlawful aid Member State encounters unforeseen unforeseeable difficulties becomes aware consequences overlooked Commission must submit problems Commission consideration together proposals suitable amendments decision issue
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also apparent Court’s case‑law entity owning controlling shareholdings company actually exercises control involving directly indirectly management thereof must regarded taking part economic activity carried controlled undertaking Case C‑22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraphs 112 118
Answer:

retrieved examples:

Text: general application derives fact decisions apply objectively determined situations produce legal effects respect category persons envisaged general abstract manner see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 31 17 September 2009 Commission v Koninglijke FrieslandCampina C‑51907 P EUC2009556 paragraph 53 caselaw cited 28 June 2018 Lowell Financial Services v Commission C‑21916 P published EUC2018508 paragraph 42 caselaw cited
Answer: Prec

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case simple separation undertaking two different entities first pursues directly former economic activity second controls first fully involved management would sufficient deprive rules European Union relating State aid practical effect
Answer:

retrieved examples:

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: would enable second entity benefit subsidies advantages granted State means State resources use whole part benefit former interest also economic unit formed two entities Cassa di Risparmio di Firenze Others paragraph 114
Answer:

retrieved examples:

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: accordance case‑law Court apprehension internal difficulties cannot justify failure Member State comply obligations Community law see inter alia Case C‑40497 Commission v Portugal 2000 ECR I‑4897 paragraph 52 Case C‑31099 Italy v Commission cited paragraph 105 Case C‑40400 Commission v Spain 2003 ECR I‑6695 paragraph 55
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: may reveal possible exercise functions relating control direction financial support – going beyond simple placing capital investor – illustrate existence organic functional links entity owning controlling shareholding company controlled company fact members management committee controlling body entity appointed equivalent bodies controlled company see effect Cassa di Risparmio di Firenze Others paragraphs 116 117
Answer:

retrieved examples:

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer:

retrieved examples:

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: Thus respect assessment context appeal General Court’s determinations national law Court Justice jurisdiction determine whether law distorted see judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 42 order 21 January 2010 Case C‑15009 P Iride Iride Energia v Commission published ECR paragraph 42
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: However European Union Courts must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn Case C1203 P Commission v Tetra Laval 2005 ECR I987 paragraph 39 Commission v Scott paragraph 65
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next clear Court’s case‑law need prevent cumulative effect aid repaid aid planned regardless whether individual aid aid covered aid scheme issue TWD v Commission caselaw allows Commission make compatibility aid conditional upon prior repayment earlier unlawful aid see effect order Iride Iride Energia v Commission paragraphs 49 50 70
Answer:

retrieved examples:

Text: second intervention must liable affect trade Member States
Answer: Class

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First Commission must appropriate take account cumulative effect earlier unlawful aid repaid new aid see effect Case C‑35595 P TWD v Commission paragraphs 26 27 second find new aid compatible common market evidence disposal enables reach conclusion see effect order Iride Iride Engergia v Commission paragraph 70
Answer:

retrieved examples:

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: common ground Commission required make complex economic assessment examines whether particular measures described State aid public authorities act way private creditor see Case C52504 P Spain v Lenzing 2007 ECR I9947 paragraph 59
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court correctly pointed paragraph 187 judgment appeal apparent TWD v Commission caselaw Commission decides initiate formal investigation procedure Member State potential beneficiary new aid provide Commission evidence capable showing aid compatible common market obligation also extends need establish new aid earlier unlawful aid incompatible common market repaid cumulative effect
Answer:

retrieved examples:

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid within meaning provision see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Lastly since clear Court’s case‑law sufficient Commission establish aid issue capable affecting trade Member States distorting competition order Iride Iride Energia v Commission paragraph 72 General Court acted correctly finding Commission required circumstances case carry specific detailed examination advantages derived aid issue referring specifically position AEP ACEA market question relative competitors trends Community trade
Answer:

retrieved examples:

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: pointed paragraph 77 duty incumbent upon General Court state reasons judgments require address expressly arguments articulated parties reasoning sufficient enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review
Answer:

retrieved examples:

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: paragraph 120 judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 Court referring inter alia two abovementioned judgments expressly stated position selectivity national measure examination holding case selectivity followed fact undertakings engaged export activities carrying certain investment transactions abroad qualified tax advantage conferred measure
Answer: Prec

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover clear paragraphs 186 188 judgment appeal General Court set therein interpretation TWD v Commission caselaw
Answer:

retrieved examples:

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: Since determination reference system constitutes starting point comparative examination carried context assessment selectivity aid scheme error made determination necessarily vitiates whole analysis condition relating selectivity see effect judgments 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 107 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraph 46
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Articles 482 Rules Procedure General Court provides new plea law may introduced course proceedings unless based matters law fact come light course procedure see effect judgment 12 November 2009 Case C‑56408 P SGL Carbon v Commission published ECR paragraphs 20 34
Answer:

retrieved examples:

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place regards plea alleging breach conditions laid fourth paragraph Article 230 EC made clear outset Article 4 Regulation 6591999 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid notified compatible common market
Answer:

retrieved examples:

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: effect caselaw simply reimbursement undertaking amount tax required pay breach EU law damages national authorities ordered pay undertakings compensate damage caused constitute State aid
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer:

retrieved examples:

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: follows foregoing neither French Republic FT rely principle order prevent recovery unlawful aid see Case C‑14804 Unicredito Italiano 2005 ECR I‑11137 paragraph 104
Answer: Prec

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination Commission finds notwithstanding fact measure notified falls within scope Article 871 EC raise doubts compatibility common market Commission adopt decision raise objections Article 43 Regulation 6591999
Answer:

retrieved examples:

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Therefore appraisal facts General Court constitute save clear sense evidence produced distorted question law subject review Court Justice judgments Archer Daniels Midland Archer Daniels Midland Ingredients v Commission C‑39703 P EUC2006328 paragraph 85 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 180
Answer: Prec

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission adopts decision raise objections declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation
Answer:

retrieved examples:

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain sectors activity see effect inter alia judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraphs 49 50
Answer: Prec

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: undertakes initial examination planned aid
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: latter provision decision call upon Member State concerned upon interested parties submit comments within prescribed period must rule exceed one month
Answer:

retrieved examples:

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Since doubts must trigger initiation formal investigation procedure interested parties referred Article 1h Regulation 6591999 participate must held interested party within meaning latter provision directly individually concerned decision
Answer:

retrieved examples:

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: However appropriate recall position adopted Court judgment Italy Sardegna Lines v Commission regard Commission Decision 9895EC 21 October 1997 concerning aid granted Region Sardinia Italy shipping companies Sardinia OJ 1998 L 20 p 30 required Italian Republic recover beneficiary loans leases question element aid contained
Answer: Prec

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Prec']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: beneficiaries procedural guarantees provided Article 882 EC Article 61 Regulation 6591999 able ensure guarantees respected must possible challenge European Union judicature decision raise objections see effect Case C‑7803 P Commission v Aktionsgemeinschaft Recht und Eigentum 2005 ECR I‑10737 paragraph 35 caselaw cited Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 28 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 31 caselaw cited
Answer:

retrieved examples:

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: follows Court seeking case determine whether market position members Aktionsgemeinschaft Recht und Eigentum association set promote collective interests class persons substantially affected aid scheme subject decision question
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly specific status ‘interested party’ within meaning Article 1h Regulation 6591999 conjunction specific subjectmatter action sufficient distinguish individually purposes fourth paragraph Article 230 EC applicant contesting decision raise objections
Answer:

retrieved examples:

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard although applicant contests Commission decision initiate formal investigation procedure must accordance Article 441c Rules Procedure General Court define subjectmatter action application initiating proceedings requirement satisfied requisite legal standard applicant identifies decision seeks annulled
Answer:

retrieved examples:

Text: Indeed according settled caselaw grounds judgment General Court disclose infringement EU law operative part shown well founded legal grounds infringement capable bringing setting aside judgment judgments 30 September 2003 Biret International v Council C‑9302 P EUC2003517 paragraph 60 caselaw cited 14 October 2014 Buono Others v Commission C‑1213 P C‑1313 P EUC20142284 paragraph 62 caselaw cited
Answer: Prec

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: matters little whether application initiating proceedings states seeking annulment ‘a decision raise objections’ – term used Article 43 Regulation 6591999 – decision initiate formal investigation procedure since Commission takes position aspects question means single decision
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard first third pleas General Court thus rightly pointed paragraph 81 judgment appeal according settled caselaw General Court interpret action challenging exclusively merits aid assessment decision seeking reality ensure respect procedural rights available applicant Article 882 EC applicant expressly raised plea effect
Answer:

retrieved examples:

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances interpretation plea would tantamount redefining subjectmatter action see effect judgment 29 November 2007 Case C‑17606 P Stadtwerke Schwäbisch Hall Others v Commission paragraph 25
Answer:

retrieved examples:

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: settled caselaw adoption order recover unlawful aid logical normal consequence finding unlawful
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: use arguments nothing however bring change subjectmatter action conditions admissibility see effect 3F v Commission paragraph 35
Answer:

retrieved examples:

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrary existence doubts concerning compatibility precisely evidence must adduced order show Commission required initiate formal investigation procedure Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Lastly regards argument General Court failed regard obligation state reasons relation principle limitation settled caselaw court thereby required provide account follows exhaustively point point reasoning articulated parties case
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 1h Regulation 6591999 ‘interested party’ means inter alia person undertaking association undertakings whose interests might affected granting aid say particular competing undertakings beneficiary aid
Answer:

retrieved examples:

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: far concerns third criterion characterising measure State aid settled caselaw measures whatever form likely directly indirectly favour certain undertakings regarded economic advantage recipient undertaking would obtained normal market conditions regarded State aid see judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraph 34
Answer: Prec

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: words term covers indeterminate group persons see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 16
Answer:

retrieved examples:

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence provision rule possibility undertaking direct competitor beneficiary aid requires raw material production process categorised interested party provided undertaking demonstrates interests could adversely affected grant aid
Answer:

retrieved examples:

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: purpose necessary undertaking establish requisite legal standard aid likely specific effect situation see effect 3F v Commission paragraph 33
Answer:

retrieved examples:

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw Court classification ‘State aid’ within meaning Article 1071 TFEU requires conditions set provision fulilled
Answer:

retrieved examples:

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Second regards appellants interest bringing proceedings part contested decision relating tax reliefs clear caselaw Court Justice Commission points individual grants aid general aid scheme approved Commission meet conditions scheme constitute existing aid need notified Italy v Commission cited paragraphs 21 26
Answer: Prec

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Class', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus first must intervention State State resources
Answer:

retrieved examples:

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second intervention must liable affect trade Member States
Answer:

retrieved examples:

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: must borne mind according settled caselaw concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system part judgments Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 145 caselaw cited BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 101
Answer: Prec

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: third must confer selective advantage recipient
Answer:

retrieved examples:

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: particular clear caselaw order assess whether measure would adopted normal market conditions private investor situation close possible State benefits obligations linked situation State shareholder — exclusion linked situation public authority — taken account see effect Case 23484 Belgium v Commission 1986 ECR 2263 paragraph 14 Case 4085 Belgium v Commission 1986 ECR 2321 paragraph 13 Joined Cases C27892 C28092 Spain v Commission 1994 ECR I4103 paragraph 22 Case C33499 Germany v Commission 2003 ECR I1139 paragraph 134
Answer: Prec

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Class']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fourth must distort threaten distort competition judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer:

retrieved examples:

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Class', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: concept ‘aid’ embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 30
Answer:

retrieved examples:

Text: principle legal certainty – one general principles European Union law – requires rules law clear precise predictable effect interested parties ascertain position situations legal relationships governed European Union law see effect Case C‑6393 Duff Others 1996 ECR I569 paragraph 20 Case C‑7606 P Britannia Alloys Chemicals v Commission 2007 ECR I‑4405 paragraph 79 Case C‑15807 Förster 2008 ECR I‑8507 paragraph 67
Answer: ['Prec', 'Princ']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70 caselaw cited
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: public creditor grants payment facilities respect debt payable undertaking assessment made applying principle private creditor test judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: test applicable among factors Commission required take account purposes establishing whether aid exists see effect Case C34296 Spain v Commission 1999 ECR I2459 paragraph 46 Case C25697 DM Transport 1999 ECR I3913 paragraph 24 Commission v EDF paragraphs 78 103
Answer: Prec

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly private creditor test exception applies Member State requests constituent elements State aid incompatible common market laid Article 1071 TFEU exist
Answer:

retrieved examples:

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fact test applicable among factors Commission required take account purposes establishing whether aid exists see effect judgments 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 103 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides competent court sufficient material exercise power review see Case C‑10504 P Nederlandse Federatieve Vereniging voor de Groothandel op Electrotechnisch Gebied v Commission 2006 ECR I‑8725 paragraph 72 Case C‑306 P Groupe Danone v Commission 2007 ECR I‑1331 paragraph 46
Answer: Prec

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: result appears private creditor test might applicable Commission ask Member State concerned provide relevant information enabling determine whether conditions applying test satisfied judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 33
Answer:

retrieved examples:

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: also noted Court Justice held paragraph 29 Commission v France provision European Union law requires Commission ordering recovery aid declared incompatible common market fix exact amount aid recovered
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place clear caselaw Court appears private creditor test might applicable Commission examine possibility irrespective request effect
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Furthermore even European Community first created situation capable giving rise legitimate expectations overriding public interest may preclude transitional measures adopted respect situations arose new rules came force still subject change Belgium Forum 187 v Commission paragraph 148 case‑law cited
Answer: Prec

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly Advocate General noted points 72 76 Opinion nothing prevents recipient aid invoking applicability test recipient invoke test falls Commission assess whether test needs applied assess application
Answer:

retrieved examples:

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: General Court pointed paragraph 42 judgment appeal review EU judicature legality decision initiate formal investigation procedure applicant challenges Commission’s assessment measure constituting State aid limited ascertaining whether Commission made manifest error assessment see effect judgment 21 July 2011 Alcoa Trasformazioni v Commission C‑19409 P EUC2011497 paragraph 61
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second place regards relevance subjective state mind must noted Advocate General pointed point 74 Opinion starting point determining whether private operator test applied must economic nature Member State’s action Member State subjectively speaking thought acting alternative courses action considered adopting measure question
Answer:

retrieved examples:

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: Moreover Court held aid notified Commission apparent failure act part relation measure irrelevant see Demesa Territorio Histόrico de Álava v Commission paragraph 52
Answer: Prec

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Class']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case private creditor test intended determine whether recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor sought recover sums due debtor financial difficulty judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 72 accordingly whether undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70
Answer:

retrieved examples:

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: hand also possible measure may raise doubts judgment 24 May 2011 Case C‑8309 P Commission v Kronoply Kronotex yet published ECR paragraph 43 order 9 June 2011 Case C‑45110 P TF1 v Commission paragraph 47 judgment 22 September 2011 Case C‑14809 P Belgium v Deutsche Post DHL International yet published ECR paragraph 53 judgment 27 October 2011 Case C‑4710 P Austria v ScheucherFleisch Others yet published ECR paragraph 40
Answer: Prec

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Second must noted Commission doubt applicability test clear paragraph 24 present judgment asked Slovak State relevant information regard carried overall assessment evidence see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 86
Answer:

retrieved examples:

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Therefore even sums corresponding measure question permanently held Treasury fact constantly remain public control therefore available competent national authorities sufficient categorised ‘State resources’ see judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 37 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 70 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 35 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 21
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: accordance Court’s settled caselaw applying private creditor test Commission must carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 73 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 47
Answer:

retrieved examples:

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 78 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 54
Answer:

retrieved examples:

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover purposes applying private creditor test relevant evidence information available developments foreseeable time decision taken see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 105
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: regard clear Court’s caselaw necessary financial balance economic viability undertaking entrusted operation service general economic interest threatened
Answer: Prec

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination Commission whether particular measures classified State aid public authorities act way private creditor requires complex economic assessment judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 74 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 48
Answer:

retrieved examples:

Text: According judgment applicant individually concerned decision addressed another person decision affects reason certain attributes peculiar reason circumstances differentiated persons see also field State aid judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 32 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 52 fields judgments 17 January 1985 PiraikiPatraiki Others v Commission 1182 EUC198518 paragraphs 11 19 31 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 93
Answer: Prec

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection must observed context review Courts European Union complex economic assessments made Commission field State aid Courts substitute economic assessment Commission judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 75 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 49
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: follows arguments submitted intervener admissible unless fall within framework provided forms order pleas law judgment 7 October 2014 Germany v Council C‑39912 EUC20142258 paragraph 27
Answer: Prec

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Courts European Union must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 76 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 50
Answer:

retrieved examples:

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: order determine whether measure selective therefore examined whether within context specified legal regime measure constitutes advantage certain undertakings others light objective pursued regime comparable factual legal situation judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: must recalled case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents case file judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 20 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection also borne mind lawfulness decision concerning State aid falls assessed European Union judicature light information available Commission time decision adopted judgment 2 September 2010 Commission v Scott C‑29007 P EUC2010480 paragraph 91 caselaw cited
Answer:

retrieved examples:

Text: concept aid embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect Case C20097 Ecotrade 1998 ECR I7907 paragraph 34 Case C697 Italy v Commission 1999 ECR I2981 paragraph 15
Answer: Prec

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However information ‘available’ Commission includes seemed relevant assessment carried accordance caselaw referred paragraphs 59 61 present judgment could obtained upon request Commission administrative procedure
Answer:

retrieved examples:

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: decision visàvis undertaking seek contest decision measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Van der Kooy Others v Commission cited paragraph 15 Case C692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Italy Sardegna Lines v Commission paragraph 33
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Paragraphs 180 213 235 judgment appeal Commission’s objections referred paragraph 64 present judgment directed read legal context referred General Court imply new requirements incompatible caselaw Court Justice
Answer:

retrieved examples:

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: appeal Courts jurisdiction thus confined review findings pleas argued Court First Instance see Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 order 28 June 2001 Case C35299 P Eridania Others v Council 2001 ECR I5037 paragraphs 52 53
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Aut']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General noted paragraphs 125 131 Opinion General Court merely noted paragraphs 191 195 198 199 judgment appeal internal contradictions decision issue made findings fact according none evidence administrative file able substantiate liquidation factors used Commission
Answer:

retrieved examples:

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: considerations far concern information normally prudent diligent private creditor situation close possible local tax office could priori ignore capable justifying General Court’s decision Commission failed take consideration relevant information see effect judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraphs 77 78 81
Answer:

retrieved examples:

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: However condition absolute impossibility implementation satisfied defendant Member State inform Commission internal difficulties legal political practical nature attributable national authorities’ acts omissions raised implementation decision issue without taking real steps recover aid undertakings concerned without suggesting Commission alternative methods implementing decision would allow difficulties overcome see effect judgments 13 November 2008 Commission v France C‑21407 EUC2008619 paragraph 50 12 February 2015 Commission v France C‑3714 published EUC201590 paragraph 66 caselaw cited
Answer: Prec

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']




LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Authoritative F1: 0.6000000000000001
Verbal Classification F1: 0.12903225806451613
Interpretation F1: 0.2033898305084746
Precedent F1: 0.7904191616766467
Rule F1: 0.6124999999999999

macro F1: 0.4670682500499275
macro F1 (reliable): 0.6676397205588822

In [18]:
test(template, 15)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

query:
Text: regard must observed follows Article 58 Statute Court Justice conjunction Article 1132 Rules Procedure Court Justice appeal appellant may put forward relevant argument provided subjectmatter proceedings General Court changed appeal Case C‑22905 P PKK KNK v Council 2007 ECR I‑439 paragraph 66 Case C‑806 P Herrero Romeu v Commission 2007 ECR I‑10333 paragraph 32
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Commission also takes relevant measure facilitate dialogue ensuring balanced support parties see effect Albany paragraphs 55 58 respect EEC Treaty Agreement social policy concluded Member States European Community exception United Kingdom Great Britain Northern Ireland OJ 1992 C 191 p 91 entry force Treaty Amsterdam
Answer: Prec

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 60
Answer: Prec

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard Court repeatedly held action annulment purposes Article 230 EC must available acts adopted institutions whatever nature form intended legal effects capable affecting interests applicant bringing distinct change legal position see inter alia Athinaïki Techniki v Commission paragraph 29 caselaw cited Case C‑36208 P Internationaler Hilfsfonds v Commission 2010 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw applicant’s interest bringing proceedings must light purpose action exist action lodged failing action inadmissible
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows also settled caselaw concerning admissibility actions annulment necessary look actual substance acts challenged order classify see particular Case 6081 IBM v Commission 1981 ECR 2639 paragraph 9 Case C‑14796 Netherlands v Commission 2000 ECR I‑4723 paragraph 27
Answer:

retrieved examples:

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part see judgments 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraphs 41 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 82 83 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 74 75 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 54 55
Answer: Prec

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: second intervention must liable affect trade Member States
Answer: Class

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: contrary settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrast form act decision adopted principle irrelevant right challenge acts decisions way action annulment
Answer:

retrieved examples:

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Prec

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore principle irrelevant classification act question whether satisfies certain formal requirements namely particular duly identified author mentions provisions providing legal basis
Answer:

retrieved examples:

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: regards whether ground well founded according settled caselaw definition aid general subsidy
Answer: Prec

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore irrelevant act may described ‘decision’ refer Article 42 3 4 Regulation 6591999
Answer:

retrieved examples:

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also importance Member State concerned notified act issue Commission infringing Article 25 regulation error capable altering substance act see Athinaïki Techniki v Commission paragraphs 43 44 caselaw cited
Answer:

retrieved examples:

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored judgment 29 April 2004 Germany v Commission C‑27700 EUC2004238 paragraph 75 caselaw cited
Answer: Prec

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore principle measures definitively determine position Commission upon conclusion administrative procedure intended legal effects capable affecting interests complainant constitute acts open challenge purposes Article 230 EC intermediate measures whose purpose prepare final decision effects see Athinaïki Techniki v Commission paragraph 42 caselaw cited
Answer:

retrieved examples:

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard possible definitive actionable nature measures taken Commission procedure reviewing State aid noted first Commission must Article 101 Regulation 6591999 carry examination possession information whatever source regarding allegedly unlawful aid
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Third must confer advantage recipient
Answer: Class

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: test applicable among factors Commission required take account purposes establishing whether aid exists see effect Case C34296 Spain v Commission 1999 ECR I2459 paragraph 46 Case C25697 DM Transport 1999 ECR I3913 paragraph 24 Commission v EDF paragraphs 78 103
Answer: Prec

Text: measure issue judgment concerned sector years receiving State aid approved Commission object meet additional costs operation already received authorised aid Case C‑33499 Germany v Commission 2003 ECR I‑1139 paragraph 44
Answer: Prec

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination complaint basis provision gives rise initiation preliminary examination stage Article 883 EC obliges Commission examine immediately possible existence aid compatibility common market see effect Athinaïki Techniki v Commission paragraph 37
Answer:

retrieved examples:

Text: third place according settled caselaw fact Member State seeks approximate unilateral measures conditions competition particular sector economy prevailing Member States cannot deprive measures question character aid Joined Cases 669 1169 Commission v France 1969 ECR 523 paragraphs 20 21 Case C697 Italy v Commission 1999 ECR I2981 paragraph 21
Answer: Prec

Text: regard Court’s established caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 94 caselaw cited
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 131 Regulation 6591999 applicable context examination complaint alleging unlawful aid obliges Commission close preliminary examination stage adopting decision pursuant Article 42 3 4 regulation say decision finding aid exist raising objections initiating formal investigation procedure since institution authorised persist failure act preliminary examination stage
Answer:

retrieved examples:

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: settled caselaw undertaking cannot principle contest Commission decision prohibiting aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme see Joined Cases C1598 C10599 Italy Sardegna Lines v Commission 2000 ECR I8855 paragraph 33 caselaw cited
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Prec']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: stage procedure completed Commission bound consequently either initiate next stage procedure provided Article 882 EC adopt definitive decision rejecting complaint see effect Athinaïki Techniki v Commission paragraph 40 caselaw cited
Answer:

retrieved examples:

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain business sectors judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 55 caselaw cited
Answer: Prec

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: assessment made public creditor grants payment facilities respect debt payable undertaking applying principle private creditor test
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission finds following examination complaint investigation revealed grounds concluding State aid within meaning Article 87 EC refuses implication initiate procedure provided Article 882 EC see effect Case C‑36795 P Commission v Sytraval Brink’s France 1998 ECR I‑1719 paragraph 47
Answer:

retrieved examples:

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: apparent judgment fact coming compulsory levy contrary sufficient identify State resources see effect judgment 28 March 2019 Germany v Commission C‑40516 P EUC2019268 paragraphs 65 72
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards Commission’s finding measures complained constituted existing aid noted existing aid course subject constant review provided Article 881 EC must regarded lawful long Commission found incompatible common market see Case C‑4493 NamurLes assurances du crédit 1994 ECR I‑3829 paragraph 34 Case C‑40099 Italy v Commission 2001 ECR I‑7303 paragraph 48
Answer:

retrieved examples:

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: may seen Joined Cases C‑7291 C‑7391 Sloman Neptun 1993 ECR I‑887 system established DIS register enables contracts employment concluded seafarers nationals nonmember countries permanent abode residence Member State concerned subjected working conditions rates pay covered law Member State considerably less favourable applicable seafarers nationals Member State constitute State aid within meaning Article 871 EC
Answer: Prec

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect inter alia judgment 18 July 2013 PC‑612 EUC2013525 paragraph 18
Answer: Prec

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However receives complaint relating allegedly unlawful aid Commission classifying measure existing aid subjects procedure provided Article 881 EC thus refuses implication initiate procedure provided Article 882 EC see effect CIRFS Others v Commission paragraphs 25 26 Case C‑32199 P ARAP Others v Commission 2002 ECR I‑4287 paragraph 61
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: Third must confer advantage recipient
Answer: Class

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: decision refusing initiate procedure provided Article 882 EC definitive cannot characterised mere provisional measure CIRFS Others v Commission paragraph 26 effect Athinaïki Techniki v Commission paragraphs 54 58
Answer:

retrieved examples:

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal see inter alia judgment A2A v Commission C‑32009 P EUC2011858 paragraph 97
Answer: Prec

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: situation persons intended benefit procedural guarantees afforded provision may secure compliance therewith able challenge decision question European Union judicature fourth paragraph Article 230 EC
Answer:

retrieved examples:

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Joined Cases 6785 6885 7085 Kwekeriij van der Kooy Others v Commission 1988 ECR 219 paragraph 15 Case C‑692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Joined Cases C‑1598 C‑10599 Italy Sardegna Lines v Commission 2000 ECR I‑8855 paragraph 33
Answer: Prec

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: New aid therefore subject precautionary review Commission may principle put effect time latter declared compatible Treaty
Answer: Itpr

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: principle applies equally whether ground decision taken Commission regards aid compatible common market view existence aid must discounted Commission v Sytraval Brink’s France paragraph 47 considers existing aid see effect CIRFS Others v Commission paragraph 27 ARAP Others v Commission paragraph 62
Answer:

retrieved examples:

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Even circumstances aid granted show liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 89 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 49
Answer: Prec

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: General Court recalled paragraph 26 judgment appeal persons decision addressed may claim individually concerned within meaning fourth paragraph Article 263 TFEU decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressedjudgments 15 July 1963 Plaumann v Commission 2562 EUC196317 107 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 72 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 46
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: finding corroborated Article 20 Regulation 6591999 governs rights interested parties
Answer:

retrieved examples:

Text: connection must observed context review conducted European Union Courts complex economic assessments made Commission field State aid Courts substitute economic assessment Commission see effect Case C29007 P Commission v Scott 2010 ECR I7763 paragraphs 64 66 caselaw cited
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: connection must observed context review conducted European Union Courts complex economic assessments made Commission field State aid Courts substitute economic assessment Commission see effect Case C29007 P Commission v Scott 2010 ECR I7763 paragraphs 64 66 caselaw cited
Answer: Prec

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According second third sentences Article 202 thereof obtaining interested party information concerning alleged unlawful aid alleged misuse aid Commission either consider insufficient grounds taking view case inform interested party thereof take decision case concerning subjectmatter information supplied
Answer:

retrieved examples:

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: accordance settled caselaw appeal plea directed ground judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Prec

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Article 2 EC Treaty amendment Article 2 EC declares particular task Community ‘to promote … harmonious balanced development economic activities’ ‘a high level employment social protection
Answer: Rule

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows Commission examined information taken position takes decision
Answer:

retrieved examples:

Text: Consequently given Article 1 Third Steel Aid Code prohibited aid aid specific steel sector Commission could implicitly withdraw 1971 Decision
Answer: Rule

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: also follows function repayment aid general rule save exceptional circumstances Commission exceed bounds discretion recognised caselaw Court asks Member State recover sums granted way unlawful aid since restoring previous situation see Case C‑7597 Belgium v Commission 1999 ECR I‑3671 paragraph 66 Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 99
Answer: Prec

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Therefore action annulment decision initiate procedure pursuant Article 882 EC brought party concerned within meaning article must considered admissible party seeks thereby safeguard procedural rights available latter provision see Athinaïki Techniki v Commission paragraph 36 caselaw cited
Answer:

retrieved examples:

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: assessment General Court facts evidence cannot challenged appeal court except facts distorted see effect judgment 15 May 2019 CJ v ECDC C‑17018 P published EUC2019410 paragraph 23 caselaw cited relied appellants claim General Court examine evidence adduced take account offer submit additional evidence
Answer: Prec

Text: noted begin assessing compatibility State aid maritime transport sector aid issue present case social aspects Community guidelines may taken account Commission part overall assessment includes large number considerations various kinds linked particular protection competition Community’s maritime policy promotion Community maritime transport promotion employment see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others v Commission 2000 ECR I‑3659 paragraph 52
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: regards thirdly Commissions claim alternative Court set aside words view paragraph 36 English version judgment appeal clear grounds judgment Court First Instance decide admissibility application basis subjective appraisal interests applicants explained basis rules governing admissibility actions Article 173 Treaty
Answer: Rule

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appellant undertaking competition company benefiting measures complained without doubt interested party purposes Article 882 EC see Commission v Sytraval Brink’s France paragraph 41 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 32 regard definition term Article 1h Regulation 6591999
Answer:

retrieved examples:

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances Commission’s complaint reference notice relating State aid field taxation ineffective see effect Case C18299 P Salzgitter v Commission 2003 ECR I10761 paragraphs 54 55 unnecessary consider content scope notice stage
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Similarly term ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 41 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 87
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw definition aid general subsidy given includes positive benefits subsidies also State measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 38 Joined Cases C‑7808 C8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer:

retrieved examples:

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: therefore follows judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 selectivity tax measure established even measure constitute derogation ordinary tax system integral part system fact remains judgment consistent Court’s settled caselaw cited paragraph 57 judgment effect sufficient order establish selectivity measure derogates ordinary tax system demonstrate measure benefits certain operators others although operators objectively comparable situation light objective pursued ordinary tax system
Answer: Prec

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Consequently measure public authorities grant certain undertakings favourable tax treatment although involving transfer State resources places recipients favourable financial position taxpayers amounts State aid within meaning Article 871 EC see Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Paint Graphos Others paragraph 46 caselaw cited
Answer:

retrieved examples:

Text: paragraphs 70 71 judgment Court stated supplementary requirement identify particular category undertakings exclusively favoured measure question may distinguished reason specific properties common characteristic cannot inferred caselaw Court Justice
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Second recalled Commission required establish aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 8 September 2011 Commission v Netherlands C‑27908 P EUC2011551 paragraph 13 caselaw cited
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: hand advantages resulting general measure applicable without distinction economic operators constitute State aid within meaning Article 87 EC see effect Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 22 Joined Cases C‑39304 C‑4105 Air Liquide Industries Belgium 2006 ECR I‑5293 paragraph 32 caselaw cited
Answer:

retrieved examples:

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: However Member State provide justification
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: said appellant entitled lodge appeal relying Court Justice grounds arguments arise judgment appeal seek criticise law correctness judgments 29 November 2007 Stadtwerke Schwäbisch Hall Others v Commission C‑17606 P published EUC2007730 paragraph 17 4 March 2021 Commission v Fútbol Club Barcelona C‑36219 P EUC2021169 paragraph 47
Answer: Prec

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore necessary determine whether proposed tax reform selective selectivity constituent factor concept State aid see Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 54
Answer:

retrieved examples:

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards appraisal condition selectivity clear settled caselaw Article 871 EC requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 41 Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 82 caselaw cited
Answer:

retrieved examples:

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: Indeed neither contended established General Court developed reasoning running manifestly counter content provisions German law issue ascribed one provisions scope manifestly light material file see effect judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 81
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: noted paragraph 73 selective advantages advantages resulting general measure applicable without distinction economic operators fall within concept State aid
Answer:

retrieved examples:

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First appropriate recall Court consistently held Article 871 EC distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see British Aggregates v Commission paragraphs 85 89 caselaw cited Case C‑27908 P Commission v Netherlands 2011 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: regards second condition set Article 230 EC borne mind fact disputed provision nature scope provision general application inasmuch applies traders concerned general prevent individual concern Belgium Forum 187 v Commission paragraph 58 case‑law cited
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court admittedly held paragraph 56 Portugal v Commission determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation
Answer:

retrieved examples:

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: regard Court’s established caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 94 caselaw cited
Answer: Prec

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 1071 TFEU
Answer: ['Princ', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However contrary General Court’s reasoning proposition put forward Government Gibraltar United Kingdom caselaw make classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general liable tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings
Answer:

retrieved examples:

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: However classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general subject tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 91
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: regards condition relating existence selective advantage accordance settled caselaw interventions form whatsoever liable favour undertakings directly indirectly must regarded economic advantages recipient undertaking would obtained normal market conditions considered State aid
Answer: Prec

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: interpretation selectivity criterion would require contrary caselaw cited paragraph 87 order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer:

retrieved examples:

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Class']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence would national tax rules fall outset outside scope control State aid merely adopted different regulatory technique although produce effects law andor fact
Answer:

retrieved examples:

Text: common ground Commission required make complex economic assessment examines whether particular measures described State aid public authorities act way private creditor see Case C52504 P Spain v Lenzing 2007 ECR I9947 paragraph 59
Answer: Prec

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Article 1071 TFEU save otherwise provided Treaties aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States incompatible internal market
Answer: Rule

Text: paragraphs 34 35 judgment Court held since Sardegna Lines concerned Decision 9895 virtue undertaking shipping sector Sardinia potential beneficiary aid scheme Sardinian shipowners also virtue actual beneficiary individual aid granted scheme recovery ordered Commission individually concerned decision action directed decision admissible
Answer: Prec

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: true absence European Union rules governing matter falls within competence Member States infra‑State bodies fiscal autonomy designate bases assessment spread tax burden across different factors production economic sectors General Court held paragraph 146 judgment appeal
Answer:

retrieved examples:

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: Consequently General Court correctly applied Article 841 Rules Procedure rejecting plea ground time
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: CIRFS case CIRFS Commission’s interlocutor regard introduction ‘discipline’ concerning aid synthetic fibre sector also extension adaptation actively pursued negotiations Commission prelitigation procedure particular submitting written observations keeping close contact responsible departments Commission
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly according caselaw cited paragraph 73 different tax burden resulting application ‘general’ tax regime sufficient establish selectivity taxation purposes Article 871 EC
Answer:

retrieved examples:

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus criteria forming basis assessment adopted tax system must also order capable recognised conferring selective advantages characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 871 EC
Answer:

retrieved examples:

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent judgment appeal documents included file appellants submitted General Court contrary Commission stated point 97 grounds contested decision normal tax rules company profits could used valid basis comparison thus reference framework assessment selectivity tax scheme issue
Answer:

retrieved examples:

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: follows rules governing proceedings EU Courts particular Article 21 Statute Court Justice European Union applicable General Court pursuant first paragraph Article 53 Statute Article 441 Rules Procedure General Court version applicable originating application lodged case principle determined delimited parties EU Courts cannot adjudicate ultra petita see effect judgment 10 December 2013 Commission v Ireland Others C‑27212 P EUC2013812 paragraph 27
Answer: ['Prec', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: noted begin assessing compatibility State aid maritime transport sector aid issue present case social aspects Community guidelines may taken account Commission part overall assessment includes large number considerations various kinds linked particular protection competition Community’s maritime policy promotion Community maritime transport promotion employment see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others v Commission 2000 ECR I‑3659 paragraph 52
Answer: Prec

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Even case tax scheme issue confer economic advantage general realignment scheme
Answer:

retrieved examples:

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: proof may furnished reference body consistent evidence question whether doubt exists requires investigation circumstances decision raise objections adopted content comparing assessments upon Commission relied decision information available ruled compatibility aid question common market see effect Case C‑19891 Cook v Commission 1993 ECR I‑2487 paragraphs 30 31 Bouygues Bouygues Télécom v Commission paragraph 63 TF1 v Commission paragraph 52 Austria v ScheucherFleisch Others paragraphs 71 72
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Class']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court Justice stated determination reference framework purpose determining whether measure selective particular importance case tax measures since existence advantage may established compared “normal” taxation Case C8803 Portugal v Commission 2006 ECR I7115 paragraph 56 say taxation normally applicable undertakings light objective pursued scheme question factual legal situation comparable undertakings benefiting scheme Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 41
Answer:

retrieved examples:

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Commission examining scheme light rules State aid envisage subjective choices might made beneficiaries scheme absence scheme examine scheme order determine whether entails objective standpoint economic advantage reference tax provisions derogates would normally applicable absence scheme see effect Case C14804 Unicredito Italiano 2005 ECR I11137 paragraph 118
Answer:

retrieved examples:

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Court thus held undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According Court’s caselaw however State aid defined Treaty Functioning European Union legal concept must interpreted basis objective factors
Answer:

retrieved examples:

Text: Also far arguments set alternative 3F seeks put forward separate specific grounds demonstrate Commission infringed principle good administration essentially alleging duration preliminary examination stage unreasonable recalled according Article 1701 Rules Procedure Court Justice subjectmatter proceedings General Court may changed appeal
Answer: Rule

Text: Third must confer advantage recipient
Answer: Class

Text: According settled case‑law correctly cited Court First Instance paragraph 169 contested judgment abolishing unlawful aid means recovery logical consequence finding unlawful
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal judgment Isdin v BialPortela C‑59712 P EUC2013672 paragraph 21
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reason European Union judicature must principle regard specific features case technical complex nature Commission’s assessments carry comprehensive review whether measure falls within scope Article 1071 TFEU see inter alia Case C8398 P France v Ladbroke Racing Commission 2000 ECR I3271 paragraph 25 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 111
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Prec

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: follows condition application receipt tax aid may grounds finding aid selective condition leads distinction made undertakings despite fact light objective pursued tax system concerned comparable factual legal situation therefore represents discrimination undertakings excluded
Answer: Itpr

Text: Article 92 Treaty states Save otherwise provided Treaty aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods shall far affects trade Member States incompatible common market
Answer: Rule

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover according equally wellestablished caselawthe concept State aid refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature general scheme system form part see effect inter alia AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 42 Portugal v Commission paragraph 52 British Aggregates v Commission paragraph 83 Joined Cases C10609 P C10709 P Commission Spain v Government Gibraltar United Kingdom 2011 ECR I11113 paragraph 145
Answer:

retrieved examples:

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent considerations carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: Second Commission specific grant aid alleged made pursuance previously authorised scheme cannot outset examine directly relation Treaty
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: rules applicable investment sugar sector thus established Regulation 178581
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly Court Justice held judicial review limited regard whether measure comes within scope Article 1071 TFEU case appraisals Commission technical complex nature see inter alia France v Ladbroke Racing Commission paragraph 25 British Aggregates v Commission paragraph 114
Answer:

retrieved examples:

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Court held nature scheme preclude finding measure concerned selective contrary ruling General Court since condition relating selectivity broader scope extends measures effects favour certain undertakings case ‘offshore’ companies account specific features characteristic undertakings
Answer: Prec

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance rightly observed measure vitiated misuse powers appears basis objective relevant consistent evidence taken exclusive main purpose achieving end stated see inter alia Case C‑11097 Netherlands v Council 2001 ECR I‑8763 paragraph 137 cases cited
Answer:

retrieved examples:

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: However Member State provide justification
Answer: Itpr

Text: Member State concerned provides Commission requisite evidence Commission carry global assessment taking account — addition evidence provided Member State — relevant evidence enabling determine whether Member State took measure question capacity shareholder public authority
Answer: Itpr

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: fourth paragraph Article 263 TFEU natural legal person may conditions laid first second paragraphs article institute proceedings act addressed person direct individual concern regulatory act direct concern entail implementing measures
Answer: Rule

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance undertook assessment facts unless clear sense evidence produced distorted constitute question law subject review Court Justice see inter alia Joined Cases C‑28099 P C‑28299 P Moccia Irme Others v Commission 2001 ECR I‑4717 paragraph 78 Joined Cases C‑23899 P C‑24499 P C‑24599 P C‑24799 P C‑25099 P C‑25299 P C‑25499 P Limburgse Vinyl Maatschappij Others v Commission 2002 ECR I‑8375 paragraph 285
Answer:

retrieved examples:

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: Admittedly stated paragraph 33 applicant must always show requisite legal standard interests might affected granting aid possible showing fact competitive position relation trade unions operating market
Answer: Itpr

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer:

retrieved examples:

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: fact however taken consideration relation obligation recover incompatible aid light principles protection legitimate expectations legal certainty done Commission contested decision declined order recovery aid granted date publication Official Journal European Communities decisions initiate procedure laid Article 882 EC
Answer: ['Princ', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: assessment General Court facts evidence cannot challenged appeal court except facts distorted see effect judgment 15 May 2019 CJ v ECDC C‑17018 P published EUC2019410 paragraph 23 caselaw cited relied appellants claim General Court examine evidence adduced take account offer submit additional evidence
Answer: Prec

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Court Justice’s jurisdiction appeal confined review findings law pleas argued General Court
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appeal Court’s jurisdiction confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C‑795 P John Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C‑21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer:

retrieved examples:

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: sufficient absence rights issue would possible undertaking perform particular tasks entrusted maintenance rights necessary enable holder perform tasks general economic interest assigned economically acceptable conditions judgment 15 November 2007 International Mail Spain C‑16206 EUC2007681 paragraph 35 caselaw cited
Answer: Prec

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: However accordance second sentence Article 141 Regulation 6591999 Commission shall require recovery aid would contrary general principle EU law
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: respect borne mind pursuant Article 58 Statute Court Justice appeal Court Justice limited points law lie grounds particular infringement Community law Court First Instance
Answer:

retrieved examples:

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus Member State makes alteration existing aid scheme breach authorisation condition scheme Member State guarantee authorised aid scheme affected alteration advantages granted basis scheme therefore retained
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However requirement General Court give reasons decisions cannot interpreted meaning obliged respond detail every single argument advanced applicant particularly argument sufficiently clear precise see inter alia Joined Cases C‑12006 P C‑12106 P FIAMM Others v Council Commission 2008 ECR I‑6513 paragraph 91 caselaw cited
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General states point 20 Opinion Commission’s appeal based precisely upon allegation Court First Instance infringed Community law failing follow apply interpretation Articles 87 EC 253 EC laid caselaw Court Justice
Answer:

retrieved examples:

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: benefit may advantage constituting aid may indeed benefit cannot justify failure recover aid recovery different sum constituting advantage procured unlawful aid question
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: regard may added Court previously ruled tax measure solely undertakings carried specified transactions benefited undertakings sector carry transactions could classified selective need assess whether measure greater benefit large undertakings see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraphs 47 50
Answer: Prec

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule', 'Aut']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Regarding Wam’s argument Commission’s appeal invites Court Justice first review substance judgment appeal rather limited review ‘essential procedural requirement’ laid Article 230 EC second carry review substance Court Justice jurisdiction appeal stage noted Article 230 EC gives Court Justice jurisdiction review acts Community institutions Court First Instance
Answer:

retrieved examples:

Text: regards fourth part ground appeal recalled appellant must pursuant Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court Justice indicate precisely evidence alleged distorted General Court demonstrate errors appraisal view led distortion
Answer: Rule

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: contrast Court held contested measure affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders see Case 1182 PiraikiPatraiki Others v Commission 1985 ECR 207 paragraph 31 Case C15288 Sofrimport v Commission 1990 ECR I‑2477 paragraph 11 Belgium Forum 187 v Commission paragraph 60
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Appeals judgments Court First Instance governed however terms Article 2251 EC Statute Court Justice
Answer:

retrieved examples:

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined judgments 16 March 1978 Unicme Others v Council 12377 EUC197873 paragraph 16 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 47 caselaw cited
Answer: Prec

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next must noted obligation provide statement reasons essential procedural requirement must distinguished question whether reasoning well founded latter concerned substantive legality measure issue see effect Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 48
Answer:

retrieved examples:

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: However Court stated State measure must regarded compensation services provided recipient undertakings order discharge public service obligations undertakings enjoy real financial advantage measure thus effect putting favourable competitive position undertakings competing measure caught Article 1071 TFEU see judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 87
Answer: Prec

Text: However financial situation recipient public undertaking depends means used place advantage however may effected amount undertaking ultimately receives
Answer: Itpr

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: appellant alleges distortion evidence General Court must Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court indicate precisely evidence alleged distorted General Court show errors appraisal view led distortion
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently considering whether private investor test applicable General Court err law focusing analysis fiscal nature means employed French State improvement — view opening electricity market — EDF’s financial situation effects measure question competition
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw statement reasons required Article 253 EC must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer:

retrieved examples:

Text: case public undertakings assessment made applying principle private investor test see effect Case C30388 Italy v Commission 1991 ECR I1433 paragraph 20 Case C48299 France v Commission 2002 ECR I4397 paragraphs 68 70 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 91 caselaw cited
Answer: Prec

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: contrast Court held contested measure affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders see Case 1182 PiraikiPatraiki Others v Commission 1985 ECR 207 paragraph 31 Case C15288 Sofrimport v Commission 1990 ECR I‑2477 paragraph 11 Belgium Forum 187 v Commission paragraph 60
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: regard true decision adopts end examination Commission may exercise discretion differentiate beneficiaries aid scheme notified regard certain characteristics display conditions fulfil
Answer: Itpr

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 88 caselaw cited
Answer:

retrieved examples:

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: addition paragraphs 80 81 judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court recalled fact recipient undertakings belong various economic sectors sufficient call question selective nature measure concerned held potentially selective nature measure issue way called question fact essential condition obtaining tax advantage conferred measure economic transaction particularly entirely financial transaction available regardless nature business recipient undertakings
Answer: Prec

Text: provisions EC Treaty apply alternative situations specific rule ECSC Treaty see particular Case 32885 Deutsche Babcock 1987 ECR 5119 paragraphs 6 14
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 871 EC
Answer:

retrieved examples:

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Princ', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard even cases apparent circumstances granted aid liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision see Portugal v Commission paragraph 89 caselaw cited
Answer:

retrieved examples:

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Text: must also borne mind far determination reference framework must based objective examination content structure applicable rules national law necessary first stage examination selectivity take account objectives pursued legislature adopting measure examination
Answer: Itpr

Text: Court First Instance held inter alia paragraphs 77 79 contested judgment course Commission’s assessment new aid pursuant Article 933 Treaty notified put effect Commission required establish whether aid real impact trade Member States competition whether aid could affect trade
Answer: Rule

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: party may therefore put forward first time Court Justice plea could raised General Court raised since would allow bring Court Justice whose jurisdiction appeals limited case wider ambit came General Court see judgment 29 September 2011 Case C‑52009 P Arkema v Commission yet published ECR paragraph 64 caselaw cited
Answer: Prec

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: context noted also according settled caselaw purpose categorising national measure State aid necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition Case C22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraph 140 caselaw cited
Answer:

retrieved examples:

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: EU law cannot permit rules State aid circumvented merely creation autonomous institutions charged allocating aid see judgment 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 23
Answer: Prec

Text: Even though true purposes ECSC Treaty rules apply based domain State aid fundamental requirement legal certainty
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard specifically condition trade Member States affected follows caselaw grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently meeting condition taxable persons perform economic activity field trade conceivable competition operators established Member States see Portugal v Commission paragraph 91 Case C‑17203 Heiser 2005 ECR I‑1627 paragraph 35
Answer:

retrieved examples:

Text: case aid derives fact another category economic operators category liable pay tax direct competition liable charge
Answer: Itpr

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore Court held aid granted Member State strengthens position undertaking compared undertakings competing intraCommunity trade latter must regarded influenced aid Cassa di Risparmio di Firenze Others paragraph 141 caselaw cited
Answer:

retrieved examples:

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second recovery unlawful aid view reestablishing status quo ante imply reconstructing past events differently basis hypothetical elements choices often numerous could made operators concerned since choices actually made aid might prove irreversible judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 118
Answer: Prec

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: apparent judgment fact coming compulsory levy contrary sufficient identify State resources see effect judgment 28 March 2019 Germany v Commission C‑40516 P EUC2019268 paragraphs 65 72
Answer: Prec

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Class']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard fact economic sector liberalised Community level may serve determine aid real potential effect competition affects trade Member States Cassa di Risparmio di Firenze Others paragraph 142 caselaw cited
Answer:

retrieved examples:

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: case public undertakings assessment made applying principle private investor test see effect Case C30388 Italy v Commission 1991 ECR I1433 paragraph 20 Case C48299 France v Commission 2002 ECR I4397 paragraphs 68 70 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 91 caselaw cited
Answer: Prec

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: According settled case‑law persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed see inter alia judgments Case 2562 Plaumann v Commission 1963 ECR 95 Case C‑32195 P Greenpeace Council Others v Commission 1998 ECR I‑1651 paragraphs 7 28 Italy Sardegna Lines v Commission cited paragraph 32
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard condition distortion competition borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition see Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 30 Heiser paragraph 55
Answer:

retrieved examples:

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: findings examination interdependence EU Far Eastern markets relate possibility indirect effect trade intraCommunity competition referred principally Tubemeuse judgement
Answer:

retrieved examples:

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 55 60 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraphs 88 89
Answer: Prec

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: paragraphs 70 71 judgment Court stated supplementary requirement identify particular category undertakings exclusively favoured measure question may distinguished reason specific properties common characteristic cannot inferred caselaw Court Justice
Answer: Prec

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law General Court obliged reject inadmissible head claim application brought essential matters law fact head claim based indicated coherently intelligibly application Case C‑21405 P Rossi v OHIM 2006 ECR I‑7057 paragraph 37 order 13 March 2007 Case C‑15006 P Arizona Chemical Others v Commission published ECR paragraph 45
Answer:

retrieved examples:

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: stated recital 14 preamble regulation limitation period established reasons legal certainty
Answer: Rule

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: Furthermore assessment reference made exclusively subject matter action see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 30 31 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 50 51 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraphs 38 39 caselaw cited
Answer: Prec

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court entitled pointing Article 441c Rules Procedure application must state subject‑matter proceedings summary pleas law application based manner sufficiently clear precise enable defendant prepare defence General Court give ruling reject argument alleging infringement Article 88 EC Regulation 6591999 inadmissible ground satisfy conditions
Answer:

retrieved examples:

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: contrary settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According established case‑law Court following restructuring entailing transfer production facilities one company newly constituted manufacturing companies since former company continues interest newly constituted manufacturing companies companies may far aid granted concerned together form single group notwithstanding fact newly constituted manufacturing companies legal personality separate former company see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 11
Answer:

retrieved examples:

Text: Indeed according settled caselaw grounds judgment General Court disclose infringement EU law operative part shown well founded legal grounds infringement capable bringing setting aside judgment judgments 30 September 2003 Biret International v Council C‑9302 P EUC2003517 paragraph 60 caselaw cited 14 October 2014 Buono Others v Commission C‑1213 P C‑1313 P EUC20142284 paragraph 62 caselaw cited
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: However first factual assessment Czech Republic voluntarily undertook implement ‘review mechanism’ apparent caselaw cited paragraph 24 fall within jurisdiction Court Justice hearing appeal except facts distorted alleged appellants
Answer: Prec

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: former company new operating companies form economic unit inter alia restructuring carried constitutes indivisible whole industrial economic point view see effect Intermills v Commission paragraph 12
Answer:

retrieved examples:

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: sufficient Commission’s decision include information enabling recipient calculate amount without overmuch difficulty see also Case C‑48098 Spain v Commission 2000 ECR I8717 paragraph 25 Case C‑41503 Commission v Greece 2005 ECR I3875 paragraph 39
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards second third parts ground appeal considered together must recalled accordance Court’s settled caselaw actions failure fulfil obligations brought ground infringement decision ordering recovery unlawful aid Member State encounters unforeseen unforeseeable difficulties becomes aware consequences overlooked Commission must submit problems Commission consideration together proposals suitable amendments decision issue
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also apparent Court’s case‑law entity owning controlling shareholdings company actually exercises control involving directly indirectly management thereof must regarded taking part economic activity carried controlled undertaking Case C‑22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraphs 112 118
Answer:

retrieved examples:

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: general application derives fact decisions apply objectively determined situations produce legal effects respect category persons envisaged general abstract manner see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 31 17 September 2009 Commission v Koninglijke FrieslandCampina C‑51907 P EUC2009556 paragraph 53 caselaw cited 28 June 2018 Lowell Financial Services v Commission C‑21916 P published EUC2018508 paragraph 42 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case simple separation undertaking two different entities first pursues directly former economic activity second controls first fully involved management would sufficient deprive rules European Union relating State aid practical effect
Answer:

retrieved examples:

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: would enable second entity benefit subsidies advantages granted State means State resources use whole part benefit former interest also economic unit formed two entities Cassa di Risparmio di Firenze Others paragraph 114
Answer:

retrieved examples:

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: accordance case‑law Court apprehension internal difficulties cannot justify failure Member State comply obligations Community law see inter alia Case C‑40497 Commission v Portugal 2000 ECR I‑4897 paragraph 52 Case C‑31099 Italy v Commission cited paragraph 105 Case C‑40400 Commission v Spain 2003 ECR I‑6695 paragraph 55
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: may reveal possible exercise functions relating control direction financial support – going beyond simple placing capital investor – illustrate existence organic functional links entity owning controlling shareholding company controlled company fact members management committee controlling body entity appointed equivalent bodies controlled company see effect Cassa di Risparmio di Firenze Others paragraphs 116 117
Answer:

retrieved examples:

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: Consequently recovery State aid unlawfully granted purpose restoring previously existing situation cannot principle regarded disproportionate objectives Treaty regard State aids see Tubemeuse cited paragraph 66 Case C‑16995 Spain v Commission 1997 ECR I135 paragraph 47
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer:

retrieved examples:

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Thus respect assessment context appeal General Court’s determinations national law Court Justice jurisdiction determine whether law distorted see judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited
Answer: Prec

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: addition must pointed according Article 1bii regulation ‘existing aid’ understood inter alia ‘authorised aid say aid schemes individual aid authorised Commission Council
Answer: Rule

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 42 order 21 January 2010 Case C‑15009 P Iride Iride Energia v Commission published ECR paragraph 42
Answer:

retrieved examples:

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: must held first Article 4c CS prohibits granting State aid steel coal undertakings without drawing distinction individual aid aid disbursed State aid scheme Article 67 CS refers expressly State aid respect protective measures Commission may authorise pursuant first indent paragraph 2 article favour coal steel undertakings suffer competitive disadvantages general economic policy measures
Answer: Rule

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: However European Union Courts must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn Case C1203 P Commission v Tetra Laval 2005 ECR I987 paragraph 39 Commission v Scott paragraph 65
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next clear Court’s case‑law need prevent cumulative effect aid repaid aid planned regardless whether individual aid aid covered aid scheme issue TWD v Commission caselaw allows Commission make compatibility aid conditional upon prior repayment earlier unlawful aid see effect order Iride Iride Energia v Commission paragraphs 49 50 70
Answer:

retrieved examples:

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: second intervention must liable affect trade Member States
Answer: Class

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: event case State aid notified delay may imputed Commission time learned existence aid incompatible common market
Answer: Itpr

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First Commission must appropriate take account cumulative effect earlier unlawful aid repaid new aid see effect Case C‑35595 P TWD v Commission paragraphs 26 27 second find new aid compatible common market evidence disposal enables reach conclusion see effect order Iride Iride Engergia v Commission paragraph 70
Answer:

retrieved examples:

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: common ground Commission required make complex economic assessment examines whether particular measures described State aid public authorities act way private creditor see Case C52504 P Spain v Lenzing 2007 ECR I9947 paragraph 59
Answer: Prec

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court correctly pointed paragraph 187 judgment appeal apparent TWD v Commission caselaw Commission decides initiate formal investigation procedure Member State potential beneficiary new aid provide Commission evidence capable showing aid compatible common market obligation also extends need establish new aid earlier unlawful aid incompatible common market repaid cumulative effect
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: presupposes action must liable successful procure advantage party bringing judgment 28 May 2013 Abdulrahim v Council Commission C‑23912 P EUC2013331 paragraph 61 caselaw cited
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Lastly since clear Court’s case‑law sufficient Commission establish aid issue capable affecting trade Member States distorting competition order Iride Iride Energia v Commission paragraph 72 General Court acted correctly finding Commission required circumstances case carry specific detailed examination advantages derived aid issue referring specifically position AEP ACEA market question relative competitors trends Community trade
Answer:

retrieved examples:

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: pointed paragraph 77 duty incumbent upon General Court state reasons judgments require address expressly arguments articulated parties reasoning sufficient enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review
Answer:

retrieved examples:

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: paragraph 120 judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 Court referring inter alia two abovementioned judgments expressly stated position selectivity national measure examination holding case selectivity followed fact undertakings engaged export activities carrying certain investment transactions abroad qualified tax advantage conferred measure
Answer: Prec

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover clear paragraphs 186 188 judgment appeal General Court set therein interpretation TWD v Commission caselaw
Answer:

retrieved examples:

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: Since determination reference system constitutes starting point comparative examination carried context assessment selectivity aid scheme error made determination necessarily vitiates whole analysis condition relating selectivity see effect judgments 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 107 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraph 46
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Articles 482 Rules Procedure General Court provides new plea law may introduced course proceedings unless based matters law fact come light course procedure see effect judgment 12 November 2009 Case C‑56408 P SGL Carbon v Commission published ECR paragraphs 20 34
Answer:

retrieved examples:

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place regards plea alleging breach conditions laid fourth paragraph Article 230 EC made clear outset Article 4 Regulation 6591999 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid notified compatible common market
Answer:

retrieved examples:

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: effect caselaw simply reimbursement undertaking amount tax required pay breach EU law damages national authorities ordered pay undertakings compensate damage caused constitute State aid
Answer: Prec

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer:

retrieved examples:

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: follows foregoing neither French Republic FT rely principle order prevent recovery unlawful aid see Case C‑14804 Unicredito Italiano 2005 ECR I‑11137 paragraph 104
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination Commission finds notwithstanding fact measure notified falls within scope Article 871 EC raise doubts compatibility common market Commission adopt decision raise objections Article 43 Regulation 6591999
Answer:

retrieved examples:

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Therefore appraisal facts General Court constitute save clear sense evidence produced distorted question law subject review Court Justice judgments Archer Daniels Midland Archer Daniels Midland Ingredients v Commission C‑39703 P EUC2006328 paragraph 85 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 180
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission adopts decision raise objections declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain sectors activity see effect inter alia judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraphs 49 50
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: undertakes initial examination planned aid
Answer: Itpr

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: position would different alteration fact constituted separate aid measure assessed separately would therefore influence assessment Commission already made original aid plan
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: latter provision decision call upon Member State concerned upon interested parties submit comments within prescribed period must rule exceed one month
Answer:

retrieved examples:

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Since doubts must trigger initiation formal investigation procedure interested parties referred Article 1h Regulation 6591999 participate must held interested party within meaning latter provision directly individually concerned decision
Answer:

retrieved examples:

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: However appropriate recall position adopted Court judgment Italy Sardegna Lines v Commission regard Commission Decision 9895EC 21 October 1997 concerning aid granted Region Sardinia Italy shipping companies Sardinia OJ 1998 L 20 p 30 required Italian Republic recover beneficiary loans leases question element aid contained
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: beneficiaries procedural guarantees provided Article 882 EC Article 61 Regulation 6591999 able ensure guarantees respected must possible challenge European Union judicature decision raise objections see effect Case C‑7803 P Commission v Aktionsgemeinschaft Recht und Eigentum 2005 ECR I‑10737 paragraph 35 caselaw cited Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 28 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 31 caselaw cited
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: order determine whether measure selective therefore examined whether within context specified legal regime measure constitutes advantage certain undertakings others light objective pursued regime comparable factual legal situation judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36
Answer: Prec

Text: follows Court seeking case determine whether market position members Aktionsgemeinschaft Recht und Eigentum association set promote collective interests class persons substantially affected aid scheme subject decision question
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly specific status ‘interested party’ within meaning Article 1h Regulation 6591999 conjunction specific subjectmatter action sufficient distinguish individually purposes fourth paragraph Article 230 EC applicant contesting decision raise objections
Answer:

retrieved examples:

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Thus General Court stated paragraphs 302 303 judgment appeal range based estimates provided French authorities administrative procedure since Member State unable calculate exactly amount advantage FT benefited regime issue Commission entitled rely data thus provided
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard although applicant contests Commission decision initiate formal investigation procedure must accordance Article 441c Rules Procedure General Court define subjectmatter action application initiating proceedings requirement satisfied requisite legal standard applicant identifies decision seeks annulled
Answer:

retrieved examples:

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: matters little whether application initiating proceedings states seeking annulment ‘a decision raise objections’ – term used Article 43 Regulation 6591999 – decision initiate formal investigation procedure since Commission takes position aspects question means single decision
Answer:

retrieved examples:

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: General Court recalled paragraph 26 judgment appeal persons decision addressed may claim individually concerned within meaning fourth paragraph Article 263 TFEU decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressedjudgments 15 July 1963 Plaumann v Commission 2562 EUC196317 107 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 72 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 46
Answer: Rule

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard first third pleas General Court thus rightly pointed paragraph 81 judgment appeal according settled caselaw General Court interpret action challenging exclusively merits aid assessment decision seeking reality ensure respect procedural rights available applicant Article 882 EC applicant expressly raised plea effect
Answer:

retrieved examples:

Text: follows Court seeking case determine whether market position members Aktionsgemeinschaft Recht und Eigentum association set promote collective interests class persons substantially affected aid scheme subject decision question
Answer: Prec

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances interpretation plea would tantamount redefining subjectmatter action see effect judgment 29 November 2007 Case C‑17606 P Stadtwerke Schwäbisch Hall Others v Commission paragraph 25
Answer:

retrieved examples:

Text: settled caselaw adoption order recover unlawful aid logical normal consequence finding unlawful
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Third must confer advantage recipient
Answer: Class

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: use arguments nothing however bring change subjectmatter action conditions admissibility see effect 3F v Commission paragraph 35
Answer:

retrieved examples:

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently given Article 1 Third Steel Aid Code prohibited aid aid specific steel sector Commission could implicitly withdraw 1971 Decision
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrary existence doubts concerning compatibility precisely evidence must adduced order show Commission required initiate formal investigation procedure Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: First order determine whether measure although applying generally set economic operators effect ultimately conferring advantage certain undertakings examined apparent caselaw recalled paragraph 41 present judgment whether certain undertakings favoured others light objective pursued legal regime concerned comparable factual legal situation
Answer: Prec

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 1h Regulation 6591999 ‘interested party’ means inter alia person undertaking association undertakings whose interests might affected granting aid say particular competing undertakings beneficiary aid
Answer:

retrieved examples:

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: far concerns third criterion characterising measure State aid settled caselaw measures whatever form likely directly indirectly favour certain undertakings regarded economic advantage recipient undertaking would obtained normal market conditions regarded State aid see judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraph 34
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: words term covers indeterminate group persons see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 16
Answer:

retrieved examples:

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence provision rule possibility undertaking direct competitor beneficiary aid requires raw material production process categorised interested party provided undertaking demonstrates interests could adversely affected grant aid
Answer:

retrieved examples:

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: EU law cannot permit rules State aid circumvented merely creation autonomous institutions charged allocating aid see judgment 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 23
Answer: Prec

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: purpose necessary undertaking establish requisite legal standard aid likely specific effect situation see effect 3F v Commission paragraph 33
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw Court classification ‘State aid’ within meaning Article 1071 TFEU requires conditions set provision fulilled
Answer:

retrieved examples:

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: Second regards appellants interest bringing proceedings part contested decision relating tax reliefs clear caselaw Court Justice Commission points individual grants aid general aid scheme approved Commission meet conditions scheme constitute existing aid need notified Italy v Commission cited paragraphs 21 26
Answer: Prec

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Class', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus first must intervention State State resources
Answer:

retrieved examples:

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second intervention must liable affect trade Member States
Answer:

retrieved examples:

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: must borne mind according settled caselaw concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system part judgments Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 145 caselaw cited BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 101
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: third must confer selective advantage recipient
Answer:

retrieved examples:

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: particular clear caselaw order assess whether measure would adopted normal market conditions private investor situation close possible State benefits obligations linked situation State shareholder — exclusion linked situation public authority — taken account see effect Case 23484 Belgium v Commission 1986 ECR 2263 paragraph 14 Case 4085 Belgium v Commission 1986 ECR 2321 paragraph 13 Joined Cases C27892 C28092 Spain v Commission 1994 ECR I4103 paragraph 22 Case C33499 Germany v Commission 2003 ECR I1139 paragraph 134
Answer: Prec

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: matters regard fact measure irrespective form legislative means used effect placing recipient undertakings position favourable undertakings although undertakings comparable factual legal situation light objective pursued tax system concerned
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fourth must distort threaten distort competition judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer:

retrieved examples:

Text: Court held judgments mere fact provisions adopted part common agricultural policy place applicant unfavourable competitive position allow concluded provisions affect applicant’s legal situation line caselaw cannot transposed actions brought competitors beneficiaries State aid
Answer: Prec

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: ['Class', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: concept ‘aid’ embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 30
Answer:

retrieved examples:

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: principle legal certainty – one general principles European Union law – requires rules law clear precise predictable effect interested parties ascertain position situations legal relationships governed European Union law see effect Case C‑6393 Duff Others 1996 ECR I569 paragraph 20 Case C‑7606 P Britannia Alloys Chemicals v Commission 2007 ECR I‑4405 paragraph 79 Case C‑15807 Förster 2008 ECR I‑8507 paragraph 67
Answer: ['Prec', 'Princ']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70 caselaw cited
Answer:

retrieved examples:

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: public creditor grants payment facilities respect debt payable undertaking assessment made applying principle private creditor test judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: test applicable among factors Commission required take account purposes establishing whether aid exists see effect Case C34296 Spain v Commission 1999 ECR I2459 paragraph 46 Case C25697 DM Transport 1999 ECR I3913 paragraph 24 Commission v EDF paragraphs 78 103
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly private creditor test exception applies Member State requests constituent elements State aid incompatible common market laid Article 1071 TFEU exist
Answer:

retrieved examples:

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fact test applicable among factors Commission required take account purposes establishing whether aid exists see effect judgments 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 103 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: provision sets four conditions
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides competent court sufficient material exercise power review see Case C‑10504 P Nederlandse Federatieve Vereniging voor de Groothandel op Electrotechnisch Gebied v Commission 2006 ECR I‑8725 paragraph 72 Case C‑306 P Groupe Danone v Commission 2007 ECR I‑1331 paragraph 46
Answer: Prec

Text: regards Court First Instance’s finding adoption Second Third Steel Aid Code led ambiguity whether subsequent application ZRFG notified ‘plan’ within meaning Article 6 third code must first held article expressly provides obligation inform Commission plans grant aid steel industry schemes already taken decision EC Treaty
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: result appears private creditor test might applicable Commission ask Member State concerned provide relevant information enabling determine whether conditions applying test satisfied judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 33
Answer:

retrieved examples:

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: also noted Court Justice held paragraph 29 Commission v France provision European Union law requires Commission ordering recovery aid declared incompatible common market fix exact amount aid recovered
Answer: Prec

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place clear caselaw Court appears private creditor test might applicable Commission examine possibility irrespective request effect
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Furthermore even European Community first created situation capable giving rise legitimate expectations overriding public interest may preclude transitional measures adopted respect situations arose new rules came force still subject change Belgium Forum 187 v Commission paragraph 148 case‑law cited
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly Advocate General noted points 72 76 Opinion nothing prevents recipient aid invoking applicability test recipient invoke test falls Commission assess whether test needs applied assess application
Answer:

retrieved examples:

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: General Court pointed paragraph 42 judgment appeal review EU judicature legality decision initiate formal investigation procedure applicant challenges Commission’s assessment measure constituting State aid limited ascertaining whether Commission made manifest error assessment see effect judgment 21 July 2011 Alcoa Trasformazioni v Commission C‑19409 P EUC2011497 paragraph 61
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: regard particular unlawful aid granted form tax advantage also Court’s settled caselaw recovery aid means transactions actually carried recipients aid question must subject tax treatment recipients would received absence unlawful aid see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 119
Answer: Prec

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second place regards relevance subjective state mind must noted Advocate General pointed point 74 Opinion starting point determining whether private operator test applied must economic nature Member State’s action Member State subjectively speaking thought acting alternative courses action considered adopting measure question
Answer:

retrieved examples:

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: Moreover Court held aid notified Commission apparent failure act part relation measure irrelevant see Demesa Territorio Histόrico de Álava v Commission paragraph 52
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: extent reaching conclusion Court relied fact measure issue worded form exception rule governing forfeiture losses recalled already pointed paragraph 92 present judgment regulatory technique used cannot decisive purposes determination reference framework
Answer: Itpr

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case private creditor test intended determine whether recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor sought recover sums due debtor financial difficulty judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 72 accordingly whether undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70
Answer:

retrieved examples:

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: hand also possible measure may raise doubts judgment 24 May 2011 Case C‑8309 P Commission v Kronoply Kronotex yet published ECR paragraph 43 order 9 June 2011 Case C‑45110 P TF1 v Commission paragraph 47 judgment 22 September 2011 Case C‑14809 P Belgium v Deutsche Post DHL International yet published ECR paragraph 53 judgment 27 October 2011 Case C‑4710 P Austria v ScheucherFleisch Others yet published ECR paragraph 40
Answer: Prec

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: regard noted distortion must obvious documents Court’s file without need carry new assessment facts evidence judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 80
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Second must noted Commission doubt applicability test clear paragraph 24 present judgment asked Slovak State relevant information regard carried overall assessment evidence see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 86
Answer:

retrieved examples:

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: follows length preliminary examination procedure constitute indication Commission may doubts regarding compatibility aid question common market length cannot lead conclusion Commission initiated formal investigation procedure see effect Case 8482 Germany v Commission 1984 ECR 1451 paragraphs 14 17 Belgium v Deutsche Post DHL International paragraph 81
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: provision sets four conditions
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: accordance Court’s settled caselaw applying private creditor test Commission must carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 73 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 47
Answer:

retrieved examples:

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 78 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 54
Answer:

retrieved examples:

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover purposes applying private creditor test relevant evidence information available developments foreseeable time decision taken see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 105
Answer:

retrieved examples:

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regard clear Court’s caselaw necessary financial balance economic viability undertaking entrusted operation service general economic interest threatened
Answer: Prec

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: contrast since assessment context appeal legal classification given national law General Court light provision EU law constitutes question law falls within jurisdiction Court Justice see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 83 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 61 63
Answer: Prec

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination Commission whether particular measures classified State aid public authorities act way private creditor requires complex economic assessment judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 74 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 48
Answer:

retrieved examples:

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: According judgment applicant individually concerned decision addressed another person decision affects reason certain attributes peculiar reason circumstances differentiated persons see also field State aid judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 32 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 52 fields judgments 17 January 1985 PiraikiPatraiki Others v Commission 1182 EUC198518 paragraphs 11 19 31 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 93
Answer: Prec

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection must observed context review Courts European Union complex economic assessments made Commission field State aid Courts substitute economic assessment Commission judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 75 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 49
Answer:

retrieved examples:

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Third must confer advantage recipient
Answer: Class

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Courts European Union must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 76 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 50
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: must recalled case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents case file judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 20 caselaw cited
Answer: Prec

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: Third must confer advantage recipient
Answer: Class

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: order determine whether measure selective therefore examined whether within context specified legal regime measure constitutes advantage certain undertakings others light objective pursued regime comparable factual legal situation judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36
Answer: Prec

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection also borne mind lawfulness decision concerning State aid falls assessed European Union judicature light information available Commission time decision adopted judgment 2 September 2010 Commission v Scott C‑29007 P EUC2010480 paragraph 91 caselaw cited
Answer:

retrieved examples:

Text: According settled caselaw order tax regarded forming integral part aid measure must hypothecated aid relevant national rules sense revenue tax necessarily allocated financing aid direct impact amount aid consequently assessment compatibility aid internal market see inter alia judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 46 caselaw cited 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraph 99
Answer: Prec

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However information ‘available’ Commission includes seemed relevant assessment carried accordance caselaw referred paragraphs 59 61 present judgment could obtained upon request Commission administrative procedure
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: decision visàvis undertaking seek contest decision measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Van der Kooy Others v Commission cited paragraph 15 Case C692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Italy Sardegna Lines v Commission paragraph 33
Answer: Prec

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Paragraphs 180 213 235 judgment appeal Commission’s objections referred paragraph 64 present judgment directed read legal context referred General Court imply new requirements incompatible caselaw Court Justice
Answer:

retrieved examples:

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: appeal Courts jurisdiction thus confined review findings pleas argued Court First Instance see Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 order 28 June 2001 Case C35299 P Eridania Others v Council 2001 ECR I5037 paragraphs 52 53
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General noted paragraphs 125 131 Opinion General Court merely noted paragraphs 191 195 198 199 judgment appeal internal contradictions decision issue made findings fact according none evidence administrative file able substantiate liquidation factors used Commission
Answer:

retrieved examples:

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Furthermore aid granted Member State strengthens position undertaking compared undertakings competing trade within European Union undertakings must regarded affected aid judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 141
Answer: Prec

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Prec']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: considerations far concern information normally prudent diligent private creditor situation close possible local tax office could priori ignore capable justifying General Court’s decision Commission failed take consideration relevant information see effect judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraphs 77 78 81
Answer:

retrieved examples:

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: However condition absolute impossibility implementation satisfied defendant Member State inform Commission internal difficulties legal political practical nature attributable national authorities’ acts omissions raised implementation decision issue without taking real steps recover aid undertakings concerned without suggesting Commission alternative methods implementing decision would allow difficulties overcome see effect judgments 13 November 2008 Commission v France C‑21407 EUC2008619 paragraph 50 12 February 2015 Commission v France C‑3714 published EUC201590 paragraph 66 caselaw cited
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']




LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Authoritative F1: 0.8571428571428572
Verbal Classification F1: 0.16216216216216217
Interpretation F1: 0.26666666666666666
Precedent F1: 0.7790697674418605
Rule F1: 0.64

macro F1: 0.5410082906827094
macro F1 (reliable): 0.7587375415282392

In [19]:
test(template, 30)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

query:
Text: regard must observed follows Article 58 Statute Court Justice conjunction Article 1132 Rules Procedure Court Justice appeal appellant may put forward relevant argument provided subjectmatter proceedings General Court changed appeal Case C‑22905 P PKK KNK v Council 2007 ECR I‑439 paragraph 66 Case C‑806 P Herrero Romeu v Commission 2007 ECR I‑10333 paragraph 32
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: undertakes initial examination planned aid
Answer: Itpr

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: includes positive benefits also measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Joined Cases C‑7808 C‑8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer: Prec

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Commission also takes relevant measure facilitate dialogue ensuring balanced support parties see effect Albany paragraphs 55 58 respect EEC Treaty Agreement social policy concluded Member States European Community exception United Kingdom Great Britain Northern Ireland OJ 1992 C 191 p 91 entry force Treaty Amsterdam
Answer: Prec

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 60
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard Court repeatedly held action annulment purposes Article 230 EC must available acts adopted institutions whatever nature form intended legal effects capable affecting interests applicant bringing distinct change legal position see inter alia Athinaïki Techniki v Commission paragraph 29 caselaw cited Case C‑36208 P Internationaler Hilfsfonds v Commission 2010 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Given condition direct concern requires contested measure produce effects directly applicant’s legal situation EU judicature must ascertain whether applicant adequately explained reasons Commission’s decision liable place unfavourable competitive position thus produce effects legal situation
Answer: Itpr

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: essential characteristic remuneration lies fact consideration service question see effect judgments 11 September 2007 Schwarz GootjesSchwarz C‑7605 EUC2007492 paragraphs 37 38 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 45 47
Answer: Prec

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: accordance Court’s settled caselaw applicant’s interest bringing proceedings must light purpose action exist action lodged failing action inadmissible
Answer: Prec

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows also settled caselaw concerning admissibility actions annulment necessary look actual substance acts challenged order classify see particular Case 6081 IBM v Commission 1981 ECR 2639 paragraph 9 Case C‑14796 Netherlands v Commission 2000 ECR I‑4723 paragraph 27
Answer:

retrieved examples:

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: contrast regulatory act entails implementing measures judicial review compliance EU legal order ensured irrespective whether measures adopted European Union Member States
Answer: Prec

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: second intervention must liable affect trade Member States
Answer: Class

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: cases Commission required undertake detailed examination difficulties pleaded suggested alternative methods recovery
Answer: Itpr

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part see judgments 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraphs 41 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 82 83 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 74 75 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 54 55
Answer: Prec

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrast form act decision adopted principle irrelevant right challenge acts decisions way action annulment
Answer:

retrieved examples:

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain business sectors judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 55 caselaw cited
Answer: Prec

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore principle irrelevant classification act question whether satisfies certain formal requirements namely particular duly identified author mentions provisions providing legal basis
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: New aid therefore subject precautionary review Commission may principle put effect time latter declared compatible Treaty
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: regards whether ground well founded according settled caselaw definition aid general subsidy
Answer: Prec

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore irrelevant act may described ‘decision’ refer Article 42 3 4 Regulation 6591999
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: position would different alteration fact constituted separate aid measure assessed separately would therefore influence assessment Commission already made original aid plan
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also importance Member State concerned notified act issue Commission infringing Article 25 regulation error capable altering substance act see Athinaïki Techniki v Commission paragraphs 43 44 caselaw cited
Answer:

retrieved examples:

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: However first factual assessment Czech Republic voluntarily undertook implement ‘review mechanism’ apparent caselaw cited paragraph 24 fall within jurisdiction Court Justice hearing appeal except facts distorted alleged appellants
Answer: Prec

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored judgment 29 April 2004 Germany v Commission C‑27700 EUC2004238 paragraph 75 caselaw cited
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore principle measures definitively determine position Commission upon conclusion administrative procedure intended legal effects capable affecting interests complainant constitute acts open challenge purposes Article 230 EC intermediate measures whose purpose prepare final decision effects see Athinaïki Techniki v Commission paragraph 42 caselaw cited
Answer:

retrieved examples:

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Court repeatedly held right rely principle protection legitimate expectations extends person situation Community institution caused entertain expectations justified precise assurances provided
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard possible definitive actionable nature measures taken Commission procedure reviewing State aid noted first Commission must Article 101 Regulation 6591999 carry examination possession information whatever source regarding allegedly unlawful aid
Answer:

retrieved examples:

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 55 60 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraphs 88 89
Answer: Prec

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: measure issue judgment concerned sector years receiving State aid approved Commission object meet additional costs operation already received authorised aid Case C‑33499 Germany v Commission 2003 ECR I‑1139 paragraph 44
Answer: Prec

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently regulatory technique used cannot decisive purposes determining reference framework see effect judgment WDFG paragraph 76 judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 92
Answer: Prec

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination complaint basis provision gives rise initiation preliminary examination stage Article 883 EC obliges Commission examine immediately possible existence aid compatibility common market see effect Athinaïki Techniki v Commission paragraph 37
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: third place according settled caselaw fact Member State seeks approximate unilateral measures conditions competition particular sector economy prevailing Member States cannot deprive measures question character aid Joined Cases 669 1169 Commission v France 1969 ECR 523 paragraphs 20 21 Case C697 Italy v Commission 1999 ECR I2981 paragraph 21
Answer: Prec

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 131 Regulation 6591999 applicable context examination complaint alleging unlawful aid obliges Commission close preliminary examination stage adopting decision pursuant Article 42 3 4 regulation say decision finding aid exist raising objections initiating formal investigation procedure since institution authorised persist failure act preliminary examination stage
Answer:

retrieved examples:

Text: cases relate provisions national law granting relief taxes charges judgments France v Commission C‑24194 EUC1996353 Piaggio C‑29597 EUC1999313 DM Transport C‑25697 EUC1999332 P C‑612 EUC2013525 Ministerio de Defensa Navantia C‑52213 EUC20142262 British Telecommunications v Commission C‑62013 P EUC20142309 exceptions matters insolvency judgment Ecotrade C‑20097 EUC1998579
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Thus according caselaw Court tax cannot hypothecated exemption payment tax category undertakings thus even undertakings operate competition undertakings liable pay tax question
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: settled caselaw undertaking cannot principle contest Commission decision prohibiting aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme see Joined Cases C1598 C10599 Italy Sardegna Lines v Commission 2000 ECR I8855 paragraph 33 caselaw cited
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: stage procedure completed Commission bound consequently either initiate next stage procedure provided Article 882 EC adopt definitive decision rejecting complaint see effect Athinaïki Techniki v Commission paragraph 40 caselaw cited
Answer:

retrieved examples:

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: assessment made public creditor grants payment facilities respect debt payable undertaking applying principle private creditor test
Answer: Prec

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission finds following examination complaint investigation revealed grounds concluding State aid within meaning Article 87 EC refuses implication initiate procedure provided Article 882 EC see effect Case C‑36795 P Commission v Sytraval Brink’s France 1998 ECR I‑1719 paragraph 47
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: apparent judgment fact coming compulsory levy contrary sufficient identify State resources see effect judgment 28 March 2019 Germany v Commission C‑40516 P EUC2019268 paragraphs 65 72
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards Commission’s finding measures complained constituted existing aid noted existing aid course subject constant review provided Article 881 EC must regarded lawful long Commission found incompatible common market see Case C‑4493 NamurLes assurances du crédit 1994 ECR I‑3829 paragraph 34 Case C‑40099 Italy v Commission 2001 ECR I‑7303 paragraph 48
Answer:

retrieved examples:

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: already noted paragraphs 83 85 purposes applying private investor test relevant evidence information available developments foreseeable time decision make investment taken
Answer: Itpr

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect inter alia judgment 18 July 2013 PC‑612 EUC2013525 paragraph 18
Answer: Prec

Text: Aid relatively small amount liable affect competition trade Member States strong competition sector undertakings receive operate see Case 25985 France v Commission 1987 ECR 4393 paragraph 24 Case C‑35198 Spain v Commission 2002 ECR I‑8031 paragraph 63
Answer: Prec

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: may seen Joined Cases C‑7291 C‑7391 Sloman Neptun 1993 ECR I‑887 system established DIS register enables contracts employment concluded seafarers nationals nonmember countries permanent abode residence Member State concerned subjected working conditions rates pay covered law Member State considerably less favourable applicable seafarers nationals Member State constitute State aid within meaning Article 871 EC
Answer: Prec

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However receives complaint relating allegedly unlawful aid Commission classifying measure existing aid subjects procedure provided Article 881 EC thus refuses implication initiate procedure provided Article 882 EC see effect CIRFS Others v Commission paragraphs 25 26 Case C‑32199 P ARAP Others v Commission 2002 ECR I‑4287 paragraph 61
Answer:

retrieved examples:

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: latter case may measure raise doubts compatibility common market
Answer: Itpr

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: According Court’s caselaw Van der Kooy CIRFS cases thus concerned particular situations applicant occupied clearly circumscribed position negotiator intimately linked actual subjectmatter decision thus placing factual situation distinguished persons Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraph 45
Answer: Prec

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: decision refusing initiate procedure provided Article 882 EC definitive cannot characterised mere provisional measure CIRFS Others v Commission paragraph 26 effect Athinaïki Techniki v Commission paragraphs 54 58
Answer:

retrieved examples:

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal see inter alia judgment A2A v Commission C‑32009 P EUC2011858 paragraph 97
Answer: Prec

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: situation persons intended benefit procedural guarantees afforded provision may secure compliance therewith able challenge decision question European Union judicature fourth paragraph Article 230 EC
Answer:

retrieved examples:

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: extent reaching conclusion Court relied fact measure issue worded form exception rule governing forfeiture losses recalled already pointed paragraph 92 present judgment regulatory technique used cannot decisive purposes determination reference framework
Answer: Itpr

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Joined Cases 6785 6885 7085 Kwekeriij van der Kooy Others v Commission 1988 ECR 219 paragraph 15 Case C‑692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Joined Cases C‑1598 C‑10599 Italy Sardegna Lines v Commission 2000 ECR I‑8855 paragraph 33
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: principle applies equally whether ground decision taken Commission regards aid compatible common market view existence aid must discounted Commission v Sytraval Brink’s France paragraph 47 considers existing aid see effect CIRFS Others v Commission paragraph 27 ARAP Others v Commission paragraph 62
Answer:

retrieved examples:

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: General Court recalled paragraph 26 judgment appeal persons decision addressed may claim individually concerned within meaning fourth paragraph Article 263 TFEU decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressedjudgments 15 July 1963 Plaumann v Commission 2562 EUC196317 107 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 72 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 46
Answer: Rule

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: Even circumstances aid granted show liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 89 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 49
Answer: Prec

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: finding corroborated Article 20 Regulation 6591999 governs rights interested parties
Answer:

retrieved examples:

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: connection must observed context review conducted European Union Courts complex economic assessments made Commission field State aid Courts substitute economic assessment Commission see effect Case C29007 P Commission v Scott 2010 ECR I7763 paragraphs 64 66 caselaw cited
Answer: Prec

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: pointed paragraph 146 appeal plea directed ground included sake completeness judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According second third sentences Article 202 thereof obtaining interested party information concerning alleged unlawful aid alleged misuse aid Commission either consider insufficient grounds taking view case inform interested party thereof take decision case concerning subjectmatter information supplied
Answer:

retrieved examples:

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Article 2 EC Treaty amendment Article 2 EC declares particular task Community ‘to promote … harmonious balanced development economic activities’ ‘a high level employment social protection
Answer: Rule

Text: accordance settled caselaw appeal plea directed ground judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Moreover true stated General Court paragraph 66 judgment appeal Autogrill España v Commission paragraph 70 judgment appeal Banco Santander Santusa v Commission Court held paragraph 42 judgment 29 March 2012 3M Italia C‑41710 EUC2012184 fact taxpayers satisfying conditions application measure concerned case could benefit measure could make selective measure
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows Commission examined information taken position takes decision
Answer:

retrieved examples:

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: also follows function repayment aid general rule save exceptional circumstances Commission exceed bounds discretion recognised caselaw Court asks Member State recover sums granted way unlawful aid since restoring previous situation see Case C‑7597 Belgium v Commission 1999 ECR I‑3671 paragraph 66 Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 99
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: appraisal facts General Court therefore constitute save clear sense evidence produced distorted question law subject review Court Justice see inter alia judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78
Answer: Prec

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: circumstances Court finds General Court responded requisite legal standard arguments relating principle limitation relied FT disregard requirement state reasons established caselaw cited paragraph 88
Answer: Itpr

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Consequently given Article 1 Third Steel Aid Code prohibited aid aid specific steel sector Commission could implicitly withdraw 1971 Decision
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Therefore action annulment decision initiate procedure pursuant Article 882 EC brought party concerned within meaning article must considered admissible party seeks thereby safeguard procedural rights available latter provision see Athinaïki Techniki v Commission paragraph 36 caselaw cited
Answer:

retrieved examples:

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: assessment General Court facts evidence cannot challenged appeal court except facts distorted see effect judgment 15 May 2019 CJ v ECDC C‑17018 P published EUC2019410 paragraph 23 caselaw cited relied appellants claim General Court examine evidence adduced take account offer submit additional evidence
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regards thirdly Commissions claim alternative Court set aside words view paragraph 36 English version judgment appeal clear grounds judgment Court First Instance decide admissibility application basis subjective appraisal interests applicants explained basis rules governing admissibility actions Article 173 Treaty
Answer: Rule

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: According settled caselaw order tax regarded forming integral part aid measure must hypothecated aid relevant national rules sense revenue tax necessarily allocated financing aid direct impact amount aid consequently assessment compatibility aid internal market see inter alia judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 46 caselaw cited 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraph 99
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appellant undertaking competition company benefiting measures complained without doubt interested party purposes Article 882 EC see Commission v Sytraval Brink’s France paragraph 41 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 32 regard definition term Article 1h Regulation 6591999
Answer:

retrieved examples:

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Indeed appellant could thus base appeal pleas law arguments already relied Court First Instance appeal would deprived part purpose
Answer: Itpr

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: follows condition application receipt tax aid may grounds finding aid selective condition leads distinction made undertakings despite fact light objective pursued tax system concerned comparable factual legal situation therefore represents discrimination undertakings excluded
Answer: Itpr

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances Commission’s complaint reference notice relating State aid field taxation ineffective see effect Case C18299 P Salzgitter v Commission 2003 ECR I10761 paragraphs 54 55 unnecessary consider content scope notice stage
Answer:

retrieved examples:

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: Third must confer advantage recipient
Answer: Class

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: Similarly term ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 41 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 87
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: measure accordingly operated de facto discrimination undertakings comparable situation light objective pursued regime case objective putting place generalised taxation resident companies
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: remove certain kinds subcategories nonlegislative acts general application scope provision would run counter objective
Answer: Itpr

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw definition aid general subsidy given includes positive benefits subsidies also State measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 38 Joined Cases C‑7808 C8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer:

retrieved examples:

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: Second Commission specific grant aid alleged made pursuance previously authorised scheme cannot outset examine directly relation Treaty
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: event case State aid notified delay may imputed Commission time learned existence aid incompatible common market
Answer: Itpr

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: therefore follows judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 selectivity tax measure established even measure constitute derogation ordinary tax system integral part system fact remains judgment consistent Court’s settled caselaw cited paragraph 57 judgment effect sufficient order establish selectivity measure derogates ordinary tax system demonstrate measure benefits certain operators others although operators objectively comparable situation light objective pursued ordinary tax system
Answer: Prec

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Consequently measure public authorities grant certain undertakings favourable tax treatment although involving transfer State resources places recipients favourable financial position taxpayers amounts State aid within meaning Article 871 EC see Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Paint Graphos Others paragraph 46 caselaw cited
Answer:

retrieved examples:

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Accordingly clear distortion alleged manifestly apparent documents Court arguments Orange fact asking Court carry fresh assessment facts evidence falls outside Court’s jurisdiction
Answer: Itpr

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: Second recalled Commission required establish aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 8 September 2011 Commission v Netherlands C‑27908 P EUC2011551 paragraph 13 caselaw cited
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: case funds issue could regarded State resource since time public control see judgment 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 36 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: hand advantages resulting general measure applicable without distinction economic operators constitute State aid within meaning Article 87 EC see effect Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 22 Joined Cases C‑39304 C‑4105 Air Liquide Industries Belgium 2006 ECR I‑5293 paragraph 32 caselaw cited
Answer:

retrieved examples:

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Member State concerned provides Commission requisite evidence Commission carry global assessment taking account — addition evidence provided Member State — relevant evidence enabling determine whether Member State took measure question capacity shareholder public authority
Answer: Itpr

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: However Member State provide justification
Answer: Itpr

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: said appellant entitled lodge appeal relying Court Justice grounds arguments arise judgment appeal seek criticise law correctness judgments 29 November 2007 Stadtwerke Schwäbisch Hall Others v Commission C‑17606 P published EUC2007730 paragraph 17 4 March 2021 Commission v Fútbol Club Barcelona C‑36219 P EUC2021169 paragraph 47
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore necessary determine whether proposed tax reform selective selectivity constituent factor concept State aid see Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 54
Answer:

retrieved examples:

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: Admittedly stated paragraph 33 applicant must always show requisite legal standard interests might affected granting aid possible showing fact competitive position relation trade unions operating market
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: presupposes action must liable successful procure advantage party bringing judgment 28 May 2013 Abdulrahim v Council Commission C‑23912 P EUC2013331 paragraph 61 caselaw cited
Answer: Prec

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: consequence would national tax rules fall outset outside scope control State aid account sole fact adopted different regulatory technique although adjusting combining various tax rules produce effects law andor fact
Answer: Itpr

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards appraisal condition selectivity clear settled caselaw Article 871 EC requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 41 Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 82 caselaw cited
Answer:

retrieved examples:

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: Indeed neither contended established General Court developed reasoning running manifestly counter content provisions German law issue ascribed one provisions scope manifestly light material file see effect judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 81
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Court Justice’s jurisdiction appeal confined review findings law pleas argued General Court
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: falls Commission show measure particular creates differences undertakings regard objective measure comparable situation
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: noted paragraph 73 selective advantages advantages resulting general measure applicable without distinction economic operators fall within concept State aid
Answer:

retrieved examples:

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: Similarly basis obliged engage new tariff negotiations supplier sign new agreement order put effect Commission’s decision
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First appropriate recall Court consistently held Article 871 EC distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see British Aggregates v Commission paragraphs 85 89 caselaw cited Case C‑27908 P Commission v Netherlands 2011 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: However financial situation recipient public undertaking depends means used place advantage however may effected amount undertaking ultimately receives
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: regards second condition set Article 230 EC borne mind fact disputed provision nature scope provision general application inasmuch applies traders concerned general prevent individual concern Belgium Forum 187 v Commission paragraph 58 case‑law cited
Answer: Rule

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Thus Member State makes alteration existing aid scheme breach authorisation condition scheme Member State guarantee authorised aid scheme affected alteration advantages granted basis scheme therefore retained
Answer: Itpr

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: EU judicature stage examination admissibility rule definitively competitive relationships applicant beneficiaries national measures assessed decision Commission State aid decision issue see effect judgments 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 28 20 December 2017 Binca Seafoods v Commission C‑26816 P EUC20171001 paragraph 59 direct effect applicant cannot deduced mere potential existence competitive relationship found judgments appeal
Answer: Prec

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court admittedly held paragraph 56 Portugal v Commission determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation
Answer:

retrieved examples:

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: regard Court’s established caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 94 caselaw cited
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 1071 TFEU
Answer: ['Princ', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: benefit may advantage constituting aid may indeed benefit cannot justify failure recover aid recovery different sum constituting advantage procured unlawful aid question
Answer: Itpr

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However contrary General Court’s reasoning proposition put forward Government Gibraltar United Kingdom caselaw make classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general liable tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings
Answer:

retrieved examples:

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: application tax exemption extent depend tax revenue
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: follows length preliminary examination procedure constitute indication Commission may doubts regarding compatibility aid question common market length cannot lead conclusion Commission initiated formal investigation procedure see effect Case 8482 Germany v Commission 1984 ECR 1451 paragraphs 14 17 Belgium v Deutsche Post DHL International paragraph 81
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: However classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general subject tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 91
Answer: Prec

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: interpretation selectivity criterion would require contrary caselaw cited paragraph 87 order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer:

retrieved examples:

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence would national tax rules fall outset outside scope control State aid merely adopted different regulatory technique although produce effects law andor fact
Answer:

retrieved examples:

Text: Consequently considering whether private investor test applicable General Court err law focusing analysis fiscal nature means employed French State improvement — view opening electricity market — EDF’s financial situation effects measure question competition
Answer: Itpr

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court held judgments mere fact provisions adopted part common agricultural policy place applicant unfavourable competitive position allow concluded provisions affect applicant’s legal situation line caselaw cannot transposed actions brought competitors beneficiaries State aid
Answer: Prec

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: paragraphs 34 35 judgment Court held since Sardegna Lines concerned Decision 9895 virtue undertaking shipping sector Sardinia potential beneficiary aid scheme Sardinian shipowners also virtue actual beneficiary individual aid granted scheme recovery ordered Commission individually concerned decision action directed decision admissible
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: case prohibition applies aid measure introduced alteration
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Article 1071 TFEU save otherwise provided Treaties aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States incompatible internal market
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: true absence European Union rules governing matter falls within competence Member States infra‑State bodies fiscal autonomy designate bases assessment spread tax burden across different factors production economic sectors General Court held paragraph 146 judgment appeal
Answer:

retrieved examples:

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Consequently General Court correctly applied Article 841 Rules Procedure rejecting plea ground time
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: According settled caselaw Court persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually way person addressed judgments 15 July 1963 Plaumann v Commission 2562 EUC196317 p 107 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraph 57
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: therefore clearly apparent wording paragraph 20 practice directions state ‘the appeal … unless special circumstances exceed 25 pages’ recital set absolute limitation number pages admissibility appeal subject merely provides recommendation regard parties
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: regard true decision adopts end examination Commission may exercise discretion differentiate beneficiaries aid scheme notified regard certain characteristics display conditions fulfil
Answer: Itpr

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: CIRFS case CIRFS Commission’s interlocutor regard introduction ‘discipline’ concerning aid synthetic fibre sector also extension adaptation actively pursued negotiations Commission prelitigation procedure particular submitting written observations keeping close contact responsible departments Commission
Answer: Prec

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly according caselaw cited paragraph 73 different tax burden resulting application ‘general’ tax regime sufficient establish selectivity taxation purposes Article 871 EC
Answer:

retrieved examples:

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards second conditions say individually concerned act question settled caselaw persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed Case 2562 Plaumann v Commission 1963 ECR 95 107 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 52 Inuit Tapiriit Kanatami Others v Parliament Council paragraph 72
Answer: Prec

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Text: hand purpose aid recovery seek compensation individual harm kind reestablish market question situation aid granted
Answer: Itpr

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: provision sets four conditions
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus criteria forming basis assessment adopted tax system must also order capable recognised conferring selective advantages characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 871 EC
Answer:

retrieved examples:

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: second intervention must liable affect trade Member States
Answer: Class

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: matters regard fact measure irrespective form legislative means used effect placing recipient undertakings position favourable undertakings although undertakings comparable factual legal situation light objective pursued tax system concerned
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent judgment appeal documents included file appellants submitted General Court contrary Commission stated point 97 grounds contested decision normal tax rules company profits could used valid basis comparison thus reference framework assessment selectivity tax scheme issue
Answer:

retrieved examples:

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Infringement proceedings based objective finding Member State failed fulfil obligations EU law see particular judgment 6 October 2009 Commission v Spain C‑56207 EUC2009614 paragraph 18
Answer: Prec

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: follows rules governing proceedings EU Courts particular Article 21 Statute Court Justice European Union applicable General Court pursuant first paragraph Article 53 Statute Article 441 Rules Procedure General Court version applicable originating application lodged case principle determined delimited parties EU Courts cannot adjudicate ultra petita see effect judgment 10 December 2013 Commission v Ireland Others C‑27212 P EUC2013812 paragraph 27
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: noted begin assessing compatibility State aid maritime transport sector aid issue present case social aspects Community guidelines may taken account Commission part overall assessment includes large number considerations various kinds linked particular protection competition Community’s maritime policy promotion Community maritime transport promotion employment see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others v Commission 2000 ECR I‑3659 paragraph 52
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: must also borne mind far determination reference framework must based objective examination content structure applicable rules national law necessary first stage examination selectivity take account objectives pursued legislature adopting measure examination
Answer: Itpr

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Even case tax scheme issue confer economic advantage general realignment scheme
Answer:

retrieved examples:

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: proof may furnished reference body consistent evidence question whether doubt exists requires investigation circumstances decision raise objections adopted content comparing assessments upon Commission relied decision information available ruled compatibility aid question common market see effect Case C‑19891 Cook v Commission 1993 ECR I‑2487 paragraphs 30 31 Bouygues Bouygues Télécom v Commission paragraph 63 TF1 v Commission paragraph 52 Austria v ScheucherFleisch Others paragraphs 71 72
Answer: Prec

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: Even though true purposes ECSC Treaty rules apply based domain State aid fundamental requirement legal certainty
Answer: ['Itpr', 'Rule']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored see Case C‑35093 Commission v Italy 1995 ECR I‑699 paragraph 22
Answer: Prec

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court Justice stated determination reference framework purpose determining whether measure selective particular importance case tax measures since existence advantage may established compared “normal” taxation Case C8803 Portugal v Commission 2006 ECR I7115 paragraph 56 say taxation normally applicable undertakings light objective pursued scheme question factual legal situation comparable undertakings benefiting scheme Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 41
Answer:

retrieved examples:

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: case aid derives fact another category economic operators category liable pay tax direct competition liable charge
Answer: Itpr

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: hand General Court rightly pointed paragraph 206 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Commission preliminary examination finds doubts raised compatibility common market notified measure far falls within scope Article 871 EC adopt decision raise objections Article 43 Regulation 6591999 Commission v Kronoply Kronotex paragraph 44 TF1 v Commission paragraph 48 Austria v ScheucherFleisch Others paragraph 41
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Commission examining scheme light rules State aid envisage subjective choices might made beneficiaries scheme absence scheme examine scheme order determine whether entails objective standpoint economic advantage reference tax provisions derogates would normally applicable absence scheme see effect Case C14804 Unicredito Italiano 2005 ECR I11137 paragraph 118
Answer:

retrieved examples:

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: Third must confer advantage recipient
Answer: Class

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: Court thus held undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According Court’s caselaw however State aid defined Treaty Functioning European Union legal concept must interpreted basis objective factors
Answer:

retrieved examples:

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection legal remedy EU judicature purpose challenging lawfulness regulatory act
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Also far arguments set alternative 3F seeks put forward separate specific grounds demonstrate Commission infringed principle good administration essentially alleging duration preliminary examination stage unreasonable recalled according Article 1701 Rules Procedure Court Justice subjectmatter proceedings General Court may changed appeal
Answer: Rule

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal judgment Isdin v BialPortela C‑59712 P EUC2013672 paragraph 21
Answer: Prec

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: However prudent alert economic operator could foreseen adoption Community measure likely affect interests cannot plead principle measure adopted see effect Belgium Forum 187 v Commission paragraph 147 case‑law cited
Answer: Prec

Text: However Member State provide justification
Answer: Itpr

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reason European Union judicature must principle regard specific features case technical complex nature Commission’s assessments carry comprehensive review whether measure falls within scope Article 1071 TFEU see inter alia Case C8398 P France v Ladbroke Racing Commission 2000 ECR I3271 paragraph 25 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 111
Answer:

retrieved examples:

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Prec

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: follows condition application receipt tax aid may grounds finding aid selective condition leads distinction made undertakings despite fact light objective pursued tax system concerned comparable factual legal situation therefore represents discrimination undertakings excluded
Answer: Itpr

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Article 92 Treaty states Save otherwise provided Treaty aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods shall far affects trade Member States incompatible common market
Answer: Rule

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: However ground judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 must read context set grounds forms part set paragraphs 87 108 judgment
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover according equally wellestablished caselawthe concept State aid refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature general scheme system form part see effect inter alia AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 42 Portugal v Commission paragraph 52 British Aggregates v Commission paragraph 83 Joined Cases C10609 P C10709 P Commission Spain v Government Gibraltar United Kingdom 2011 ECR I11113 paragraph 145
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: However fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see Geigy v Commission cited paragraphs 20 21 Joined Cases C‑7400 P C‑7500 P Falck Acciaierie di Bolzano v Commission 2002 ECR I‑7869 paragraph 140
Answer: Prec

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Consequently appears private investor test could applicable Commission duty ask Member State concerned provide relevant information enabling determine whether conditions governing applicability application test met cannot refuse examine information unless evidence produced established adoption decision make investment question
Answer: Itpr

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent considerations carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part
Answer:

retrieved examples:

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: rules applicable investment sugar sector thus established Regulation 178581
Answer: Rule

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: examination therefore principle requires prior definition reference framework within measure concerned fits
Answer: Itpr

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Second Commission specific grant aid alleged made pursuance previously authorised scheme cannot outset examine directly relation Treaty
Answer: Itpr

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr', 'Prec']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly Court Justice held judicial review limited regard whether measure comes within scope Article 1071 TFEU case appraisals Commission technical complex nature see inter alia France v Ladbroke Racing Commission paragraph 25 British Aggregates v Commission paragraph 114
Answer:

retrieved examples:

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: Contrary General Court’s assertion paragraphs 59 62 judgment appeal Autogrill España v Commission paragraphs 63 66 judgment appeal Banco Santander Santusa v Commission indication contrary regards analysis condition relating selectivity tax measure may deduced judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467
Answer: ['Itpr', 'Prec']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Court held nature scheme preclude finding measure concerned selective contrary ruling General Court since condition relating selectivity broader scope extends measures effects favour certain undertakings case ‘offshore’ companies account specific features characteristic undertakings
Answer: Prec

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance rightly observed measure vitiated misuse powers appears basis objective relevant consistent evidence taken exclusive main purpose achieving end stated see inter alia Case C‑11097 Netherlands v Council 2001 ECR I‑8763 paragraph 137 cases cited
Answer:

retrieved examples:

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: However Member State provide justification
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: Member State concerned provides Commission requisite evidence Commission carry global assessment taking account — addition evidence provided Member State — relevant evidence enabling determine whether Member State took measure question capacity shareholder public authority
Answer: Itpr

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: third place regards first part decision issue true according settled caselaw Court recovery order individual concern beneficiaries aid scheme question order adopted exposed risk benefits received recovered therefore members restricted class see effect judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 33 35 29 April 2004 Italy v Commission C‑29800 P EUC2004240 paragraph 39 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 56
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: fourth paragraph Article 263 TFEU natural legal person may conditions laid first second paragraphs article institute proceedings act addressed person direct individual concern regulatory act direct concern entail implementing measures
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance undertook assessment facts unless clear sense evidence produced distorted constitute question law subject review Court Justice see inter alia Joined Cases C‑28099 P C‑28299 P Moccia Irme Others v Commission 2001 ECR I‑4717 paragraph 78 Joined Cases C‑23899 P C‑24499 P C‑24599 P C‑24799 P C‑25099 P C‑25299 P C‑25499 P Limburgse Vinyl Maatschappij Others v Commission 2002 ECR I‑8375 paragraph 285
Answer:

retrieved examples:

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Furthermore pointed paragraph 53 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Admittedly stated paragraph 33 applicant must always show requisite legal standard interests might affected granting aid possible showing fact competitive position relation trade unions operating market
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer:

retrieved examples:

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Since determination reference system constitutes starting point comparative examination carried context assessment selectivity aid scheme error made determination necessarily vitiates whole analysis condition relating selectivity see effect judgments 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 107 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraph 46
Answer: Prec

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: fact however taken consideration relation obligation recover incompatible aid light principles protection legitimate expectations legal certainty done Commission contested decision declined order recovery aid granted date publication Official Journal European Communities decisions initiate procedure laid Article 882 EC
Answer: ['Princ', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Court Justice’s jurisdiction appeal confined review findings law pleas argued General Court
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appeal Court’s jurisdiction confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C‑795 P John Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C‑21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer:

retrieved examples:

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: sufficient absence rights issue would possible undertaking perform particular tasks entrusted maintenance rights necessary enable holder perform tasks general economic interest assigned economically acceptable conditions judgment 15 November 2007 International Mail Spain C‑16206 EUC2007681 paragraph 35 caselaw cited
Answer: Prec

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: However accordance second sentence Article 141 Regulation 6591999 Commission shall require recovery aid would contrary general principle EU law
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: follows General Court correctly held paragraph 217 judgment appeal context proceedings Court must make necessary determinations order reach finding failure fulfil obligations result plea defence raised intervener relates element fact law Commission must necessarily take account analysis capable altering framework dispute even relied Member State concerned
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: respect borne mind pursuant Article 58 Statute Court Justice appeal Court Justice limited points law lie grounds particular infringement Community law Court First Instance
Answer:

retrieved examples:

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Thus Member State makes alteration existing aid scheme breach authorisation condition scheme Member State guarantee authorised aid scheme affected alteration advantages granted basis scheme therefore retained
Answer: Itpr

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard particular unlawful aid granted form tax advantage also Court’s settled caselaw recovery aid means transactions actually carried recipients aid question must subject tax treatment recipients would received absence unlawful aid see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 119
Answer: Prec

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: However requirement General Court give reasons decisions cannot interpreted meaning obliged respond detail every single argument advanced applicant particularly argument sufficiently clear precise see inter alia Joined Cases C‑12006 P C‑12106 P FIAMM Others v Council Commission 2008 ECR I‑6513 paragraph 91 caselaw cited
Answer: Prec

Text: selective follows reasoning set paragraphs 41 47 55 present judgment within context particular legal regime effect conferring advantage certain undertakings others different sector sector light objective pursued regime comparable factual legal situation
Answer: Itpr

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General states point 20 Opinion Commission’s appeal based precisely upon allegation Court First Instance infringed Community law failing follow apply interpretation Articles 87 EC 253 EC laid caselaw Court Justice
Answer:

retrieved examples:

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: benefit may advantage constituting aid may indeed benefit cannot justify failure recover aid recovery different sum constituting advantage procured unlawful aid question
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court accepted Albany restrictions competition inherent collective agreements organisations representing employers workers
Answer: Prec

Text: apparent provisions read together reply may seek annulment judgment appeal basis distinct independent grounds raised appeal since grounds may raised part crossappeal
Answer: Itpr

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: regard may added Court previously ruled tax measure solely undertakings carried specified transactions benefited undertakings sector carry transactions could classified selective need assess whether measure greater benefit large undertakings see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraphs 47 50
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule', 'Aut']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Regarding Wam’s argument Commission’s appeal invites Court Justice first review substance judgment appeal rather limited review ‘essential procedural requirement’ laid Article 230 EC second carry review substance Court Justice jurisdiction appeal stage noted Article 230 EC gives Court Justice jurisdiction review acts Community institutions Court First Instance
Answer:

retrieved examples:

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: According Court’s wellestablished caselaw appeal complaints directed ground included judgment General Court purely sake completeness must immediately dismissed ineffective since cannot lead judgment appeal set aside see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 75 caselaw cited
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: contrast Court held contested measure affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders see Case 1182 PiraikiPatraiki Others v Commission 1985 ECR 207 paragraph 31 Case C15288 Sofrimport v Commission 1990 ECR I‑2477 paragraph 11 Belgium Forum 187 v Commission paragraph 60
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Prior initiation procedure must first examine whether aid covered general scheme satisfies conditions laid decision approving
Answer: Itpr

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Text: regards fourth part ground appeal recalled appellant must pursuant Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court Justice indicate precisely evidence alleged distorted General Court demonstrate errors appraisal view led distortion
Answer: Rule

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Appeals judgments Court First Instance governed however terms Article 2251 EC Statute Court Justice
Answer:

retrieved examples:

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next must noted obligation provide statement reasons essential procedural requirement must distinguished question whether reasoning well founded latter concerned substantive legality measure issue see effect Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 48
Answer:

retrieved examples:

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: However Court stated State measure must regarded compensation services provided recipient undertakings order discharge public service obligations undertakings enjoy real financial advantage measure thus effect putting favourable competitive position undertakings competing measure caught Article 1071 TFEU see judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 87
Answer: Prec

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: Consequently considering whether private investor test applicable General Court err law focusing analysis fiscal nature means employed French State improvement — view opening electricity market — EDF’s financial situation effects measure question competition
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: Article 2 EC Treaty amendment Article 2 EC declares particular task Community ‘to promote … harmonious balanced development economic activities’ ‘a high level employment social protection
Answer: Rule

Text: Thus Member State stage procedure encounters difficulties recovering aid concerned must submit difficulties Commission consideration cooperate good faith Commission view overcoming particular suggesting alternative methods allowing recovery part aid
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: appellant alleges distortion evidence General Court must Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court indicate precisely evidence alleged distorted General Court show errors appraisal view led distortion
Answer: Rule

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw statement reasons required Article 253 EC must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer:

retrieved examples:

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: regard true decision adopts end examination Commission may exercise discretion differentiate beneficiaries aid scheme notified regard certain characteristics display conditions fulfil
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: case public undertakings assessment made applying principle private investor test see effect Case C30388 Italy v Commission 1991 ECR I1433 paragraph 20 Case C48299 France v Commission 2002 ECR I4397 paragraphs 68 70 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 91 caselaw cited
Answer: Prec

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 88 caselaw cited
Answer:

retrieved examples:

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: provisions EC Treaty apply alternative situations specific rule ECSC Treaty see particular Case 32885 Deutsche Babcock 1987 ECR 5119 paragraphs 6 14
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: addition paragraphs 80 81 judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court recalled fact recipient undertakings belong various economic sectors sufficient call question selective nature measure concerned held potentially selective nature measure issue way called question fact essential condition obtaining tax advantage conferred measure economic transaction particularly entirely financial transaction available regardless nature business recipient undertakings
Answer: Prec

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Since Lico Leasing PYMAR dispute admissibility first complaint first part Commission’s first ground appeal alleging error law identification beneficiaries advantages arising tax measures issue ground question fact true assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: provision sets four conditions
Answer: Class

Text: regards thirdly Commissions claim alternative Court set aside words view paragraph 36 English version judgment appeal clear grounds judgment Court First Instance decide admissibility application basis subjective appraisal interests applicants explained basis rules governing admissibility actions Article 173 Treaty
Answer: Rule

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 871 EC
Answer:

retrieved examples:

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regard noted distortion must obvious documents Court’s file without need carry new assessment facts evidence judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 80
Answer: Prec

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined judgments 16 March 1978 Unicme Others v Council 12377 EUC197873 paragraph 16 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 47 caselaw cited
Answer: Prec

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Princ', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard even cases apparent circumstances granted aid liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision see Portugal v Commission paragraph 89 caselaw cited
Answer:

retrieved examples:

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: party may therefore put forward first time Court Justice plea could raised General Court raised since would allow bring Court Justice whose jurisdiction appeals limited case wider ambit came General Court see judgment 29 September 2011 Case C‑52009 P Arkema v Commission yet published ECR paragraph 64 caselaw cited
Answer: Prec

Text: must also borne mind far determination reference framework must based objective examination content structure applicable rules national law necessary first stage examination selectivity take account objectives pursued legislature adopting measure examination
Answer: Itpr

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: follows paragraph 78 applicable test among factors Commission required take account purposes establishing existence aid
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Court First Instance held inter alia paragraphs 77 79 contested judgment course Commission’s assessment new aid pursuant Article 933 Treaty notified put effect Commission required establish whether aid real impact trade Member States competition whether aid could affect trade
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: confirmed fact reference made subsequent judgments Court restate principle see inter alia judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 73 29 March 2012 3M Italia C‑41710 EUC2012184 paragraph 39
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: context noted also according settled caselaw purpose categorising national measure State aid necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition Case C22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraph 140 caselaw cited
Answer:

retrieved examples:

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: EU law cannot permit rules State aid circumvented merely creation autonomous institutions charged allocating aid see judgment 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 23
Answer: Prec

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: Even though true purposes ECSC Treaty rules apply based domain State aid fundamental requirement legal certainty
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard specifically condition trade Member States affected follows caselaw grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently meeting condition taxable persons perform economic activity field trade conceivable competition operators established Member States see Portugal v Commission paragraph 91 Case C‑17203 Heiser 2005 ECR I‑1627 paragraph 35
Answer:

retrieved examples:

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: case aid derives fact another category economic operators category liable pay tax direct competition liable charge
Answer: Itpr

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: method aid financed may render entire aid scheme intended fund incompatible internal market
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore Court held aid granted Member State strengthens position undertaking compared undertakings competing intraCommunity trade latter must regarded influenced aid Cassa di Risparmio di Firenze Others paragraph 141 caselaw cited
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second recovery unlawful aid view reestablishing status quo ante imply reconstructing past events differently basis hypothetical elements choices often numerous could made operators concerned since choices actually made aid might prove irreversible judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 118
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner see judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 33 caselaw cited 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 49
Answer: Prec

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard fact economic sector liberalised Community level may serve determine aid real potential effect competition affects trade Member States Cassa di Risparmio di Firenze Others paragraph 142 caselaw cited
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: regards first argument must recalled accordance Court’s settled caselaw proceedings annulment General Court cannot substitute reasoning author contested act see judgments DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 141
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: According settled case‑law persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed see inter alia judgments Case 2562 Plaumann v Commission 1963 ECR 95 Case C‑32195 P Greenpeace Council Others v Commission 1998 ECR I‑1651 paragraphs 7 28 Italy Sardegna Lines v Commission cited paragraph 32
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Class']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard condition distortion competition borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition see Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 30 Heiser paragraph 55
Answer:

retrieved examples:

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Furthermore aid granted Member State strengthens position undertaking compared undertakings competing trade within European Union undertakings must regarded affected aid judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 141
Answer: Prec

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: findings examination interdependence EU Far Eastern markets relate possibility indirect effect trade intraCommunity competition referred principally Tubemeuse judgement
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: Given condition direct concern requires contested measure produce effects directly applicant’s legal situation EU judicature must ascertain whether applicant adequately explained reasons Commission’s decision liable place unfavourable competitive position thus produce effects legal situation
Answer: Itpr

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: paragraphs 70 71 judgment Court stated supplementary requirement identify particular category undertakings exclusively favoured measure question may distinguished reason specific properties common characteristic cannot inferred caselaw Court Justice
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: examination whether measure selective thus essence coextensive examination whether applies set economic operators nondiscriminatory manner see effect judgment 14 January 2015 Eventech C‑51813 EUC20159 paragraph 53
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law General Court obliged reject inadmissible head claim application brought essential matters law fact head claim based indicated coherently intelligibly application Case C‑21405 P Rossi v OHIM 2006 ECR I‑7057 paragraph 37 order 13 March 2007 Case C‑15006 P Arizona Chemical Others v Commission published ECR paragraph 45
Answer:

retrieved examples:

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: regards second condition set Article 230 EC borne mind fact disputed provision nature scope provision general application inasmuch applies traders concerned general prevent individual concern Belgium Forum 187 v Commission paragraph 58 case‑law cited
Answer: Rule

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Furthermore assessment reference made exclusively subject matter action see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 30 31 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 50 51 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraphs 38 39 caselaw cited
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: stated recital 14 preamble regulation limitation period established reasons legal certainty
Answer: Rule

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: cases Commission required undertake detailed examination difficulties pleaded suggested alternative methods recovery
Answer: Itpr

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court entitled pointing Article 441c Rules Procedure application must state subject‑matter proceedings summary pleas law application based manner sufficiently clear precise enable defendant prepare defence General Court give ruling reject argument alleging infringement Article 88 EC Regulation 6591999 inadmissible ground satisfy conditions
Answer:

retrieved examples:

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: contrary settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 1071 TFEU
Answer: ['Princ', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According established case‑law Court following restructuring entailing transfer production facilities one company newly constituted manufacturing companies since former company continues interest newly constituted manufacturing companies companies may far aid granted concerned together form single group notwithstanding fact newly constituted manufacturing companies legal personality separate former company see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 11
Answer:

retrieved examples:

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: Third must confer advantage recipient
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: New aid therefore subject precautionary review Commission may principle put effect time latter declared compatible Treaty
Answer: Itpr

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: applicability private investor test ultimately depends therefore Member State concerned conferred capacity shareholder capacity public authority economic advantage undertaking belonging
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Indeed according settled caselaw grounds judgment General Court disclose infringement EU law operative part shown well founded legal grounds infringement capable bringing setting aside judgment judgments 30 September 2003 Biret International v Council C‑9302 P EUC2003517 paragraph 60 caselaw cited 14 October 2014 Buono Others v Commission C‑1213 P C‑1313 P EUC20142284 paragraph 62 caselaw cited
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: former company new operating companies form economic unit inter alia restructuring carried constitutes indivisible whole industrial economic point view see effect Intermills v Commission paragraph 12
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: regards second third parts ground appeal considered together must recalled accordance Court’s settled caselaw actions failure fulfil obligations brought ground infringement decision ordering recovery unlawful aid Member State encounters unforeseen unforeseeable difficulties becomes aware consequences overlooked Commission must submit problems Commission consideration together proposals suitable amendments decision issue
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: position would different alteration fact constituted separate aid measure assessed separately would therefore influence assessment Commission already made original aid plan
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also apparent Court’s case‑law entity owning controlling shareholdings company actually exercises control involving directly indirectly management thereof must regarded taking part economic activity carried controlled undertaking Case C‑22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraphs 112 118
Answer:

retrieved examples:

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 2 EC Treaty amendment Article 2 EC declares particular task Community ‘to promote … harmonious balanced development economic activities’ ‘a high level employment social protection
Answer: Rule

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: general application derives fact decisions apply objectively determined situations produce legal effects respect category persons envisaged general abstract manner see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 31 17 September 2009 Commission v Koninglijke FrieslandCampina C‑51907 P EUC2009556 paragraph 53 caselaw cited 28 June 2018 Lowell Financial Services v Commission C‑21916 P published EUC2018508 paragraph 42 caselaw cited
Answer: Prec

Text: Article 1071 TFEU save otherwise provided Treaties aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States incompatible internal market
Answer: Rule

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case simple separation undertaking two different entities first pursues directly former economic activity second controls first fully involved management would sufficient deprive rules European Union relating State aid practical effect
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Consequently General Court correctly applied Article 841 Rules Procedure rejecting plea ground time
Answer: Rule

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: would enable second entity benefit subsidies advantages granted State means State resources use whole part benefit former interest also economic unit formed two entities Cassa di Risparmio di Firenze Others paragraph 114
Answer:

retrieved examples:

Text: reasons given therefore enabled accordance Court’s established caselaw interested parties know grounds upon General Court relied provided Court sufficient material exercise powers review appeal complaint alleging judgment appeal failed give adequate reasons must rejected
Answer: Prec

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regards thirdly Commissions claim alternative Court set aside words view paragraph 36 English version judgment appeal clear grounds judgment Court First Instance decide admissibility application basis subjective appraisal interests applicants explained basis rules governing admissibility actions Article 173 Treaty
Answer: Rule

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: accordance case‑law Court apprehension internal difficulties cannot justify failure Member State comply obligations Community law see inter alia Case C‑40497 Commission v Portugal 2000 ECR I‑4897 paragraph 52 Case C‑31099 Italy v Commission cited paragraph 105 Case C‑40400 Commission v Spain 2003 ECR I‑6695 paragraph 55
Answer: Prec

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: may reveal possible exercise functions relating control direction financial support – going beyond simple placing capital investor – illustrate existence organic functional links entity owning controlling shareholding company controlled company fact members management committee controlling body entity appointed equivalent bodies controlled company see effect Cassa di Risparmio di Firenze Others paragraphs 116 117
Answer:

retrieved examples:

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards condition relating existence selective advantage accordance settled caselaw interventions form whatsoever liable favour undertakings directly indirectly must regarded economic advantages recipient undertaking would obtained normal market conditions considered State aid
Answer: Prec

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Consequently recovery State aid unlawfully granted purpose restoring previously existing situation cannot principle regarded disproportionate objectives Treaty regard State aids see Tubemeuse cited paragraph 66 Case C‑16995 Spain v Commission 1997 ECR I135 paragraph 47
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer:

retrieved examples:

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Thus according caselaw Court tax cannot hypothecated exemption payment tax category undertakings thus even undertakings operate competition undertakings liable pay tax question
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: addition must pointed according Article 1bii regulation ‘existing aid’ understood inter alia ‘authorised aid say aid schemes individual aid authorised Commission Council
Answer: Rule

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Thus respect assessment context appeal General Court’s determinations national law Court Justice jurisdiction determine whether law distorted see judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited
Answer: Prec

Text: follows rules governing proceedings EU Courts particular Article 21 Statute Court Justice European Union applicable General Court pursuant first paragraph Article 53 Statute Article 441 Rules Procedure General Court version applicable originating application lodged case principle determined delimited parties EU Courts cannot adjudicate ultra petita see effect judgment 10 December 2013 Commission v Ireland Others C‑27212 P EUC2013812 paragraph 27
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: follows foregoing appropriate criterion establishing selectivity measure issue consists determining whether measure introduces operators light objective pursued general tax system concerned comparable factual legal situation distinction justified nature general structure system see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 61
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 42 order 21 January 2010 Case C‑15009 P Iride Iride Energia v Commission published ECR paragraph 42
Answer:

retrieved examples:

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: must held first Article 4c CS prohibits granting State aid steel coal undertakings without drawing distinction individual aid aid disbursed State aid scheme Article 67 CS refers expressly State aid respect protective measures Commission may authorise pursuant first indent paragraph 2 article favour coal steel undertakings suffer competitive disadvantages general economic policy measures
Answer: Rule

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Secondly also apparent caselaw examination selectivity must carried within context ‘a particular legal regime
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: However European Union Courts must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn Case C1203 P Commission v Tetra Laval 2005 ECR I987 paragraph 39 Commission v Scott paragraph 65
Answer: Prec

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next clear Court’s case‑law need prevent cumulative effect aid repaid aid planned regardless whether individual aid aid covered aid scheme issue TWD v Commission caselaw allows Commission make compatibility aid conditional upon prior repayment earlier unlawful aid see effect order Iride Iride Energia v Commission paragraphs 49 50 70
Answer:

retrieved examples:

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First Commission must appropriate take account cumulative effect earlier unlawful aid repaid new aid see effect Case C‑35595 P TWD v Commission paragraphs 26 27 second find new aid compatible common market evidence disposal enables reach conclusion see effect order Iride Iride Engergia v Commission paragraph 70
Answer:

retrieved examples:

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: common ground Commission required make complex economic assessment examines whether particular measures described State aid public authorities act way private creditor see Case C52504 P Spain v Lenzing 2007 ECR I9947 paragraph 59
Answer: Prec

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Commission also takes relevant measure facilitate dialogue ensuring balanced support parties see effect Albany paragraphs 55 58 respect EEC Treaty Agreement social policy concluded Member States European Community exception United Kingdom Great Britain Northern Ireland OJ 1992 C 191 p 91 entry force Treaty Amsterdam
Answer: Prec

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: already noted paragraphs 83 85 purposes applying private investor test relevant evidence information available developments foreseeable time decision make investment taken
Answer: Itpr

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court correctly pointed paragraph 187 judgment appeal apparent TWD v Commission caselaw Commission decides initiate formal investigation procedure Member State potential beneficiary new aid provide Commission evidence capable showing aid compatible common market obligation also extends need establish new aid earlier unlawful aid incompatible common market repaid cumulative effect
Answer:

retrieved examples:

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Also far arguments set alternative 3F seeks put forward separate specific grounds demonstrate Commission infringed principle good administration essentially alleging duration preliminary examination stage unreasonable recalled according Article 1701 Rules Procedure Court Justice subjectmatter proceedings General Court may changed appeal
Answer: Rule

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: accordance Court’s settled caselaw applicant’s interest bringing proceedings must light purpose action exist action lodged failing action inadmissible
Answer: Prec

Text: latter case may measure raise doubts compatibility common market
Answer: Itpr

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid within meaning provision see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Lastly since clear Court’s case‑law sufficient Commission establish aid issue capable affecting trade Member States distorting competition order Iride Iride Energia v Commission paragraph 72 General Court acted correctly finding Commission required circumstances case carry specific detailed examination advantages derived aid issue referring specifically position AEP ACEA market question relative competitors trends Community trade
Answer:

retrieved examples:

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: Article 92 Treaty states Save otherwise provided Treaty aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods shall far affects trade Member States incompatible common market
Answer: Rule

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part see judgments 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraphs 41 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 82 83 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 74 75 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 54 55
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: pointed paragraph 77 duty incumbent upon General Court state reasons judgments require address expressly arguments articulated parties reasoning sufficient enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review
Answer:

retrieved examples:

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: extent reaching conclusion Court relied fact measure issue worded form exception rule governing forfeiture losses recalled already pointed paragraph 92 present judgment regulatory technique used cannot decisive purposes determination reference framework
Answer: Itpr

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: paragraph 120 judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 Court referring inter alia two abovementioned judgments expressly stated position selectivity national measure examination holding case selectivity followed fact undertakings engaged export activities carrying certain investment transactions abroad qualified tax advantage conferred measure
Answer: Prec

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover clear paragraphs 186 188 judgment appeal General Court set therein interpretation TWD v Commission caselaw
Answer:

retrieved examples:

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: regards second condition set Article 230 EC borne mind fact disputed provision nature scope provision general application inasmuch applies traders concerned general prevent individual concern Belgium Forum 187 v Commission paragraph 58 case‑law cited
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Since determination reference system constitutes starting point comparative examination carried context assessment selectivity aid scheme error made determination necessarily vitiates whole analysis condition relating selectivity see effect judgments 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 107 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraph 46
Answer: Prec

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: rules applicable investment sugar sector thus established Regulation 178581
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: regards whether ground well founded according settled caselaw definition aid general subsidy
Answer: Prec

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Articles 482 Rules Procedure General Court provides new plea law may introduced course proceedings unless based matters law fact come light course procedure see effect judgment 12 November 2009 Case C‑56408 P SGL Carbon v Commission published ECR paragraphs 20 34
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: pointed paragraph 146 appeal plea directed ground included sake completeness judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 1071 TFEU
Answer: ['Princ', 'Rule']

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place regards plea alleging breach conditions laid fourth paragraph Article 230 EC made clear outset Article 4 Regulation 6591999 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid notified compatible common market
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: fourth paragraph Article 263 TFEU natural legal person may conditions laid first second paragraphs article institute proceedings act addressed person direct individual concern regulatory act direct concern entail implementing measures
Answer: Rule

Text: effect caselaw simply reimbursement undertaking amount tax required pay breach EU law damages national authorities ordered pay undertakings compensate damage caused constitute State aid
Answer: Prec

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer:

retrieved examples:

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: circumstances Court finds General Court responded requisite legal standard arguments relating principle limitation relied FT disregard requirement state reasons established caselaw cited paragraph 88
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: follows foregoing neither French Republic FT rely principle order prevent recovery unlawful aid see Case C‑14804 Unicredito Italiano 2005 ECR I‑11137 paragraph 104
Answer: Prec

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination Commission finds notwithstanding fact measure notified falls within scope Article 871 EC raise doubts compatibility common market Commission adopt decision raise objections Article 43 Regulation 6591999
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Article 1071 TFEU save otherwise provided Treaties aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States incompatible internal market
Answer: Rule

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Therefore appraisal facts General Court constitute save clear sense evidence produced distorted question law subject review Court Justice judgments Archer Daniels Midland Archer Daniels Midland Ingredients v Commission C‑39703 P EUC2006328 paragraph 85 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 180
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Consequently regulatory technique used cannot decisive purposes determining reference framework see effect judgment WDFG paragraph 76 judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 92
Answer: Prec

Text: fact however taken consideration relation obligation recover incompatible aid light principles protection legitimate expectations legal certainty done Commission contested decision declined order recovery aid granted date publication Official Journal European Communities decisions initiate procedure laid Article 882 EC
Answer: ['Princ', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission adopts decision raise objections declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: Consequently General Court correctly applied Article 841 Rules Procedure rejecting plea ground time
Answer: Rule

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Indeed appellant could thus base appeal pleas law arguments already relied Court First Instance appeal would deprived part purpose
Answer: Itpr

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: third place according settled caselaw fact Member State seeks approximate unilateral measures conditions competition particular sector economy prevailing Member States cannot deprive measures question character aid Joined Cases 669 1169 Commission v France 1969 ECR 523 paragraphs 20 21 Case C697 Italy v Commission 1999 ECR I2981 paragraph 21
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: However accordance second sentence Article 141 Regulation 6591999 Commission shall require recovery aid would contrary general principle EU law
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation
Answer:

retrieved examples:

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: remove certain kinds subcategories nonlegislative acts general application scope provision would run counter objective
Answer: Itpr

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain sectors activity see effect inter alia judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraphs 49 50
Answer: Prec

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: settled caselaw undertaking cannot principle contest Commission decision prohibiting aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme see Joined Cases C1598 C10599 Italy Sardegna Lines v Commission 2000 ECR I8855 paragraph 33 caselaw cited
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: latter provision decision call upon Member State concerned upon interested parties submit comments within prescribed period must rule exceed one month
Answer:

retrieved examples:

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: assessment made public creditor grants payment facilities respect debt payable undertaking applying principle private creditor test
Answer: Prec

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: event case State aid notified delay may imputed Commission time learned existence aid incompatible common market
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Since doubts must trigger initiation formal investigation procedure interested parties referred Article 1h Regulation 6591999 participate must held interested party within meaning latter provision directly individually concerned decision
Answer:

retrieved examples:

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: However appropriate recall position adopted Court judgment Italy Sardegna Lines v Commission regard Commission Decision 9895EC 21 October 1997 concerning aid granted Region Sardinia Italy shipping companies Sardinia OJ 1998 L 20 p 30 required Italian Republic recover beneficiary loans leases question element aid contained
Answer: Prec

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: applicability private investor test ultimately depends therefore Member State concerned conferred capacity shareholder capacity public authority economic advantage undertaking belonging
Answer: Itpr

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: follows rules governing proceedings EU Courts particular Article 21 Statute Court Justice European Union applicable General Court pursuant first paragraph Article 53 Statute Article 441 Rules Procedure General Court version applicable originating application lodged case principle determined delimited parties EU Courts cannot adjudicate ultra petita see effect judgment 10 December 2013 Commission v Ireland Others C‑27212 P EUC2013812 paragraph 27
Answer: ['Prec', 'Rule']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: regards fourth part ground appeal recalled appellant must pursuant Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court Justice indicate precisely evidence alleged distorted General Court demonstrate errors appraisal view led distortion
Answer: Rule

Text: Accordingly clear distortion alleged manifestly apparent documents Court arguments Orange fact asking Court carry fresh assessment facts evidence falls outside Court’s jurisdiction
Answer: Itpr

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: beneficiaries procedural guarantees provided Article 882 EC Article 61 Regulation 6591999 able ensure guarantees respected must possible challenge European Union judicature decision raise objections see effect Case C‑7803 P Commission v Aktionsgemeinschaft Recht und Eigentum 2005 ECR I‑10737 paragraph 35 caselaw cited Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 28 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 31 caselaw cited
Answer:

retrieved examples:

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect inter alia judgment 18 July 2013 PC‑612 EUC2013525 paragraph 18
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: follows Court seeking case determine whether market position members Aktionsgemeinschaft Recht und Eigentum association set promote collective interests class persons substantially affected aid scheme subject decision question
Answer: Prec

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly specific status ‘interested party’ within meaning Article 1h Regulation 6591999 conjunction specific subjectmatter action sufficient distinguish individually purposes fourth paragraph Article 230 EC applicant contesting decision raise objections
Answer:

retrieved examples:

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: appellant alleges distortion evidence General Court must Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court indicate precisely evidence alleged distorted General Court show errors appraisal view led distortion
Answer: Rule

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: consequence would national tax rules fall outset outside scope control State aid account sole fact adopted different regulatory technique although adjusting combining various tax rules produce effects law andor fact
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard although applicant contests Commission decision initiate formal investigation procedure must accordance Article 441c Rules Procedure General Court define subjectmatter action application initiating proceedings requirement satisfied requisite legal standard applicant identifies decision seeks annulled
Answer:

retrieved examples:

Text: falls Commission show measure particular creates differences undertakings regard objective measure comparable situation
Answer: Itpr

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: Indeed according settled caselaw grounds judgment General Court disclose infringement EU law operative part shown well founded legal grounds infringement capable bringing setting aside judgment judgments 30 September 2003 Biret International v Council C‑9302 P EUC2003517 paragraph 60 caselaw cited 14 October 2014 Buono Others v Commission C‑1213 P C‑1313 P EUC20142284 paragraph 62 caselaw cited
Answer: Prec

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: matters little whether application initiating proceedings states seeking annulment ‘a decision raise objections’ – term used Article 43 Regulation 6591999 – decision initiate formal investigation procedure since Commission takes position aspects question means single decision
Answer:

retrieved examples:

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: provisions EC Treaty apply alternative situations specific rule ECSC Treaty see particular Case 32885 Deutsche Babcock 1987 ECR 5119 paragraphs 6 14
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Joined Cases 6785 6885 7085 Kwekeriij van der Kooy Others v Commission 1988 ECR 219 paragraph 15 Case C‑692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Joined Cases C‑1598 C‑10599 Italy Sardegna Lines v Commission 2000 ECR I‑8855 paragraph 33
Answer: Prec

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Also far arguments set alternative 3F seeks put forward separate specific grounds demonstrate Commission infringed principle good administration essentially alleging duration preliminary examination stage unreasonable recalled according Article 1701 Rules Procedure Court Justice subjectmatter proceedings General Court may changed appeal
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: General Court recalled paragraph 26 judgment appeal persons decision addressed may claim individually concerned within meaning fourth paragraph Article 263 TFEU decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressedjudgments 15 July 1963 Plaumann v Commission 2562 EUC196317 107 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 72 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 46
Answer: Rule

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard first third pleas General Court thus rightly pointed paragraph 81 judgment appeal according settled caselaw General Court interpret action challenging exclusively merits aid assessment decision seeking reality ensure respect procedural rights available applicant Article 882 EC applicant expressly raised plea effect
Answer:

retrieved examples:

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: Article 92 Treaty states Save otherwise provided Treaty aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods shall far affects trade Member States incompatible common market
Answer: Rule

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: However financial situation recipient public undertaking depends means used place advantage however may effected amount undertaking ultimately receives
Answer: Itpr

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances interpretation plea would tantamount redefining subjectmatter action see effect judgment 29 November 2007 Case C‑17606 P Stadtwerke Schwäbisch Hall Others v Commission paragraph 25
Answer:

retrieved examples:

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Court First Instance held inter alia paragraphs 77 79 contested judgment course Commission’s assessment new aid pursuant Article 933 Treaty notified put effect Commission required establish whether aid real impact trade Member States competition whether aid could affect trade
Answer: Rule

Text: settled caselaw adoption order recover unlawful aid logical normal consequence finding unlawful
Answer: Prec

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: use arguments nothing however bring change subjectmatter action conditions admissibility see effect 3F v Commission paragraph 35
Answer:

retrieved examples:

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Consequently given Article 1 Third Steel Aid Code prohibited aid aid specific steel sector Commission could implicitly withdraw 1971 Decision
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: rules applicable investment sugar sector thus established Regulation 178581
Answer: Rule

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: application tax exemption extent depend tax revenue
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrary existence doubts concerning compatibility precisely evidence must adduced order show Commission required initiate formal investigation procedure Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Lastly regards argument General Court failed regard obligation state reasons relation principle limitation settled caselaw court thereby required provide account follows exhaustively point point reasoning articulated parties case
Answer: Prec

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 1h Regulation 6591999 ‘interested party’ means inter alia person undertaking association undertakings whose interests might affected granting aid say particular competing undertakings beneficiary aid
Answer:

retrieved examples:

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: fourth paragraph Article 263 TFEU natural legal person may conditions laid first second paragraphs article institute proceedings act addressed person direct individual concern regulatory act direct concern entail implementing measures
Answer: Rule

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: case prohibition applies aid measure introduced alteration
Answer: Itpr

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: far concerns third criterion characterising measure State aid settled caselaw measures whatever form likely directly indirectly favour certain undertakings regarded economic advantage recipient undertaking would obtained normal market conditions regarded State aid see judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraph 34
Answer: Prec

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: words term covers indeterminate group persons see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 16
Answer:

retrieved examples:

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: therefore clearly apparent wording paragraph 20 practice directions state ‘the appeal … unless special circumstances exceed 25 pages’ recital set absolute limitation number pages admissibility appeal subject merely provides recommendation regard parties
Answer: Itpr

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence provision rule possibility undertaking direct competitor beneficiary aid requires raw material production process categorised interested party provided undertaking demonstrates interests could adversely affected grant aid
Answer:

retrieved examples:

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: fact however taken consideration relation obligation recover incompatible aid light principles protection legitimate expectations legal certainty done Commission contested decision declined order recovery aid granted date publication Official Journal European Communities decisions initiate procedure laid Article 882 EC
Answer: ['Princ', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: hand purpose aid recovery seek compensation individual harm kind reestablish market question situation aid granted
Answer: Itpr

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: purpose necessary undertaking establish requisite legal standard aid likely specific effect situation see effect 3F v Commission paragraph 33
Answer:

retrieved examples:

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: matters regard fact measure irrespective form legislative means used effect placing recipient undertakings position favourable undertakings although undertakings comparable factual legal situation light objective pursued tax system concerned
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However accordance second sentence Article 141 Regulation 6591999 Commission shall require recovery aid would contrary general principle EU law
Answer: Rule

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw Court classification ‘State aid’ within meaning Article 1071 TFEU requires conditions set provision fulilled
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: Second regards appellants interest bringing proceedings part contested decision relating tax reliefs clear caselaw Court Justice Commission points individual grants aid general aid scheme approved Commission meet conditions scheme constitute existing aid need notified Italy v Commission cited paragraphs 21 26
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: stated recital 14 preamble regulation limitation period established reasons legal certainty
Answer: Rule

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Class', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus first must intervention State State resources
Answer:

retrieved examples:

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second intervention must liable affect trade Member States
Answer:

retrieved examples:

Text: Third must confer advantage recipient
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: must borne mind according settled caselaw concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system part judgments Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 145 caselaw cited BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 101
Answer: Prec

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: regards fourth part ground appeal recalled appellant must pursuant Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court Justice indicate precisely evidence alleged distorted General Court demonstrate errors appraisal view led distortion
Answer: Rule

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: hand General Court rightly pointed paragraph 206 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: third must confer selective advantage recipient
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: particular clear caselaw order assess whether measure would adopted normal market conditions private investor situation close possible State benefits obligations linked situation State shareholder — exclusion linked situation public authority — taken account see effect Case 23484 Belgium v Commission 1986 ECR 2263 paragraph 14 Case 4085 Belgium v Commission 1986 ECR 2321 paragraph 13 Joined Cases C27892 C28092 Spain v Commission 1994 ECR I4103 paragraph 22 Case C33499 Germany v Commission 2003 ECR I1139 paragraph 134
Answer: Prec

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr', 'Rule']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fourth must distort threaten distort competition judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer:

retrieved examples:

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection legal remedy EU judicature purpose challenging lawfulness regulatory act
Answer: Itpr

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: appellant alleges distortion evidence General Court must Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court indicate precisely evidence alleged distorted General Court show errors appraisal view led distortion
Answer: Rule

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Third must confer advantage recipient
Answer: Class

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: ['Class', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: concept ‘aid’ embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 30
Answer:

retrieved examples:

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: principle legal certainty – one general principles European Union law – requires rules law clear precise predictable effect interested parties ascertain position situations legal relationships governed European Union law see effect Case C‑6393 Duff Others 1996 ECR I569 paragraph 20 Case C‑7606 P Britannia Alloys Chemicals v Commission 2007 ECR I‑4405 paragraph 79 Case C‑15807 Förster 2008 ECR I‑8507 paragraph 67
Answer: ['Prec', 'Princ']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70 caselaw cited
Answer:

retrieved examples:

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Consequently appears private investor test could applicable Commission duty ask Member State concerned provide relevant information enabling determine whether conditions governing applicability application test met cannot refuse examine information unless evidence produced established adoption decision make investment question
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: provisions EC Treaty apply alternative situations specific rule ECSC Treaty see particular Case 32885 Deutsche Babcock 1987 ECR 5119 paragraphs 6 14
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: public creditor grants payment facilities respect debt payable undertaking assessment made applying principle private creditor test judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: test applicable among factors Commission required take account purposes establishing whether aid exists see effect Case C34296 Spain v Commission 1999 ECR I2459 paragraph 46 Case C25697 DM Transport 1999 ECR I3913 paragraph 24 Commission v EDF paragraphs 78 103
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Text: examination therefore principle requires prior definition reference framework within measure concerned fits
Answer: Itpr

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: Consequently recovery State aid unlawfully granted purpose restoring previously existing situation cannot principle regarded disproportionate objectives Treaty regard State aids see Tubemeuse cited paragraph 66 Case C‑16995 Spain v Commission 1997 ECR I135 paragraph 47
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly private creditor test exception applies Member State requests constituent elements State aid incompatible common market laid Article 1071 TFEU exist
Answer:

retrieved examples:

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: addition must pointed according Article 1bii regulation ‘existing aid’ understood inter alia ‘authorised aid say aid schemes individual aid authorised Commission Council
Answer: Rule

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Contrary General Court’s assertion paragraphs 59 62 judgment appeal Autogrill España v Commission paragraphs 63 66 judgment appeal Banco Santander Santusa v Commission indication contrary regards analysis condition relating selectivity tax measure may deduced judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467
Answer: ['Itpr', 'Prec']

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Text: Court First Instance held inter alia paragraphs 77 79 contested judgment course Commission’s assessment new aid pursuant Article 933 Treaty notified put effect Commission required establish whether aid real impact trade Member States competition whether aid could affect trade
Answer: Rule

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fact test applicable among factors Commission required take account purposes establishing whether aid exists see effect judgments 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 103 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: provision sets four conditions
Answer: Class

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides competent court sufficient material exercise power review see Case C‑10504 P Nederlandse Federatieve Vereniging voor de Groothandel op Electrotechnisch Gebied v Commission 2006 ECR I‑8725 paragraph 72 Case C‑306 P Groupe Danone v Commission 2007 ECR I‑1331 paragraph 46
Answer: Prec

Text: must held first Article 4c CS prohibits granting State aid steel coal undertakings without drawing distinction individual aid aid disbursed State aid scheme Article 67 CS refers expressly State aid respect protective measures Commission may authorise pursuant first indent paragraph 2 article favour coal steel undertakings suffer competitive disadvantages general economic policy measures
Answer: Rule

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: result appears private creditor test might applicable Commission ask Member State concerned provide relevant information enabling determine whether conditions applying test satisfied judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 33
Answer:

retrieved examples:

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Furthermore pointed paragraph 53 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: also noted Court Justice held paragraph 29 Commission v France provision European Union law requires Commission ordering recovery aid declared incompatible common market fix exact amount aid recovered
Answer: Prec

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place clear caselaw Court appears private creditor test might applicable Commission examine possibility irrespective request effect
Answer:

retrieved examples:

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Furthermore even European Community first created situation capable giving rise legitimate expectations overriding public interest may preclude transitional measures adopted respect situations arose new rules came force still subject change Belgium Forum 187 v Commission paragraph 148 case‑law cited
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly Advocate General noted points 72 76 Opinion nothing prevents recipient aid invoking applicability test recipient invoke test falls Commission assess whether test needs applied assess application
Answer:

retrieved examples:

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: follows General Court correctly held paragraph 217 judgment appeal context proceedings Court must make necessary determinations order reach finding failure fulfil obligations result plea defence raised intervener relates element fact law Commission must necessarily take account analysis capable altering framework dispute even relied Member State concerned
Answer: Itpr

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: General Court pointed paragraph 42 judgment appeal review EU judicature legality decision initiate formal investigation procedure applicant challenges Commission’s assessment measure constituting State aid limited ascertaining whether Commission made manifest error assessment see effect judgment 21 July 2011 Alcoa Trasformazioni v Commission C‑19409 P EUC2011497 paragraph 61
Answer: Prec

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second place regards relevance subjective state mind must noted Advocate General pointed point 74 Opinion starting point determining whether private operator test applied must economic nature Member State’s action Member State subjectively speaking thought acting alternative courses action considered adopting measure question
Answer:

retrieved examples:

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: selective follows reasoning set paragraphs 41 47 55 present judgment within context particular legal regime effect conferring advantage certain undertakings others different sector sector light objective pursued regime comparable factual legal situation
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover Court held aid notified Commission apparent failure act part relation measure irrelevant see Demesa Territorio Histόrico de Álava v Commission paragraph 52
Answer: Prec

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case private creditor test intended determine whether recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor sought recover sums due debtor financial difficulty judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 72 accordingly whether undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70
Answer:

retrieved examples:

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: hand also possible measure may raise doubts judgment 24 May 2011 Case C‑8309 P Commission v Kronoply Kronotex yet published ECR paragraph 43 order 9 June 2011 Case C‑45110 P TF1 v Commission paragraph 47 judgment 22 September 2011 Case C‑14809 P Belgium v Deutsche Post DHL International yet published ECR paragraph 53 judgment 27 October 2011 Case C‑4710 P Austria v ScheucherFleisch Others yet published ECR paragraph 40
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: apparent provisions read together reply may seek annulment judgment appeal basis distinct independent grounds raised appeal since grounds may raised part crossappeal
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Second must noted Commission doubt applicability test clear paragraph 24 present judgment asked Slovak State relevant information regard carried overall assessment evidence see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 86
Answer:

retrieved examples:

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: provision sets four conditions
Answer: Class

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Prior initiation procedure must first examine whether aid covered general scheme satisfies conditions laid decision approving
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: stated recital 14 preamble regulation limitation period established reasons legal certainty
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Therefore even sums corresponding measure question permanently held Treasury fact constantly remain public control therefore available competent national authorities sufficient categorised ‘State resources’ see judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 37 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 70 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 35 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 21
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: accordance Court’s settled caselaw applying private creditor test Commission must carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 73 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 47
Answer:

retrieved examples:

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: follows arguments submitted intervener admissible unless fall within framework provided forms order pleas law judgment 7 October 2014 Germany v Council C‑39912 EUC20142258 paragraph 27
Answer: Prec

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 78 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 54
Answer:

retrieved examples:

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Thus Member State stage procedure encounters difficulties recovering aid concerned must submit difficulties Commission consideration cooperate good faith Commission view overcoming particular suggesting alternative methods allowing recovery part aid
Answer: Itpr

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: must recalled case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents case file judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 20 caselaw cited
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover purposes applying private creditor test relevant evidence information available developments foreseeable time decision taken see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 105
Answer:

retrieved examples:

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: regard clear Court’s caselaw necessary financial balance economic viability undertaking entrusted operation service general economic interest threatened
Answer: Prec

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: However Member State provide justification
Answer: Itpr

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination Commission whether particular measures classified State aid public authorities act way private creditor requires complex economic assessment judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 74 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 48
Answer:

retrieved examples:

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Since Lico Leasing PYMAR dispute admissibility first complaint first part Commission’s first ground appeal alleging error law identification beneficiaries advantages arising tax measures issue ground question fact true assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: According judgment applicant individually concerned decision addressed another person decision affects reason certain attributes peculiar reason circumstances differentiated persons see also field State aid judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 32 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 52 fields judgments 17 January 1985 PiraikiPatraiki Others v Commission 1182 EUC198518 paragraphs 11 19 31 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 93
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection must observed context review Courts European Union complex economic assessments made Commission field State aid Courts substitute economic assessment Commission judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 75 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 49
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows arguments submitted intervener admissible unless fall within framework provided forms order pleas law judgment 7 October 2014 Germany v Council C‑39912 EUC20142258 paragraph 27
Answer: Prec

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Courts European Union must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 76 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 50
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: order determine whether measure selective therefore examined whether within context specified legal regime measure constitutes advantage certain undertakings others light objective pursued regime comparable factual legal situation judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36
Answer: Prec

Text: follows paragraph 78 applicable test among factors Commission required take account purposes establishing existence aid
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Third must confer advantage recipient
Answer: Class

Text: must recalled case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents case file judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 20 caselaw cited
Answer: Prec

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection also borne mind lawfulness decision concerning State aid falls assessed European Union judicature light information available Commission time decision adopted judgment 2 September 2010 Commission v Scott C‑29007 P EUC2010480 paragraph 91 caselaw cited
Answer:

retrieved examples:

Text: concept aid embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect Case C20097 Ecotrade 1998 ECR I7907 paragraph 34 Case C697 Italy v Commission 1999 ECR I2981 paragraph 15
Answer: Prec

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: Consequently recovery State aid unlawfully granted purpose restoring previously existing situation cannot principle regarded disproportionate objectives Treaty regard State aids see Tubemeuse cited paragraph 66 Case C‑16995 Spain v Commission 1997 ECR I135 paragraph 47
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However information ‘available’ Commission includes seemed relevant assessment carried accordance caselaw referred paragraphs 59 61 present judgment could obtained upon request Commission administrative procedure
Answer:

retrieved examples:

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: said regards analysis substance Commission’s single ground appeal noted first obligation Member State concerned abolish recovery aid considered Commission incompatible single market purpose according Court’s established caselaw restore situation aid granted see effect judgment 4 April 1995 Commission v Italy C‑35093 EUC199596 paragraph 21 caselaw cited
Answer: Prec

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: addition must pointed according Article 1bii regulation ‘existing aid’ understood inter alia ‘authorised aid say aid schemes individual aid authorised Commission Council
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: decision visàvis undertaking seek contest decision measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Van der Kooy Others v Commission cited paragraph 15 Case C692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Italy Sardegna Lines v Commission paragraph 33
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Paragraphs 180 213 235 judgment appeal Commission’s objections referred paragraph 64 present judgment directed read legal context referred General Court imply new requirements incompatible caselaw Court Justice
Answer:

retrieved examples:

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned able demonstrate differentiation justified since flows nature general structure system measures form part see effect inter alia judgments 29 April 2004 Netherlands v Commission C‑15901 EUC2004246 paragraphs 42 43 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraphs 64 65 29 March 2012 3M Italia C‑41710 EUC2012184 paragraph 40
Answer: Prec

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: must held first Article 4c CS prohibits granting State aid steel coal undertakings without drawing distinction individual aid aid disbursed State aid scheme Article 67 CS refers expressly State aid respect protective measures Commission may authorise pursuant first indent paragraph 2 article favour coal steel undertakings suffer competitive disadvantages general economic policy measures
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: appeal Courts jurisdiction thus confined review findings pleas argued Court First Instance see Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 order 28 June 2001 Case C35299 P Eridania Others v Council 2001 ECR I5037 paragraphs 52 53
Answer: Prec

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Aut']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General noted paragraphs 125 131 Opinion General Court merely noted paragraphs 191 195 198 199 judgment appeal internal contradictions decision issue made findings fact according none evidence administrative file able substantiate liquidation factors used Commission
Answer:

retrieved examples:

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Prec']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: considerations far concern information normally prudent diligent private creditor situation close possible local tax office could priori ignore capable justifying General Court’s decision Commission failed take consideration relevant information see effect judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraphs 77 78 81
Answer:

retrieved examples:

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Court also held absence overriding public interest Commission infringed superior rule law fails couple repeal set rules transitional measures protection expectations trader might legitimately derived Community rules Belgium Forum 187 paragraph 149 case‑law cited
Answer: Prec

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: provision sets four conditions
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: However condition absolute impossibility implementation satisfied defendant Member State inform Commission internal difficulties legal political practical nature attributable national authorities’ acts omissions raised implementation decision issue without taking real steps recover aid undertakings concerned without suggesting Commission alternative methods implementing decision would allow difficulties overcome see effect judgments 13 November 2008 Commission v France C‑21407 EUC2008619 paragraph 50 12 February 2015 Commission v France C‑3714 published EUC201590 paragraph 66 caselaw cited
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut




LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Authoritative F1: 0.8888888888888888
Verbal Classification F1: 0.23809523809523814
Interpretation F1: 0.13333333333333333
Precedent F1: 0.7428571428571429
Rule F1: 0.6575342465753425

macro F1: 0.5321417699499891
macro F1 (reliable): 0.7630934261071247

In [20]:
test(template, 50)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

query:
Text: regard must observed follows Article 58 Statute Court Justice conjunction Article 1132 Rules Procedure Court Justice appeal appellant may put forward relevant argument provided subjectmatter proceedings General Court changed appeal Case C‑22905 P PKK KNK v Council 2007 ECR I‑439 paragraph 66 Case C‑806 P Herrero Romeu v Commission 2007 ECR I‑10333 paragraph 32
Answer:

retrieved examples:

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: case aid derives fact another category economic operators category liable pay tax direct competition liable charge
Answer: Itpr

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Commission also takes relevant measure facilitate dialogue ensuring balanced support parties see effect Albany paragraphs 55 58 respect EEC Treaty Agreement social policy concluded Member States European Community exception United Kingdom Great Britain Northern Ireland OJ 1992 C 191 p 91 entry force Treaty Amsterdam
Answer: Prec

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: includes positive benefits also measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Joined Cases C‑7808 C‑8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer: Prec

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 60
Answer: Prec

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: undertakes initial examination planned aid
Answer: Itpr

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard Court repeatedly held action annulment purposes Article 230 EC must available acts adopted institutions whatever nature form intended legal effects capable affecting interests applicant bringing distinct change legal position see inter alia Athinaïki Techniki v Commission paragraph 29 caselaw cited Case C‑36208 P Internationaler Hilfsfonds v Commission 2010 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: essential characteristic remuneration lies fact consideration service question see effect judgments 11 September 2007 Schwarz GootjesSchwarz C‑7605 EUC2007492 paragraphs 37 38 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 45 47
Answer: Prec

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: accordance Court’s settled caselaw applicant’s interest bringing proceedings must light purpose action exist action lodged failing action inadmissible
Answer: Prec

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: settled caselaw adoption order recover unlawful aid logical normal consequence finding unlawful
Answer: Prec

Text: Given condition direct concern requires contested measure produce effects directly applicant’s legal situation EU judicature must ascertain whether applicant adequately explained reasons Commission’s decision liable place unfavourable competitive position thus produce effects legal situation
Answer: Itpr

Text: includes positive benefits also measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Joined Cases C‑7808 C‑8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer: Prec

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Third must confer advantage recipient
Answer: Class

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows also settled caselaw concerning admissibility actions annulment necessary look actual substance acts challenged order classify see particular Case 6081 IBM v Commission 1981 ECR 2639 paragraph 9 Case C‑14796 Netherlands v Commission 2000 ECR I‑4723 paragraph 27
Answer:

retrieved examples:

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part see judgments 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraphs 41 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 82 83 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 74 75 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 54 55
Answer: Prec

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: cases Commission required undertake detailed examination difficulties pleaded suggested alternative methods recovery
Answer: Itpr

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: contrast regulatory act entails implementing measures judicial review compliance EU legal order ensured irrespective whether measures adopted European Union Member States
Answer: Prec

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrast form act decision adopted principle irrelevant right challenge acts decisions way action annulment
Answer:

retrieved examples:

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain business sectors judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 55 caselaw cited
Answer: Prec

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: provision sets four conditions
Answer: Class

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: contrast regulatory act entails implementing measures judicial review compliance EU legal order ensured irrespective whether measures adopted European Union Member States
Answer: Prec

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Lastly regards argument General Court failed regard obligation state reasons relation principle limitation settled caselaw court thereby required provide account follows exhaustively point point reasoning articulated parties case
Answer: Prec

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Prec

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore principle irrelevant classification act question whether satisfies certain formal requirements namely particular duly identified author mentions provisions providing legal basis
Answer:

retrieved examples:

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: far concerns third criterion characterising measure State aid settled caselaw measures whatever form likely directly indirectly favour certain undertakings regarded economic advantage recipient undertaking would obtained normal market conditions regarded State aid see judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraph 34
Answer: Prec

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: regards whether ground well founded according settled caselaw definition aid general subsidy
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain business sectors judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 55 caselaw cited
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: New aid therefore subject precautionary review Commission may principle put effect time latter declared compatible Treaty
Answer: Itpr

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore irrelevant act may described ‘decision’ refer Article 42 3 4 Regulation 6591999
Answer:

retrieved examples:

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: position would different alteration fact constituted separate aid measure assessed separately would therefore influence assessment Commission already made original aid plan
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also importance Member State concerned notified act issue Commission infringing Article 25 regulation error capable altering substance act see Athinaïki Techniki v Commission paragraphs 43 44 caselaw cited
Answer:

retrieved examples:

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored judgment 29 April 2004 Germany v Commission C‑27700 EUC2004238 paragraph 75 caselaw cited
Answer: Prec

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: However first factual assessment Czech Republic voluntarily undertook implement ‘review mechanism’ apparent caselaw cited paragraph 24 fall within jurisdiction Court Justice hearing appeal except facts distorted alleged appellants
Answer: Prec

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore principle measures definitively determine position Commission upon conclusion administrative procedure intended legal effects capable affecting interests complainant constitute acts open challenge purposes Article 230 EC intermediate measures whose purpose prepare final decision effects see Athinaïki Techniki v Commission paragraph 42 caselaw cited
Answer:

retrieved examples:

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: Court repeatedly held right rely principle protection legitimate expectations extends person situation Community institution caused entertain expectations justified precise assurances provided
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: However first factual assessment Czech Republic voluntarily undertook implement ‘review mechanism’ apparent caselaw cited paragraph 24 fall within jurisdiction Court Justice hearing appeal except facts distorted alleged appellants
Answer: Prec

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard possible definitive actionable nature measures taken Commission procedure reviewing State aid noted first Commission must Article 101 Regulation 6591999 carry examination possession information whatever source regarding allegedly unlawful aid
Answer:

retrieved examples:

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 55 60 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraphs 88 89
Answer: Prec

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: measure issue judgment concerned sector years receiving State aid approved Commission object meet additional costs operation already received authorised aid Case C‑33499 Germany v Commission 2003 ECR I‑1139 paragraph 44
Answer: Prec

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Consequently regulatory technique used cannot decisive purposes determining reference framework see effect judgment WDFG paragraph 76 judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 92
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second regards appellants interest bringing proceedings part contested decision relating tax reliefs clear caselaw Court Justice Commission points individual grants aid general aid scheme approved Commission meet conditions scheme constitute existing aid need notified Italy v Commission cited paragraphs 21 26
Answer: Prec

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Court repeatedly held right rely principle protection legitimate expectations extends person situation Community institution caused entertain expectations justified precise assurances provided
Answer: Prec

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination complaint basis provision gives rise initiation preliminary examination stage Article 883 EC obliges Commission examine immediately possible existence aid compatibility common market see effect Athinaïki Techniki v Commission paragraph 37
Answer:

retrieved examples:

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: third place according settled caselaw fact Member State seeks approximate unilateral measures conditions competition particular sector economy prevailing Member States cannot deprive measures question character aid Joined Cases 669 1169 Commission v France 1969 ECR 523 paragraphs 20 21 Case C697 Italy v Commission 1999 ECR I2981 paragraph 21
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 55 60 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraphs 88 89
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 131 Regulation 6591999 applicable context examination complaint alleging unlawful aid obliges Commission close preliminary examination stage adopting decision pursuant Article 42 3 4 regulation say decision finding aid exist raising objections initiating formal investigation procedure since institution authorised persist failure act preliminary examination stage
Answer:

retrieved examples:

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: cases relate provisions national law granting relief taxes charges judgments France v Commission C‑24194 EUC1996353 Piaggio C‑29597 EUC1999313 DM Transport C‑25697 EUC1999332 P C‑612 EUC2013525 Ministerio de Defensa Navantia C‑52213 EUC20142262 British Telecommunications v Commission C‑62013 P EUC20142309 exceptions matters insolvency judgment Ecotrade C‑20097 EUC1998579
Answer: Prec

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Thus according caselaw Court tax cannot hypothecated exemption payment tax category undertakings thus even undertakings operate competition undertakings liable pay tax question
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: settled caselaw undertaking cannot principle contest Commission decision prohibiting aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme see Joined Cases C1598 C10599 Italy Sardegna Lines v Commission 2000 ECR I8855 paragraph 33 caselaw cited
Answer: Prec

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: must borne mind according settled caselaw concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system part judgments Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 145 caselaw cited BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 101
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: stage procedure completed Commission bound consequently either initiate next stage procedure provided Article 882 EC adopt definitive decision rejecting complaint see effect Athinaïki Techniki v Commission paragraph 40 caselaw cited
Answer:

retrieved examples:

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: assessment made public creditor grants payment facilities respect debt payable undertaking applying principle private creditor test
Answer: Prec

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: cases relate provisions national law granting relief taxes charges judgments France v Commission C‑24194 EUC1996353 Piaggio C‑29597 EUC1999313 DM Transport C‑25697 EUC1999332 P C‑612 EUC2013525 Ministerio de Defensa Navantia C‑52213 EUC20142262 British Telecommunications v Commission C‑62013 P EUC20142309 exceptions matters insolvency judgment Ecotrade C‑20097 EUC1998579
Answer: Prec

Text: particular clear caselaw order assess whether measure would adopted normal market conditions private investor situation close possible State benefits obligations linked situation State shareholder — exclusion linked situation public authority — taken account see effect Case 23484 Belgium v Commission 1986 ECR 2263 paragraph 14 Case 4085 Belgium v Commission 1986 ECR 2321 paragraph 13 Joined Cases C27892 C28092 Spain v Commission 1994 ECR I4103 paragraph 22 Case C33499 Germany v Commission 2003 ECR I1139 paragraph 134
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission finds following examination complaint investigation revealed grounds concluding State aid within meaning Article 87 EC refuses implication initiate procedure provided Article 882 EC see effect Case C‑36795 P Commission v Sytraval Brink’s France 1998 ECR I‑1719 paragraph 47
Answer:

retrieved examples:

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: apparent judgment fact coming compulsory levy contrary sufficient identify State resources see effect judgment 28 March 2019 Germany v Commission C‑40516 P EUC2019268 paragraphs 65 72
Answer: Prec

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards Commission’s finding measures complained constituted existing aid noted existing aid course subject constant review provided Article 881 EC must regarded lawful long Commission found incompatible common market see Case C‑4493 NamurLes assurances du crédit 1994 ECR I‑3829 paragraph 34 Case C‑40099 Italy v Commission 2001 ECR I‑7303 paragraph 48
Answer:

retrieved examples:

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Aid relatively small amount liable affect competition trade Member States strong competition sector undertakings receive operate see Case 25985 France v Commission 1987 ECR 4393 paragraph 24 Case C‑35198 Spain v Commission 2002 ECR I‑8031 paragraph 63
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: already noted paragraphs 83 85 purposes applying private investor test relevant evidence information available developments foreseeable time decision make investment taken
Answer: Itpr

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: may seen Joined Cases C‑7291 C‑7391 Sloman Neptun 1993 ECR I‑887 system established DIS register enables contracts employment concluded seafarers nationals nonmember countries permanent abode residence Member State concerned subjected working conditions rates pay covered law Member State considerably less favourable applicable seafarers nationals Member State constitute State aid within meaning Article 871 EC
Answer: Prec

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect inter alia judgment 18 July 2013 PC‑612 EUC2013525 paragraph 18
Answer: Prec

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: principle legal certainty – one general principles European Union law – requires rules law clear precise predictable effect interested parties ascertain position situations legal relationships governed European Union law see effect Case C‑6393 Duff Others 1996 ECR I569 paragraph 20 Case C‑7606 P Britannia Alloys Chemicals v Commission 2007 ECR I‑4405 paragraph 79 Case C‑15807 Förster 2008 ECR I‑8507 paragraph 67
Answer: ['Prec', 'Princ']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However receives complaint relating allegedly unlawful aid Commission classifying measure existing aid subjects procedure provided Article 881 EC thus refuses implication initiate procedure provided Article 882 EC see effect CIRFS Others v Commission paragraphs 25 26 Case C‑32199 P ARAP Others v Commission 2002 ECR I‑4287 paragraph 61
Answer:

retrieved examples:

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: latter case may measure raise doubts compatibility common market
Answer: Itpr

Text: According Court’s caselaw Van der Kooy CIRFS cases thus concerned particular situations applicant occupied clearly circumscribed position negotiator intimately linked actual subjectmatter decision thus placing factual situation distinguished persons Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraph 45
Answer: Prec

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Aid relatively small amount liable affect competition trade Member States strong competition sector undertakings receive operate see Case 25985 France v Commission 1987 ECR 4393 paragraph 24 Case C‑35198 Spain v Commission 2002 ECR I‑8031 paragraph 63
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: decision refusing initiate procedure provided Article 882 EC definitive cannot characterised mere provisional measure CIRFS Others v Commission paragraph 26 effect Athinaïki Techniki v Commission paragraphs 54 58
Answer:

retrieved examples:

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal see inter alia judgment A2A v Commission C‑32009 P EUC2011858 paragraph 97
Answer: Prec

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: According Court’s caselaw Van der Kooy CIRFS cases thus concerned particular situations applicant occupied clearly circumscribed position negotiator intimately linked actual subjectmatter decision thus placing factual situation distinguished persons Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraph 45
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: test applicable among factors Commission required take account purposes establishing whether aid exists see effect Case C34296 Spain v Commission 1999 ECR I2459 paragraph 46 Case C25697 DM Transport 1999 ECR I3913 paragraph 24 Commission v EDF paragraphs 78 103
Answer: Prec

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: situation persons intended benefit procedural guarantees afforded provision may secure compliance therewith able challenge decision question European Union judicature fourth paragraph Article 230 EC
Answer:

retrieved examples:

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: extent reaching conclusion Court relied fact measure issue worded form exception rule governing forfeiture losses recalled already pointed paragraph 92 present judgment regulatory technique used cannot decisive purposes determination reference framework
Answer: Itpr

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Joined Cases 6785 6885 7085 Kwekeriij van der Kooy Others v Commission 1988 ECR 219 paragraph 15 Case C‑692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Joined Cases C‑1598 C‑10599 Italy Sardegna Lines v Commission 2000 ECR I‑8855 paragraph 33
Answer: Prec

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: principle applies equally whether ground decision taken Commission regards aid compatible common market view existence aid must discounted Commission v Sytraval Brink’s France paragraph 47 considers existing aid see effect CIRFS Others v Commission paragraph 27 ARAP Others v Commission paragraph 62
Answer:

retrieved examples:

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: Even circumstances aid granted show liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 89 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 49
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides competent court sufficient material exercise power review see Case C‑10504 P Nederlandse Federatieve Vereniging voor de Groothandel op Electrotechnisch Gebied v Commission 2006 ECR I‑8725 paragraph 72 Case C‑306 P Groupe Danone v Commission 2007 ECR I‑1331 paragraph 46
Answer: Prec

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: General Court recalled paragraph 26 judgment appeal persons decision addressed may claim individually concerned within meaning fourth paragraph Article 263 TFEU decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressedjudgments 15 July 1963 Plaumann v Commission 2562 EUC196317 107 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 72 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 46
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: finding corroborated Article 20 Regulation 6591999 governs rights interested parties
Answer:

retrieved examples:

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: also noted Court Justice held paragraph 29 Commission v France provision European Union law requires Commission ordering recovery aid declared incompatible common market fix exact amount aid recovered
Answer: Prec

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: connection must observed context review conducted European Union Courts complex economic assessments made Commission field State aid Courts substitute economic assessment Commission see effect Case C29007 P Commission v Scott 2010 ECR I7763 paragraphs 64 66 caselaw cited
Answer: Prec

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: pointed paragraph 146 appeal plea directed ground included sake completeness judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According second third sentences Article 202 thereof obtaining interested party information concerning alleged unlawful aid alleged misuse aid Commission either consider insufficient grounds taking view case inform interested party thereof take decision case concerning subjectmatter information supplied
Answer:

retrieved examples:

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: Moreover true stated General Court paragraph 66 judgment appeal Autogrill España v Commission paragraph 70 judgment appeal Banco Santander Santusa v Commission Court held paragraph 42 judgment 29 March 2012 3M Italia C‑41710 EUC2012184 fact taxpayers satisfying conditions application measure concerned case could benefit measure could make selective measure
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Furthermore even European Community first created situation capable giving rise legitimate expectations overriding public interest may preclude transitional measures adopted respect situations arose new rules came force still subject change Belgium Forum 187 v Commission paragraph 148 case‑law cited
Answer: Prec

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Article 2 EC Treaty amendment Article 2 EC declares particular task Community ‘to promote … harmonious balanced development economic activities’ ‘a high level employment social protection
Answer: Rule

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: accordance settled caselaw appeal plea directed ground judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: follows arguments submitted intervener admissible unless fall within framework provided forms order pleas law judgment 7 October 2014 Germany v Council C‑39912 EUC20142258 paragraph 27
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Prec']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: follows Commission examined information taken position takes decision
Answer:

retrieved examples:

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: appraisal facts General Court therefore constitute save clear sense evidence produced distorted question law subject review Court Justice see inter alia judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78
Answer: Prec

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Consequently given Article 1 Third Steel Aid Code prohibited aid aid specific steel sector Commission could implicitly withdraw 1971 Decision
Answer: Rule

Text: also follows function repayment aid general rule save exceptional circumstances Commission exceed bounds discretion recognised caselaw Court asks Member State recover sums granted way unlawful aid since restoring previous situation see Case C‑7597 Belgium v Commission 1999 ECR I‑3671 paragraph 66 Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 99
Answer: Prec

Text: must recalled case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents case file judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 20 caselaw cited
Answer: Prec

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: circumstances Court finds General Court responded requisite legal standard arguments relating principle limitation relied FT disregard requirement state reasons established caselaw cited paragraph 88
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: General Court pointed paragraph 42 judgment appeal review EU judicature legality decision initiate formal investigation procedure applicant challenges Commission’s assessment measure constituting State aid limited ascertaining whether Commission made manifest error assessment see effect judgment 21 July 2011 Alcoa Trasformazioni v Commission C‑19409 P EUC2011497 paragraph 61
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Moreover true stated General Court paragraph 66 judgment appeal Autogrill España v Commission paragraph 70 judgment appeal Banco Santander Santusa v Commission Court held paragraph 42 judgment 29 March 2012 3M Italia C‑41710 EUC2012184 fact taxpayers satisfying conditions application measure concerned case could benefit measure could make selective measure
Answer: Prec

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Therefore action annulment decision initiate procedure pursuant Article 882 EC brought party concerned within meaning article must considered admissible party seeks thereby safeguard procedural rights available latter provision see Athinaïki Techniki v Commission paragraph 36 caselaw cited
Answer:

retrieved examples:

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Moreover Court held aid notified Commission apparent failure act part relation measure irrelevant see Demesa Territorio Histόrico de Álava v Commission paragraph 52
Answer: Prec

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer: Itpr

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: assessment General Court facts evidence cannot challenged appeal court except facts distorted see effect judgment 15 May 2019 CJ v ECDC C‑17018 P published EUC2019410 paragraph 23 caselaw cited relied appellants claim General Court examine evidence adduced take account offer submit additional evidence
Answer: Prec

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: According settled caselaw order tax regarded forming integral part aid measure must hypothecated aid relevant national rules sense revenue tax necessarily allocated financing aid direct impact amount aid consequently assessment compatibility aid internal market see inter alia judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 46 caselaw cited 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraph 99
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: regards thirdly Commissions claim alternative Court set aside words view paragraph 36 English version judgment appeal clear grounds judgment Court First Instance decide admissibility application basis subjective appraisal interests applicants explained basis rules governing admissibility actions Article 173 Treaty
Answer: Rule

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: appraisal facts General Court therefore constitute save clear sense evidence produced distorted question law subject review Court Justice see inter alia judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appellant undertaking competition company benefiting measures complained without doubt interested party purposes Article 882 EC see Commission v Sytraval Brink’s France paragraph 41 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 32 regard definition term Article 1h Regulation 6591999
Answer:

retrieved examples:

Text: According settled caselaw order tax regarded forming integral part aid measure must hypothecated aid relevant national rules sense revenue tax necessarily allocated financing aid direct impact amount aid consequently assessment compatibility aid internal market see inter alia judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 46 caselaw cited 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraph 99
Answer: Prec

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: applicability private investor test ultimately depends therefore Member State concerned conferred capacity shareholder capacity public authority economic advantage undertaking belonging
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: hand also possible measure may raise doubts judgment 24 May 2011 Case C‑8309 P Commission v Kronoply Kronotex yet published ECR paragraph 43 order 9 June 2011 Case C‑45110 P TF1 v Commission paragraph 47 judgment 22 September 2011 Case C‑14809 P Belgium v Deutsche Post DHL International yet published ECR paragraph 53 judgment 27 October 2011 Case C‑4710 P Austria v ScheucherFleisch Others yet published ECR paragraph 40
Answer: Prec

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Indeed appellant could thus base appeal pleas law arguments already relied Court First Instance appeal would deprived part purpose
Answer: Itpr

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: follows condition application receipt tax aid may grounds finding aid selective condition leads distinction made undertakings despite fact light objective pursued tax system concerned comparable factual legal situation therefore represents discrimination undertakings excluded
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances Commission’s complaint reference notice relating State aid field taxation ineffective see effect Case C18299 P Salzgitter v Commission 2003 ECR I10761 paragraphs 54 55 unnecessary consider content scope notice stage
Answer:

retrieved examples:

Text: Similarly term ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 41 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 87
Answer: Prec

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Therefore even sums corresponding measure question permanently held Treasury fact constantly remain public control therefore available competent national authorities sufficient categorised ‘State resources’ see judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 37 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 70 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 35 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 21
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: remove certain kinds subcategories nonlegislative acts general application scope provision would run counter objective
Answer: Itpr

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: measure accordingly operated de facto discrimination undertakings comparable situation light objective pursued regime case objective putting place generalised taxation resident companies
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw definition aid general subsidy given includes positive benefits subsidies also State measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 38 Joined Cases C‑7808 C8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer:

retrieved examples:

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: therefore follows judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 selectivity tax measure established even measure constitute derogation ordinary tax system integral part system fact remains judgment consistent Court’s settled caselaw cited paragraph 57 judgment effect sufficient order establish selectivity measure derogates ordinary tax system demonstrate measure benefits certain operators others although operators objectively comparable situation light objective pursued ordinary tax system
Answer: Prec

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: measure accordingly operated de facto discrimination undertakings comparable situation light objective pursued regime case objective putting place generalised taxation resident companies
Answer: Prec

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Second Commission specific grant aid alleged made pursuance previously authorised scheme cannot outset examine directly relation Treaty
Answer: Itpr

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: event case State aid notified delay may imputed Commission time learned existence aid incompatible common market
Answer: Itpr

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Consequently measure public authorities grant certain undertakings favourable tax treatment although involving transfer State resources places recipients favourable financial position taxpayers amounts State aid within meaning Article 871 EC see Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Paint Graphos Others paragraph 46 caselaw cited
Answer:

retrieved examples:

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Second recalled Commission required establish aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 8 September 2011 Commission v Netherlands C‑27908 P EUC2011551 paragraph 13 caselaw cited
Answer: Prec

Text: case funds issue could regarded State resource since time public control see judgment 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 36 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Accordingly clear distortion alleged manifestly apparent documents Court arguments Orange fact asking Court carry fresh assessment facts evidence falls outside Court’s jurisdiction
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: hand advantages resulting general measure applicable without distinction economic operators constitute State aid within meaning Article 87 EC see effect Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 22 Joined Cases C‑39304 C‑4105 Air Liquide Industries Belgium 2006 ECR I‑5293 paragraph 32 caselaw cited
Answer:

retrieved examples:

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: Member State concerned provides Commission requisite evidence Commission carry global assessment taking account — addition evidence provided Member State — relevant evidence enabling determine whether Member State took measure question capacity shareholder public authority
Answer: Itpr

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: said regards analysis substance Commission’s single ground appeal noted first obligation Member State concerned abolish recovery aid considered Commission incompatible single market purpose according Court’s established caselaw restore situation aid granted see effect judgment 4 April 1995 Commission v Italy C‑35093 EUC199596 paragraph 21 caselaw cited
Answer: Prec

Text: regard clear Court’s caselaw necessary financial balance economic viability undertaking entrusted operation service general economic interest threatened
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: said appellant entitled lodge appeal relying Court Justice grounds arguments arise judgment appeal seek criticise law correctness judgments 29 November 2007 Stadtwerke Schwäbisch Hall Others v Commission C‑17606 P published EUC2007730 paragraph 17 4 March 2021 Commission v Fútbol Club Barcelona C‑36219 P EUC2021169 paragraph 47
Answer: Prec

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: case funds issue could regarded State resource since time public control see judgment 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 36 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: However Member State provide justification
Answer: Itpr

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: therefore necessary determine whether proposed tax reform selective selectivity constituent factor concept State aid see Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 54
Answer:

retrieved examples:

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned able demonstrate differentiation justified since flows nature general structure system measures form part see effect inter alia judgments 29 April 2004 Netherlands v Commission C‑15901 EUC2004246 paragraphs 42 43 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraphs 64 65 29 March 2012 3M Italia C‑41710 EUC2012184 paragraph 40
Answer: Prec

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: consequence would national tax rules fall outset outside scope control State aid account sole fact adopted different regulatory technique although adjusting combining various tax rules produce effects law andor fact
Answer: Itpr

Text: According judgment applicant individually concerned decision addressed another person decision affects reason certain attributes peculiar reason circumstances differentiated persons see also field State aid judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 32 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 52 fields judgments 17 January 1985 PiraikiPatraiki Others v Commission 1182 EUC198518 paragraphs 11 19 31 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 93
Answer: Prec

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: presupposes action must liable successful procure advantage party bringing judgment 28 May 2013 Abdulrahim v Council Commission C‑23912 P EUC2013331 paragraph 61 caselaw cited
Answer: Prec

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Admittedly stated paragraph 33 applicant must always show requisite legal standard interests might affected granting aid possible showing fact competitive position relation trade unions operating market
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regards appraisal condition selectivity clear settled caselaw Article 871 EC requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 41 Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 82 caselaw cited
Answer:

retrieved examples:

Text: Third must confer advantage recipient
Answer: Class

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Court Justice’s jurisdiction appeal confined review findings law pleas argued General Court
Answer: Itpr

Text: applicability private investor test ultimately depends therefore Member State concerned conferred capacity shareholder capacity public authority economic advantage undertaking belonging
Answer: Itpr

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: presupposes action must liable successful procure advantage party bringing judgment 28 May 2013 Abdulrahim v Council Commission C‑23912 P EUC2013331 paragraph 61 caselaw cited
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: falls Commission show measure particular creates differences undertakings regard objective measure comparable situation
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: Indeed neither contended established General Court developed reasoning running manifestly counter content provisions German law issue ascribed one provisions scope manifestly light material file see effect judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 81
Answer: Prec

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: noted paragraph 73 selective advantages advantages resulting general measure applicable without distinction economic operators fall within concept State aid
Answer:

retrieved examples:

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: order determine whether measure selective therefore examined whether within context specified legal regime measure constitutes advantage certain undertakings others light objective pursued regime comparable factual legal situation judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36
Answer: Prec

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: Court also held absence overriding public interest Commission infringed superior rule law fails couple repeal set rules transitional measures protection expectations trader might legitimately derived Community rules Belgium Forum 187 paragraph 149 case‑law cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Similarly basis obliged engage new tariff negotiations supplier sign new agreement order put effect Commission’s decision
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First appropriate recall Court consistently held Article 871 EC distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see British Aggregates v Commission paragraphs 85 89 caselaw cited Case C‑27908 P Commission v Netherlands 2011 ECR I‑0000 paragraph 51
Answer:

retrieved examples:

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: EU judicature stage examination admissibility rule definitively competitive relationships applicant beneficiaries national measures assessed decision Commission State aid decision issue see effect judgments 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 28 20 December 2017 Binca Seafoods v Commission C‑26816 P EUC20171001 paragraph 59 direct effect applicant cannot deduced mere potential existence competitive relationship found judgments appeal
Answer: Prec

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: regards second condition set Article 230 EC borne mind fact disputed provision nature scope provision general application inasmuch applies traders concerned general prevent individual concern Belgium Forum 187 v Commission paragraph 58 case‑law cited
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: provision sets four conditions
Answer: Class

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: concept aid embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect Case C20097 Ecotrade 1998 ECR I7907 paragraph 34 Case C697 Italy v Commission 1999 ECR I2981 paragraph 15
Answer: Prec

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Similarly basis obliged engage new tariff negotiations supplier sign new agreement order put effect Commission’s decision
Answer: Prec

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: However financial situation recipient public undertaking depends means used place advantage however may effected amount undertaking ultimately receives
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Thus Member State makes alteration existing aid scheme breach authorisation condition scheme Member State guarantee authorised aid scheme affected alteration advantages granted basis scheme therefore retained
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court admittedly held paragraph 56 Portugal v Commission determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation
Answer:

retrieved examples:

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: addition obligation state reasons require General Court provide account follows exhaustively onebyone arguments put forward parties case General Court’s reasoning may therefore implicit condition enables persons concerned know upheld arguments provides Court Justice sufficient material exercise power review order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 28
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: regard Court’s established caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 94 caselaw cited
Answer: Prec

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 1071 TFEU
Answer: ['Princ', 'Rule']

Text: decision visàvis undertaking seek contest decision measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Van der Kooy Others v Commission cited paragraph 15 Case C692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Italy Sardegna Lines v Commission paragraph 33
Answer: Prec

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: benefit may advantage constituting aid may indeed benefit cannot justify failure recover aid recovery different sum constituting advantage procured unlawful aid question
Answer: Itpr

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: EU judicature stage examination admissibility rule definitively competitive relationships applicant beneficiaries national measures assessed decision Commission State aid decision issue see effect judgments 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 28 20 December 2017 Binca Seafoods v Commission C‑26816 P EUC20171001 paragraph 59 direct effect applicant cannot deduced mere potential existence competitive relationship found judgments appeal
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However contrary General Court’s reasoning proposition put forward Government Gibraltar United Kingdom caselaw make classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general liable tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings
Answer:

retrieved examples:

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general subject tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 91
Answer: Prec

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: appeal Courts jurisdiction thus confined review findings pleas argued Court First Instance see Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 order 28 June 2001 Case C35299 P Eridania Others v Council 2001 ECR I5037 paragraphs 52 53
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: follows length preliminary examination procedure constitute indication Commission may doubts regarding compatibility aid question common market length cannot lead conclusion Commission initiated formal investigation procedure see effect Case 8482 Germany v Commission 1984 ECR 1451 paragraphs 14 17 Belgium v Deutsche Post DHL International paragraph 81
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Text: application tax exemption extent depend tax revenue
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: interpretation selectivity criterion would require contrary caselaw cited paragraph 87 order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer:

retrieved examples:

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: follows length preliminary examination procedure constitute indication Commission may doubts regarding compatibility aid question common market length cannot lead conclusion Commission initiated formal investigation procedure see effect Case 8482 Germany v Commission 1984 ECR 1451 paragraphs 14 17 Belgium v Deutsche Post DHL International paragraph 81
Answer: Prec

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: recalled Van der Kooy Landbouwschap negotiated supplier gas preferential tariff challenged Commission also one signatories agreement establishing tariff
Answer: Prec

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence would national tax rules fall outset outside scope control State aid merely adopted different regulatory technique although produce effects law andor fact
Answer:

retrieved examples:

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: decision individual concern natural legal person within meaning provision essential condition locus standi proceedings seeking judicial review Community act proceedings inadmissible inadmissibility therefore constitutes ground involving question public policy may even must raised motion Community judicature see regard party interest bringing maintaining appeal Case C‑1993 P Rendo Others v Commission 1995 ECR I‑3319 paragraph 13
Answer: Prec

Text: case prohibition applies aid measure introduced alteration
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently considering whether private investor test applicable General Court err law focusing analysis fiscal nature means employed French State improvement — view opening electricity market — EDF’s financial situation effects measure question competition
Answer: Itpr

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: paragraphs 34 35 judgment Court held since Sardegna Lines concerned Decision 9895 virtue undertaking shipping sector Sardinia potential beneficiary aid scheme Sardinian shipowners also virtue actual beneficiary individual aid granted scheme recovery ordered Commission individually concerned decision action directed decision admissible
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 1071 TFEU save otherwise provided Treaties aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States incompatible internal market
Answer: Rule

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: However condition absolute impossibility implementation satisfied defendant Member State inform Commission internal difficulties legal political practical nature attributable national authorities’ acts omissions raised implementation decision issue without taking real steps recover aid undertakings concerned without suggesting Commission alternative methods implementing decision would allow difficulties overcome see effect judgments 13 November 2008 Commission v France C‑21407 EUC2008619 paragraph 50 12 February 2015 Commission v France C‑3714 published EUC201590 paragraph 66 caselaw cited
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Court held judgments mere fact provisions adopted part common agricultural policy place applicant unfavourable competitive position allow concluded provisions affect applicant’s legal situation line caselaw cannot transposed actions brought competitors beneficiaries State aid
Answer: Prec

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: true absence European Union rules governing matter falls within competence Member States infra‑State bodies fiscal autonomy designate bases assessment spread tax burden across different factors production economic sectors General Court held paragraph 146 judgment appeal
Answer:

retrieved examples:

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: regard true decision adopts end examination Commission may exercise discretion differentiate beneficiaries aid scheme notified regard certain characteristics display conditions fulfil
Answer: Itpr

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: According caselaw Court Justice infringement principle protection legitimate expectations established necessary EU institution giving citizen precise assurances led person entertain justified expectations
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: CIRFS case CIRFS Commission’s interlocutor regard introduction ‘discipline’ concerning aid synthetic fibre sector also extension adaptation actively pursued negotiations Commission prelitigation procedure particular submitting written observations keeping close contact responsible departments Commission
Answer: Prec

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Text: therefore clearly apparent wording paragraph 20 practice directions state ‘the appeal … unless special circumstances exceed 25 pages’ recital set absolute limitation number pages admissibility appeal subject merely provides recommendation regard parties
Answer: Itpr

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually way person addressed judgments 15 July 1963 Plaumann v Commission 2562 EUC196317 p 107 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraph 57
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Consequently General Court correctly applied Article 841 Rules Procedure rejecting plea ground time
Answer: Rule

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Court held judgments mere fact provisions adopted part common agricultural policy place applicant unfavourable competitive position allow concluded provisions affect applicant’s legal situation line caselaw cannot transposed actions brought competitors beneficiaries State aid
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: paragraph 67 judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court recalled regard national measure conferring tax advantage general application condition relating selectivity satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly according caselaw cited paragraph 73 different tax burden resulting application ‘general’ tax regime sufficient establish selectivity taxation purposes Article 871 EC
Answer:

retrieved examples:

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: context contrary held General Court paragraph 57 judgment appeal Autogrill España v Commission paragraph 61 judgment appeal Banco Santander Santusa v Commission cannot inferred paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 according measures selective apply undertakings national territory ‘regardless activity’ measure whose application depend nature undertakings’ activity priori selective
Answer: Prec

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: however examine effects alteration original aid scheme
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: hand purpose aid recovery seek compensation individual harm kind reestablish market question situation aid granted
Answer: Itpr

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: regards second conditions say individually concerned act question settled caselaw persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed Case 2562 Plaumann v Commission 1963 ECR 95 107 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 52 Inuit Tapiriit Kanatami Others v Parliament Council paragraph 72
Answer: Prec

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually way person addressed judgments 15 July 1963 Plaumann v Commission 2562 EUC196317 p 107 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraph 57
Answer: Prec

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus criteria forming basis assessment adopted tax system must also order capable recognised conferring selective advantages characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 871 EC
Answer:

retrieved examples:

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: regards second conditions say individually concerned act question settled caselaw persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed Case 2562 Plaumann v Commission 1963 ECR 95 107 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 52 Inuit Tapiriit Kanatami Others v Parliament Council paragraph 72
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: matters regard fact measure irrespective form legislative means used effect placing recipient undertakings position favourable undertakings although undertakings comparable factual legal situation light objective pursued tax system concerned
Answer: Itpr

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: limb without subjecting admissibility actions annulment brought natural legal persons condition individual concern allows actions brought ‘regulatory acts’ entail implementing measures direct concern applicant see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 57
Answer: Prec

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Court also held compatibility aid common market assessed context Steel Aid Codes light rules force date actually paid Falck Acciaierie di Bolzano v Commission paragraph 117
Answer: Prec

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent judgment appeal documents included file appellants submitted General Court contrary Commission stated point 97 grounds contested decision normal tax rules company profits could used valid basis comparison thus reference framework assessment selectivity tax scheme issue
Answer:

retrieved examples:

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: According settled case‑law correctly cited Court First Instance paragraph 169 contested judgment abolishing unlawful aid means recovery logical consequence finding unlawful
Answer: Prec

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Infringement proceedings based objective finding Member State failed fulfil obligations EU law see particular judgment 6 October 2009 Commission v Spain C‑56207 EUC2009614 paragraph 18
Answer: Prec

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: noted begin assessing compatibility State aid maritime transport sector aid issue present case social aspects Community guidelines may taken account Commission part overall assessment includes large number considerations various kinds linked particular protection competition Community’s maritime policy promotion Community maritime transport promotion employment see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others v Commission 2000 ECR I‑3659 paragraph 52
Answer: Prec

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: follows rules governing proceedings EU Courts particular Article 21 Statute Court Justice European Union applicable General Court pursuant first paragraph Article 53 Statute Article 441 Rules Procedure General Court version applicable originating application lodged case principle determined delimited parties EU Courts cannot adjudicate ultra petita see effect judgment 10 December 2013 Commission v Ireland Others C‑27212 P EUC2013812 paragraph 27
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: regard delay Commission deciding aid illegal must abolished recovered Member State could certain circumstances establish legitimate expectation part recipients aid prevent Commission requiring Member State order refund aid see Case 22385 RSV v Commission 1987 ECR 4617 paragraph 17
Answer: Prec

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: must also borne mind far determination reference framework must based objective examination content structure applicable rules national law necessary first stage examination selectivity take account objectives pursued legislature adopting measure examination
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Even case tax scheme issue confer economic advantage general realignment scheme
Answer:

retrieved examples:

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Infringement proceedings based objective finding Member State failed fulfil obligations EU law see particular judgment 6 October 2009 Commission v Spain C‑56207 EUC2009614 paragraph 18
Answer: Prec

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant see effect Case C36795 P Commission v Sytraval Brink’s France 1998 ECR I1719 paragraph 67 Case C26597 P VBA v Florimex Others 2000 ECR I2061 paragraph 114 Commission v Ireland Others paragraph 40
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Even though true purposes ECSC Treaty rules apply based domain State aid fundamental requirement legal certainty
Answer: ['Itpr', 'Rule']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored see Case C‑35093 Commission v Italy 1995 ECR I‑699 paragraph 22
Answer: Prec

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: proof may furnished reference body consistent evidence question whether doubt exists requires investigation circumstances decision raise objections adopted content comparing assessments upon Commission relied decision information available ruled compatibility aid question common market see effect Case C‑19891 Cook v Commission 1993 ECR I‑2487 paragraphs 30 31 Bouygues Bouygues Télécom v Commission paragraph 63 TF1 v Commission paragraph 52 Austria v ScheucherFleisch Others paragraphs 71 72
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court Justice stated determination reference framework purpose determining whether measure selective particular importance case tax measures since existence advantage may established compared “normal” taxation Case C8803 Portugal v Commission 2006 ECR I7115 paragraph 56 say taxation normally applicable undertakings light objective pursued scheme question factual legal situation comparable undertakings benefiting scheme Case C14399 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke 2001 ECR I8365 paragraph 41
Answer:

retrieved examples:

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: case aid derives fact another category economic operators category liable pay tax direct competition liable charge
Answer: Itpr

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Commission preliminary examination finds doubts raised compatibility common market notified measure far falls within scope Article 871 EC adopt decision raise objections Article 43 Regulation 6591999 Commission v Kronoply Kronotex paragraph 44 TF1 v Commission paragraph 48 Austria v ScheucherFleisch Others paragraph 41
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored see Case C‑35093 Commission v Italy 1995 ECR I‑699 paragraph 22
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First order determine whether measure although applying generally set economic operators effect ultimately conferring advantage certain undertakings examined apparent caselaw recalled paragraph 41 present judgment whether certain undertakings favoured others light objective pursued legal regime concerned comparable factual legal situation
Answer: Prec

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: hand General Court rightly pointed paragraph 206 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Commission examining scheme light rules State aid envisage subjective choices might made beneficiaries scheme absence scheme examine scheme order determine whether entails objective standpoint economic advantage reference tax provisions derogates would normally applicable absence scheme see effect Case C14804 Unicredito Italiano 2005 ECR I11137 paragraph 118
Answer:

retrieved examples:

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: Court thus held undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: contrast decision affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders judgments 13 March 2008 Commission v Infront WM C‑12506 P EUC2008159 paragraph 71 caselaw cited 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraph 59
Answer: Prec

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Commission preliminary examination finds doubts raised compatibility common market notified measure far falls within scope Article 871 EC adopt decision raise objections Article 43 Regulation 6591999 Commission v Kronoply Kronotex paragraph 44 TF1 v Commission paragraph 48 Austria v ScheucherFleisch Others paragraph 41
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According Court’s caselaw however State aid defined Treaty Functioning European Union legal concept must interpreted basis objective factors
Answer:

retrieved examples:

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection legal remedy EU judicature purpose challenging lawfulness regulatory act
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: Third must confer advantage recipient
Answer: Class

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer: Itpr

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal judgment Isdin v BialPortela C‑59712 P EUC2013672 paragraph 21
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Also far arguments set alternative 3F seeks put forward separate specific grounds demonstrate Commission infringed principle good administration essentially alleging duration preliminary examination stage unreasonable recalled according Article 1701 Rules Procedure Court Justice subjectmatter proceedings General Court may changed appeal
Answer: Rule

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Third must confer selective advantage recipient
Answer: Class

Text: However Member State provide justification
Answer: Itpr

Text: However prudent alert economic operator could foreseen adoption Community measure likely affect interests cannot plead principle measure adopted see effect Belgium Forum 187 v Commission paragraph 147 case‑law cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reason European Union judicature must principle regard specific features case technical complex nature Commission’s assessments carry comprehensive review whether measure falls within scope Article 1071 TFEU see inter alia Case C8398 P France v Ladbroke Racing Commission 2000 ECR I3271 paragraph 25 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 111
Answer:

retrieved examples:

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows condition application receipt tax aid may grounds finding aid selective condition leads distinction made undertakings despite fact light objective pursued tax system concerned comparable factual legal situation therefore represents discrimination undertakings excluded
Answer: Itpr

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: However ground judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 must read context set grounds forms part set paragraphs 87 108 judgment
Answer: Prec

Text: Article 92 Treaty states Save otherwise provided Treaty aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods shall far affects trade Member States incompatible common market
Answer: Rule

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: sufficient Commission’s decision include information enabling recipient calculate amount without overmuch difficulty see also Case C‑48098 Spain v Commission 2000 ECR I8717 paragraph 25 Case C‑41503 Commission v Greece 2005 ECR I3875 paragraph 39
Answer: Prec

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: However prudent alert economic operator could foreseen adoption Community measure likely affect interests cannot plead principle measure adopted see effect Belgium Forum 187 v Commission paragraph 147 case‑law cited
Answer: Prec

Text: However must forgotten notification State aid central element Community rules supervising aid undertakings aid granted may entertain legitimate expectation aid lawful granted compliance procedure Alcan Deutschland paragraph 25
Answer: Prec

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover according equally wellestablished caselawthe concept State aid refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature general scheme system form part see effect inter alia AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke paragraph 42 Portugal v Commission paragraph 52 British Aggregates v Commission paragraph 83 Joined Cases C10609 P C10709 P Commission Spain v Government Gibraltar United Kingdom 2011 ECR I11113 paragraph 145
Answer:

retrieved examples:

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: However fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see Geigy v Commission cited paragraphs 20 21 Joined Cases C‑7400 P C‑7500 P Falck Acciaierie di Bolzano v Commission 2002 ECR I‑7869 paragraph 140
Answer: Prec

Text: However ground judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 must read context set grounds forms part set paragraphs 87 108 judgment
Answer: Prec

Text: Consequently appears private investor test could applicable Commission duty ask Member State concerned provide relevant information enabling determine whether conditions governing applicability application test met cannot refuse examine information unless evidence produced established adoption decision make investment question
Answer: Itpr

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: apparent considerations carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: rules applicable investment sugar sector thus established Regulation 178581
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: accordance settled caselaw appeal plea directed ground judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Prec

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Second Commission specific grant aid alleged made pursuance previously authorised scheme cannot outset examine directly relation Treaty
Answer: Itpr

Text: requirement satisfied plea complains General Court reached certain conclusion without specifying legal basis ought reached different one Case C‑25798 P Lucaccioni v Commission 1999 ECR I‑5251 paragraph 62 order 26 January 2005 Case C‑15304 P Euroagri v Commission paragraph 38
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: However fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see Geigy v Commission cited paragraphs 20 21 Joined Cases C‑7400 P C‑7500 P Falck Acciaierie di Bolzano v Commission 2002 ECR I‑7869 paragraph 140
Answer: Prec

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: examination therefore principle requires prior definition reference framework within measure concerned fits
Answer: Itpr

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Admittedly Court Justice held judicial review limited regard whether measure comes within scope Article 1071 TFEU case appraisals Commission technical complex nature see inter alia France v Ladbroke Racing Commission paragraph 25 British Aggregates v Commission paragraph 114
Answer:

retrieved examples:

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Court held nature scheme preclude finding measure concerned selective contrary ruling General Court since condition relating selectivity broader scope extends measures effects favour certain undertakings case ‘offshore’ companies account specific features characteristic undertakings
Answer: Prec

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: first place recalled according settled case‑law relatively small amount aid relatively small size undertaking receives exclude possibility intraCommunity trade might affected see Case C14287 Belgium v Commission 1990 ECR I959 ‘Tubemeuse’ paragraph 43 Joined Cases C‑27892 C‑28092 Spain v Commission 1994 ECR I‑4103 paragraph 42 Case C‑28000 Altmark Trans Regierungspräsidium Magdeburg 2003 ECR I‑7747 paragraph 81
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: Contrary General Court’s assertion paragraphs 59 62 judgment appeal Autogrill España v Commission paragraphs 63 66 judgment appeal Banco Santander Santusa v Commission indication contrary regards analysis condition relating selectivity tax measure may deduced judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467
Answer: ['Itpr', 'Prec']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance rightly observed measure vitiated misuse powers appears basis objective relevant consistent evidence taken exclusive main purpose achieving end stated see inter alia Case C‑11097 Netherlands v Council 2001 ECR I‑8763 paragraph 137 cases cited
Answer:

retrieved examples:

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: provision sets four conditions
Answer: Class

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: However Member State provide justification
Answer: Itpr

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: third place regards first part decision issue true according settled caselaw Court recovery order individual concern beneficiaries aid scheme question order adopted exposed risk benefits received recovered therefore members restricted class see effect judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 33 35 29 April 2004 Italy v Commission C‑29800 P EUC2004240 paragraph 39 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 56
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Member State concerned provides Commission requisite evidence Commission carry global assessment taking account — addition evidence provided Member State — relevant evidence enabling determine whether Member State took measure question capacity shareholder public authority
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: provisions EC Treaty apply alternative situations specific rule ECSC Treaty see particular Case 32885 Deutsche Babcock 1987 ECR 5119 paragraphs 6 14
Answer: ['Prec', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 55 60 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraphs 88 89
Answer: Prec

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: fourth paragraph Article 263 TFEU natural legal person may conditions laid first second paragraphs article institute proceedings act addressed person direct individual concern regulatory act direct concern entail implementing measures
Answer: Rule

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Court First Instance undertook assessment facts unless clear sense evidence produced distorted constitute question law subject review Court Justice see inter alia Joined Cases C‑28099 P C‑28299 P Moccia Irme Others v Commission 2001 ECR I‑4717 paragraph 78 Joined Cases C‑23899 P C‑24499 P C‑24599 P C‑24799 P C‑25099 P C‑25299 P C‑25499 P Limburgse Vinyl Maatschappij Others v Commission 2002 ECR I‑8375 paragraph 285
Answer:

retrieved examples:

Text: State perfectly capable exercising dominant influence undertakings directing use resources order occasion arises finance specific advantages favour undertakings see effect judgment 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 38
Answer: Prec

Text: third place regards first part decision issue true according settled caselaw Court recovery order individual concern beneficiaries aid scheme question order adopted exposed risk benefits received recovered therefore members restricted class see effect judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 33 35 29 April 2004 Italy v Commission C‑29800 P EUC2004240 paragraph 39 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 56
Answer: Prec

Text: contrast since assessment context appeal legal classification given national law General Court light provision EU law constitutes question law falls within jurisdiction Court Justice see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 83 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 61 63
Answer: Prec

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Admittedly stated paragraph 33 applicant must always show requisite legal standard interests might affected granting aid possible showing fact competitive position relation trade unions operating market
Answer: Itpr

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Furthermore pointed paragraph 53 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer:

retrieved examples:

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Since determination reference system constitutes starting point comparative examination carried context assessment selectivity aid scheme error made determination necessarily vitiates whole analysis condition relating selectivity see effect judgments 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 107 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraph 46
Answer: Prec

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: Court Justice’s jurisdiction appeal confined review findings law pleas argued General Court
Answer: Itpr

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: fact however taken consideration relation obligation recover incompatible aid light principles protection legitimate expectations legal certainty done Commission contested decision declined order recovery aid granted date publication Official Journal European Communities decisions initiate procedure laid Article 882 EC
Answer: ['Princ', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Contrary General Court’s assertion paragraphs 59 62 judgment appeal Autogrill España v Commission paragraphs 63 66 judgment appeal Banco Santander Santusa v Commission indication contrary regards analysis condition relating selectivity tax measure may deduced judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: appeal Court’s jurisdiction confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C‑795 P John Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C‑21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer:

retrieved examples:

Text: Third must confer selective advantage recipient
Answer: Class

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Thus measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict meaning word similar character effect considered constitute aid judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 65 66 caselaw cited
Answer: Prec

Text: sufficient absence rights issue would possible undertaking perform particular tasks entrusted maintenance rights necessary enable holder perform tasks general economic interest assigned economically acceptable conditions judgment 15 November 2007 International Mail Spain C‑16206 EUC2007681 paragraph 35 caselaw cited
Answer: Prec

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: follows General Court correctly held paragraph 217 judgment appeal context proceedings Court must make necessary determinations order reach finding failure fulfil obligations result plea defence raised intervener relates element fact law Commission must necessarily take account analysis capable altering framework dispute even relied Member State concerned
Answer: Itpr

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Since determination reference system constitutes starting point comparative examination carried context assessment selectivity aid scheme error made determination necessarily vitiates whole analysis condition relating selectivity see effect judgments 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 107 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraph 46
Answer: Prec

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: However accordance second sentence Article 141 Regulation 6591999 Commission shall require recovery aid would contrary general principle EU law
Answer: Rule

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: respect borne mind pursuant Article 58 Statute Court Justice appeal Court Justice limited points law lie grounds particular infringement Community law Court First Instance
Answer:

retrieved examples:

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: However requirement General Court give reasons decisions cannot interpreted meaning obliged respond detail every single argument advanced applicant particularly argument sufficiently clear precise see inter alia Joined Cases C‑12006 P C‑12106 P FIAMM Others v Council Commission 2008 ECR I‑6513 paragraph 91 caselaw cited
Answer: Prec

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: Thus Member State makes alteration existing aid scheme breach authorisation condition scheme Member State guarantee authorised aid scheme affected alteration advantages granted basis scheme therefore retained
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard particular unlawful aid granted form tax advantage also Court’s settled caselaw recovery aid means transactions actually carried recipients aid question must subject tax treatment recipients would received absence unlawful aid see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 119
Answer: Prec

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: selective follows reasoning set paragraphs 41 47 55 present judgment within context particular legal regime effect conferring advantage certain undertakings others different sector sector light objective pursued regime comparable factual legal situation
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General states point 20 Opinion Commission’s appeal based precisely upon allegation Court First Instance infringed Community law failing follow apply interpretation Articles 87 EC 253 EC laid caselaw Court Justice
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: regard particular unlawful aid granted form tax advantage also Court’s settled caselaw recovery aid means transactions actually carried recipients aid question must subject tax treatment recipients would received absence unlawful aid see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 119
Answer: Prec

Text: Court accepted Albany restrictions competition inherent collective agreements organisations representing employers workers
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: apparent provisions read together reply may seek annulment judgment appeal basis distinct independent grounds raised appeal since grounds may raised part crossappeal
Answer: Itpr

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: First must intervention State State resources
Answer: Class

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: benefit may advantage constituting aid may indeed benefit cannot justify failure recover aid recovery different sum constituting advantage procured unlawful aid question
Answer: Itpr

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: regard may added Court previously ruled tax measure solely undertakings carried specified transactions benefited undertakings sector carry transactions could classified selective need assess whether measure greater benefit large undertakings see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraphs 47 50
Answer: Prec

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule', 'Aut']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Regarding Wam’s argument Commission’s appeal invites Court Justice first review substance judgment appeal rather limited review ‘essential procedural requirement’ laid Article 230 EC second carry review substance Court Justice jurisdiction appeal stage noted Article 230 EC gives Court Justice jurisdiction review acts Community institutions Court First Instance
Answer:

retrieved examples:

Text: provision sets four conditions
Answer: Class

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: Court accepted Albany restrictions competition inherent collective agreements organisations representing employers workers
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 60
Answer: Prec

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: includes positive benefits also measures various forms mitigate charges normally included budget undertaking thus without subsidies strict sense word similar character effect see Joined Cases C‑7808 C‑8008 Paint Graphos Others 2011 ECR I‑0000 paragraph 45 caselaw cited
Answer: Prec

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Prior initiation procedure must first examine whether aid covered general scheme satisfies conditions laid decision approving
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: contrast Court held contested measure affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders see Case 1182 PiraikiPatraiki Others v Commission 1985 ECR 207 paragraph 31 Case C15288 Sofrimport v Commission 1990 ECR I‑2477 paragraph 11 Belgium Forum 187 v Commission paragraph 60
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: regards fourth part ground appeal recalled appellant must pursuant Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court Justice indicate precisely evidence alleged distorted General Court demonstrate errors appraisal view led distortion
Answer: Rule

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: According Court’s wellestablished caselaw appeal complaints directed ground included judgment General Court purely sake completeness must immediately dismissed ineffective since cannot lead judgment appeal set aside see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 75 caselaw cited
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Appeals judgments Court First Instance governed however terms Article 2251 EC Statute Court Justice
Answer:

retrieved examples:

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: According Court’s wellestablished caselaw appeal complaints directed ground included judgment General Court purely sake completeness must immediately dismissed ineffective since cannot lead judgment appeal set aside see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 75 caselaw cited
Answer: Prec

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: essential characteristic remuneration lies fact consideration service question see effect judgments 11 September 2007 Schwarz GootjesSchwarz C‑7605 EUC2007492 paragraphs 37 38 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 45 47
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next must noted obligation provide statement reasons essential procedural requirement must distinguished question whether reasoning well founded latter concerned substantive legality measure issue see effect Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 48
Answer:

retrieved examples:

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: appellant alleges distortion evidence General Court must Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court indicate precisely evidence alleged distorted General Court show errors appraisal view led distortion
Answer: Rule

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: contrast regulatory act entails implementing measures judicial review compliance EU legal order ensured irrespective whether measures adopted European Union Member States
Answer: Prec

Text: Article 2 EC Treaty amendment Article 2 EC declares particular task Community ‘to promote … harmonious balanced development economic activities’ ‘a high level employment social protection
Answer: Rule

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: However Court stated State measure must regarded compensation services provided recipient undertakings order discharge public service obligations undertakings enjoy real financial advantage measure thus effect putting favourable competitive position undertakings competing measure caught Article 1071 TFEU see judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 87
Answer: Prec

Text: Thus Member State stage procedure encounters difficulties recovering aid concerned must submit difficulties Commission consideration cooperate good faith Commission view overcoming particular suggesting alternative methods allowing recovery part aid
Answer: Itpr

Text: Third must confer advantage recipient
Answer: Class

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: Consequently considering whether private investor test applicable General Court err law focusing analysis fiscal nature means employed French State improvement — view opening electricity market — EDF’s financial situation effects measure question competition
Answer: Itpr

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw statement reasons required Article 253 EC must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer:

retrieved examples:

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: circumstances Court found agreements concluded context collective negotiations management labour pursuit objectives must virtue nature purpose regarded falling outside scope provision
Answer: Prec

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain business sectors judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 55 caselaw cited
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: case public undertakings assessment made applying principle private investor test see effect Case C30388 Italy v Commission 1991 ECR I1433 paragraph 20 Case C48299 France v Commission 2002 ECR I4397 paragraphs 68 70 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 91 caselaw cited
Answer: Prec

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard true decision adopts end examination Commission may exercise discretion differentiate beneficiaries aid scheme notified regard certain characteristics display conditions fulfil
Answer: Itpr

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Prec

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question Case C‑8803 Portugal v Commission 2006 ECR I‑7115 paragraph 88 caselaw cited
Answer:

retrieved examples:

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: regards thirdly Commissions claim alternative Court set aside words view paragraph 36 English version judgment appeal clear grounds judgment Court First Instance decide admissibility application basis subjective appraisal interests applicants explained basis rules governing admissibility actions Article 173 Treaty
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: Since Lico Leasing PYMAR dispute admissibility first complaint first part Commission’s first ground appeal alleging error law identification beneficiaries advantages arising tax measures issue ground question fact true assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: addition paragraphs 80 81 judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court recalled fact recipient undertakings belong various economic sectors sufficient call question selective nature measure concerned held potentially selective nature measure issue way called question fact essential condition obtaining tax advantage conferred measure economic transaction particularly entirely financial transaction available regardless nature business recipient undertakings
Answer: Prec

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: provisions EC Treaty apply alternative situations specific rule ECSC Treaty see particular Case 32885 Deutsche Babcock 1987 ECR 5119 paragraphs 6 14
Answer: ['Prec', 'Rule']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 871 EC
Answer:

retrieved examples:

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: regard noted distortion must obvious documents Court’s file without need carry new assessment facts evidence judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 80
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined judgments 16 March 1978 Unicme Others v Council 12377 EUC197873 paragraph 16 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 47 caselaw cited
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Court previously held Commission cannot pain invalid adopt order recovery moment adoption objectively absolutely impossible implement see effect judgment 17 June 1999 Belgium v Commission C‑7597 EUC1999311 paragraph 86
Answer: Prec

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: ['Princ', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard even cases apparent circumstances granted aid liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision see Portugal v Commission paragraph 89 caselaw cited
Answer:

retrieved examples:

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Court First Instance held inter alia paragraphs 77 79 contested judgment course Commission’s assessment new aid pursuant Article 933 Treaty notified put effect Commission required establish whether aid real impact trade Member States competition whether aid could affect trade
Answer: Rule

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: held certain associations economic operators played significant role procedure provision must recognised individually concerned decision far affected capacity negotiators see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraphs 40 42
Answer: Prec

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: confirmed fact reference made subsequent judgments Court restate principle see inter alia judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 73 29 March 2012 3M Italia C‑41710 EUC2012184 paragraph 39
Answer: Prec

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: However first factual assessment Czech Republic voluntarily undertook implement ‘review mechanism’ apparent caselaw cited paragraph 24 fall within jurisdiction Court Justice hearing appeal except facts distorted alleged appellants
Answer: Prec

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: follows paragraph 78 applicable test among factors Commission required take account purposes establishing existence aid
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: must also borne mind far determination reference framework must based objective examination content structure applicable rules national law necessary first stage examination selectivity take account objectives pursued legislature adopting measure examination
Answer: Itpr

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: party may therefore put forward first time Court Justice plea could raised General Court raised since would allow bring Court Justice whose jurisdiction appeals limited case wider ambit came General Court see judgment 29 September 2011 Case C‑52009 P Arkema v Commission yet published ECR paragraph 64 caselaw cited
Answer: Prec

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored judgment 29 April 2004 Germany v Commission C‑27700 EUC2004238 paragraph 75 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: Moreover apparent first paragraph Article 136 EC Community Member States objectives inter alia promotion employment improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour
Answer: Rule

Text: regard noted distortion must obvious documents Court’s file without need carry new assessment facts evidence judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 80
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: context noted also according settled caselaw purpose categorising national measure State aid necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition Case C22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraph 140 caselaw cited
Answer:

retrieved examples:

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Even though true purposes ECSC Treaty rules apply based domain State aid fundamental requirement legal certainty
Answer: ['Itpr', 'Rule']

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: Court repeatedly held right rely principle protection legitimate expectations extends person situation Community institution caused entertain expectations justified precise assurances provided
Answer: Prec

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: EU law cannot permit rules State aid circumvented merely creation autonomous institutions charged allocating aid see judgment 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 23
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: confirmed fact reference made subsequent judgments Court restate principle see inter alia judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 73 29 March 2012 3M Italia C‑41710 EUC2012184 paragraph 39
Answer: Prec

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard specifically condition trade Member States affected follows caselaw grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently meeting condition taxable persons perform economic activity field trade conceivable competition operators established Member States see Portugal v Commission paragraph 91 Case C‑17203 Heiser 2005 ECR I‑1627 paragraph 35
Answer:

retrieved examples:

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 55 60 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraphs 88 89
Answer: Prec

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: appeal Court’s jurisdiction thus confined review findings law pleas argued Court First Instance see particular Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 Case C795 P Deere v Commission 1998 ECR I‑3111 paragraph 62 Case C21701 P Hendrickx v Cedefop 2003 ECR I‑3701 paragraph 37
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: method aid financed may render entire aid scheme intended fund incompatible internal market
Answer: Prec

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: measure issue judgment concerned sector years receiving State aid approved Commission object meet additional costs operation already received authorised aid Case C‑33499 Germany v Commission 2003 ECR I‑1139 paragraph 44
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: case aid derives fact another category economic operators category liable pay tax direct competition liable charge
Answer: Itpr

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Furthermore Court held aid granted Member State strengthens position undertaking compared undertakings competing intraCommunity trade latter must regarded influenced aid Cassa di Risparmio di Firenze Others paragraph 141 caselaw cited
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: follows paragraphs 22 23 judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467 case gave rise judgment Commission classified measure concerned selective relation certain geographically defined undertakings private investors reinvested profits derived sales financial assets relation investors respect Commission considered measure constitute aid since general measure benefited operators indiscriminately assessment moreover challenged Court Court therefore give ruling
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Third must confer advantage recipient
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: method aid financed may render entire aid scheme intended fund incompatible internal market
Answer: Prec

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner see judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 33 caselaw cited 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 49
Answer: Prec

Text: Second recovery unlawful aid view reestablishing status quo ante imply reconstructing past events differently basis hypothetical elements choices often numerous could made operators concerned since choices actually made aid might prove irreversible judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 118
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Court accordingly held preferential rediscount rate exports constitutes aid case point authorised Commission Article 672 CS far concerned industry covered ECSC Treaty see Commission v France paragraph 44
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard fact economic sector liberalised Community level may serve determine aid real potential effect competition affects trade Member States Cassa di Risparmio di Firenze Others paragraph 142 caselaw cited
Answer:

retrieved examples:

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: regards first argument must recalled accordance Court’s settled caselaw proceedings annulment General Court cannot substitute reasoning author contested act see judgments DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 141
Answer: Prec

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: According settled case‑law persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed see inter alia judgments Case 2562 Plaumann v Commission 1963 ECR 95 Case C‑32195 P Greenpeace Council Others v Commission 1998 ECR I‑1651 paragraphs 7 28 Italy Sardegna Lines v Commission cited paragraph 32
Answer: Prec

Text: principal objective order eliminate distortion competition caused competitive advantage conferred unlawful aid see effect judgments 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 113 caselaw cited 1 October 2015 Electrabel Dunamenti Erőmű v Commission C‑35714 P EUC2015642 paragraph 111 caselaw cited 21 December 2016 Commission v Aer Lingus Ryanair Designated Activity C‑16415 P C‑16515 P EUC2016990 paragraph 116
Answer: Prec

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: cases relate provisions national law granting relief taxes charges judgments France v Commission C‑24194 EUC1996353 Piaggio C‑29597 EUC1999313 DM Transport C‑25697 EUC1999332 P C‑612 EUC2013525 Ministerio de Defensa Navantia C‑52213 EUC20142262 British Telecommunications v Commission C‑62013 P EUC20142309 exceptions matters insolvency judgment Ecotrade C‑20097 EUC1998579
Answer: Prec

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer: Itpr

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner see judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 33 caselaw cited 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 49
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard condition distortion competition borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition see Case C‑15698 Germany v Commission 2000 ECR I‑6857 paragraph 30 Heiser paragraph 55
Answer:

retrieved examples:

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regards first argument must recalled accordance Court’s settled caselaw proceedings annulment General Court cannot substitute reasoning author contested act see judgments DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 141
Answer: Prec

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Text: provision sets four conditions
Answer: Class

Text: Thus Court stated undertaking cannot general rule contest decision Commission prohibits sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: follows condition application receipt tax aid may grounds finding aid selective condition leads distinction made undertakings despite fact light objective pursued tax system concerned comparable factual legal situation therefore represents discrimination undertakings excluded
Answer: Itpr

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Furthermore aid granted Member State strengthens position undertaking compared undertakings competing trade within European Union undertakings must regarded affected aid judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 141
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: findings examination interdependence EU Far Eastern markets relate possibility indirect effect trade intraCommunity competition referred principally Tubemeuse judgement
Answer:

retrieved examples:

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Given condition direct concern requires contested measure produce effects directly applicant’s legal situation EU judicature must ascertain whether applicant adequately explained reasons Commission’s decision liable place unfavourable competitive position thus produce effects legal situation
Answer: Itpr

Text: Furthermore aid granted Member State strengthens position undertaking compared undertakings competing trade within European Union undertakings must regarded affected aid judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 141
Answer: Prec

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: paragraphs 70 71 judgment Court stated supplementary requirement identify particular category undertakings exclusively favoured measure question may distinguished reason specific properties common characteristic cannot inferred caselaw Court Justice
Answer: Prec

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: apparent judgment fact coming compulsory levy contrary sufficient identify State resources see effect judgment 28 March 2019 Germany v Commission C‑40516 P EUC2019268 paragraphs 65 72
Answer: Prec

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: examination whether measure selective thus essence coextensive examination whether applies set economic operators nondiscriminatory manner see effect judgment 14 January 2015 Eventech C‑51813 EUC20159 paragraph 53
Answer: Prec

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law General Court obliged reject inadmissible head claim application brought essential matters law fact head claim based indicated coherently intelligibly application Case C‑21405 P Rossi v OHIM 2006 ECR I‑7057 paragraph 37 order 13 March 2007 Case C‑15006 P Arizona Chemical Others v Commission published ECR paragraph 45
Answer:

retrieved examples:

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: cases Commission required undertake detailed examination difficulties pleaded suggested alternative methods recovery
Answer: Itpr

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: regard new aid Article 933 Treaty provides Commission informed sufficient time enable submit comments plans grant alter aid
Answer: Rule

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Second Commission specific grant aid alleged made pursuance previously authorised scheme cannot outset examine directly relation Treaty
Answer: Itpr

Text: Furthermore assessment reference made exclusively subject matter action see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 30 31 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 50 51 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraphs 38 39 caselaw cited
Answer: Prec

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Aid relatively small amount liable affect competition trade Member States strong competition sector undertakings receive operate see Case 25985 France v Commission 1987 ECR 4393 paragraph 24 Case C‑35198 Spain v Commission 2002 ECR I‑8031 paragraph 63
Answer: Prec

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: regards second condition set Article 230 EC borne mind fact disputed provision nature scope provision general application inasmuch applies traders concerned general prevent individual concern Belgium Forum 187 v Commission paragraph 58 case‑law cited
Answer: Rule

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: stated recital 14 preamble regulation limitation period established reasons legal certainty
Answer: Rule

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: may seen Joined Cases C‑7291 C‑7391 Sloman Neptun 1993 ECR I‑887 system established DIS register enables contracts employment concluded seafarers nationals nonmember countries permanent abode residence Member State concerned subjected working conditions rates pay covered law Member State considerably less favourable applicable seafarers nationals Member State constitute State aid within meaning Article 871 EC
Answer: Prec

Text: examination whether measure selective thus essence coextensive examination whether applies set economic operators nondiscriminatory manner see effect judgment 14 January 2015 Eventech C‑51813 EUC20159 paragraph 53
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court entitled pointing Article 441c Rules Procedure application must state subject‑matter proceedings summary pleas law application based manner sufficiently clear precise enable defendant prepare defence General Court give ruling reject argument alleging infringement Article 88 EC Regulation 6591999 inadmissible ground satisfy conditions
Answer:

retrieved examples:

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Last situation issue present case comparable situation case gave rise judgment 13 March 2001 PreussenElektra C‑37998 EUC2001160 Court held obligation imposed private electricity supply undertakings purchase electricity produced renewable energy sources fixed minimum prices involve direct indirect transfer State resources undertakings produced type electricity see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 59 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 34
Answer: Prec

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: contrary settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: According Court’s caselaw Van der Kooy CIRFS cases thus concerned particular situations applicant occupied clearly circumscribed position negotiator intimately linked actual subjectmatter decision thus placing factual situation distinguished persons Case C‑10698 P Comité d’entreprise de la Société française de production Others paragraph 45
Answer: Prec

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 1071 TFEU
Answer: ['Princ', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule', 'Itpr']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According established case‑law Court following restructuring entailing transfer production facilities one company newly constituted manufacturing companies since former company continues interest newly constituted manufacturing companies companies may far aid granted concerned together form single group notwithstanding fact newly constituted manufacturing companies legal personality separate former company see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 11
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Indeed according settled caselaw grounds judgment General Court disclose infringement EU law operative part shown well founded legal grounds infringement capable bringing setting aside judgment judgments 30 September 2003 Biret International v Council C‑9302 P EUC2003517 paragraph 60 caselaw cited 14 October 2014 Buono Others v Commission C‑1213 P C‑1313 P EUC20142284 paragraph 62 caselaw cited
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Finally far Italian Republic claims since recipient undertakings relied lawfulness aid instituted paid many years Court First Instance concluded long period given rise legitimate expectations part recipients regard recovery aid dispute Court Justice already held justified temporal limitation power held Commission sufficient reply order fulfil function limitation period must fixed advance fixing duration detailed rules application coming within powers Community legislature see effect Case 5269 Geigy v Commission 1972 ECR 787 paragraph 21
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal see inter alia judgment A2A v Commission C‑32009 P EUC2011858 paragraph 97
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: New aid therefore subject precautionary review Commission may principle put effect time latter declared compatible Treaty
Answer: Itpr

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Member State concerned provides Commission requisite evidence Commission carry global assessment taking account — addition evidence provided Member State — relevant evidence enabling determine whether Member State took measure question capacity shareholder public authority
Answer: Itpr

Text: applicability private investor test ultimately depends therefore Member State concerned conferred capacity shareholder capacity public authority economic advantage undertaking belonging
Answer: Itpr

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: former company new operating companies form economic unit inter alia restructuring carried constitutes indivisible whole industrial economic point view see effect Intermills v Commission paragraph 12
Answer:

retrieved examples:

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Admittedly stated paragraph 33 applicant must always show requisite legal standard interests might affected granting aid possible showing fact competitive position relation trade unions operating market
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards second third parts ground appeal considered together must recalled accordance Court’s settled caselaw actions failure fulfil obligations brought ground infringement decision ordering recovery unlawful aid Member State encounters unforeseen unforeseeable difficulties becomes aware consequences overlooked Commission must submit problems Commission consideration together proposals suitable amendments decision issue
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: Furthermore General Court stated paragraphs 186 187 judgment appeal Court also consistently held adopting rules conduct announcing publishing henceforth apply cases relate Commission imposes limit exercise aforementioned discretion principle cannot depart rules without found appropriate breach general principles law equal treatment protection legitimate expectations judgments Holland Malt v Commission C‑46409 P EUC2010733 paragraph 46 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 69
Answer: Prec

Text: position would different alteration fact constituted separate aid measure assessed separately would therefore influence assessment Commission already made original aid plan
Answer: Itpr

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: also apparent Court’s case‑law entity owning controlling shareholdings company actually exercises control involving directly indirectly management thereof must regarded taking part economic activity carried controlled undertaking Case C‑22204 Cassa di Risparmio di Firenze Others 2006 ECR I‑289 paragraphs 112 118
Answer:

retrieved examples:

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Article 2 EC Treaty amendment Article 2 EC declares particular task Community ‘to promote … harmonious balanced development economic activities’ ‘a high level employment social protection
Answer: Rule

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Article 1071 TFEU save otherwise provided Treaties aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States incompatible internal market
Answer: Rule

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Court Justice’s jurisdiction appeal confined review findings law pleas argued General Court
Answer: Itpr

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Even circumstances aid granted show liable affect trade Member States distort threaten distort competition Commission must least set circumstances statement reasons decision judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 89 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 49
Answer: Prec

Text: general application derives fact decisions apply objectively determined situations produce legal effects respect category persons envisaged general abstract manner see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 31 17 September 2009 Commission v Koninglijke FrieslandCampina C‑51907 P EUC2009556 paragraph 53 caselaw cited 28 June 2018 Lowell Financial Services v Commission C‑21916 P published EUC2018508 paragraph 42 caselaw cited
Answer: Prec

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case simple separation undertaking two different entities first pursues directly former economic activity second controls first fully involved management would sufficient deprive rules European Union relating State aid practical effect
Answer:

retrieved examples:

Text: Consequently General Court correctly applied Article 841 Rules Procedure rejecting plea ground time
Answer: Rule

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: apparent Article 152 regulation limitation period begin run day unlawful aid awarded beneficiary
Answer: Rule

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: connection must observed context review conducted European Union Courts complex economic assessments made Commission field State aid Courts substitute economic assessment Commission see effect Case C29007 P Commission v Scott 2010 ECR I7763 paragraphs 64 66 caselaw cited
Answer: Prec

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: would enable second entity benefit subsidies advantages granted State means State resources use whole part benefit former interest also economic unit formed two entities Cassa di Risparmio di Firenze Others paragraph 114
Answer:

retrieved examples:

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: reasons given therefore enabled accordance Court’s established caselaw interested parties know grounds upon General Court relied provided Court sufficient material exercise powers review appeal complaint alleging judgment appeal failed give adequate reasons must rejected
Answer: Prec

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: accordance settled caselaw appeal plea directed ground judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Prec

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: provision sets four conditions
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: Thus Member State makes alteration existing aid scheme breach authorisation condition scheme Member State guarantee authorised aid scheme affected alteration advantages granted basis scheme therefore retained
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: accordance case‑law Court apprehension internal difficulties cannot justify failure Member State comply obligations Community law see inter alia Case C‑40497 Commission v Portugal 2000 ECR I‑4897 paragraph 52 Case C‑31099 Italy v Commission cited paragraph 105 Case C‑40400 Commission v Spain 2003 ECR I‑6695 paragraph 55
Answer: Prec

Text: must nonetheless recalled grounds decision General Court reveal infringement EU law operative part judgment seen well founded legal grounds infringement capable leading annulment decision substitution grounds must made judgment 26 July 2017 Council v LTTE C‑59914 P EUC2017583 paragraph 75 caselaw cited
Answer: Prec

Text: Moreover true stated General Court paragraph 66 judgment appeal Autogrill España v Commission paragraph 70 judgment appeal Banco Santander Santusa v Commission Court held paragraph 42 judgment 29 March 2012 3M Italia C‑41710 EUC2012184 fact taxpayers satisfying conditions application measure concerned case could benefit measure could make selective measure
Answer: Prec

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: regards thirdly Commissions claim alternative Court set aside words view paragraph 36 English version judgment appeal clear grounds judgment Court First Instance decide admissibility application basis subjective appraisal interests applicants explained basis rules governing admissibility actions Article 173 Treaty
Answer: Rule

Text: second intervention must liable affect trade Member States
Answer: Class

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: may reveal possible exercise functions relating control direction financial support – going beyond simple placing capital investor – illustrate existence organic functional links entity owning controlling shareholding company controlled company fact members management committee controlling body entity appointed equivalent bodies controlled company see effect Cassa di Risparmio di Firenze Others paragraphs 116 117
Answer:

retrieved examples:

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: appraisal facts General Court therefore constitute save clear sense evidence produced distorted question law subject review Court Justice see inter alia judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78
Answer: Prec

Text: regards condition relating existence selective advantage accordance settled caselaw interventions form whatsoever liable favour undertakings directly indirectly must regarded economic advantages recipient undertaking would obtained normal market conditions considered State aid
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Consequently recovery State aid unlawfully granted purpose restoring previously existing situation cannot principle regarded disproportionate objectives Treaty regard State aids see Tubemeuse cited paragraph 66 Case C‑16995 Spain v Commission 1997 ECR I135 paragraph 47
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: benefit may advantage constituting aid may indeed benefit cannot justify failure recover aid recovery different sum constituting advantage procured unlawful aid question
Answer: Itpr

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: reasons given therefore enabled accordance Court’s established caselaw interested parties know grounds upon General Court relied provided Court sufficient material exercise powers review appeal complaint alleging judgment appeal failed give adequate reasons must rejected
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: also follows function repayment aid general rule save exceptional circumstances Commission exceed bounds discretion recognised caselaw Court asks Member State recover sums granted way unlawful aid since restoring previous situation see Case C‑7597 Belgium v Commission 1999 ECR I‑3671 paragraph 66 Case C‑31099 Italy v Commission 2002 ECR I‑2289 paragraph 99
Answer: Prec

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: follows EC Treaty ECSC Treaty independent treaties consequently EC Treaty secondary legislation enacted basis cannot produce effects areas fall within scope ECSC Treaty see effect Joined Cases 18880 19080 France Others v Commission 1982 ECR 2545 paragraph 31
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: settled case‑law duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer:

retrieved examples:

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: assessment General Court facts evidence cannot challenged appeal court except facts distorted see effect judgment 15 May 2019 CJ v ECDC C‑17018 P published EUC2019410 paragraph 23 caselaw cited relied appellants claim General Court examine evidence adduced take account offer submit additional evidence
Answer: Prec

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Thus respect assessment context appeal General Court’s determinations national law Court Justice jurisdiction determine whether law distorted see judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: regards condition relating existence selective advantage accordance settled caselaw interventions form whatsoever liable favour undertakings directly indirectly must regarded economic advantages recipient undertaking would obtained normal market conditions considered State aid
Answer: Prec

Text: addition must pointed according Article 1bii regulation ‘existing aid’ understood inter alia ‘authorised aid say aid schemes individual aid authorised Commission Council
Answer: Rule

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: According settled caselaw order tax regarded forming integral part aid measure must hypothecated aid relevant national rules sense revenue tax necessarily allocated financing aid direct impact amount aid consequently assessment compatibility aid internal market see inter alia judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 46 caselaw cited 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraph 99
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: follows foregoing appropriate criterion establishing selectivity measure issue consists determining whether measure introduces operators light objective pursued general tax system concerned comparable factual legal situation distinction justified nature general structure system see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 61
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: apparent Court’s established caselaw Article 1071 TFEU draw distinction measures State intervention basis techniques used national authorities see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: ['Prec', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: Thus according caselaw Court tax cannot hypothecated exemption payment tax category undertakings thus even undertakings operate competition undertakings liable pay tax question
Answer: Itpr

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: However Member State provide justification
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: follows rules governing proceedings EU Courts particular Article 21 Statute Court Justice European Union applicable General Court pursuant first paragraph Article 53 Statute Article 441 Rules Procedure General Court version applicable originating application lodged case principle determined delimited parties EU Courts cannot adjudicate ultra petita see effect judgment 10 December 2013 Commission v Ireland Others C‑27212 P EUC2013812 paragraph 27
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 42 order 21 January 2010 Case C‑15009 P Iride Iride Energia v Commission published ECR paragraph 42
Answer:

retrieved examples:

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: must held first Article 4c CS prohibits granting State aid steel coal undertakings without drawing distinction individual aid aid disbursed State aid scheme Article 67 CS refers expressly State aid respect protective measures Commission may authorise pursuant first indent paragraph 2 article favour coal steel undertakings suffer competitive disadvantages general economic policy measures
Answer: Rule

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Article 1073b TFEU ‘the following may considered compatible internal market … aid … remedy serious disturbance economy Member State
Answer: Rule

Text: However European Union Courts must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn Case C1203 P Commission v Tetra Laval 2005 ECR I987 paragraph 39 Commission v Scott paragraph 65
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: follows foregoing appropriate criterion establishing selectivity measure issue consists determining whether measure introduces operators light objective pursued general tax system concerned comparable factual legal situation distinction justified nature general structure system see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 61
Answer: Prec

Text: Secondly also apparent caselaw examination selectivity must carried within context ‘a particular legal regime
Answer: Prec

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: regards first first part Aer Lingus’ single ground appeal noted decisive factor determining whether tax measure classified State aid particular ascertaining whether measure gives rise favourable tax treatment beneficiaries comparison taxpayers effects produced measure see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Next clear Court’s case‑law need prevent cumulative effect aid repaid aid planned regardless whether individual aid aid covered aid scheme issue TWD v Commission caselaw allows Commission make compatibility aid conditional upon prior repayment earlier unlawful aid see effect order Iride Iride Energia v Commission paragraphs 49 50 70
Answer:

retrieved examples:

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: second intervention must liable affect trade Member States
Answer: Class

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: Consequently considering whether private investor test applicable General Court err law focusing analysis fiscal nature means employed French State improvement — view opening electricity market — EDF’s financial situation effects measure question competition
Answer: Itpr

Text: measure accordingly operated de facto discrimination undertakings comparable situation light objective pursued regime case objective putting place generalised taxation resident companies
Answer: Prec

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: Secondly also apparent caselaw examination selectivity must carried within context ‘a particular legal regime
Answer: Prec

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: reality appeal amounts request reexamination application submitted Court First Instance Article 49 EC Statute Court Justice falls outside jurisdiction Court Justice see particular order 25 March 1998 Case C17497 P FFSA Others v Commission 1998 ECR I1303 paragraph 24
Answer: ['Prec', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: absence implementing measures natural legal person although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national court judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 27 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 35 caselaw cited
Answer: Prec

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Similarly term ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 41 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 87
Answer: Prec

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: First Commission must appropriate take account cumulative effect earlier unlawful aid repaid new aid see effect Case C‑35595 P TWD v Commission paragraphs 26 27 second find new aid compatible common market evidence disposal enables reach conclusion see effect order Iride Iride Engergia v Commission paragraph 70
Answer:

retrieved examples:

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Text: therefore follows judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 selectivity tax measure established even measure constitute derogation ordinary tax system integral part system fact remains judgment consistent Court’s settled caselaw cited paragraph 57 judgment effect sufficient order establish selectivity measure derogates ordinary tax system demonstrate measure benefits certain operators others although operators objectively comparable situation light objective pursued ordinary tax system
Answer: Prec

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: already noted paragraphs 83 85 purposes applying private investor test relevant evidence information available developments foreseeable time decision make investment taken
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Commission also takes relevant measure facilitate dialogue ensuring balanced support parties see effect Albany paragraphs 55 58 respect EEC Treaty Agreement social policy concluded Member States European Community exception United Kingdom Great Britain Northern Ireland OJ 1992 C 191 p 91 entry force Treaty Amsterdam
Answer: Prec

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: regard true decision adopts end examination Commission may exercise discretion differentiate beneficiaries aid scheme notified regard certain characteristics display conditions fulfil
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: General Court misconstrued concept ‘new aid’ within meaning Article 1c Regulation 6591999 therefore committed error law
Answer: ['Itpr', 'Rule']

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: According settled case‑law applicant interest bringing proceedings light subject‑matter action action must capable outcome procuring advantage party brought see effect Case C‑5000 P Unión de Pequeños Agricultores v Council 2002 ECR I‑6677 paragraph 23 Case C‑27701 P Parliament v Samper 2003 ECR I‑3019 paragraphs 30 31 order 5 March 2009 Case C‑18308 P Commission v Provincia di Imperia paragraph 19 case‑law cited
Answer: Prec

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: common ground Commission required make complex economic assessment examines whether particular measures described State aid public authorities act way private creditor see Case C52504 P Spain v Lenzing 2007 ECR I9947 paragraph 59
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: General Court correctly pointed paragraph 187 judgment appeal apparent TWD v Commission caselaw Commission decides initiate formal investigation procedure Member State potential beneficiary new aid provide Commission evidence capable showing aid compatible common market obligation also extends need establish new aid earlier unlawful aid incompatible common market repaid cumulative effect
Answer:

retrieved examples:

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid within meaning provision see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56
Answer: Prec

Text: must borne mind allow party put forward first time Court Justice plea law raised Court First Instance would allow bring Court whose jurisdiction appeals limited case wider ambit came Court First Instance
Answer: Itpr

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Also far arguments set alternative 3F seeks put forward separate specific grounds demonstrate Commission infringed principle good administration essentially alleging duration preliminary examination stage unreasonable recalled according Article 1701 Rules Procedure Court Justice subjectmatter proceedings General Court may changed appeal
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: Second recalled Commission required establish aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 8 September 2011 Commission v Netherlands C‑27908 P EUC2011551 paragraph 13 caselaw cited
Answer: Prec

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Commission also takes relevant measure facilitate dialogue ensuring balanced support parties see effect Albany paragraphs 55 58 respect EEC Treaty Agreement social policy concluded Member States European Community exception United Kingdom Great Britain Northern Ireland OJ 1992 C 191 p 91 entry force Treaty Amsterdam
Answer: Prec

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: Information precise unconditional consistent whatever form given constitutes assurances judgment 12 October 2016 Land Hessen v Pollmeier Massivholz C‑24215 P published EUC2016765 paragraph 63
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: must pointed connection order assess measure Article 1062 TFEU Commission required contrary claimed appellant examine whether conditions laid caselaw Altmark particular second fourth conditions met
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: case funds issue could regarded State resource since time public control see judgment 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 36 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: accordance Court’s settled caselaw applicant’s interest bringing proceedings must light purpose action exist action lodged failing action inadmissible
Answer: Prec

Text: latter case may measure raise doubts compatibility common market
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Lastly since clear Court’s case‑law sufficient Commission establish aid issue capable affecting trade Member States distorting competition order Iride Iride Energia v Commission paragraph 72 General Court acted correctly finding Commission required circumstances case carry specific detailed examination advantages derived aid issue referring specifically position AEP ACEA market question relative competitors trends Community trade
Answer:

retrieved examples:

Text: According settled caselaw Court Justice allow party put forward first time Court Justice plea law raised General Court would effect allow party bring Court Justice wider case heard General Court see effect judgments Alliance One International Standard Commercial Tobacco v Commission Commission v Alliance One International Others C‑62810 P C‑1411 P EUC2012479 paragraph 111 Groupe Gascogne v Commission C‑5812 P EUC2013770 paragraph 35
Answer: Prec

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Article 92 Treaty states Save otherwise provided Treaty aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods shall far affects trade Member States incompatible common market
Answer: Rule

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Third must confer advantage recipient
Answer: Class

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw applicant’s interest bringing proceedings must light purpose action exist action lodged failing action inadmissible
Answer: Prec

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: said appellant entitled lodge appeal relying Court Justice grounds arguments arise judgment appeal seek criticise law correctness judgments 29 November 2007 Stadtwerke Schwäbisch Hall Others v Commission C‑17606 P published EUC2007730 paragraph 17 4 March 2021 Commission v Fútbol Club Barcelona C‑36219 P EUC2021169 paragraph 47
Answer: Prec

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part see judgments 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraphs 41 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 82 83 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 74 75 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 54 55
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: follows condition application receipt tax aid may grounds finding aid selective condition leads distinction made undertakings despite fact light objective pursued tax system concerned comparable factual legal situation therefore represents discrimination undertakings excluded
Answer: Itpr

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Article 1062 TFEU provides undertakings entrusted operation services general economic interest subject rules contained Treaties particular rules competition far application rules obstruct performance law fact particular tasks assigned development trade must affected extent would contrary interests Union
Answer: Rule

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: pointed paragraph 77 duty incumbent upon General Court state reasons judgments require address expressly arguments articulated parties reasoning sufficient enables persons concerned know measures question taken provides Court Justice sufficient material exercise powers review
Answer:

retrieved examples:

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: paragraph 120 judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 Court referring inter alia two abovementioned judgments expressly stated position selectivity national measure examination holding case selectivity followed fact undertakings engaged export activities carrying certain investment transactions abroad qualified tax advantage conferred measure
Answer: Prec

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system form part see judgments 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraphs 41 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 82 83 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 74 75 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 54 55
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: provision sets four conditions
Answer: Class

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: extent reaching conclusion Court relied fact measure issue worded form exception rule governing forfeiture losses recalled already pointed paragraph 92 present judgment regulatory technique used cannot decisive purposes determination reference framework
Answer: Itpr

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: must also borne mind far determination reference framework must based objective examination content structure applicable rules national law necessary first stage examination selectivity take account objectives pursued legislature adopting measure examination
Answer: Itpr

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: presupposes action must liable successful procure advantage party bringing judgment 28 May 2013 Abdulrahim v Council Commission C‑23912 P EUC2013331 paragraph 61 caselaw cited
Answer: Prec

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: However Member State provide justification
Answer: Itpr

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: guideline Commission communications relating State aid sector 12 July 1994 23 March 1995 communication 2 February 1996 issued events subject dispute
Answer: Rule

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover clear paragraphs 186 188 judgment appeal General Court set therein interpretation TWD v Commission caselaw
Answer:

retrieved examples:

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: Since determination reference system constitutes starting point comparative examination carried context assessment selectivity aid scheme error made determination necessarily vitiates whole analysis condition relating selectivity see effect judgments 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 107 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraph 46
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: Indeed neither contended established General Court developed reasoning running manifestly counter content provisions German law issue ascribed one provisions scope manifestly light material file see effect judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 81
Answer: Prec

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: regards whether ground well founded according settled caselaw definition aid general subsidy
Answer: Prec

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Second Commission specific grant aid alleged made pursuance previously authorised scheme cannot outset examine directly relation Treaty
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Even though true purposes ECSC Treaty rules apply based domain State aid fundamental requirement legal certainty
Answer: ['Itpr', 'Rule']

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards second condition set Article 230 EC borne mind fact disputed provision nature scope provision general application inasmuch applies traders concerned general prevent individual concern Belgium Forum 187 v Commission paragraph 58 case‑law cited
Answer: Rule

Text: rules applicable investment sugar sector thus established Regulation 178581
Answer: Rule

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Articles 482 Rules Procedure General Court provides new plea law may introduced course proceedings unless based matters law fact come light course procedure see effect judgment 12 November 2009 Case C‑56408 P SGL Carbon v Commission published ECR paragraphs 20 34
Answer:

retrieved examples:

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Similarly basis obliged engage new tariff negotiations supplier sign new agreement order put effect Commission’s decision
Answer: Prec

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards whether ground well founded according settled caselaw definition aid general subsidy
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: case aid derives fact another category economic operators category liable pay tax direct competition liable charge
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: would jeopardise principles protection legitimate expectations legal certainty Italy v Commission cited paragraph 24
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: Applied classification measure aid principle requires statement reasons Commission considers measure concerned falls within scope Article 1071 TFEU
Answer: ['Princ', 'Rule']

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: pointed paragraph 146 appeal plea directed ground included sake completeness judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Itpr

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place regards plea alleging breach conditions laid fourth paragraph Article 230 EC made clear outset Article 4 Regulation 6591999 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid notified compatible common market
Answer:

retrieved examples:

Text: Member State concerned provides Commission requisite evidence Commission carry global assessment taking account — addition evidence provided Member State — relevant evidence enabling determine whether Member State took measure question capacity shareholder public authority
Answer: Itpr

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: effect caselaw simply reimbursement undertaking amount tax required pay breach EU law damages national authorities ordered pay undertakings compensate damage caused constitute State aid
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: EU judicature stage examination admissibility rule definitively competitive relationships applicant beneficiaries national measures assessed decision Commission State aid decision issue see effect judgments 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 28 20 December 2017 Binca Seafoods v Commission C‑26816 P EUC20171001 paragraph 59 direct effect applicant cannot deduced mere potential existence competitive relationship found judgments appeal
Answer: Prec

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 49
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: fourth paragraph Article 263 TFEU natural legal person may conditions laid first second paragraphs article institute proceedings act addressed person direct individual concern regulatory act direct concern entail implementing measures
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer:

retrieved examples:

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: Admittedly stated paragraph 33 applicant must always show requisite legal standard interests might affected granting aid possible showing fact competitive position relation trade unions operating market
Answer: Itpr

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Court Justice already held respect national measure conferring tax advantage general application like measure issue condition relating selectivity fulfilled Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation judgment WDFG paragraph 67
Answer: Prec

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: circumstances Court finds General Court responded requisite legal standard arguments relating principle limitation relied FT disregard requirement state reasons established caselaw cited paragraph 88
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: follows rules governing procedure Courts European Union particular Article 21 Statute Court Article 441 Rules Procedure General Court dispute principle determined circumscribed parties Courts European Union may rule ultra petita
Answer: Rule

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: case Member State Commission must virtue principle sincere cooperation work together good faith view overcoming difficulties fully observing provisions FEU Treaty particular aid see effect judgments 2 July 2002 Commission v Spain C‑49999 EUC2002408 paragraph 24 22 December 2010 Commission v Italy C‑30409 EUC2010812 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: provision sets four conditions
Answer: Class

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: General Court err law third place relying paragraph 122 judgment appeal paragraph 81 judgment Freskot C‑35500 EUC2003298 since Court held paragraph regard previous version Article 5a Law 17901988 version essence identical applicable present dispute legislation ‘clearly established benefits provided ELGA granted State resources imputable State within meaning Court’s caselaw
Answer: ['Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: follows foregoing neither French Republic FT rely principle order prevent recovery unlawful aid see Case C‑14804 Unicredito Italiano 2005 ECR I‑11137 paragraph 104
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments submitted General Court including based facts expressly rejected Court satisfy requirements state reasons second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice requirements recalled paragraph 51 present judgment
Answer: ['Prec', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: regard Court’s established caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 94 caselaw cited
Answer: Prec

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination Commission finds notwithstanding fact measure notified falls within scope Article 871 EC raise doubts compatibility common market Commission adopt decision raise objections Article 43 Regulation 6591999
Answer:

retrieved examples:

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Court Justice’s jurisdiction appeal confined review findings law pleas argued General Court
Answer: Itpr

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 72 73 caselaw cited see also judgments 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 56 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 85
Answer: Prec

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Consequently regulatory technique used cannot decisive purposes determining reference framework see effect judgment WDFG paragraph 76 judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 92
Answer: Prec

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Article 1071 TFEU save otherwise provided Treaties aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States incompatible internal market
Answer: Rule

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: Regarding admissibility crossappeal recalled pursuant second sentence Article 1783 Rules Procedure pleas legal arguments put forward support crossappeal must already stated paragraph 100 present judgment distinct relied reply relating appeal main proceedings
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: follows length preliminary examination procedure constitute indication Commission may doubts regarding compatibility aid question common market length cannot lead conclusion Commission initiated formal investigation procedure see effect Case 8482 Germany v Commission 1984 ECR 1451 paragraphs 14 17 Belgium v Deutsche Post DHL International paragraph 81
Answer: Prec

Text: fact however taken consideration relation obligation recover incompatible aid light principles protection legitimate expectations legal certainty done Commission contested decision declined order recovery aid granted date publication Official Journal European Communities decisions initiate procedure laid Article 882 EC
Answer: ['Princ', 'Rule']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Therefore appraisal facts General Court constitute save clear sense evidence produced distorted question law subject review Court Justice judgments Archer Daniels Midland Archer Daniels Midland Ingredients v Commission C‑39703 P EUC2006328 paragraph 85 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 180
Answer: Prec

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: However classification tax system ‘selective’ conditional upon system designed way undertakings might enjoy selective advantage general subject tax burden undertakings benefit derogating provisions selective advantage may identified difference normal tax burden borne former undertakings judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 91
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Commission adopts decision raise objections declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: Indeed appellant could thus base appeal pleas law arguments already relied Court First Instance appeal would deprived part purpose
Answer: Itpr

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: However accordance second sentence Article 141 Regulation 6591999 Commission shall require recovery aid would contrary general principle EU law
Answer: Rule

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Consequently regulatory technique used cannot decisive purposes determining reference framework see effect judgment WDFG paragraph 76 judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 92
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently General Court correctly applied Article 841 Rules Procedure rejecting plea ground time
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: third place according settled caselaw fact Member State seeks approximate unilateral measures conditions competition particular sector economy prevailing Member States cannot deprive measures question character aid Joined Cases 669 1169 Commission v France 1969 ECR 523 paragraphs 20 21 Case C697 Italy v Commission 1999 ECR I2981 paragraph 21
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation
Answer:

retrieved examples:

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court held paragraphs 29 31 Case C11002 Commission v Council 2004 ECR I6333 intention EC Treaty providing Article 88 EC aid kept constant review monitored Commission finding aid may incompatible common market arrived subject review General Court Court Justice means appropriate procedure Commission’s responsibility set motion
Answer: ['Itpr', 'Prec', 'Rule']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: paragraphs 34 35 judgment Court held since Sardegna Lines concerned Decision 9895 virtue undertaking shipping sector Sardinia potential beneficiary aid scheme Sardinian shipowners also virtue actual beneficiary individual aid granted scheme recovery ordered Commission individually concerned decision action directed decision admissible
Answer: Prec

Text: third place according settled caselaw fact Member State seeks approximate unilateral measures conditions competition particular sector economy prevailing Member States cannot deprive measures question character aid Joined Cases 669 1169 Commission v France 1969 ECR 523 paragraphs 20 21 Case C697 Italy v Commission 1999 ECR I2981 paragraph 21
Answer: Prec

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Thus Member State makes alteration existing aid scheme breach authorisation condition scheme Member State guarantee authorised aid scheme affected alteration advantages granted basis scheme therefore retained
Answer: Itpr

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: remove certain kinds subcategories nonlegislative acts general application scope provision would run counter objective
Answer: Itpr

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: settled caselaw undertaking cannot principle contest Commission decision prohibiting aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme see Joined Cases C1598 C10599 Italy Sardegna Lines v Commission 2000 ECR I8855 paragraph 33 caselaw cited
Answer: Prec

Text: Court held judgments mere fact provisions adopted part common agricultural policy place applicant unfavourable competitive position allow concluded provisions affect applicant’s legal situation line caselaw cannot transposed actions brought competitors beneficiaries State aid
Answer: Prec

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: measure issue conceived aid scheme individual aid Commission establish measure although confers advantage general application confers benefit advantage exclusively certain undertakings certain sectors activity see effect inter alia judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraphs 49 50
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: undertakes initial examination planned aid
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: latter provision decision call upon Member State concerned upon interested parties submit comments within prescribed period must rule exceed one month
Answer:

retrieved examples:

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: settled caselaw undertaking cannot principle contest Commission decision prohibiting aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme see Joined Cases C1598 C10599 Italy Sardegna Lines v Commission 2000 ECR I8855 paragraph 33 caselaw cited
Answer: Prec

Text: applicant seeks annulment decision raise objections must prove existence doubts aid’s compatibility Commission v Kronoply Kronotex paragraph 59
Answer: Prec

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: CIRFS case CIRFS Commission’s interlocutor regard introduction ‘discipline’ concerning aid synthetic fibre sector also extension adaptation actively pursued negotiations Commission prelitigation procedure particular submitting written observations keeping close contact responsible departments Commission
Answer: Prec

Text: According settled caselaw Court persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually way person addressed judgments 15 July 1963 Plaumann v Commission 2562 EUC196317 p 107 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraph 57
Answer: Prec

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: benefit may advantage constituting aid may indeed benefit cannot justify failure recover aid recovery different sum constituting advantage procured unlawful aid question
Answer: Itpr

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: event case State aid notified delay may imputed Commission time learned existence aid incompatible common market
Answer: Itpr

Text: assessment made public creditor grants payment facilities respect debt payable undertaking applying principle private creditor test
Answer: Prec

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Since doubts must trigger initiation formal investigation procedure interested parties referred Article 1h Regulation 6591999 participate must held interested party within meaning latter provision directly individually concerned decision
Answer:

retrieved examples:

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: follows arguments submitted intervener admissible unless fall within framework provided forms order pleas law judgment 7 October 2014 Germany v Council C‑39912 EUC20142258 paragraph 27
Answer: Prec

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: appellants could intervened complainants procedure Commission opened would deprived guarantee option challenging Court First Instance assessment made Commission see effect Case C19891 Cook v Commission 1993 ECR I2487 paragraphs 20 24
Answer: Prec

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: following preliminary examination finds measure notified raises doubts compatibility common market Commission required adopt basis Article 44 Regulation 6591999 decision initiating formal investigation procedure Article 882 EC Article 61 regulation Commission v Kronoply Kronotex paragraph 46 TF1 v Commission paragraph 50 Belgium v Deutsche Post DHL International paragraph 77
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: follows rules governing proceedings EU Courts particular Article 21 Statute Court Justice European Union applicable General Court pursuant first paragraph Article 53 Statute Article 441 Rules Procedure General Court version applicable originating application lodged case principle determined delimited parties EU Courts cannot adjudicate ultra petita see effect judgment 10 December 2013 Commission v Ireland Others C‑27212 P EUC2013812 paragraph 27
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Consequently contrary Scuola Elementare Maria Montessori’s submission principle require Commission attach order recovery every decision declaring aid unlawful incompatible internal market requires take consideration arguments put Member State concerned existence absolute impossibility recovery
Answer: Itpr

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: assessment made public creditor grants payment facilities respect debt payable undertaking applying principle private creditor test
Answer: Prec

Text: Accordingly clear distortion alleged manifestly apparent documents Court arguments Orange fact asking Court carry fresh assessment facts evidence falls outside Court’s jurisdiction
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However appropriate recall position adopted Court judgment Italy Sardegna Lines v Commission regard Commission Decision 9895EC 21 October 1997 concerning aid granted Region Sardinia Italy shipping companies Sardinia OJ 1998 L 20 p 30 required Italian Republic recover beneficiary loans leases question element aid contained
Answer: Prec

Text: apparent paragraphs 53 60 judgment respect national measure conferring tax advantage general application measure issue condition satisfied Commission able demonstrate measure derogation ordinary ‘normal’ tax system applicable Member State concerned thereby introducing actual effects differences treatment operators although operators qualify tax advantage light objective pursued Member State’s tax system comparable factual legal situation
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: regards second conditions say individually concerned act question settled caselaw persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed Case 2562 Plaumann v Commission 1963 ECR 95 107 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 52 Inuit Tapiriit Kanatami Others v Parliament Council paragraph 72
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: regards fourth part ground appeal recalled appellant must pursuant Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court Justice indicate precisely evidence alleged distorted General Court demonstrate errors appraisal view led distortion
Answer: Rule

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: applicability private investor test ultimately depends therefore Member State concerned conferred capacity shareholder capacity public authority economic advantage undertaking belonging
Answer: Itpr

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Rule
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: beneficiaries procedural guarantees provided Article 882 EC Article 61 Regulation 6591999 able ensure guarantees respected must possible challenge European Union judicature decision raise objections see effect Case C‑7803 P Commission v Aktionsgemeinschaft Recht und Eigentum 2005 ECR I‑10737 paragraph 35 caselaw cited Case C‑48706 P British Aggregates v Commission 2008 ECR I‑10515 paragraph 28 Case C‑31907 P 3F v Commission 2009 ECR I‑5963 paragraph 31 caselaw cited
Answer:

retrieved examples:

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: regards purported substitution grounds part General Court sufficient note court exceed powers review substituting assessment Commission since tax differential question fact business tax paid annually provided General Tax Code form integral part reasoning adopted Commission contested decision
Answer: Itpr

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: regards second limb fourth paragraph Article 263 TFEU Court repeatedly held field State aid decisions Commission authorising prohibiting national scheme general application
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: provision sets four conditions
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: must recalled case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents case file judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 20 caselaw cited
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: follows Court seeking case determine whether market position members Aktionsgemeinschaft Recht und Eigentum association set promote collective interests class persons substantially affected aid scheme subject decision question
Answer: Prec

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect inter alia judgment 18 July 2013 PC‑612 EUC2013525 paragraph 18
Answer: Prec

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Secondly paragraphs 89 95 judgment 13 June 2013 HGA Others v Commission C‑63011 P C‑63311 P EUC2013387 Court Justice examined issue whether alteration made original aid scheme breach approval conditions aid scheme constituted alteration existing aid within meaning Article 1c Regulation 6591999 thereby giving rise new unlawful aid
Answer: ['Prec', 'Rule']

Text: Article 1d Regulation 6591999 defines ‘aid scheme’ ‘any act basis without implementing measures required individual aid awards may made undertakings defined within act general abstract manner act basis aid linked specific project may awarded one several undertakings indefinite period time andor indefinite amount
Answer: Rule

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly specific status ‘interested party’ within meaning Article 1h Regulation 6591999 conjunction specific subjectmatter action sufficient distinguish individually purposes fourth paragraph Article 230 EC applicant contesting decision raise objections
Answer:

retrieved examples:

Text: hand tax advantage resulting general measure applicable without distinction economic operators constitute aid see effect inter alia judgment 18 July 2013 PC‑612 EUC2013525 paragraph 18
Answer: Prec

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: appellant alleges distortion evidence General Court must Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court indicate precisely evidence alleged distorted General Court show errors appraisal view led distortion
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: short answer State aid defined Treaty legal concept must interpreted basis objective factors
Answer: ['Itpr', 'Rule']

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: Consequently considering whether private investor test applicable General Court err law focusing analysis fiscal nature means employed French State improvement — view opening electricity market — EDF’s financial situation effects measure question competition
Answer: Itpr

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act see Case C16498 P DIR International Film Others v Commission 2000 ECR I447 paragraph 38 Case C48706 P British Aggregates v Commission 2008 ECR I10515 paragraph 141
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: Infringement proceedings based objective finding Member State failed fulfil obligations EU law see particular judgment 6 October 2009 Commission v Spain C‑56207 EUC2009614 paragraph 18
Answer: Prec

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: noted begin assessing compatibility State aid maritime transport sector aid issue present case social aspects Community guidelines may taken account Commission part overall assessment includes large number considerations various kinds linked particular protection competition Community’s maritime policy promotion Community maritime transport promotion employment see effect Case C‑10698 P Comité d’entreprise de la Société française de production Others v Commission 2000 ECR I‑3659 paragraph 52
Answer: Prec

Text: consequence would national tax rules fall outset outside scope control State aid account sole fact adopted different regulatory technique although adjusting combining various tax rules produce effects law andor fact
Answer: Itpr

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard although applicant contests Commission decision initiate formal investigation procedure must accordance Article 441c Rules Procedure General Court define subjectmatter action application initiating proceedings requirement satisfied requisite legal standard applicant identifies decision seeks annulled
Answer:

retrieved examples:

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: Indeed according settled caselaw grounds judgment General Court disclose infringement EU law operative part shown well founded legal grounds infringement capable bringing setting aside judgment judgments 30 September 2003 Biret International v Council C‑9302 P EUC2003517 paragraph 60 caselaw cited 14 October 2014 Buono Others v Commission C‑1213 P C‑1313 P EUC20142284 paragraph 62 caselaw cited
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: First must intervention State State resources
Answer: Class

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: proof may furnished reference body consistent evidence question whether doubt exists requires investigation circumstances decision raise objections adopted content comparing assessments upon Commission relied decision information available ruled compatibility aid question common market see effect Case C‑19891 Cook v Commission 1993 ECR I‑2487 paragraphs 30 31 Bouygues Bouygues Télécom v Commission paragraph 63 TF1 v Commission paragraph 52 Austria v ScheucherFleisch Others paragraphs 71 72
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: regard fact economic sector subject liberalisation EU level may serve determine aid question real potential effect competition affects trade Member States judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 53 caselaw cited
Answer: Prec

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: regard true decision adopts end examination Commission may exercise discretion differentiate beneficiaries aid scheme notified regard certain characteristics display conditions fulfil
Answer: Itpr

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection direct legal remedy European Union judicature purpose challenging legality regulatory act
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: repaying aid recipient forfeits advantage enjoyed competitors market situation prior payment aid restored see Case C‑35093 Commission v Italy 1995 ECR I‑699 paragraph 22
Answer: Prec

Text: stated paragraph 86 judgment tax reliefs could examined light decision 3 July 1991 refers rules common agricultural policy directly light Article 92 Treaty
Answer: ['Itpr', 'Rule']

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: falls Commission show measure particular creates differences undertakings regard objective measure comparable situation
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: matters little whether application initiating proceedings states seeking annulment ‘a decision raise objections’ – term used Article 43 Regulation 6591999 – decision initiate formal investigation procedure since Commission takes position aspects question means single decision
Answer:

retrieved examples:

Text: General Court recalled paragraph 26 judgment appeal persons decision addressed may claim individually concerned within meaning fourth paragraph Article 263 TFEU decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressedjudgments 15 July 1963 Plaumann v Commission 2562 EUC196317 107 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 72 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 46
Answer: Rule

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: provisions EC Treaty apply alternative situations specific rule ECSC Treaty see particular Case 32885 Deutsche Babcock 1987 ECR 5119 paragraphs 6 14
Answer: ['Prec', 'Rule']

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Joined Cases 6785 6885 7085 Kwekeriij van der Kooy Others v Commission 1988 ECR 219 paragraph 15 Case C‑692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Joined Cases C‑1598 C‑10599 Italy Sardegna Lines v Commission 2000 ECR I‑8855 paragraph 33
Answer: Prec

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: However General Court found paragraphs 158 159 judgment appeal assertions form part necessary grounds decision issue
Answer: Itpr

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Also far arguments set alternative 3F seeks put forward separate specific grounds demonstrate Commission infringed principle good administration essentially alleging duration preliminary examination stage unreasonable recalled according Article 1701 Rules Procedure Court Justice subjectmatter proceedings General Court may changed appeal
Answer: Rule

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 98
Answer: Prec

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: Commission preliminary examination finds doubts raised compatibility common market notified measure far falls within scope Article 871 EC adopt decision raise objections Article 43 Regulation 6591999 Commission v Kronoply Kronotex paragraph 44 TF1 v Commission paragraph 48 Austria v ScheucherFleisch Others paragraph 41
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard first third pleas General Court thus rightly pointed paragraph 81 judgment appeal according settled caselaw General Court interpret action challenging exclusively merits aid assessment decision seeking reality ensure respect procedural rights available applicant Article 882 EC applicant expressly raised plea effect
Answer:

retrieved examples:

Text: First must intervention State State resources
Answer: Class

Text: Article 92 Treaty states Save otherwise provided Treaty aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods shall far affects trade Member States incompatible common market
Answer: Rule

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Joined Cases 6785 6885 7085 Kwekeriij van der Kooy Others v Commission 1988 ECR 219 paragraph 15 Case C‑692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Joined Cases C‑1598 C‑10599 Italy Sardegna Lines v Commission 2000 ECR I‑8855 paragraph 33
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: Court thus held undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Prec

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: However financial situation recipient public undertaking depends means used place advantage however may effected amount undertaking ultimately receives
Answer: Itpr

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: General Court therefore err law concluding paragraph 218 judgment appeal Commission entitled refuse apply setoff one hand amounts paid FT 1991 1993 way fixed levy tax differentials arising result special tax regime established company years 1994 2002
Answer: Itpr

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: circumstances interpretation plea would tantamount redefining subjectmatter action see effect judgment 29 November 2007 Case C‑17606 P Stadtwerke Schwäbisch Hall Others v Commission paragraph 25
Answer:

retrieved examples:

Text: Moreover noted paragraph 78 private investor test applied order determine whether effects economic advantage granted whatever form State resources public undertaking distorts threatens distort competition affects trade Member States
Answer: Itpr

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: reasoning may therefore implicit condition enables persons concerned understand grounds General Court’s judgment provides Court Justice sufficient information exercise powers review appeal judgment Isdin v BialPortela C‑59712 P EUC2013672 paragraph 21
Answer: Prec

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: However prudent alert economic operator could foreseen adoption Community measure likely affect interests cannot plead principle measure adopted see effect Belgium Forum 187 v Commission paragraph 147 case‑law cited
Answer: Prec

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: must also borne mind far determination reference framework must based objective examination content structure applicable rules national law necessary first stage examination selectivity take account objectives pursued legislature adopting measure examination
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court First Instance held inter alia paragraphs 77 79 contested judgment course Commission’s assessment new aid pursuant Article 933 Treaty notified put effect Commission required establish whether aid real impact trade Member States competition whether aid could affect trade
Answer: Rule

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: According settled caselaw obligation state reasons owed General Court Article 36 Statute Court Justice applies General Court virtue first paragraph Article 53 Statute Article 81 Rules Procedure General Court requires disclose clearly unequivocally reasoning followed way enable persons concerned ascertain reasons decision taken Court Justice exercise power review see inter alia Case C‑28008 P Deutsche Telekom v Commission 2010 ECR I‑9555 paragraphs 135 136 caselaw cited
Answer: ['Prec', 'Rule']

Text: settled caselaw adoption order recover unlawful aid logical normal consequence finding unlawful
Answer: Prec

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: However also follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system see effect judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 77
Answer: ['Itpr', 'Prec']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: Third must confer advantage recipient
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: payment facilities constitute State aid purposes Article 1071 TFEU taking account significance economic advantage thereby granted recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor seeking recover sums due debtor financial difficulty see effect Spain v Commission paragraph 46 DM Transport paragraph 30 Commission v EDF paragraph 79
Answer: ['Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: use arguments nothing however bring change subjectmatter action conditions admissibility see effect 3F v Commission paragraph 35
Answer:

retrieved examples:

Text: application tax exemption extent depend tax revenue
Answer: Itpr

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: Consequently given Article 1 Third Steel Aid Code prohibited aid aid specific steel sector Commission could implicitly withdraw 1971 Decision
Answer: Rule

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: rules applicable investment sugar sector thus established Regulation 178581
Answer: Rule

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: However ground judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 must read context set grounds forms part set paragraphs 87 108 judgment
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: said regards analysis substance Commission’s single ground appeal noted first obligation Member State concerned abolish recovery aid considered Commission incompatible single market purpose according Court’s established caselaw restore situation aid granted see effect judgment 4 April 1995 Commission v Italy C‑35093 EUC199596 paragraph 21 caselaw cited
Answer: Prec

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: Third must confer advantage recipient
Answer: Class

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: event must borne mind mere fact measure issue general nature may priori benefit undertakings subject corporate tax mean cannot selective
Answer: Itpr

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Even though true purposes ECSC Treaty rules apply based domain State aid fundamental requirement legal certainty
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: contrary existence doubts concerning compatibility precisely evidence must adduced order show Commission required initiate formal investigation procedure Article 882 EC Article 61 Regulation 6591999
Answer:

retrieved examples:

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned able demonstrate differentiation justified since flows nature general structure system measures form part see effect inter alia judgments 29 April 2004 Netherlands v Commission C‑15901 EUC2004246 paragraphs 42 43 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraphs 64 65 29 March 2012 3M Italia C‑41710 EUC2012184 paragraph 40
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: particular appellants effectively challenge finding paragraph 79 judgment appeal exceptional circumstances taken account present case far consideration envisaged judgment 11 July 1996 SFEI Others C‑3994 EUC1996285 order establish certain cases repayment State aid sought national court inappropriate
Answer: Prec

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: However fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see Geigy v Commission cited paragraphs 20 21 Joined Cases C‑7400 P C‑7500 P Falck Acciaierie di Bolzano v Commission 2002 ECR I‑7869 paragraph 140
Answer: Prec

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Lastly regards argument General Court failed regard obligation state reasons relation principle limitation settled caselaw court thereby required provide account follows exhaustively point point reasoning articulated parties case
Answer: Prec

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: case aid derives fact another category economic operators category liable pay tax direct competition liable charge
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Article 1h Regulation 6591999 ‘interested party’ means inter alia person undertaking association undertakings whose interests might affected granting aid say particular competing undertakings beneficiary aid
Answer:

retrieved examples:

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must recalled accordance Court’s settled caselaw Article 1071 TFEU covers financial means public authorities may actually support undertakings irrespective whether means permanent assets State
Answer: ['Prec', 'Rule']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Indeed necessary make distinction one hand adoption aid scheme namely present case special tax regime grant annual aid FT basis regime precise total amount depended certain external factors
Answer: Itpr

Text: far concerns third criterion characterising measure State aid settled caselaw measures whatever form likely directly indirectly favour certain undertakings regarded economic advantage recipient undertaking would obtained normal market conditions regarded State aid see judgment 30 June 2016 Belgium v Commission C‑27015 P EUC2016489 paragraph 34
Answer: Prec

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: case prohibition applies aid measure introduced alteration
Answer: Itpr

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: fourth paragraph Article 263 TFEU natural legal person may conditions laid first second paragraphs article institute proceedings act addressed person direct individual concern regulatory act direct concern entail implementing measures
Answer: Rule

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: According settled caselaw relating Article 253 EC applied Article 15 CS statement reasons required act adverse effects must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable Court carry review
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: words term covers indeterminate group persons see effect Case 32382 Intermills v Commission 1984 ECR 3809 paragraph 16
Answer:

retrieved examples:

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Court held nature scheme preclude finding measure concerned selective contrary ruling General Court since condition relating selectivity broader scope extends measures effects favour certain undertakings case ‘offshore’ companies account specific features characteristic undertakings
Answer: Prec

Text: Third must confer selective advantage recipient
Answer: Class

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: therefore clearly apparent wording paragraph 20 practice directions state ‘the appeal … unless special circumstances exceed 25 pages’ recital set absolute limitation number pages admissibility appeal subject merely provides recommendation regard parties
Answer: Itpr

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: caselaw reflects fact beneficiary aid scheme satisfies conditions national law eligible scheme request national authorities grant aid would granted unconditional decision declaring scheme compatible internal market contest national courts measure refusing request pleading invalidity Commission’s decision declaring scheme incompatible internal market compatible market subject compliance commitments entered Member State concerned order cause courts refer questions Court preliminary ruling validity see effect judgment 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 36 59 order 15 January 2015 Banco Bilbao Vizcaya Argentaria Telefónica v Commission C‑58713 P C‑58813 P published EUC201518 paragraphs 49 65
Answer: ['Itpr', 'Prec']

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: Court also held absence overriding public interest Commission infringed superior rule law fails couple repeal set rules transitional measures protection expectations trader might legitimately derived Community rules Belgium Forum 187 paragraph 149 case‑law cited
Answer: Prec

Text: First remembered European Union union based rule law acts institutions subject review compatibility particular Treaties general principles law fundamental rights Inuit Tapiriit Kanatami Others v Parliament Council paragraph 91
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: necessary therefore advantage granted selectively liable place certain undertakings favourable situation others
Answer: Itpr

Text: Regulation 86690 sets conditions Guidance Section EAGGF helps objectives regional cohesion common agricultural policy
Answer: Rule

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: implementation matter Member States persons may plead invalidity basic act concerned national courts cause refer questions Court preliminary ruling Article 267 TFEU judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 29 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 37 caselaw cited
Answer: ['Prec', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: consequence provision rule possibility undertaking direct competitor beneficiary aid requires raw material production process categorised interested party provided undertaking demonstrates interests could adversely affected grant aid
Answer:

retrieved examples:

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Prec', 'Rule']

Text: third place regards first part decision issue true according settled caselaw Court recovery order individual concern beneficiaries aid scheme question order adopted exposed risk benefits received recovered therefore members restricted class see effect judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 33 35 29 April 2004 Italy v Commission C‑29800 P EUC2004240 paragraph 39 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 56
Answer: Prec

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: fact however taken consideration relation obligation recover incompatible aid light principles protection legitimate expectations legal certainty done Commission contested decision declined order recovery aid granted date publication Official Journal European Communities decisions initiate procedure laid Article 882 EC
Answer: ['Princ', 'Rule']

Text: hand purpose aid recovery seek compensation individual harm kind reestablish market question situation aid granted
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: regard selectivity tax measure cannot assessed basis reference framework consisting provisions national law Member State concerned artificially taken broader legislative framework judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 103
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: respect must held regards State aid falling within scope EC Treaty Article 101 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 93 EC Treaty OJ 1999 L 83 p 1 provides Commission possession information whatever source regarding alleged unlawful aid examine information without delay
Answer: Rule

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: According reasoning existence derogation exception reference framework identified Commission cannot establish measure issue favours ‘certain undertakings production certain goods’ within meaning provision measure available priori undertaking directed particular category undertakings would undertakings favoured measure category economic transactions
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: purpose necessary undertaking establish requisite legal standard aid likely specific effect situation see effect 3F v Commission paragraph 33
Answer:

retrieved examples:

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: addition obligation state reasons require General Court provide account follows exhaustively onebyone arguments put forward parties case General Court’s reasoning may therefore implicit condition enables persons concerned know upheld arguments provides Court Justice sufficient material exercise power review order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 28
Answer: Prec

Text: Court Justice General Court cannot therefore circumstances substitute reasoning author contested act judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 4 June 2020 Hungary v Commission C‑45618 P EUC2020421 paragraph 70 caselaw cited
Answer: Prec

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: General Court recalled paragraph 185 judgment appeal according settled caselaw statement reasons required Article 296 TFEU must appropriate act issue must disclose clear unequivocal fashion reasoning followed institution adopted measure question way enable persons concerned ascertain reasons measure enable Court European Union exercise power review
Answer: ['Prec', 'Rule']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: one hand Court already held question whether tax integral part aid financed tax depends existence competitive relationship person liable pay tax beneficiary aid whether tax hypothecated aid question relevant national legislation see effect judgment 22 December 2008 Régie Networks C‑33307 EUC2008764 paragraphs 93 99
Answer: ['Itpr', 'Prec']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However accordance second sentence Article 141 Regulation 6591999 Commission shall require recovery aid would contrary general principle EU law
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: matters regard fact measure irrespective form legislative means used effect placing recipient undertakings position favourable undertakings although undertakings comparable factual legal situation light objective pursued tax system concerned
Answer: Itpr

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: According settled caselaw Court classification ‘State aid’ within meaning Article 1071 TFEU requires conditions set provision fulilled
Answer:

retrieved examples:

Text: However concept ‘reference framework’ refers first step assessment condition relating selectivity advantage according caselaw Court constituent factor concept ‘State aid’ within meaning Article 1071 TFEU judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 74 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54
Answer: ['Prec', 'Rule']

Text: Since determination reference system constitutes starting point comparative examination carried context assessment selectivity aid scheme error made determination necessarily vitiates whole analysis condition relating selectivity see effect judgments 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 107 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraph 46
Answer: Prec

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: However also clear settled caselaw conditions measure must meet order treated ‘aid’ purposes Article 87 EC met recipient public undertaking could circumstances correspond normal market conditions obtain advantage made available State resources
Answer: ['Prec', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: settled caselaw statement reasons required Article 296 TFEU must appropriate measure issue must disclose clear unequivocal fashion reasoning followed institution adopted measure way enable persons concerned ascertain reasons enable competent Court European Union exercise jurisdiction review legality judgment 29 September 2011 Elf Aquitaine v Commission C‑52109 P EUC2011620 paragraph 147 caselaw cited
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: stated recital 14 preamble regulation limitation period established reasons legal certainty
Answer: Rule

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: follows since resources public undertakings subject control State therefore disposal resources fall within scope concept ‘State resources’ within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: Second regards appellants interest bringing proceedings part contested decision relating tax reliefs clear caselaw Court Justice Commission points individual grants aid general aid scheme approved Commission meet conditions scheme constitute existing aid need notified Italy v Commission cited paragraphs 21 26
Answer: Prec

Text: First noted Practice directions parties indicative binding force
Answer: Itpr

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: First must intervention State State resources
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Class', 'Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Thus first must intervention State State resources
Answer:

retrieved examples:

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned thirdly able demonstrate differentiation justified since flows nature general structure system measures form part see effect judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 52 see also judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 58 caselaw cited
Answer: Prec

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: recalled Van der Kooy Landbouwschap negotiated supplier gas preferential tariff challenged Commission also one signatories agreement establishing tariff
Answer: Prec

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: sufficient absence rights issue would possible undertaking perform particular tasks entrusted maintenance rights necessary enable holder perform tasks general economic interest assigned economically acceptable conditions judgment 15 November 2007 International Mail Spain C‑16206 EUC2007681 paragraph 35 caselaw cited
Answer: Prec

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: must noted regard Article 921 Treaty defines aid regulated aid granted Member State State resources form whatsoever distorts threatens distort competition favouring certain undertakings production certain goods far affects trade Member States
Answer: Rule

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: Third must confer selective advantage recipient
Answer: Class

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: affirmation part General Court based correct interpretation Article 871 EC see Case 17373 Italy v Commission 1974 ECR 709 paragraph 34 notwithstanding fact referred incorrectly regard judgment Case C‑6602 Italy v Commission
Answer: ['Prec', 'Rule']

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second intervention must liable affect trade Member States
Answer:

retrieved examples:

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: Furthermore accordance Article 172 rules party relevant case General Court may submit document separate response crossappeal according Article 1781 3 second sentence Rules Procedure must seek set aside whole part judgment appeal basis pleas law arguments separate relied response
Answer: Rule

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: decision individual concern natural legal person within meaning provision essential condition locus standi proceedings seeking judicial review Community act proceedings inadmissible inadmissibility therefore constitutes ground involving question public policy may even must raised motion Community judicature see regard party interest bringing maintaining appeal Case C‑1993 P Rendo Others v Commission 1995 ECR I‑3319 paragraph 13
Answer: Prec

Text: Third must confer advantage recipient
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: regards fourth part ground appeal recalled appellant must pursuant Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court Justice indicate precisely evidence alleged distorted General Court demonstrate errors appraisal view led distortion
Answer: Rule

Text: Admittedly argued Commission follows caselaw Court one hand acknowledges actual recipients individual aid granted aid scheme incompatible internal market individually concerned Commission decision declaring scheme incompatible internal market ordering recovery hand precludes applicant regarded individually concerned merely potential beneficiary scheme
Answer: ['Itpr', 'Prec']

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: provision sets four conditions
Answer: Class

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: regards condition advantage must granted directly indirectly State resources must recalled measures involving transfer State resources may fall within concept ‘aid’ within meaning Article 1071 TFEU see inter alia judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 36 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 34 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 19
Answer: ['Prec', 'Rule']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: According Court’s settled caselaw EU competition law particular prohibition Article 1071 TFEU applies activities undertakings
Answer: ['Prec', 'Rule']

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: However requirement General Court give reasons decisions cannot interpreted meaning obliged respond detail every single argument advanced applicant particularly argument sufficiently clear precise see inter alia Joined Cases C‑12006 P C‑12106 P FIAMM Others v Council Commission 2008 ECR I‑6513 paragraph 91 caselaw cited
Answer: Prec

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: hand General Court rightly pointed paragraph 206 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: regard particular unlawful aid granted form tax advantage also Court’s settled caselaw recovery aid means transactions actually carried recipients aid question must subject tax treatment recipients would received absence unlawful aid see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 119
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: must borne mind according settled caselaw concept ‘State aid’ refer State measures differentiate undertakings therefore prima facie selective differentiation arises nature overall structure system part judgments Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 145 caselaw cited BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 101
Answer: Prec

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: third must confer selective advantage recipient
Answer:

retrieved examples:

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Admittedly appellants rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: However natural legal persons may claim contested provision individual concern affects reason certain attributes peculiar reason circumstances differentiated persons Belgium Forum 187 v Commission paragraph 59
Answer: Prec

Text: event situation private investors cannot treated equivalent resident undertakings benefit measure issue
Answer: Itpr

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: According caselaw Court Justice infringement principle protection legitimate expectations established necessary EU institution giving citizen precise assurances led person entertain justified expectations
Answer: Prec

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: particular clear caselaw order assess whether measure would adopted normal market conditions private investor situation close possible State benefits obligations linked situation State shareholder — exclusion linked situation public authority — taken account see effect Case 23484 Belgium v Commission 1986 ECR 2263 paragraph 14 Case 4085 Belgium v Commission 1986 ECR 2321 paragraph 13 Joined Cases C27892 C28092 Spain v Commission 1994 ECR I4103 paragraph 22 Case C33499 Germany v Commission 2003 ECR I1139 paragraph 134
Answer: Prec

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Third order determine whether measure challenged entails implementing measures reference made exclusively subjectmatter action applicant seeks partial annulment act solely implementing measures part act may entail must case may taken consideration
Answer: Itpr

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court accepted Albany restrictions competition inherent collective agreements organisations representing employers workers
Answer: Prec

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: article also provides general rule applicable save otherwise provided Regulation
Answer: Rule

Text: regard may added Court previously ruled tax measure solely undertakings carried specified transactions benefited undertakings sector carry transactions could classified selective need assess whether measure greater benefit large undertakings see effect judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraphs 47 50
Answer: Prec

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: arguments cannot however upheld since apparent caselaw question whether selective advantage complies principle proportionality arises third stage examination selectivity examines whether advantage justified nature general scheme tax system Member State concerned
Answer: ['Prec', 'Princ']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class']
ground truth: Class
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fourth must distort threaten distort competition judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer:

retrieved examples:

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: follows reading grounds measure issue judgment take form tax advantage derogated ordinary tax system rather involved application ‘general’ tax scheme based criteria also general
Answer: Prec

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: connection recalled follows first paragraph Article 21 Statute Court Justice read conjunction Article 441c Rules Procedure General Court application initiating proceedings must contain inter alia summary pleas law based
Answer: ['Itpr', 'Rule']

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: however examine effects alteration original aid scheme
Answer: Prec

Text: regulatory act directly affects legal situation natural legal person without requiring implementing measures person could denied effective judicial protection legal remedy EU judicature purpose challenging lawfulness regulatory act
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: According Court’s wellestablished caselaw appeal complaints directed ground included judgment General Court purely sake completeness must immediately dismissed ineffective since cannot lead judgment appeal set aside see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 75 caselaw cited
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: contrast Court held contested measure affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders see Case 1182 PiraikiPatraiki Others v Commission 1985 ECR 207 paragraph 31 Case C15288 Sofrimport v Commission 1990 ECR I‑2477 paragraph 11 Belgium Forum 187 v Commission paragraph 60
Answer: Prec

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Third must confer advantage recipient
Answer: Class

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Albany International BV undertaking textile sector refused pay fund contributions certain period ground compulsory affiliation fund virtue contributions claimed inter alia contrary Article 851 Treaty
Answer: ['Prec', 'Rule']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Text: present case far actions brought Mr Ferracci Scuola Elementare Maria Montessori sought annulment first part decision issue must considered Advocate General observes point 69 Opinion materialisation legal effects decision order recovery aid found unlawful incompatible internal market subject first part need implementing measures could subject judicial review EU judicature national courts
Answer: ['Itpr', 'Prec', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: appellant alleges distortion evidence General Court must Article 256 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure Court indicate precisely evidence alleged distorted General Court show errors appraisal view led distortion
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: ['Class', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: concept ‘aid’ embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 30
Answer:

retrieved examples:

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: principle legal certainty – one general principles European Union law – requires rules law clear precise predictable effect interested parties ascertain position situations legal relationships governed European Union law see effect Case C‑6393 Duff Others 1996 ECR I569 paragraph 20 Case C‑7606 P Britannia Alloys Chemicals v Commission 2007 ECR I‑4405 paragraph 79 Case C‑15807 Förster 2008 ECR I‑8507 paragraph 67
Answer: ['Prec', 'Princ']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: Finally State aid granted undertaking falling within scope ECSC Treaty identical anticompetitive effects regardless whether constitutes individual aid aid granted State aid scheme specific coal steel sector
Answer: Itpr

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: limb without subjecting admissibility actions annulment brought natural legal persons condition individual concern allows actions brought ‘regulatory acts’ entail implementing measures direct concern applicant see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraph 57
Answer: Prec

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: However claimed Commission concept State aid corresponds objective situation cannot depend conduct statements institutions Commission v Ireland Others paragraph 72
Answer: Prec

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: implementation matter Member States persons may plead invalidity basic act issue national courts tribunals cause latter request preliminary ruling Court Justice pursuant Article 267 TFEU Case C58311 P Inuit Tapiriit Kanatami Others v Parliament Council 2013 ECR paragraph 93
Answer: ['Prec', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70 caselaw cited
Answer:

retrieved examples:

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: According settled case‑law correctly cited Court First Instance paragraph 169 contested judgment abolishing unlawful aid means recovery logical consequence finding unlawful
Answer: Prec

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: However Court stated State measure must regarded compensation services provided recipient undertakings order discharge public service obligations undertakings enjoy real financial advantage measure thus effect putting favourable competitive position undertakings competing measure caught Article 1071 TFEU see judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 87
Answer: Prec

Text: provisions EC Treaty apply alternative situations specific rule ECSC Treaty see particular Case 32885 Deutsche Babcock 1987 ECR 5119 paragraphs 6 14
Answer: ['Prec', 'Rule']

Text: Moreover Article 15 Regulation 6591999 provides recovery illegal aid subject limitation period 10 years beginning day granted
Answer: Rule

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: Consequently appears private investor test could applicable Commission duty ask Member State concerned provide relevant information enabling determine whether conditions governing applicability application test met cannot refuse examine information unless evidence produced established adoption decision make investment question
Answer: Itpr

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Consequently must considered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU extends nonlegislative acts general application
Answer: ['Itpr', 'Rule']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: undertakes initial examination planned aid
Answer: Itpr

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: Indeed appellant could thus base appeal pleas law arguments already relied General Court appeal would deprived part purpose see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 27 caselaw cited
Answer: ['Itpr', 'Prec']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec', 'Rule']
ground truth: ['Prec', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: public creditor grants payment facilities respect debt payable undertaking assessment made applying principle private creditor test judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: stated paragraphs 59 60 recipient aid cannot principle rely considerations based principle protection legitimate expectations aid question notified Commission
Answer: ['Itpr', 'Princ']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: noted Commission national courts give definitive decision claim reimbursement tax alleged unlawful light law Member State concerned contrary provisions EU law Articles 107 108 TFEU necessary court obtained Court Justice way reference preliminary ruling clarification may necessary scope interpretation EU law
Answer: ['Itpr', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: case public undertakings assessment made applying principle private investor test see effect Case C30388 Italy v Commission 1991 ECR I1433 paragraph 20 Case C48299 France v Commission 2002 ECR I4397 paragraphs 68 70 Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 91 caselaw cited
Answer: Prec

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant see effect Case C36795 P Commission v Sytraval Brink’s France 1998 ECR I1719 paragraph 67 Case C26597 P VBA v Florimex Others 2000 ECR I2061 paragraph 114 Commission v Ireland Others paragraph 40
Answer: Prec

Text: contrast appellant’s action annulment Court First Instance complaining Commission failed initiate formal review procedure provided Article 882 EC ultimately aiming safeguarding procedural rights conferred provision application annulment Aktionsgemeinschaft Recht und Eigentum concerned Commission decision terminating procedure
Answer: ['Prec', 'Rule']

Text: context must stated preliminary point determination reference framework must carried following exchange arguments Member State concerned must follow objective examination content structure specific effects applicable rules national law State
Answer: Itpr

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Even action annulment Commission decision raise objections hence initiate formal review procedure Article 882 EC held admissible applicant shows party concerned within meaning provision stricter criteria defined line caselaw following Plaumann applicable case interpret caselaw cited preceding paragraph referring person made complaint Commission would amount depriving substance caselaw considered connection first ground appeal cited paragraph 30 order appeal relating effect applicant’s competitive position
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: regards admissibility arguments evidence submitted support part single ground appeal consideration – admissibility contested Commission ground arguments advanced support appellant’s claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: Consequently recovery State aid unlawfully granted purpose restoring previously existing situation cannot principle regarded disproportionate objectives Treaty regard State aids see Tubemeuse cited paragraph 66 Case C‑16995 Spain v Commission 1997 ECR I135 paragraph 47
Answer: ['Prec', 'Rule']

Text: circumstances General Court correct hold paragraph 323 judgment appeal finding existence aid depended number ‘circumstances unrelated to’ special tax regime fact business tax charged annually level tax rates voted year authorities territory FT establishments
Answer: Itpr

Text: Third must confer advantage recipient
Answer: Class

Text: examination therefore principle requires prior definition reference framework within measure concerned fits
Answer: Itpr

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regard Court held numerous occasions objective pursued measures State intervention sufficient exclude measures outright classification ‘aid’ purposes Article 107 TFEU since provision distinguish measures State intervention reference causes aims defines relation effects see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraphs 84 85 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 48
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: test applicable among factors Commission required take account purposes establishing whether aid exists see effect Case C34296 Spain v Commission 1999 ECR I2459 paragraph 46 Case C25697 DM Transport 1999 ECR I3913 paragraph 24 Commission v EDF paragraphs 78 103
Answer: Prec

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly private creditor test exception applies Member State requests constituent elements State aid incompatible common market laid Article 1071 TFEU exist
Answer:

retrieved examples:

Text: Natural legal persons unable conditions admissibility fourth paragraph Article 263 TFEU challenge EU regulatory act directly EU judicature protected application act ability challenge implementing measures act entails judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 28 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 36 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: applicability private investor test ultimately depends therefore Member State concerned conferred capacity shareholder capacity public authority economic advantage undertaking belonging
Answer: Itpr

Text: addition paragraphs 80 81 judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court recalled fact recipient undertakings belong various economic sectors sufficient call question selective nature measure concerned held potentially selective nature measure issue way called question fact essential condition obtaining tax advantage conferred measure economic transaction particularly entirely financial transaction available regardless nature business recipient undertakings
Answer: Prec

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: addition settled caselaw Court distortion must obvious documents Court’s file without need carry new assessment facts evidence judgments Lafarge v Commission C‑41308 P EUC2010346 paragraph 16 caselaw cited Austria v ScheucherFleisch Others C‑4710 P EUC2011698 paragraph 59 caselaw cited
Answer: ['Itpr', 'Prec']

Text: First order determine whether measure although applying generally set economic operators effect ultimately conferring advantage certain undertakings examined apparent caselaw recalled paragraph 41 present judgment whether certain undertakings favoured others light objective pursued legal regime concerned comparable factual legal situation
Answer: Prec

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: According settled caselaw procedure Article 882 EC essential whenever Commission serious difficulties determining whether aid compatible common market
Answer: ['Prec', 'Rule']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: regards second third parts decision issue Commission found Article 1494 TUIR exemption IMU scheme constitute State aid within meaning Article 1071 TFEU must recalled Court indeed repeatedly held beneficiaries aid scheme national provisions establishing scheme measures implementing provisions tax notice constitute implementing measures entailed decision declaring aid scheme incompatible internal market declaring compatible internal market subject compliance commitments entered Member State concerned see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 35 36 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 52 53 27 February 2014 Stichting Woonlinie Others v Commission C‑13312 P EUC2014105 paragraphs 39 40
Answer: ['Prec', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Court First Instance’s interpretation Albany paragraph 32 order appeal must observed Albany case concerned collective agreement establishing supplementary pension scheme managed pension fund textile industry sector affiliation could made compulsory public authorities
Answer: Prec

Text: Article 118 Rules Procedure Court Justice Article 422 rules prohibits generally introduction new pleas law course procedure applies procedure Court Justice appeal decision Court First Instance
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: Contrary General Court’s assertion paragraphs 59 62 judgment appeal Autogrill España v Commission paragraphs 63 66 judgment appeal Banco Santander Santusa v Commission indication contrary regards analysis condition relating selectivity tax measure may deduced judgment 19 September 2000 Germany v Commission C‑15698 EUC2000467
Answer: ['Itpr', 'Prec']

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: addition must pointed according Article 1bii regulation ‘existing aid’ understood inter alia ‘authorised aid say aid schemes individual aid authorised Commission Council
Answer: Rule

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: Court Justice held measure measure issue designed facilitate exports may regarded selective benefits undertakings carrying crossborder transactions particular investment transactions disadvantage undertakings comparable factual legal situation light objective pursued tax system concerned carry transactions kind within national territory judgment WDFG paragraph 119
Answer: Prec

Text: According caselaw measure granted State resources puts recipient undertaking favourable financial situation competitors reason distorts threatens distort competition affects trade Member States excluded outright categorised ‘aid’ purposes Article 87 EC aims pursued State see effect Case C697 Italy v Commission 1999 ECR I2981 paragraph 15 Case C15698 Germany v Commission 2000 ECR I6857 paragraph 25 caselaw cited Joined Cases C7109 P C7309 P C7609 P Comitato ‘Venezia vuole vivere’ Others v Commission 2011 ECR I4727 paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 28 General Court fully entitled refer paragraph 135 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Court First Instance held inter alia paragraphs 77 79 contested judgment course Commission’s assessment new aid pursuant Article 933 Treaty notified put effect Commission required establish whether aid real impact trade Member States competition whether aid could affect trade
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Moreover stated paragraph 33 excluded trade union may regarded ‘concerned’ within meaning Article 882 EC shows interests members might affected granting aid
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Rule']
ground truth: ['Itpr', 'Rule']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: fact test applicable among factors Commission required take account purposes establishing whether aid exists see effect judgments 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 103 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 32
Answer:

retrieved examples:

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: regard noted distortion must obvious documents Court’s file without need carry new assessment facts evidence judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 80
Answer: Prec

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: provision sets four conditions
Answer: Class

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: appellant therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: regard recalled judgment Court held essence case asymmetrical tax liability one two categories competing traders liable pay tax traders liable pay tax may plead illegality
Answer: Prec

Text: reasoning may therefore implicit condition enables persons concerned know measures question taken provides competent court sufficient material exercise power review see Case C‑10504 P Nederlandse Federatieve Vereniging voor de Groothandel op Electrotechnisch Gebied v Commission 2006 ECR I‑8725 paragraph 72 Case C‑306 P Groupe Danone v Commission 2007 ECR I‑1331 paragraph 46
Answer: Prec

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: Article 871 EC distinguish measures State intervention reference causes aims defines relation effects Comitato ‘Venezia vuole vivere’ Others v Commission paragraph 94 caselaw cited
Answer: ['Prec', 'Rule']

Text: regard condition concerning distortion competition recalled General Court paragraph 188 judgment appeal clear caselaw Court Justice principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgments 19 September 2000 Germany v Commission C‑15698 EUC2000467 paragraph 30 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 55
Answer: Prec

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: Since Commission objected admissibility first limb ground concerned questions fact noted admittedly assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined judgments 16 March 1978 Unicme Others v Council 12377 EUC197873 paragraph 16 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 47 caselaw cited
Answer: Prec

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: far Scuola Elementare Maria Montessori also bases first part first ground appeal principle sincere cooperation must recalled Article 43 TEU principle applies throughout procedure examination measure reference provisions EU law State aid see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 147 caselaw cited 21 December 2016 Club Hotel Loutraki Others v Commission C‑13115 P EUC2016989 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: contrast decision affects group persons identified identifiable measure adopted reason criteria specific members group persons might individually concerned measure inasmuch form part limited class traders judgments 13 March 2008 Commission v Infront WM C‑12506 P EUC2008159 paragraph 71 caselaw cited 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraph 59
Answer: Prec

Text: objective attained aid question together appropriate default interest repaid recipient words undertakings actually enjoyed benefit
Answer: Itpr

Text: Thus respect assessment context appeal General Court’s findings national law field State aid constitute findings fact Court Justice jurisdiction determine whether law distorted
Answer: Itpr

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: must held first Article 4c CS prohibits granting State aid steel coal undertakings without drawing distinction individual aid aid disbursed State aid scheme Article 67 CS refers expressly State aid respect protective measures Commission may authorise pursuant first indent paragraph 2 article favour coal steel undertakings suffer competitive disadvantages general economic policy measures
Answer: Rule

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Itpr']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: result appears private creditor test might applicable Commission ask Member State concerned provide relevant information enabling determine whether conditions applying test satisfied judgment 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 33
Answer:

retrieved examples:

Text: party may therefore put forward first time Court Justice plea could raised General Court raised since would allow bring Court Justice whose jurisdiction appeals limited case wider ambit came General Court see judgment 29 September 2011 Case C‑52009 P Arkema v Commission yet published ECR paragraph 64 caselaw cited
Answer: Prec

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: must recalled Article 173 Treaty virtue Court Justice review legality Community acts provides natural legal person may grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers institute proceedings decision addressed person decision although form regulation decision addressed another person direct individual concern former
Answer: Rule

Text: Third must confer advantage recipient
Answer: Class

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: confirmed fact reference made subsequent judgments Court restate principle see inter alia judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 73 29 March 2012 3M Italia C‑41710 EUC2012184 paragraph 39
Answer: Prec

Text: end FEU Treaty established Articles 263 TFEU 277 TFEU one hand Article 267 TFEU complete system legal remedies procedures designed ensure judicial review legality European Union acts entrusted review European Union judicature Inuit Tapiriit Kanatami Others v Parliament Council paragraphs 90 92
Answer: ['Itpr', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: contrast provided appellant challenges interpretation application EU law General Court points law examined first instance may discussed course appeal
Answer: Itpr

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Furthermore pointed paragraph 53 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: follows Member State relies test administrative procedure must doubt establish unequivocally basis objective verifiable evidence measure implemented falls ascribed State acting shareholder
Answer: Itpr

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: also noted Court Justice held paragraph 29 Commission v France provision European Union law requires Commission ordering recovery aid declared incompatible common market fix exact amount aid recovered
Answer: Prec

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action EU judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU unlawfulness basic act concerned
Answer: ['Prec', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: obligation state reasons require General Court provide account follows exhaustively one one arguments put forward parties case reasoning may therefore implicit condition enables persons concerned know General Court upheld arguments provides Court Justice sufficient material exercise power review see judgment FIAMM Others v Council Commission C‑12006 P C‑12106 P EUC2008476 paragraph 96 caselaw cited
Answer: Prec

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: latter case related private undertakings appointed State administer State resource bound obligation purchase means financial resources see judgments 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 74 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 35 order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 32
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: first place clear caselaw Court appears private creditor test might applicable Commission examine possibility irrespective request effect
Answer:

retrieved examples:

Text: However provided appellant challenges interpretation application Community law Court First Instance points law examined first instance may discussed course appeal Case C21098 P Salzgitter v Commission 2000 ECR I5843 paragraph 43
Answer: Prec

Text: Furthermore even European Community first created situation capable giving rise legitimate expectations overriding public interest may preclude transitional measures adopted respect situations arose new rules came force still subject change Belgium Forum 187 v Commission paragraph 148 case‑law cited
Answer: Prec

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: EU law cannot permit rules State aid circumvented merely creation autonomous institutions charged allocating aid see judgment 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 23
Answer: Prec

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: follows settled caselaw Court defence may relied Member State action failure fulfil obligations brought Commission basis Article 1082 TFEU absolute impossibility implementing correctly Commission’s decision order recovery aid question see effect judgments 15 January 1986 Commission v Belgium 5284 EUC19863 paragraph 14 1 June 2006 Commission v Italy C‑20705 published EUC2006366 paragraph 45 9 November 2017 Commission v Greece C‑48116 published EUC2017845 paragraph 28 caselaw cited caselaw relates however solely pleas raised defence Member State order recovery made Commission whether absolute impossibility recovering aid may already established stage formal investigation procedure
Answer: ['Itpr', 'Prec', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Furthermore tax specifically intended finance aid proves contrary provisions Treaty Commission cannot declare aid scheme charge forms part compatible internal market see effect judgment 21 October 2003 van Calster Others C‑26101 C‑26201 EUC2003571 paragraphs 47 48 caselaw cited
Answer: ['Prec', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: sufficient Commission’s decision include information enabling recipient calculate amount without overmuch difficulty see also Case C‑48098 Spain v Commission 2000 ECR I8717 paragraph 25 Case C‑41503 Commission v Greece 2005 ECR I3875 paragraph 39
Answer: Prec

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Moreover contrast EC Treaty ECSC Treaty distinguish new aid existing aid
Answer: Rule

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: explained regard first regulatory act entails implementing measures judicial review compliance European Union legal order ensured irrespective whether measures adopted European Union Member States
Answer: Itpr

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: borne mind appeal limited points law General Court alone jurisdiction assess relevant facts assess evidence
Answer: Itpr

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: regard requirement competition distorted must borne mind regard principle aid intended release undertaking costs would normally bear daytoday management normal activities distorts conditions competition judgment 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 54 caselaw cited
Answer: Prec

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake appeal see judgment 30 May 2013 Quinn Barlo Others v Commission C‑7012 P published EUC2013351 paragraph 26 caselaw cited
Answer: ['Itpr', 'Prec']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Accordingly Advocate General noted points 72 76 Opinion nothing prevents recipient aid invoking applicability test recipient invoke test falls Commission assess whether test needs applied assess application
Answer:

retrieved examples:

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: Natural legal persons unable conditions governing admissibility laid fourth paragraph Article 263 TFEU challenge regulatory act European Union directly European Union judicature protected application act ability challenge implementing measures act entails
Answer: ['Itpr', 'Rule']

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: first place recalled Treaty Lisbon third limb added fourth paragraph Article 263 TFEU relaxing conditions admissibility actions annulment brought natural legal persons
Answer: Rule

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: Court held particular inconceivable authors ECSC Treaty decided Article 4c CS subsidies aids granted Member States form whatsoever abolished prohibited declared Article 67 CS without even authorised Commission aid could allowed subject measures recommended Commission mitigate remedy effects De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 21
Answer: ['Itpr', 'Prec', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Court also held action taken Article 67 CS cannot form whatsoever Article 4 CS declares incompatible common market coal steel abolished prohibited De Gezamenlijke Steenkolenmijnen Limburg v High Authority p 22
Answer: ['Prec', 'Rule']

Text: General Court pointed paragraph 42 judgment appeal review EU judicature legality decision initiate formal investigation procedure applicant challenges Commission’s assessment measure constituting State aid limited ascertaining whether Commission made manifest error assessment see effect judgment 21 July 2011 Alcoa Trasformazioni v Commission C‑19409 P EUC2011497 paragraph 61
Answer: Prec

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: addition argument support judgment appeal cannot case based judgment 18 July 2013 P C‑612 EUC2013525 since judgment Court rule constitute reference framework case
Answer: ['Itpr', 'Prec']

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: method aid financed may render entire aid scheme intended fund incompatible internal market
Answer: Prec

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: Also clear consistent caselaw Articles 4 CS 67 CS concern two distinct areas first abolishing prohibiting certain actions Member States field ECSC Treaty places Community jurisdiction second intended prevent distortion competition exercise residual powers Member States inevitably entails see Banks paragraph 88 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: clear provisions per se authorise payment State aid project intended utilise quota Regulation 178581 way precludes possibility
Answer: Rule

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: contrast action annulment defined particular pleas law relied applicant
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: follows General Court correctly held paragraph 217 judgment appeal context proceedings Court must make necessary determinations order reach finding failure fulfil obligations result plea defence raised intervener relates element fact law Commission must necessarily take account analysis capable altering framework dispute even relied Member State concerned
Answer: Itpr

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: aid measure therefore tax tax aid constituting two elements one fiscal measure inseparable
Answer: Itpr

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Second Commission approves general aid scheme take necessary measures ensure sectoral rules general competition rules complied Member State concerned
Answer: Itpr

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: Accordingly concept intervention ‘through State resources’ within meaning provision intended cover addition advantages granted directly State granted public private body appointed established State administer aid see judgments 13 March 2001 PreussenElektra C‑37998 EUC2001160 paragraph 58 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 26 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 20
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: second place regards relevance subjective state mind must noted Advocate General pointed point 74 Opinion starting point determining whether private operator test applied must economic nature Member State’s action Member State subjectively speaking thought acting alternative courses action considered adopting measure question
Answer:

retrieved examples:

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: decision visàvis undertaking measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner see judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 33 caselaw cited 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraph 49
Answer: Prec

Text: appeal amounts reality request reexamination application submitted General Court Court Justice jurisdiction undertake see inter alia Bergaderm Goupil v Commission paragraph 35 Comunità montana della Valnerina v Commission paragraph 106 caselaw cited
Answer: Prec

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: also appear legislative texts governing structural regional policy measures Community
Answer: Rule

Text: Cofinancing Member States issue thus authorised required regulation
Answer: Itpr

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Contrary held General Court judgments appeal neither required Commission order establish selectivity measure identify certain specific features characteristic common undertakings recipients tax advantage distinguished undertakings excluded advantage
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Third must confer selective advantage recipient
Answer: Class

Text: Articles 87 EC 88 EC thus reserve central role Commission determining whether aid incompatible
Answer: Itpr

Text: Thus liable pay charge cannot rely argument exemption enjoyed undertakings constitutes State aid order avoid payment charge obtain reimbursement thereof see effect inter alia judgment 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraphs 41 42
Answer: ['Itpr', 'Prec']

Text: Moreover Court held aid notified Commission apparent failure act part relation measure irrelevant see Demesa Territorio Histόrico de Álava v Commission paragraph 52
Answer: Prec

Text: selective follows reasoning set paragraphs 41 47 55 present judgment within context particular legal regime effect conferring advantage certain undertakings others different sector sector light objective pursued regime comparable factual legal situation
Answer: Itpr

Text: Nonetheless except material factor justify course action General Court may led proceedings annulment interpret reasoning contested measure manner differs author even certain circumstances reject latter’s formal statement reasons see effect judgments 27 January 2000 DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 42 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 142
Answer: Prec

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: stated paragraph 38 judgment duty incumbent upon General Court state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: Itpr

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: addition order assess whether decision issue sufficiently reasoned regard selectivity advantages arising tax measures issue distortion competition effect trade Member States necessary examine content decision entirety
Answer: Itpr

Text: accordance settled caselaw appeal plea directed ground judgment appeal operative part sufficiently founded law grounds ineffective must therefore rejected
Answer: Prec

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: Commission may therefore restrict preliminary examination Article 883 EC taking decision favour aid able satisfy initial examination aid compatible common market see Case C‑43107 P Bouygues Bouygues Télécom v Commission 2009 ECR I‑2665 paragraph 61 caselaw cited Austria v ScheucherFleisch Others paragraph 70
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: regards finally purpose third limb fourth paragraph Article 263 TFEU may seen paragraphs 22 23 26 objective relax conditions admissibility actions annulment brought natural legal persons acts general application exception legislative nature
Answer: ['Itpr', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: lays ground rule Article 163 4 Member States concerned investment projects eligible Fund Portuguese Republic project issue must like beneficiaries Fund undertake participate financing investments selected Commission assistance EAGGF
Answer: Rule

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: Second recovery unlawful aid view reestablishing status quo ante imply reconstructing past events differently basis hypothetical elements choices often numerous could made operators concerned since choices actually made aid might prove irreversible judgment 15 December 2005 Unicredito Italiano C‑14804 EUC2005774 paragraph 118
Answer: Prec

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Itpr']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: case private creditor test intended determine whether recipient undertaking would manifestly obtained comparable facilities private creditor situation close possible public creditor sought recover sums due debtor financial difficulty judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 72 accordingly whether undertaking could circumstances correspond normal market conditions obtained advantage made available State resources judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 70
Answer:

retrieved examples:

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: Secondly noted according second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union Article 1681d Rules Procedure appeal must penalty deemed inadmissible indicate precisely contested elements judgment appellant seeks set aside legal arguments specifically advanced support appeal failing appeal ground appeal question dismissed inadmissible see inter alia judgment 10 July 2014 Telefónica Telefónica de España v Commission C‑29512 P EUC20142062 paragraph 29 caselaw cited
Answer: ['Prec', 'Rule']

Text: Thus aid subject authorisation decision result alteration satisfy condition laid decision order ensure compatibility aid internal market longer covered decision authorised may constitute new aid
Answer: Itpr

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: According settled case‑law persons decision addressed may claim individually concerned decision affects reason certain attributes peculiar reason circumstances differentiated persons virtue factors distinguishes individually case person addressed see inter alia judgments Case 2562 Plaumann v Commission 1963 ECR 95 Case C‑32195 P Greenpeace Council Others v Commission 1998 ECR I‑1651 paragraphs 7 28 Italy Sardegna Lines v Commission cited paragraph 32
Answer: Prec

Text: Commission demonstrate decision real effect aid already granted requirement would effect favouring Member States grant aid breach obligation notify laid Article 933 Treaty detriment notify aid planning stage Case C30187 France v Commission 1990 ECR I307 ‘Boussac Saint Frères’ paragraphs 32 33
Answer: ['Itpr', 'Prec', 'Rule']

Text: However imposition supplementary requirement identify particular category undertakings additional analytical method applicable selectivity tax matters may deduced Court’s settled caselaw essentially involves ascertaining whether exclusion certain operators benefit tax advantage arises measure derogating ordinary tax system constitutes discrimination respect operators cannot inferred Court’s caselaw particular judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732
Answer: ['Itpr', 'Prec']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: particular aid implemented without prior notification Commission result unlawful Article 883 EC recipient aid cannot time legitimate expectation grant lawful see Joined Cases C‑18302 P C‑18702 P Demesa Territorio Histórico de Álava v Commission 2004 ECR I‑10609 paragraphs 44 45 caselaw cited
Answer: ['Prec', 'Rule']

Text: General Court therefore entitled find contested decision vitiated unlawfulness simply refers indicative range regards amount aid recovered
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Third must confer selective advantage recipient
Answer: Class

Text: regards first argument must recalled accordance Court’s settled caselaw proceedings annulment General Court cannot substitute reasoning author contested act see judgments DIR International Film Others v Commission C‑16498 P EUC200048 paragraph 38 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 141
Answer: Prec

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: latter case identification economic advantage principle sufficient support presumption selective
Answer: Itpr

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: must held analysis Commission’s decisionmaking practice regard aid granted undertakings fall ECSC Treaty cannot affect interpretation Court First Instance Articles 4c CS 67 CS
Answer: ['Itpr', 'Rule']

Text: apparent provisions read together reply may seek annulment judgment appeal basis distinct independent grounds raised appeal since grounds may raised part crossappeal
Answer: Itpr

Text: hand also possible measure may raise doubts judgment 24 May 2011 Case C‑8309 P Commission v Kronoply Kronotex yet published ECR paragraph 43 order 9 June 2011 Case C‑45110 P TF1 v Commission paragraph 47 judgment 22 September 2011 Case C‑14809 P Belgium v Deutsche Post DHL International yet published ECR paragraph 53 judgment 27 October 2011 Case C‑4710 P Austria v ScheucherFleisch Others yet published ECR paragraph 40
Answer: Prec

Text: However must noted paragraph Court expressly stated absence selectivity due finding persons eligible measure concerned factual legal situation comparable taxpayers eligible light objective pursued national legislature
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: first place recalled according settled case‑law relatively small amount aid relatively small size undertaking receives exclude possibility intraCommunity trade might affected see Case C14287 Belgium v Commission 1990 ECR I959 ‘Tubemeuse’ paragraph 43 Joined Cases C‑27892 C‑28092 Spain v Commission 1994 ECR I‑4103 paragraph 42 Case C‑28000 Altmark Trans Regierungspräsidium Magdeburg 2003 ECR I‑7747 paragraph 81
Answer: Prec

Text: basis caselaw use regulatory technique cannot enable national tax rules escape outset scrutiny concerning State aid provided FEU Treaty resorting regulatory technique used sufficient define relevant reference framework purposes assessing condition relating selectivity except order ensure form State intervention prevails decisively effects
Answer: ['Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: However specific area State aid Commission bound guidelines issues extent depart rules TFEU including particular Article 1073b TFEU see effect judgment Holland Malt v Commission C‑46409 P EUC2010733 paragraph 47 extent application breach general principles law equal treatment particular exceptional circumstances different envisaged guidelines distinguish given sector economy Member State
Answer: ['Prec', 'Rule']

Text: fact resources concerned may administered entities distinct public authorities source resources may private significance regard see effect judgments 2 July 1974 Italy v Commission 17373 EUC197471 paragraph 35 8 May 2003 Italy SIM 2 Multimedia v Commission C‑32899 C‑39900 EUC2003252 paragraph 33
Answer: Prec

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: undertaking cannot principle contest Commission decision prohibiting sectoral aid scheme concerned decision solely virtue belonging sector question potential beneficiary scheme
Answer: Itpr

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: intention underlying Article 871 EC private investor test thus prevent recipient public undertaking placed means State resources favourable position competitors see effect Case C38792 Banco Exterior de España 1994 ECR I877 paragraph 14 Case C697 Italy v Commission paragraph 16
Answer: ['Itpr', 'Prec', 'Rule']

Text: However cannot inferred Commission claims Commission decision declaring aid scheme incompatible internal market issue relevant criterion purpose determining whether applicant individually concerned within meaning fourth paragraph Article 263 TFEU decision whether applicant actual potential recipient aid granted scheme
Answer: ['Itpr', 'Rule']

Text: regards educational activities Court held courses provided educational establishments financed essentially private funds come provider constitute services since aim establishments offer service remuneration judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraph 48 caselaw cited
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Class', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Second must noted Commission doubt applicability test clear paragraph 24 present judgment asked Slovak State relevant information regard carried overall assessment evidence see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 86
Answer:

retrieved examples:

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: noted regard paragraphs 46 48 judgment 23 March 2016 Enirisorse C‑23704 EUC2006197 Court held national legislation offers advantage neither shareholders company company far merely prevents budget burdened charge normal situation would existed therefore simply regulates exceptional right without seeking reduce charge company would normally bear cannot regarded advantage within meaning Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: Prior initiation procedure must first examine whether aid covered general scheme satisfies conditions laid decision approving
Answer: Itpr

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Moreover interpretation according act could time general application relation second limb fourth paragraph Article 263 TFEU general application relation third limb fourth paragraph Article 263 TFEU would run counter objective behind addition provision relax conditions admissibility annulment actions brought natural legal persons
Answer: ['Itpr', 'Rule']

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Firstly aid strict sense may substantially affect trade Member States thus deemed admissible could disruptive effect exacerbated method financing would make whole incompatible internal market
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgments 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 55 60 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraphs 88 89
Answer: Prec

Text: provided caselaw wording Article 1062 TFEU shows exemptions Treaty rules permitted provided necessary performance particular tasks assigned undertaking entrusted operation service general economic interest see effect judgments 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 54 28 February 2013 Ordem dos Técnicos Oficiais de Contas C‑112 EUC2013127 paragraph 106
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: term ‘undertaking’ context covers entity engaged economic activity regardless legal status way financed
Answer: Class

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: stated recital 14 preamble regulation limitation period established reasons legal certainty
Answer: Rule

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: provision sets four conditions
Answer: Class

Text: follows caselaw could applicable within limits specified Court actions annulment either Commission decision closing procedure initiated Article 882 EC decision raise objections hence initiate formal review procedure provision
Answer: ['Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: fourth paragraph Article 230 EC natural legal person may institute proceedings decision addressed another person decision direct individual concern former
Answer: Rule

Text: Therefore even sums corresponding measure question permanently held Treasury fact constantly remain public control therefore available competent national authorities sufficient categorised ‘State resources’ see judgments 16 May 2002 France v Commission C‑48299 EUC2002294 paragraph 37 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 70 30 May 2013 Doux Élevage Coopérative agricole UKLARREE C‑67711 EUC2013348 paragraph 35 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 21
Answer: Prec

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: Thus actual recipients individual aid granted aid scheme Commission ordered recovery accordingly individually concerned within meaning fourth paragraph Article 263 TFEU see effect judgment 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraphs 34 35 see also judgment 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 53
Answer: ['Prec', 'Rule']

Text: regards criterion trade affected General Court recalled paragraph 191 judgment appeal follows caselaw Court Justice grant aid Member State form tax relief taxable persons must regarded likely effect trade consequently fulfilling criterion taxable persons perform economic activity field trade conceivable competition operators established Member States judgments 3 March 2005 Heiser C‑17203 EUC2005130 paragraph 35 30 April 2009 Commission v Italy Wam C‑49406 P EUC2009272 paragraph 51
Answer: Prec

Text: Since provision established broad terms capable covering alteration also aid concerned alteration
Answer: Itpr

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore aid granted Member State strengthens position undertaking compared undertakings competing trade within European Union undertakings must regarded affected aid judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 141
Answer: Prec

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: First must intervention State State resources
Answer: Class

Text: Commission challenges view line argument set paragraph 13 present judgment pointed case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents file see effect judgments 5 July 2011 Edwin v OHIM C‑26309 P EUC2011452 paragraph 53 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraphs 79 80 caselaw cited
Answer: Prec

Text: reason Community courts must principle regard specific features case technical complex nature Commissions assessments carry comprehensive review whether measure falls within scope Article 921 Treaty
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: regards admissibility arguments evidence submitted support parts single grounds appeal consideration – admissibility contested Commission ground arguments advanced support appellants’ claims concerning determination reference framework new arguments – borne mind Article 1701 Rules Procedure Court Justice subject matter proceedings General Court may changed appeal
Answer: Rule

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion contrary appellants’ contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: accordance Court’s settled caselaw applying private creditor test Commission must carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 73 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 47
Answer:

retrieved examples:

Text: therefore Commission carry overall assessment taking account relevant evidence case enabling determine whether recipient company would manifestly obtained comparable facilities private creditor see effect Commission v EDF paragraph 86
Answer: Prec

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: examination whether measure selective thus essence coextensive examination whether applies set economic operators nondiscriminatory manner see effect judgment 14 January 2015 Eventech C‑51813 EUC20159 paragraph 53
Answer: Prec

Text: contrast since assessment context appeal legal classification given national law General Court light provision EU law constitutes question law falls within jurisdiction Court Justice see effect judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 83 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraphs 61 63
Answer: Prec

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgment 25 July 2018 Commission v Spain Others C‑12816 P EUC2018591 paragraph 31 caselaw cited
Answer: ['Prec', 'Rule']

Text: However General Court determined assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation legal conclusions drawn therefrom judgments 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 78 caselaw cited 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: appellants therefore entitled call question findings made General Court irrespective fact put forward first instance arguments intended specifically challenge decision issue point
Answer: Itpr

Text: However General Court established assessed facts Court Justice jurisdiction Article 256 TFEU review legal characterisation facts legal conclusions drawn judgments 6 April 2006 General Motors v Commission C‑55103 P EUC2006229 paragraph 51 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 96 20 December 2017 Comunidad Autónoma del País Vasco Others v Commission C‑6616 P C‑6916 P EUC2017999 paragraph 97
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: deferral payment constitute alteration purely formal administrative nature qualified increase original budget aid scheme within meaning Article 41 Regulation 7942004
Answer: ['Itpr', 'Rule']

Text: regards merits settled caselaw Commission may approve general aid schemes course review must carry Articles 92 93 Treaty dispense notification Member States individual aid measures taken schemes subject reservations may express decision allowing schemes Italy v Commission cited paragraph 21 Case C27895 P Siemens v Commission 1997 ECR I2507 paragraphs 31 33
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: follows arguments submitted intervener admissible unless fall within framework provided forms order pleas law judgment 7 October 2014 Germany v Council C‑39912 EUC20142258 paragraph 27
Answer: Prec

Text: following examination considers plan compatible common market must without delay initiate procedure provided paragraph 2 article
Answer: ['Itpr', 'Rule']

Text: paragraphs 70 71 judgment Court stated supplementary requirement identify particular category undertakings exclusively favoured measure question may distinguished reason specific properties common characteristic cannot inferred caselaw Court Justice
Answer: Prec

Text: borne mind first view mandatory nature review State aid Commission Article 93 Treaty undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid article second diligent businessman normally able determine whether procedure followed Case C589 Commission v Germany 1990 ECR I3437 paragraph 14 Case C16995 Spain v Commission 1997 ECR I135 paragraph 51 Case C2495 Alcan Deutschland 1997 ECR I1591 paragraph 25
Answer: ['Prec', 'Rule']

Text: Admittedly Court held even Community legislature laid period limitation fundamental requirement legal certainty effect preventing Commission indefinitely delaying exercise powers see effect 5269 Geigy v Commission 1972 ECR 787 paragraph 21 regards State aid falling within scope ECSC Treaty Falck Acciaierie di Bolzano v Commission paragraphs 140 141
Answer: Prec

Text: Accordingly first Advocate General observed point 86 Opinion judgment appeal sets clearly reasons General Court rejected Orange’s claims
Answer: Aut

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: Viasat conceded contested decision would vitiated failure state reasons Commission required apply analytical framework according Viasat results Article 1062 TFEU
Answer: ['Itpr', 'Rule']

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: hand appears measure clearly severable general system cannot ruled reference framework taken account may limited general system even may equate measure latter appears rule legal logic possible identify consistent body rules external measure
Answer: Itpr

Text: regards second plea inadmissibility raised Commission alleging appellant intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: must pointed recipient illegally granted aid precluded relying exceptional circumstances basis legitimately assumed aid lawful thus declining refund aid
Answer: Itpr

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second parameters basis compensation calculated must established advance objective transparent manner
Answer: Class

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: follows aid granted ECSC Treaty without notified delay Commission exercising supervisory powers ordering recovery aid render recovery decision unlawful except exceptional cases show Commission manifestly failed act clearly breached duty diligence
Answer: ['Itpr', 'Rule']

Text: provision sets four conditions
Answer: Class

Text: However course considering second ground appeal found Member State confers economic advantage upon undertaking belonging fiscal nature process used grant advantage mean applicability private investor test automatically ruled
Answer: Itpr

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: First must intervention State State resources
Answer: Class

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 78 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 54
Answer:

retrieved examples:

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: finding follows examination wording context aim Article 1c Regulation 6591999
Answer: ['Itpr', 'Rule']

Text: latter provision supplemented Protocol 26 Services General Interest OJ 2010 C 83 p 308 regards field issue present case Protocol 29 System Public Broadcasting Member States OJ 2010 C 83 p 312 cannot interpreted isolation regard merely wording without also taking account additional information protocols
Answer: Itpr

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Consequently view mandatory nature review State aid Commission undertakings aid granted may principle entertain legitimate expectation aid lawful unless granted compliance procedure laid Article 88 EC diligent business operator normally able determine whether procedure followed
Answer: ['Itpr', 'Rule']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Furthermore assessment reference made exclusively subject matter action see effect judgments 19 December 2013 Telefónica v Commission C‑27412 P EUC2013852 paragraphs 30 31 27 February 2014 Stichting Woonpunt Others v Commission C‑13212 P EUC2014100 paragraphs 50 51 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraphs 38 39 caselaw cited
Answer: Prec

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Itpr

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Since figures delimit range within final amount established General Court found referring particular paragraphs 31 40 Commission v France contested decision contained appropriate information enable amount determined without much difficulty
Answer: Prec

Text: noted Court Justice consistently held General Court established assessed facts Court Justice jurisdiction Article 256 TFEU solely review legal characterisation facts conclusions law drawn
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: hand irrelevant financing mechanism issue strictly speaking fall within category fiscal levies national law see effect order 22 October 2014 Elcogás C‑27513 published EUC20142314 paragraph 31
Answer: ['Itpr', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion clear appellants’ arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: far Article 141 Regulation 6591999 requires Commission general rule adopt order recover unlawful aid allows refrain exceptionally Commission show decision issue conditions decline adopt order satisfied Scuola Elementare Maria Montessori prove General Court existed alternative methods enabling recovery part aid question
Answer: Rule

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 296 TFEU must assessed regard wording also context legal rules governing matter question see inter alia judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 88 2 December 2009 Commission v Ireland Others C‑8908 P EUC2009742 paragraph 77
Answer: ['Itpr', 'Prec', 'Rule']

Text: must recalled case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents case file judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 20 caselaw cited
Answer: Prec

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: recalled first obligation notify one fundamental features system control put place Treaty field State aid
Answer: ['Itpr', 'Rule']

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: thus follows Albany later judgments confirmed Albany competent authorities courts consider individual case whether nature purpose agreement question social policy objectives pursued warrant exclusion scope Article 811 EC see effect inter alia Case C‑22298 Van der Woude 2000 ECR I‑7111 paragraph 23
Answer: Prec

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: follows even situation Community legislature expressly laid period limitation Commission cannot indefinitely delay exercise power
Answer: Itpr

Text: Next since outside spheres EU tax law harmonised Member State concerned defines exercising exclusive competence matter direct taxation characteristics constituting tax determination reference system ‘normal’ tax regime necessary analyse condition relating selectivity must take account characteristics see effect judgment 16 March 2021 Commission v Poland C‑56219 P EUC2021201 paragraphs 38 39
Answer: Prec

Text: General policy measures liable appreciable repercussions conditions competition coal steel industry within meaning Article 671 CS without constituting State aid
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: second place contrary Commission’s contentions measure benefits one economic sector undertakings sector necessarily selective
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Thus Member State stage procedure encounters difficulties recovering aid concerned must submit difficulties Commission consideration cooperate good faith Commission view overcoming particular suggesting alternative methods allowing recovery part aid
Answer: Itpr

Text: Moreover approach adopted General Court confirmed wording Article 151 Regulation 6591999 apparent Commission’s powers recover aid subject limitation period
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Moreover purposes applying private creditor test relevant evidence information available developments foreseeable time decision taken see effect judgment 5 June 2012 Commission v EDF C‑12410 P EUC2012318 paragraph 105
Answer:

retrieved examples:

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: must also taken consideration particularly strict nature State aid regime ECSC Treaty sets apart State aid regime EC Treaty see respect Falck Acciaierie di Bolzano v Commission paragraphs 101 102
Answer: ['Prec', 'Rule']

Text: respect whether crossappeal well founded recalled party pursuant Article 40 Statute Court Justice European Union granted leave intervene case submitted Court may alter subject matter dispute defined forms order sought pleas law raised main parties
Answer: Rule

Text: field fact Commission decision leaves intact effects national measures applicant complaint addressed institution claimed compatible objective placed unfavourable competitive position makes possible conclude decision directly affects legal situation particular right provisions State aid FEU Treaty subject competition distorted national measures concerned see effect judgment 28 January 1986 Cofaz Others v Commission 16984 EUC198642 paragraph 30
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: regards second plea inadmissibility raised Commission alleging appellants intended call question findings fact principle subject review Court Justice must borne mind according settled caselaw assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Prec

Text: second place recalled according settled caselaw Court act general application applies objectively determined situations produces legal effects respect categories persons envisaged general abstract manner judgments 11 July 1968 Zuckerfabrik Watenstedt v Council 668 EUC196843 p 415 15 January 2002 Libéros v Commission C‑17100 P EUC200217 paragraph 28 caselaw cited 17 March 2011 AJD Tuna C‑22109 EUC2011153 paragraph 51 caselaw cited
Answer: ['Class', 'Prec']

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: regards specifically rules State aid must noted objective preserve competition see effect judgments 15 June 2006 Air Liquide Industries Belgium C‑39304 C‑4105 EUC2006403 paragraph 27 caselaw cited 17 July 2008 Essent Network Noord Others C‑20606 EUC2008413 paragraph 60
Answer: ['Itpr', 'Prec']

Text: Article 165 Regulation 86690 provides Member States may take aid measures subject conditions rules concerning granting differ provided regulation amounts aid exceed ceilings specified herein condition measures comply Articles 92 94 Treaty thus concern national financial contribution required Article 163 4 regulation aid Member States wish give obligatory contribution investment projects eligible Guidance Section EAGGF
Answer: Rule

Text: particular competent authorities discretionary power determine beneficiaries conditions measure granted basis criteria unrelated tax system
Answer: Itpr

Text: Secondly adoption guidelines relieve Commission obligation examine specific exceptional circumstances relied Member State particular case purpose requesting direct application Article 1073b TFEU provide reasons refusal grant request case arise
Answer: ['Itpr', 'Rule']

Text: According settled caselaw Court expression ‘does entail implementing measures’ within meaning third limb fourth paragraph Article 263 TFEU must interpreted light objective provision apparent drafting history ensure individuals break law order access court
Answer: ['Itpr', 'Prec', 'Rule']

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: Thus measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict meaning word similar character effect considered constitute aid judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 65 66 caselaw cited
Answer: Prec

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: First must intervention State State resources
Answer: Class

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU clear equally settled caselaw Court assessment condition requires determination whether particular legal regime national measure favour ‘certain undertakings production certain goods’ undertakings light objective pursued regime comparable factual legal situation accordingly suffer different treatment essence classified discriminatory see inter alia judgments 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 75 101 14 January 2015 Eventech C‑51813 EUC20159 paragraphs 53 55 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 59
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: contrary settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 87 caselaw cited
Answer: Prec

Text: Consequently Council decision authorising Member State accordance Article 84 Directive 9281 introduce exemption excise duties could effect preventing Commission exercising powers conferred Treaty consequently setting motion procedure laid Article 88 EC order review whether exemption constituted State aid conclusion procedure appropriate adopt decision contested decision
Answer: ['Itpr', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: regard clear Court’s caselaw necessary financial balance economic viability undertaking entrusted operation service general economic interest threatened
Answer: Prec

Text: However Member State provide justification
Answer: Itpr

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: Furthermore contrary assertions made Commission EFTA Surveillance Authority private investor test exception applies Member State requests situations characterised constituent elements State aid incompatible common market laid Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Advocate General observes substance point 52 Opinion consideration contested Commission appeals vitiated error law
Answer: Aut

Text: activity consisting offering services given market services normally provided remuneration economic activity
Answer: Class

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: Second regards merits plea Article 44 Regulation 178581 merely provides Articles 92 93 94 Treaty apply production trade sugar save otherwise provided Regulation
Answer: Rule

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: examination Commission whether particular measures classified State aid public authorities act way private creditor requires complex economic assessment judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 74 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 48
Answer:

retrieved examples:

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: According judgment applicant individually concerned decision addressed another person decision affects reason certain attributes peculiar reason circumstances differentiated persons see also field State aid judgments 19 October 2000 Italy Sardegna Lines v Commission C‑1598 C‑10599 EUC2000570 paragraph 32 9 June 2011 Comitato Venezia vuole vivere Others v Commission C‑7109 P C‑7309 P C‑7609 P EUC2011368 paragraph 52 fields judgments 17 January 1985 PiraikiPatraiki Others v Commission 1182 EUC198518 paragraphs 11 19 31 13 March 2018 European Union Copper Task Force v Commission C‑38416 P EUC2018176 paragraph 93
Answer: Prec

Text: may also decide order interim measures order safeguard first interests parties concerned secondly effectiveness Commission’s decision initiate formal investigation procedure
Answer: Itpr

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Indeed according settled caselaw grounds judgment General Court disclose infringement EU law operative part shown well founded legal grounds infringement capable bringing setting aside judgment judgments 30 September 2003 Biret International v Council C‑9302 P EUC2003517 paragraph 60 caselaw cited 14 October 2014 Buono Others v Commission C‑1213 P C‑1313 P EUC20142284 paragraph 62 caselaw cited
Answer: Prec

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: Since conditions cumulative State measure cannot characterised State aid one satisfied
Answer: Itpr

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Admittedly appellant rightly argued apparent caselaw use particular regulatory technique cannot enable national tax rules evade outset scrutiny State aid rules provided FEU Treaty use sufficient define relevant reference framework purposes assessing condition relating selectivity since would cause form State intervention prevail decisively effects
Answer: ['Prec', 'Rule']

Text: necessary reasoning go relevant facts points law since question whether statement reasons meets requirements Article 253 EC must assessed regard wording also context legal rules governing matter question see C‑50100 Spain v Commission 2004 ECR I‑6717 paragraph 73 caselaw cited
Answer: ['Prec', 'Rule']

Text: situation thus comparable exemption tax general application tax may distinguished see effect Laboratoires Boiron judgment paragraphs 30 48
Answer: ['Itpr', 'Prec']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: accordance Court’s settled caselaw classification ‘aid’ within meaning Article 1071 TFEU requires conditions set provision fulfilled see judgment 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 63 caselaw cited
Answer: ['Class', 'Prec', 'Rule']

Text: accordance paragraphs 88 93 judgment 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 order measure characterised State aid number conditions must met
Answer: ['Class', 'Prec']

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Since Lico Leasing PYMAR dispute admissibility first complaint first part Commission’s first ground appeal alleging error law identification beneficiaries advantages arising tax measures issue ground question fact true assessment facts evidence constitute save clear sense facts evidence distorted question law subject review Court Justice context appeal
Answer: Itpr

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: contrast examining general scheme aid necessary identify whether measure question notwithstanding finding confers advantage general application exclusive benefit certain undertakings certain sectors activity
Answer: Itpr

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: also settled caselaw purpose categorising national measure ‘State aid’ necessary demonstrate aid real effect trade Member States competition actually distorted examine whether aid liable affect trade distort competition judgment 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 140 caselaw cited
Answer: Prec

Text: However according settled caselaw follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice Articles 1681d 1692 Rules Procedure Court Justice appeal must indicate precisely contested elements judgment appellant seeks set aside also legal arguments specifically advanced support appeal see particular Case C‑35298 P Bergaderm Goupil v Commission 2000 ECR I‑5291 paragraph 34 Case C‑24003 P Comunità montana della Valnerina v Commission 2006 ECR I‑731 paragraph 105 caselaw cited
Answer: ['Prec', 'Rule']

Text: effectiveness Article 107 TFEU would substantially diminished Commission required classifying measure State aid within meaning provision wait decision courts jurisdiction regarding reimbursement excess tax tax paid certain taxpayers
Answer: ['Itpr', 'Rule']

Text: However conditions measure must meet order treated ‘aid’ purposes Article 107 TFEU met recipient undertaking could circumstances correspond normal market conditions obtained advantage made available State resources see effect judgment 5 June 2012 Case C12410 P Commission v EDF paragraph 78 caselaw cited
Answer: ['Prec', 'Rule']

Text: far FT argues obligation notify established advantage noted neither purported complexity tax regime issue periodic nature aid measure release Member State obligation notify give rise legitimate expectation part company receiving aid
Answer: Itpr

Text: procedural rules laid Treaty vary depending whether aid existing aid new aid
Answer: Rule

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: Since two categories bet identical existence advantage purposes Article 921 Treaty cannot deduced automatically difference treatment subject
Answer: ['Class', 'Rule']

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: aid may therefore lawfully put effect long Commission found incompatible see judgments Italy v Commission cited paragraphs 23 25 Banco Exterior de España cited paragraph 20
Answer: Prec

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: Advocate General observed points 40 41 Opinion concept ‘regulatory act … entail implementing measures’ within meaning final limb fourth paragraph Article 263 TFEU interpreted light provision’s objective clear origin consists preventing individual obliged infringe law order access court
Answer: ['Aut', 'Itpr', 'Rule']

Text: follows roles State shareholder undertaking one hand State acting public authority must distinguished correctly argued Commission EFTA Surveillance Authority Iberdrola General Court held paragraphs 223 228 judgment appeal
Answer: Itpr

Text: However possibility cannot excluded priori reference Albany line caselaw excessively restrictive interpretation concept ‘market’ connection question status party concerned within meaning Article 882 EC organisation trade union seeking argue action annulment admissible
Answer: ['Itpr', 'Prec', 'Rule']

Text: also held considering admissibility application annulment brought CIRFS application understood seeking annulment Commission’s refusal initiate procedure provided Article 882 EC
Answer: ['Prec', 'Rule']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Itpr', 'Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection must observed context review Courts European Union complex economic assessments made Commission field State aid Courts substitute economic assessment Commission judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 75 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 49
Answer:

retrieved examples:

Text: follows considerations General Court err law finding special tax regime conferred advantage FT purposes Article 871 EC even though exact amount aid granted regime determined reference certain factors unrelated regime
Answer: ['Itpr', 'Rule']

Text: However existence discretion may enable authorities favour certain undertakings production certain goods detriment others therefore establish existence aid within meaning Article 1071 TFEU see effect judgment 15 July 2004 Spain v Commission C‑50100 EUC2004438 paragraph 121
Answer: ['Prec', 'Rule']

Text: contrast conditions met measure constitutes State aid accordingly unless covered derogation provided Treaties incompatible internal market
Answer: ['Itpr', 'Rule']

Text: paragraph 236 judgment appeal Court First Instance correctly held referring inter alia Commission v Germany cited argument based principle protection legitimate interests could upheld
Answer: ['Itpr', 'Prec']

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: may seen paragraphs 90 92 recovery unlawful aid may considered objectively absolutely impossible Commission finds following detailed examination two cumulative conditions satisfied namely difficulties relied Member State concerned real alternative methods recovery
Answer: ['Class', 'Itpr']

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Text: regard suffice state Advocate General done points 37 39 Opinion arguments relate Court First Instances assessment facts cannot challenged Court Justice appeal
Answer: Aut

Text: Fourth must distort threaten distort competition see judgments 24 July 2003 Altmark Trans Regierungspräsidium Magdeburg C‑28000 EUC2003415 paragraph 75 17 July 2008 Essent Netwerk Noord Others C‑20606 EUC2008413 paragraph 64 19 December 2013 Association Vent De Colère Others C‑26212 EUC2013851 paragraph 15
Answer: ['Class', 'Prec']

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: paragraph 20 judgment 10 December 1969 Commission v France 669 1169 published EUC196968 paragraph 8 judgment 7 June 1988 Greece v Commission 5786 EUC1988284 Court finding State aid necessarily held conditions laid subject Article 1071 TFEU including condition relating selectivity satisfied
Answer: ['Prec', 'Rule']

Text: regards second part first ground appeal must recalled according settled caselaw Court duty incumbent upon General Court Article 36 first paragraph Article 53 Statute Court Justice European Union state reasons judgments require General Court provide account follows exhaustively one one arguments articulated parties case
Answer: ['Prec', 'Rule']

Text: conditions referred previous paragraph met State measure issue would deemed confer selective advantage recipient undertaking moreover criteria set Article 1071 TFEU met measure would constitute aid principle incompatible internal market
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: Moreover regulation refers implicitly necessarily implementation provisions contained indicating Article 45 application must take account general objectives common agricultural policy set Article 39 Treaty one aspect alleviation regional disparities area
Answer: Rule

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: regards second third parts ground appeal considered together must recalled accordance Court’s settled caselaw actions failure fulfil obligations brought ground infringement decision ordering recovery unlawful aid Member State encounters unforeseen unforeseeable difficulties becomes aware consequences overlooked Commission must submit problems Commission consideration together proposals suitable amendments decision issue
Answer: Prec

Text: evidence must show clearly time conferring economic advantage see effect France v Commission paragraphs 71 72 Member State concerned took decision make investment means measure actually implemented public undertaking
Answer: ['Itpr', 'Prec']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: present case even fifth part single ground appeal well founded must inasmuch incapable invalidating judgment appeal rejected ineffective since conclusion question remains wellfounded grounds see effect judgment 29 March 2011 AnheuserBusch v Budějovický Budvar C‑9609 P EUC2011189 paragraph 211 caselaw cited
Answer: Prec

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: therefore conflicts settled caselaw Article 1071 TFEU distinguish measures State intervention reference causes aims defines relation effects thus independently techniques used see effect judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 caselaw cited
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: completion stage Commission make finding either measure constitute aid falls within scope Article 871 EC
Answer: ['Itpr', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Advocate General stated points 107 114 Opinion preliminary explanations General Court fact sought deal issue links existing 2005 agreement 2008 amendment Commission specifically addressed decision issue particularly underline fact given chronological andor functional link two elements cannot interpreted constituting single aid measure
Answer: Aut

Text: follows arguments submitted intervener admissible unless fall within framework provided forms order pleas law judgment 7 October 2014 Germany v Council C‑39912 EUC20142258 paragraph 27
Answer: Prec

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: contrast conditions laid Altmark caselaw longer applied Commission found measure must characterised aid particular far recipient undertaking unable pass test comparison typical undertaking well run adequately equipped able meet necessary publicservice requirements examines whether aid justified Article 1062 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent reading grounds judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 paragraph 36 read light paragraph 35 judgment Court held national measures issue case selective applied indiscriminately undertakings Member State concerned constituted reason general measure within meaning caselaw cited paragraph 56 present judgment
Answer: ['Itpr', 'Prec']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: regards first wording provision refers ‘regulatory acts’ generally contains indication reference certain kinds subcategories acts
Answer: Itpr

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Moreover common ground Commission prevented adoption decision approving general aid scheme examining compatibility individual aid measure decision
Answer: Itpr

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 40 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53
Answer: ['Class', 'Prec']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However Courts European Union must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn judgments 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraph 76 21 March 2013 Commission v Buczek Automotive C‑40511 P published EUC2013186 paragraph 50
Answer:

retrieved examples:

Text: Thus determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective necessary applicable examine whether factual legal situation undertakings favoured measure question comparable judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 60
Answer: Prec

Text: Consequently first Commission may fail regard Article 1073 TFEU adopting guidelines vitiated error law manifest error assessment may waive adoption guidelines exercise discretion provision confers
Answer: ['Itpr', 'Rule']

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: activity consisting offering goods services given market economic activity see effect judgment 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 45 caselaw cited
Answer: ['Class', 'Prec']

Text: According settled caselaw appeal merely repeats reproduces verbatim pleas law arguments previously submitted Court First Instance including based facts expressly rejected Court fails satisfy requirements Article 51 EC Statute Court Justice Article 1121c Rules Procedure
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court condition natural legal person must directly concerned decision action brought laid fourth paragraph Article 263 TFEU requires two cumulative criteria met namely first contested measure must directly affect legal situation individual second must leave discretion addressees entrusted task implementing implementation purely automatic resulting EU rules alone without application intermediate rules judgments 5 May 1998 Glencore Grain v Commission C‑40496 P EUC1998196 paragraph 41 caselaw cited 13 October 2011 Deutsche Post Germany v Commission C‑46310 P C‑47510 P EUC2011656 paragraph 66 order 19 July 2017 Lysoform Dr Hans Rosemann Ecolab Deutschland v ECHA C‑66616 P published EUC2017569 paragraph 42
Answer: ['Class', 'Prec', 'Rule']

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: must recalled case interpretation national law General Court Court Justice jurisdiction appeal determine whether law distorted distortion must obvious documents case file judgment 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 20 caselaw cited
Answer: Prec

Text: Moreover follows line authority purposes comparison assessment must carried reference objective verifiable evidence available
Answer: Itpr

Text: allowing derogations made general rules Treaty certain circumstances Article 1062 TFEU seeks reconcile Member States’ interest using certain undertakings particular public sector instrument economic fiscal policy Union’s interest ensuring compliance rules competition preservation unity common market see effect judgment 23 October 1997 Commission v France C‑15994 EUC1997501 paragraph 55
Answer: ['Itpr', 'Prec', 'Rule']

Text: Commission adopts decision declares measure compatible common market also – implication – refuses initiate formal investigation procedure laid Article 882 EC Article 61 Regulation 6591999 Commission v Kronoply Kronotex paragraph 45 Austria v ScheucherFleisch Others paragraph 42
Answer: ['Prec', 'Rule']

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: Third must confer advantage recipient
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: regard existing aid provisions Article 931 2 Treaty accordance principle legal certainty context constant review aid giving notice parties concerned submit comments Commission finds aid compatible common market regard Article 92 Treaty aid misused decide State concerned must abolish alter aid within period time determined Commission
Answer: ['Princ', 'Rule']

Text: general application derives fact decisions apply objectively determined situations produce legal effects respect category persons envisaged general abstract manner see effect judgments 22 December 2008 British Aggregates v Commission C‑48706 P EUC2008757 paragraph 31 17 September 2009 Commission v Koninglijke FrieslandCampina C‑51907 P EUC2009556 paragraph 53 caselaw cited 28 June 2018 Lowell Financial Services v Commission C‑21916 P published EUC2018508 paragraph 42 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: Advocate General observes point 26 Opinion interpretation supported Commission namely nonlegislative acts general application decision issue covered concept ‘regulatory act’ within meaning third limb fourth paragraph Article 263 TFEU cannot accepted
Answer: ['Aut', 'Itpr', 'Rule']

Text: hand already stated paragraph 65 present judgment taxes principle subject rules State aid
Answer: Itpr

Text: Third must confer selective advantage recipient
Answer: Class

Text: Thus clear caselaw Court Justice contrary Commission’s submissions obligation suspend implementation measure question legal effect decision initiate formal investigation procedure
Answer: ['Itpr', 'Prec']

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: Advocate General stated point 91 Opinion issue question present case caselaw arising judgments relevant proceedings
Answer: Aut

Text: merits recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Rule']

Text: Furthermore pointed paragraph 70 General Court cannot circumstances substitute reasoning author contested act result Court Justice jurisdiction appeal ascertain whether General Court made substitution thus erred law
Answer: Itpr

Text: particular aid paid without prior notification Commission unlawful Article 933 Treaty recipient aid cannot time legitimate expectation grant lawful see Alcan Deutschland cited paragraphs 30 31
Answer: ['Prec', 'Rule']

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Accordingly fact tax measure contrary provisions EU law Articles 107 108 TFEU mean exemption measure enjoyed certain taxpayers cannot classified State aid long measure question produces effects visàvis taxpayers either repealed declared unlawful therefore inapplicable see effect judgment 30 March 2005 Heiser C‑17203 EUC2005130 paragraph 38
Answer: ['Prec', 'Rule']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: determination reference framework particular importance case tax measures since existence economic advantage purposes Article 1071 TFEU may established compared ‘normal’ taxation
Answer: ['Itpr', 'Rule']

Text: However follows caselaw purposes establishing selectivity tax measure regulatory technique used decisive result always necessary derogate common tax system fact derogation result use regulatory technique relevant purposes follows two categories operators distinguished priori treated differently namely covered derogation covered ordinary taxation regime even though two categories comparable situation regard objective pursued system judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 93 caselaw cited
Answer: ['Itpr', 'Prec']

Text: order determine whether measure selective therefore examined whether within context specified legal regime measure constitutes advantage certain undertakings others light objective pursued regime comparable factual legal situation judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 28 July 2011 Mediaset v Commission C‑40310 P published EUC2011533 paragraph 36
Answer: Prec

Text: regard must borne mind accordance caselaw mentioned paragraph 35 General Court fully entitled refer paragraph 145 judgment appeal examination comparability second stage analysis selectivity must carried light objective reference system measure issue
Answer: ['Itpr', 'Prec']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: cases national authorities impose charges order maintain equal treatment operators simple fact authorities enjoy discretion defined law unlimited Commission claimed appeal cannot sufficient establish corresponding scheme selective
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: Moreover although Article 1322b Rules Procedure statement intervention contain pleas law arguments relied intervener mean intervener free rely new pleas law distinct relied applicant
Answer: ['Itpr', 'Rule']

Text: purposes assessing selective nature tax measure general application therefore necessary common tax regime reference system applicable Member State concerned correctly identified Commission decision examined court hearing dispute concerning identification
Answer: Itpr

Text: Advocate General stated point 86 Opinion fundamental difference one hand assessment selectivity general schemes exemption relief definition confer advantage assessment selectivity optional provisions national law prescribing imposition additional charges
Answer: ['Aut', 'Itpr']

Text: regard Court Justice points reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty rule law relating application misuse powers
Answer: ['Prec', 'Rule']

Text: follows paragraph 78 applicable test among factors Commission required take account purposes establishing existence aid
Answer: Itpr

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Court’s established caselaw appraising requirement selectivity Article 1071 TFEU requires assessment whether particular legal regime national measure favour ‘certain undertakings production certain goods’ comparison others light objective pursued regime comparable factual legal situation judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraph 75 caselaw cited
Answer: ['Prec', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: connection also borne mind lawfulness decision concerning State aid falls assessed European Union judicature light information available Commission time decision adopted judgment 2 September 2010 Commission v Scott C‑29007 P EUC2010480 paragraph 91 caselaw cited
Answer:

retrieved examples:

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed essence point 49 Opinion tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Advocate General argues points 77 86 89 Opinion method limited solely examination tax measures Court merely observed determination reference framework particular importance case tax measures since existence advantage may established compared ‘normal’ taxation judgment 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56
Answer: ['Aut', 'Prec']

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: concept aid embraces positive benefits subsidies also measures various forms mitigate charges normally included budget undertaking therefore without subsidies strict sense word similar character effect Case C20097 Ecotrade 1998 ECR I7907 paragraph 34 Case C697 Italy v Commission 1999 ECR I2981 paragraph 15
Answer: Prec

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: far concerns condition relating selectivity advantage constituent factor concept ‘State aid’ within meaning Article 1071 TFEU since provision prohibits aid ‘favouring certain undertakings production certain goods’ clear Court’s settled caselaw recalled paragraphs 45 46 judgment appeal assessment condition requires determined whether particular legal regime national measure favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation
Answer: ['Class', 'Prec', 'Rule']

Text: essential characteristic remuneration lies fact consideration service question see effect judgments 11 September 2007 Schwarz GootjesSchwarz C‑7605 EUC2007492 paragraphs 37 38 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 45 47
Answer: Prec

Text: Article 174 Rules Procedure response shall seek appeal allowed dismissed whole part
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Accordingly follows foregoing view objectives underlying Article 871 EC private investor test economic advantage must — even granted fiscal means — assessed inter alia light private investor test conclusion global assessment may required appears notwithstanding fact means used instruments State power Member State concerned conferred advantage capacity shareholder undertaking belonging
Answer: ['Itpr', 'Rule']

Text: true paragraph 104 judgment 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 Court held order capable recognised conferring selective advantages criteria forming basis assessment adopted tax system must characterise recipient undertakings virtue properties specific privileged category thus permitting regime described favouring ‘certain’ undertakings production ‘certain’ goods within meaning Article 1071 TFEU
Answer: ['Itpr', 'Prec', 'Rule']

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Text: concept selectivity Advocate General states point 75 Opinion thus linked discrimination
Answer: ['Aut', 'Itpr']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: Moreover apparent paragraphs 301 305 judgment appeal judgment vitiated inadequate statement reasons regards assessment plea alleging breach principle legal certainty raised FT French Republic
Answer: Itpr

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: regards argument FT could interpreted context La Poste decision adopted definition Commission’s opinion tax regime issue must noted General Court without erring law rejected argument paragraphs 265 269 judgment appeal
Answer: Itpr

Text: Since notified implemented aid require express decision Commission legality assessed national courts TWD Textilwerke Deggendorf cited paragraphs 15 18
Answer: Prec

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: far concerns condition relating selectivity advantage clear settled caselaw order assess condition necessary determine whether particular legal regime national measure question favour ‘certain undertakings production certain goods’ others light objective pursued regime comparable factual legal situation accordingly subject different treatment essence classified discriminatory see judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 54 caselaw cited
Answer: ['Class', 'Prec']

Text: cannot deduced fact agreement could excluded reason nature purpose social policy objectives pursed scope provisions Article 811 EC collective negotiations parties involved likewise entirely automatically excluded Treaty rules State aid action annulment might brought parties would almost automatically regarded inadmissible involvement negotiations
Answer: ['Itpr', 'Rule']

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: Consequently recovery State aid unlawfully granted purpose restoring previously existing situation cannot principle regarded disproportionate objectives Treaty regard State aids see Tubemeuse cited paragraph 66 Case C‑16995 Spain v Commission 1997 ECR I135 paragraph 47
Answer: ['Prec', 'Rule']

Text: system Member States obligation first notify Commission measure intended grant new aid alter aid purposes Article 871 EC second implement measure accordance Article 883 EC institution taken final decision measure
Answer: Rule

Text: Commission take account factors put forward Member State concerned generally carry examination rigorous sufficiently reasoned manner order enable full judicial review
Answer: Itpr

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: First must intervention State State resources
Answer: Class

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: regards first part first ground appeal must recalled accordance first sentence Article 141 Regulation 6591999 negative decisions taken cases unlawful aid Commission decide Member State concerned shall take necessary measures recover aid beneficiary
Answer: Rule

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: context concept ‘undertaking’ covers entity engaged economic activity regardless legal status way financed see effect judgments 10 January 2006 Cassa di Risparmio di Firenze Others C‑22204 EUC20068 paragraph 107 27 June 2017 Congregación de Escuelas Pías Provincia Betania C‑7416 EUC2017496 paragraphs 39 41 caselaw cited
Answer: ['Class', 'Prec']

Text: basis interpretation wording origin purpose provision
Answer: Itpr

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: General Court stated paragraphs 159 161 judgment appeal settled caselaw Court application Article 1073 TFEU Commission enjoys wide discretion exercise involves complex economic social assessments judgments Germany Others v Kronofrance C‑7505 P C‑8005 P EUC2008482 paragraph 59 Banco Privado Português Massa Insolvente Banco Privado Português C‑66713 EUC2015151 paragraph 67
Answer: ['Prec', 'Rule']

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: Advocate General observes points 107 110 Opinion principle ‘no one obliged impossible’ among general principles EU law see effect order 3 March 2016 Daimler C‑17915 EUC2016134 paragraph 42
Answer: ['Aut', 'Prec', 'Princ']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: finding paragraph 35 present judgment supported Advocate General observed point 43 Opinion wording Protocol 29 states ‘the provisions Treaties shall without prejudice competence Member States provide funding public service broadcasting far funding granted broadcasting organisations fulfilment public service remit conferred defined organised Member State far funding affect trading conditions competition Union extent would contrary common interest realisation remit public service shall taken account
Answer: ['Aut', 'Rule']

Text: Accordingly whilst cannot ruled measure public undertaking lays conditions use goods services selective despite applying undertakings using goods services necessary order determine whether case regard nature measure effects examining whether advantage supposed procure fact benefits undertakings opposed others although light objective pursued regime concerned undertakings comparable factual legal situation
Answer: Itpr

Text: Court deduces Article 67 CS covers general measures Member States may adopt context economic social policy measures taken Member States apply industries coal steel capable significant repercussions conditions competition industries see Banks paragraph 88
Answer: ['Prec', 'Rule']

Text: regard first part first ground appeal recalled first place regards argument General Court distorted facts follows second subparagraph Article 2561 TFEU first paragraph Article 58 Statute Court Justice European Union General Court exclusive jurisdiction first find facts except substantive inaccuracy findings apparent documents file submitted second assess facts judgments General Motors v Commission C‑55103 P EUC2006229 paragraph 51 ThyssenKrupp Nirosta v Commission C‑35209 P EUC2011191 paragraph 179
Answer: ['Prec', 'Rule']

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: fourth paragraph Article 263 TFEU natural legal persons may institute proceedings act addressed entails implementing measures act direct individual concern
Answer: Rule

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: However information ‘available’ Commission includes seemed relevant assessment carried accordance caselaw referred paragraphs 59 61 present judgment could obtained upon request Commission administrative procedure
Answer:

retrieved examples:

Text: accordance case‑law Court apprehension internal difficulties cannot justify failure Member State comply obligations Community law see inter alia Case C‑40497 Commission v Portugal 2000 ECR I‑4897 paragraph 52 Case C‑31099 Italy v Commission cited paragraph 105 Case C‑40400 Commission v Spain 2003 ECR I‑6695 paragraph 55
Answer: Prec

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Advocate General noted points 90 93 Opinion observations made General Court paragraphs 99 101 judgment appeal made purely sake completeness
Answer: Aut

Text: Fourth level compensation needed must determined basis analysis costs typical undertaking well run adequately equipped able meet necessary public service requirements would incurred discharging obligations
Answer: Class

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: reviewing legality acts Article 263 TFEU Court Justice General Court jurisdiction actions brought grounds lack competence infringement essential procedural requirement infringement Treaty Functioning European Union rule law relating application misuse powers
Answer: ['Itpr', 'Rule']

Text: Article 45 Regulation 178581 refers general objectives common agricultural policy set Article 39 Treaty include Article 392a taking account particular nature agricultural activity results social structure agriculture structural natural disparities various agricultural regions
Answer: Rule

Text: cases cited preceding paragraph concern rules State aid objective precisely preserve competition noted paragraph 43
Answer: Itpr

Text: Advocate General states point 42 Opinion assessment leaves room criticism legal correctness
Answer: Aut

Text: Moreover Scuola Elementare Maria Montessori’s argument absolute impossibility recovering unlawful aid established adoption order recovery conflicts wording second sentence Article 141 Regulation 6591999 Commission adopt order recovery would contrary general principle EU law
Answer: ['Itpr', 'Rule']

Text: Consequently General Court entitled find nothing relevance La Poste decision could given rise legitimate expectation part FT tax regime issue lawful light rules State aid
Answer: Itpr

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: noted contrary Commission’s submissions certainly follow caselaw Court Justice measure public undertaking lays conditions use goods services always therefore nature selective measure purposes Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: Accordingly apparent Advocate General states point 112 Opinion relevant reference framework examining whether 2006 schedule effect favouring certain airlines others comparable factual legal situation regime applicable Lübeck Airport alone
Answer: Aut

Text: Lastly rules must make reference system identified according objective criteria particular enable judicial review assessments identification based
Answer: Itpr

Text: noted Advocate General point 219 Opinion provision falls within context limits established intervention procedure must read light Article 129 regulation states intervention limited supporting whole part form order sought one parties ancillary main proceedings intervener must accept case finds time intervention
Answer: ['Aut', 'Itpr', 'Rule']

Text: However social policy objectives pursued agreements would seriously undermined management labour subject Article 851 Treaty seeking jointly adopt measures improve conditions work employment
Answer: ['Prec', 'Rule']

Text: certain pleas may indeed must raised courts motion question whether statement reasons decision issue lacking inadequate falls within scope essential procedural requirements plea going substantive legality decision falls within scope infringement Treaties rule law relating application within meaning Article 263 TFEU contrast examined Courts European Union raised applicant judgment 10 December 2013 Commission v Irelandand Others C‑27212 P EUC2013812 paragraph 28 caselaw cited
Answer: ['Prec', 'Rule']

Text: decision visàvis undertaking seek contest decision measure general application covering situations determined objectively entails legal effects class persons envisaged general abstract manner Van der Kooy Others v Commission cited paragraph 15 Case C692 Federmineraria Others v Commission 1993 ECR I‑6357 paragraph 14 Italy Sardegna Lines v Commission paragraph 33
Answer: Prec

Text: result aid cannot considered separately method financing see effect judgment 14 April 2005 AEM AEM Torino C‑12803 C‑12903 EUC2005224 paragraph 45
Answer: ['Itpr', 'Prec']

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: examination selectivity condition therefore implies principle determination first reference framework within measure concerned falls determination greater importance case tax measures since existence advantage may established compared ‘normal’ taxation see effect judgments 6 September 2006 Portugal v Commission C‑8803 EUC2006511 paragraph 56 21 December 2016 Commission v Hansestadt Lübeck C‑52414 P EUC2016971 paragraph 55
Answer: ['Class', 'Prec']

Text: judgment Case T35894 Air France v Commission 1996 ECR II2109 relied appellant provides clear confirmation paragraph 67 Article 921 Treaty covers financial means public sector may actually support undertakings irrespective whether means permanent assets public sector
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: Commission finds following detailed examination alternative methods allowing even partial recovery unlawful aid question may recovery considered objectively absolutely impossible carry
Answer: Itpr

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: applicability private investor test ultimately depends therefore Member State concerned conferred capacity shareholder capacity public authority economic advantage undertaking belonging
Answer: Itpr

Text: Furthermore Advocate General observed point 35 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 clear appellant’s arguments include detailed specific criticism grounds judgment appeal seek large extent challenge observance General Court limits detailed rules governing exercise review could event raised
Answer: Aut

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: regard recalled Court Justice also held judgment 21 November 2013 Deutsche Lufthansa C‑28412 EUC2013755 paragraph 45 order Court 4 April 2014 Flughafen Lübeck C‑2713 published EUC2014240 paragraph 27 accordance Article 1083 TFEU Commission initiated formal investigation procedure regard measure notified course implementation national court hearing application cessation implementation measure recovery sums already paid required adopt measures necessary order draw appropriate conclusions infringement obligation suspend implementation measure
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: General Court recalled paragraph 43 judgment appeal accordance settled caselaw classification ‘State aid’ requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Advocate General stated point 59 Opinion present case involves dual categorisation existence advantage attributable first fixed element forming part special tax regime applied FT opposed general law regime second variable element depends factual circumstances namely location premises land various local authorities tax rate applicable authorities
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: noted Advocate General point 96 Opinion DTS’s argument followed would lead conclusion tax levied sectoral level imposed undertakings competition beneficiary aid financed tax must examined Articles 107 108 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: addition must pointed according Article 1bii regulation ‘existing aid’ understood inter alia ‘authorised aid say aid schemes individual aid authorised Commission Council
Answer: Rule

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: said regards analysis substance Commission’s single ground appeal noted first obligation Member State concerned abolish recovery aid considered Commission incompatible single market purpose according Court’s established caselaw restore situation aid granted see effect judgment 4 April 1995 Commission v Italy C‑35093 EUC199596 paragraph 21 caselaw cited
Answer: Prec

Text: authorisation decisions adopted pursuant Article 84 Directive 9281 granted Council acting unanimously proposal Commission power authorise Member State introduce exemptions reductions laid directive ‘for specific policy considerations
Answer: Rule

Text: reasons given therefore enabled accordance Court’s established caselaw interested parties know grounds upon General Court relied provided Court sufficient material exercise powers review appeal complaint alleging judgment appeal failed give adequate reasons must rejected
Answer: Prec

Text: case brought national court court assess material circumstances necessary obtaining preliminary ruling interpretation Court Justice Case C‑589 Commission v Germany 1990 ECR I‑3437 paragraph 16 Case C‑31099 Italy v Commission cited paragraph 103
Answer: Prec

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: ['Itpr', 'Prec']
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Paragraphs 180 213 235 judgment appeal Commission’s objections referred paragraph 64 present judgment directed read legal context referred General Court imply new requirements incompatible caselaw Court Justice
Answer:

retrieved examples:

Text: must held first Article 4c CS prohibits granting State aid steel coal undertakings without drawing distinction individual aid aid disbursed State aid scheme Article 67 CS refers expressly State aid respect protective measures Commission may authorise pursuant first indent paragraph 2 article favour coal steel undertakings suffer competitive disadvantages general economic policy measures
Answer: Rule

Text: second intervention must liable affect trade Member States
Answer: Class

Text: Advocate General states points 25 26 Opinion Commission rely priori vague terms particular nature French system fiscal levies horserace betting order decide reduction public levies State aid
Answer: Aut

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: must also made clear Court paragraph 36 judgment 8 November 2001 AdriaWien Pipeline Wietersdorfer Peggauer Zementwerke C‑14399 EUC2001598 referred activity undertakings benefiting national measures reference explained wording second question submitted referring court case gave rise judgment
Answer: ['Itpr', 'Prec']

Text: context order classify national tax measure ‘selective’ Commission must begin identifying ordinary ‘normal’ tax system applicable Member State concerned thereafter demonstrate tax measure issue derogation ordinary system far differentiates operators light objective pursued ordinary tax system comparable factual legal situation see effect inter alia judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 57 caselaw cited
Answer: ['Class', 'Prec']

Text: apparent Article 152 Regulation 6591999 purpose determining date limitation period starts run provision refers grant aid beneficiary date aid scheme adopted
Answer: ['Itpr', 'Rule']

Text: appeal Courts jurisdiction thus confined review findings pleas argued Court First Instance see Case C13692 P Commission v Brazzelli Lualdi Others 1994 ECR I1981 paragraph 59 order 28 June 2001 Case C35299 P Eridania Others v Council 2001 ECR I5037 paragraphs 52 53
Answer: Prec

Text: Contrary arguments Commission conclusion called question judgments 28 April 2015 TL Sugars Sidul Açúcares v Commission C‑45613 P EUC2015284 17 September 2015 Confederazione Cooperative Italiane Others v Anicav Others C‑45513 P C‑45713 P C‑46013 P published EUC2015616
Answer: Prec

Text: responsibility implementation acts lies institutions bodies offices agencies European Union natural legal persons entitled bring direct action European Union judicature implementing acts conditions stated fourth paragraph Article 263 TFEU plead support action pursuant Article 277 TFEU illegality basic act issue
Answer: Rule

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: apparent recitals 1 3 directions adopted order supplement clarify rules applicable conduct proceedings Court interest proper administration justice intended replace relevant provisions Statute Court Justice European Union Rules Procedure Court see effect order President Court 30 April 2010 Ziegler v Commission C‑11309 PR published EUC2010242 paragraph 33
Answer: ['Prec', 'Rule']

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Text: Court occasion contemplate application caselaw actions seeking annulment Commission decision terminating procedure initiated Article 882 EC
Answer: ['Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Advocate General observed point 100 Opinion overtaxation exhausted effects given time necessarily entailed conferring advantage FT special tax regime
Answer: Aut

Text: circumstances Advocate General observes point 71 Opinion would artificial require competitor request national authorities grant benefit contest refusal request national court order cause national court make reference Court validity Commission’s decision concerning measure
Answer: Aut

Text: Article 4c CS prohibits purely simply aid granted Member States form whatsoever
Answer: Rule

Text: Advocate General observes points 48 49 Opinion caselaw may applied third limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: Second Advocate General observed point 48 Opinion question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings final limb fourth paragraph Article 263 TFEU
Answer: ['Aut', 'Itpr', 'Rule']

Text: concept ‘State aid’ however cover measures differentiate undertakings light objective pursued legal regime concerned comparable factual legal situation therefore priori selective Member State concerned able demonstrate differentiation justified since flows nature general structure system measures form part see effect inter alia judgments 29 April 2004 Netherlands v Commission C‑15901 EUC2004246 paragraphs 42 43 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraphs 64 65 29 March 2012 3M Italia C‑41710 EUC2012184 paragraph 40
Answer: Prec

Text: regards reasoning Court First Instance adoption Second Third Steel Aid Code constituted partial withdrawal Commission 1971 decision object application ZRFG led uncertainty legal regime concerning ZRFG must held Article 3051 EC states ‘the provisions … EC Treaty shall affect provisions ECSC Treaty particular regards rights obligations Member States powers institutions Community rules laid Treaty functioning common market coal steel
Answer: Rule

Text: therefore irrelevant whether act question entails implementing measures regard persons
Answer: Prec

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: conclusion supported fact since Community economic also social purpose rights provisions Treaty State aid competition must balanced appropriate objectives pursued social policy include clear first paragraph Article 136 EC inter alia improved living working conditions make possible harmonisation improvement maintained proper social protection dialogue management labour see effect respect Treaty provisions freedom establishment Case C‑43805 International Transport Workers’ Federation Finnish Seamen’s Union 2007 ECR I‑10779 paragraph 79
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: end national court may decide suspend implementation measure question order recovery sums already paid
Answer: Itpr

Text: regard must pointed first context appeal purpose review Court Justice inter alia consider whether General Court addressed requisite legal standard arguments raised appellant secondly plea alleging General Court failed respond arguments relied first instance amounts essentially pleading breach obligation state reasons derives Article 36 Statute Court Justice applicable General Court virtue first paragraph Article 53 Statute Article 117 Rules Procedure General Court order 13 December 2012 Alliance One International v Commission C‑59311 P published EUC2012804 paragraph 27
Answer: ['Prec', 'Rule']

Text: According settled caselaw Court Justice classification national measure ‘State aid’ purposes Article 1071 TFEU requires conditions set provision fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: regards condition relating existence selective advantage accordance settled caselaw interventions form whatsoever liable favour undertakings directly indirectly must regarded economic advantages recipient undertaking would obtained normal market conditions considered State aid
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: caselaw applicable mutatis mutandis assessment formal investigation procedure whether absolutely impossible recover unlawful aid
Answer: Itpr

Text: Aid constitutes strict foreseeable application conditions laid decision approving general aid scheme thus considered existing aid Italy v Commission cited paragraph 25 need notified Commission examined light Article 92 Treaty
Answer: ['Prec', 'Rule']

Text: carrying necessary comprehensive review characterisation tax scheme issue State aid General Court examine whether differentiation undertakings arising scheme due nature general scheme tax system formed part judgment BNP Paribas BNL v Commission C‑45210 P EUC2012366 paragraph 102
Answer: Prec

Text: Contrary French Republic’s FT’s claims circumstances way preclude possibility even time adoption special tax regime could classified State aid purposes Article 871 EC
Answer: ['Itpr', 'Rule']

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed points 32 34 Opinion even apparent paragraphs 185 188 judgment appeal response fourth plea law action annulment General Court rule existence 2009 serious disturbance Greek economy Hellenic Republic entitled claim Court General Court erred law rejecting argument disturbance justified application Article 1073b TFEU facts present case
Answer: Aut

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: must however noted selectivity requirement differs depending whether measure question envisaged general scheme aid individual aid
Answer: Itpr

Text: hand General Court rightly pointed paragraph 196 judgment appeal Commission decision issue determine conditions application measure issue might made possible certain situations classify measure aid
Answer: Itpr

Text: connection must recalled national measure categorised State aid within meaning Article 1071 TFEU must first intervention State State resources
Answer: ['Class', 'Rule']

Text: absence implementing measures natural legal persons although directly concerned act question would able obtain judicial review act infringed provisions pleading provisions unlawful proceedings initiated national courts
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: Indeed always necessary tax measure order established selective derogate ordinary tax system fact characterised highly relevant regard effect measure two categories operators distinguished subject priori different treatment namely fall within scope derogating measure continue fall within scope ordinary tax system although two categories comparable situation light objective pursued system
Answer: ['Itpr', 'Rule']

Text: issue whether act general application concerns objective characteristic act cannot vary according different limbs fourth paragraph Article 263 TFEU
Answer: ['Class', 'Rule']

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Prec', 'Rule']
ground truth: Itpr
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: Advocate General noted paragraphs 125 131 Opinion General Court merely noted paragraphs 191 195 198 199 judgment appeal internal contradictions decision issue made findings fact according none evidence administrative file able substantiate liquidation factors used Commission
Answer:

retrieved examples:

Text: must recalled order establish selective nature tax advantage necessary competent national authorities discretionary power grant benefit measure
Answer: Itpr

Text: follows foregoing appropriate criterion establishing selectivity measure issue consists determining whether measure introduces operators light objective pursued general tax system concerned comparable factual legal situation distinction justified nature general structure system see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 61
Answer: Prec

Text: party entitled put forward pleas arguments arising judgment appeal seek criticise law correctness
Answer: Itpr

Text: interpretation selectivity criterion would require order tax system classifiable ‘selective’ must designed accordance certain regulatory technique
Answer: Itpr

Text: First must intervention State State resources
Answer: Class

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: Fourth must distort threaten distort competition judgments 10 June 2010 Fallimento Traghetti del Mediterraneo C‑14009 EUC2010335 paragraph 31 caselaw cited 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 paragraph 53 caselaw cited
Answer: ['Class', 'Prec']

Text: However penalty falling foul distinction made Rules Procedure appeal main proceedings crossappeal requirement laid second sentence Article 1783 rules may understood based premiss pleas arguments set reply analogous raised appeal main proceedings
Answer: ['Itpr', 'Rule']

Text: findings observed Advocate General points 66 72 Opinion consistent Court’s caselaw field see effect judgment 4 June 2015 Commission v MOL C‑1514 P EUC2015362 paragraph 60
Answer: ['Aut', 'Prec']

Text: Moreover Advocate General observed point 58 Opinion complaint alleging failure respond pleas raised application first instance insufficiently developed parties appeal respond Court rule
Answer: Aut

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: third place follows reasoning set paragraphs 52 55 present judgment determination set undertakings comparable factual legal situation depends prior definition legal regime light whose objective must case may examined whether factual legal situation undertakings favoured measure question comparable
Answer: Itpr

Text: present case Court First Instance held paragraph 94 judgment appeal clear Article 2 contested decision Netherlands Authorities obliged without discretion whatsoever matter reject pending request first GFA authorisation undertakings beneficiaries GFA scheme time 11 July 2001 decision could benefit transitional scheme
Answer: ['Class', 'Prec', 'Rule']

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: Second Advocate General observed point 85 Opinion argument summarised paragraph 71 cannot invalidate finding set paragraph 92 judgment appeal
Answer: Aut

Text: stage Member State thus called demonstrate difference treatment arising measure’s objective consistent principle proportionality go beyond necessary achieve objective objective could achieved less restrictive measures see effect judgment 8 September 2011 Paint Graphos Others C‑7808 C‑8008 EUC2011550 paragraph 75
Answer: ['Prec', 'Princ']

Text: contrast since assessment context appeal legal classification attributed national law General Court provision EU law constitutes question law falls within jurisdiction Court Justice judgment 28 June 2018 Andres insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 78 caselaw cited
Answer: Prec

Text: Thus virtue Article 1c regulation ‘new aid’ defined ‘all aid say aid schemes individual aid existing aid including alterations existing aid
Answer: Rule

Text: difficult see social policy objectives pursed collective agreements could seriously undermined – risk reason exclusion agreements scope Article 851 Treaty Albany – acknowledging negotiates terms conditions work members trade union appellant could competitive situation relation trade unions whose members benefit different wage conditions establishment register DIS register
Answer: ['Itpr', 'Rule']

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Judicial review compliance European Union legal order ensured seen Article 191 TEU Court Justice courts tribunals Member States
Answer: Rule

Text: Consequently Advocate General observed essence point 49 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 tax measure question inseparable general tax system Member State concerned reference must made system
Answer: ['Aut', 'Itpr', 'Prec']

Text: regards question whether applicability private investor test could ruled present case simply means employed French State fiscal recalled Article 871 EC aid granted State resources — form whatsoever — terms effects distorts threatens distort competition incompatible common market far affects trade Member States see Case C15698 Germany v Commission paragraph 25 caselaw cited
Answer: ['Prec', 'Rule']

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: noted observed Advocate General point 42 Opinion particular feature situation gave rise judgment 23 March 2006 Enirisorse C‑23704 EUC2006197 concerned national measure effect neutralising effects system derogated general system place
Answer: Aut

Text: contrary exclude priori possibility case present trade union could show party concerned within meaning Article 882 EC relying role collective negotiations effects role national tax measures regarded Commission aid compatible common market would liable undermine social policy objectives induced Court exclude collective agreement issue Albany application Article 851 Treaty
Answer: ['Itpr', 'Rule']

Text: follows caselaw fact part individual concern restricted class beneficiaries aid scheme concerned preclude part regarded general application applies objectively determined situations produces legal effects categories persons envisaged general abstract manner
Answer: Itpr

Text: purpose scope procedure laid article differ rules established Article 88 EC
Answer: Itpr

Text: party cannot therefore put forward first time Court Justice plea law raised General Court since would allow party bring Court Justice whose jurisdiction appeal proceedings limited wider case heard General Court judgment 29 July 2019 Bayerische Motoren Werke Freistaat Sachsen v Commission C‑65417 P EUC2019634 paragraph 69 caselaw cited
Answer: Prec

Text: Thus respect assessment context appeal General Court’s determinations national law Court Justice jurisdiction determine whether law distorted see judgment 3 April 2014 France v Commission C‑55912 P EUC2014217 paragraph 79 caselaw cited
Answer: Prec

Text: Court moreover repeatedly held question whether regulatory act entails implementing measures assessed reference position person pleading right bring proceedings third limb fourth paragraph Article 263 TFEU
Answer: ['Prec', 'Rule']

Text: follows fortiori precise modus operandi chosen Member State irrelevant purposes assessing whether test applies
Answer: Itpr

Text: established caselaw Article 871 EC distinguish causes objectives State aid defines relation effects see Case C‑40900 Spain v Commission 2003 ECR I‑1487 paragraph 46 caselaw cited
Answer: ['Prec', 'Rule']

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: must borne mind Directive 9281 adopted basis Article 99 EEC Treaty became Article 99 EC Treaty became Article 93 EC conferred Council power adopt provisions harmonisation legislation concerning turnover taxes excise duties forms indirect taxation extent harmonisation necessary ensure establishment functioning internal market
Answer: ['Itpr', 'Rule']

Text: Contrary German Government claims interpretation undermine effectiveness Article 67 CS
Answer: ['Itpr', 'Rule']

Text: regards next origin provision appears legislative history Article III‑3654 draft Treaty establishing Constitution Europe content repeated words fourth paragraph Article 263 TFEU addition third limb provision intended broaden conditions admissibility actions annulment respect natural legal persons acts general application restrictive approach maintained legislative acts see particular Secretariat European Convention Final report discussion circle Court Justice 25 March 2003 CONV 63603 point 22 Cover note Praesidium Convention 12 May 2003 CONV 73403 p 20
Answer: ['Itpr', 'Rule']

Text: Consequently also noted essence Advocate General point 108 Opinion regulatory technique used cannot decisive purposes determining reference framework
Answer: Aut

Text: particular directive made clear recitals 3 4 thereof seeks ensure person considers adversely affected infringement competition rules laid Articles 101 102 TFEU may effectively exercise right claim compensation harm believes suffered
Answer: Rule

Text: Article 1071 TFEU distinguish measures State intervention reference causes aims defines basis effects thus independently techniques used see effect judgments 15 November 2011 Commission Spain v Government Gibraltar United Kingdom C‑10609 P C‑10709 P EUC2011732 paragraphs 87 92 93 28 June 2018 Andres liquidator insolvency Heitkamp BauHolding v Commission C‑20316 P EUC2018505 paragraph 91
Answer: ['Prec', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: regards concept ‘regulatory acts’ Court held scope restricted concept ‘acts’ used first second limbs fourth paragraph Article 263 TFEU refers acts acts general application legislative acts see effect judgment 3 October 2013 Inuit Tapiriit Kanatami Others v Parliament Council C‑58311 P EUC2013625 paragraphs 58 61
Answer: ['Itpr', 'Prec', 'Rule']

Text: apparent Court’s caselaw cited paragraphs 89 90 recovery unlawful aid different purpose Directive 2014104
Answer: ['Prec', 'Rule']

Text: General Court pointed paragraph 28 order appeal also clear settled caselaw possibility determining less precisely number even identity persons measure applies means implies must regarded individual concern long measure applied virtue objective legal factual situation defined see effect Case C45198 Antillean Rice Mills v Council 2001 ECR I8949 paragraph 52
Answer: Prec

Text: Fourth must distort threaten distort competition see inter alia judgment 16 July 2015 BVVG C‑3914 EUC2015470 paragraph 24
Answer: ['Class', 'Prec']

Text: relation first condition set therein settled caselaw person directly concerned Community measure measure must directly affect legal situation individual leave discretion addressees entrusted task implementing implementation purely automatic resulting Community rules without application intermediate rules Case C‑38696 P Dreyfus v Commission 1998 ECR I‑2309 paragraph 43 case‑law cited
Answer: ['Class', 'Prec']

Text: Therefore arguments put forward Orange appeal ineffective even well founded could result judgment appeal set aside
Answer: Aut

Text: Furthermore contrary appellants claim cannot regarded extension first plea action General Court alleged 2004 letter Commission adopted position proposed scheme promotion electricity production RES decision
Answer: Class

Text: order State aid within meaning provision necessary first aid favouring certain undertakings production certain goods second advantage come State State resources
Answer: ['Class', 'Rule']

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

LLM output: ['Aut', 'Prec']
ground truth: Aut
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
query:
Text: considerations far concern information normally prudent diligent private creditor situation close possible local tax office could priori ignore capable justifying General Court’s decision Commission failed take consideration relevant information see effect judgment 24 January 2013 Frucona Košice v Commission C‑7311 P EUC201332 paragraphs 77 78 81
Answer:

retrieved examples:

Text: However European Union Courts must inter alia establish whether evidence relied factually accurate reliable consistent also whether evidence contains relevant information must taken account order assess complex situation whether capable substantiating conclusions drawn Case C1203 P Commission v Tetra Laval 2005 ECR I987 paragraph 39 Commission v Scott paragraph 65
Answer: Prec

Text: Second intervention must liable affect trade Member States
Answer: Class

Text: observed essence Advocate General points 133 136 Opinion caselaw cannot understood meaning national measure must necessarily classified selective measure benefits exclusively undertakings export goods services even fact may case respect particular tax measures issue judgments concerned
Answer: Aut

Text: power conferred upon Council area State aid third subparagraph Article 882 EC exceptional character means must necessarily interpreted strictly see also effect judgment 4 December 2013 Case C‑11110 Commission v Council 2013 ECR paragraph 39
Answer: ['Prec', 'Rule']

Text: However condition absolute impossibility implementation satisfied defendant Member State inform Commission internal difficulties legal political practical nature attributable national authorities’ acts omissions raised implementation decision issue without taking real steps recover aid undertakings concerned without suggesting Commission alternative methods implementing decision would allow difficulties overcome see effect judgments 13 November 2008 Commission v France C‑21407 EUC2008619 paragraph 50 12 February 2015 Commission v France C‑3714 published EUC201590 paragraph 66 caselaw cited
Answer: Prec

Text: First must intervention State State resources
Answer: Class

Text: Yet submitted Commission stated Advocate General points 57 63 Opinion none applicants General Court relied plea
Answer: Aut

Text: Article 44 regulation provides Articles 92 93 94 Treaty apply production trade sugar
Answer: Rule

Text: Court also held absence overriding public interest Commission infringed superior rule law fails couple repeal set rules transitional measures protection expectations trader might legitimately derived Community rules Belgium Forum 187 paragraph 149 case‑law cited
Answer: Prec

Text: addition Advocate General stated point 38 opinion clear paragraphs 22 32 36 defence lodged Commission General Court Commission indeed understood complaint summarised refuted pleading
Answer: Aut

Text: regard information liable significant influence decisionmaking process normally prudent diligent private creditor situation close possible public creditor seeking recover sums due debtor experiencing difficulty making payments must regarded relevant
Answer: Itpr

Text: must observed outset Advocate General stated point 47 Opinion requirement selectivity Article 1071 TFEU must clearly distinguished concomitant detection economic advantage Commission identified advantage understood broad sense arising directly indirectly particular measure also required establish advantage specifically benefits one undertakings
Answer: ['Aut', 'Class', 'Rule']

Text: Article 264 TFEU provides action well founded act concerned must declared void
Answer: Rule

Text: Advocate General observed essence point 41 Opinion assessment cannot carried comparing amount airlines subject lower rate ATT required pay hypothetical tax amount calculated basis rate Ryanair accepts apply flight airline period covered decision issue
Answer: Aut

Text: General Court indeed held paragraph 63 judgment appeal verification conditions laid Altmark caselaw occurs upstream say examination issue whether measures issue must characterised State aid
Answer: ['Itpr', 'Prec']

Text: must added sufficiently broad interpretation concept ‘new aid’ within meaning Article 1c Regulation 6591999 covering alteration made Member State concerned existing aid scheme breach authorisation conditions scheme also entire aid scheme altered makes possible ensure effectiveness system review State aid European Union promoting compliance Member State concerned authorisation conditions aid scheme
Answer: ['Itpr', 'Rule']

Text: light foregoing must consequently held Article 4c CS applies State aid paid coal steel undertakings State aid scheme specific coal steel sector
Answer: ['Itpr', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constitutes State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: examining present plea noted first Article 4 Council Regulation EC 6591999 22 March 1999 laying detailed rules application Article 88 EC Treaty OJ 1999 L 83 p 1 provides stage aid measures notified undergo preliminary examination purpose enable Commission form initial view whether aid compatible common market
Answer: ['Itpr', 'Rule']

Text: circumstances Member State concerned must put proposed measures effect procedure resulted final decision
Answer: Itpr

Text: follows Advocate General observed essence point 62 Opinion recovery aid entails restitution advantage procured aid recipient restitution economic benefit recipient may enjoyed result exploiting advantage
Answer: ['Aut', 'Itpr']

Text: First must recalled according Court’s settled caselaw classification national measure ‘State aid’ within meaning Article 1071 TFEU requires following conditions fulfilled
Answer: ['Class', 'Prec', 'Rule']

Text: third must confer selective advantage recipient fourth must distort threaten distort competition see effect judgment 2 September 2010 Commission v Deutsche Post C‑39908 P EUC2010481 paragraph 39 caselaw cited
Answer: Class

Text: Thus according settled caselaw jurisdiction Court Justice appeal limited review findings law pleas arguments debated General Court
Answer: Prec

Text: Consequently plea based infringement Article 871 EC non‑attributability measure question State cannot raised court motion
Answer: ['Itpr', 'Rule']

Text: Third must confer selective advantage recipient
Answer: Class

Text: settled caselaw Court taxes fall within scope provisions Treaty relating State aid unless constitute method financing aid measure form integral part measure judgments 13 January 2005 Streekgewest C‑17402 EUC200510 paragraph 25 13 January 2005 Pape C‑17502 EUC200511 paragraph 14 27 October 2005 Distribution Casino France Others C‑26604 C‑27004 C‑27604 C‑32104 C‑32504 EUC2005657 paragraph 34
Answer: ['Itpr', 'Prec', 'Rule']

Text: regards particular national measures confer tax advantage must recalled measure nature although involving transfer State resources places recipients favourable position taxpayers capable procuring selective advantage recipients consequently constituting State aid within meaning Article 1071 TFEU
Answer: ['Itpr', 'Rule']

Text: examination carried time Article 931 Treaty particularly event complaints Commission may receive
Answer: Rule

Text: Consequently fact applicant may fall within outside category actual potential recipients individual aid granted aid scheme declared incompatible internal market Commission decision decisive regards determining whether applicant individually concerned decision event established applicant otherwise affected reason certain attributes peculiar factual situation differentiates persons
Answer: Itpr

Text: regards principle limitation Article 151 Regulation 6591999 provides powers Commission recover aid subject limitation period 10 years
Answer: Rule

Text: However follows paragraph 37 Article 1062 TFEU require Commission take consideration second fourth Altmark conditions order decide whether State aid compatible internal market provision
Answer: ['Itpr', 'Prec', 'Rule']

Text: First must intervention State State resources
Answer: Class

Text: regards caselaw relating aid exports relied contested decisions particular judgments 10 December 1969 Commission v France 669 1169 published EUC196968 7 June 1988 Greece v Commission 5786 EUC1988284 15 July 2004 Spain v Commission C‑50100 EUC2004438 clear stated essence Advocate General points 126 130 Opinion General Court erred law holding paragraphs 69 76 judgment appeal Autogrill España v Commission paragraphs 73 80 judgment appeal Banco Santander Santusa v Commission caselaw concern condition relating selectivity national measure condition relating question whether competition trade affected
Answer: ['Aut', 'Itpr', 'Prec']

Text: Secondly also apparent caselaw examination selectivity must carried within context ‘a particular legal regime
Answer: Prec

Text: provision sets four conditions
Answer: Class

Text: Moreover follows provisions appeal inadmissible far merely repeats pleas law arguments previously submitted General Court including based facts expressly rejected
Answer: Itpr

Text: Commission could whenever examined individual aid measure go back decision approving aid scheme already involved examination light Article 92 Treaty
Answer: Rule

Text: First recipient undertaking must actually public service obligations discharge obligations must clearly defined
Answer: Class

Text: question law subject review Court Justice appeal C‑16695 P Commission v Daffix 1997 ECR I‑983
Answer: Prec

Text: Third compensation must exceed necessary cover part costs incurred discharging public service obligations
Answer: Class

Text: First apparent paragraph 21 judgment 9 October 1984 Heineken Brouwerijen 9183 12783 EUC1984307 plan initially notified meantime undergone alteration Commission informed prohibition implementation Article 1083 TFEU applies plan altered entirety
Answer: ['Itpr', 'Prec', 'Rule']

Text: Court also held first indent Article 672 CS derogation Article 4 CS allows granting State aid respect protective measures undertakings referred Article 80 CS distinguish aid specific coal steel industry aid applies result general measure Commission v France paragraph 43
Answer: ['Prec', 'Rule']

Text: also noted essence Advocate General point 109 Opinion follows caselaw Court recalled paragraphs 90 93 present judgment selectivity tax measure cannot precisely assessed basis reference framework consisting provisions artificially taken broader legislative framework
Answer: ['Aut', 'Itpr']

Text: also noted essence Advocate General points 57 59 67 68 Opinion caselaw cited paragraphs 43 45 present judgment specific context State aid merely specific expression relevant legal test assessing individual concern within meaning fourth paragraph Article 263 TFEU stemming judgment 15 July 1963 Plaumann v Commission 2562 EUC196317
Answer: ['Aut', 'Prec', 'Rule']

Text: Article 1381 EC Commission task promoting consultation management labour Community level dialogue may desire lead contractual relations
Answer: Rule

Text: apparent paragraphs 46 52 observed essence Advocate General point 76 Opinion existing aid altered breach compatibility conditions imposed Commission Council longer regarded authorised result loses status existing aid entirety
Answer: ['Aut', 'Itpr']

Text: Consequently Advocate General observed point 65 Opinion Joined Cases World Duty Free Group Spain v Commission C‑5119 P C‑6419 P EUC202151 contrary appellant’s contentions lack recognition obstacles crossborder business combinations Commission decided measure issue could correct reference system purposes selectivity analysis took view measure assessed light broader set rules included rules applicable amortisation financial goodwill case acquisition shareholdings resident companies principles applicable amortisation goodwill general according Commission aligned providing goodwill deductible acquisition shareholding followed business combination
Answer: Aut

Text: Court considered whether nature purpose agreement issue Albany justified exclusion scope Article 851 Treaty concluded case exclusion scope provision justified see Albany paragraphs 59 64
Answer: ['Prec', 'Rule']

Text: Moreover judgment 21 December 2016 Commission v World Duty Free Group Others C‑2015 P C‑2115 P EUC2016981 Court Justice held reasoning judgments 7 November 2014 Banco Santander Santusa v Commission T‑39911 EUT2014938 7 November 2014 Autogrill España v Commission T‑21910 EUT2014939 based misapplication condition relating selectivity laid Article 1071 TFEU
Answer: ['Prec', 'Rule']




LLM output: ['Itpr', 'Prec']
ground truth: Prec
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Authoritative F1: 1.0
Verbal Classification F1: 0.29411764705882354
Interpretation F1: 0.125
Precedent F1: 0.7428571428571429
Rule F1: 0.6451612903225806

macro F1: 0.5614272160477094
macro F1 (reliable): 0.7960061443932411